### PR TITLE
status: fix/improve status handling

### LINKED ISSUE #5485: Allow client-side parsing of the `grpc-status-details-bin`
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?

Integrating go service into an existing infrastructure with proto services written in C++, Java, Python, where the format of the grpc-status-details-bin is not enforced.

This would be consistent with other clients, that only suggest the expected format, but do not enforce it.

### Proposed Solution

Right now we can't even detect, whether `grpc-status-details-bin` can be parsed correctly.
The simplest solution would be a flag to disable the extended errors support entirely

```
func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
  ...
case "grpc-status-details-bin":
  if grpcStatusDetailsEnabled {
    statusGen, err = decodeGRPCStatusDetails(hf.Value)
    if err != nil {
      headerError = fmt.Sprintf("transport: malformed grpc-status-details-bin: %v", err)
    }
  } else {
    mdata[hf.Name] = append(mdata[hf.Name], hf.Value)
  }
...
```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #5485

cc @ejona86 @markdroth FYI / to review the behavior to confirm it conforms to the grpc spec or the intentions of the spec, since there is unfortunately no written spec for `grpc-status-details-bin`.

### API-layer:

If the user sets a status code outside the bounds defined in the `codes` package 0-16 (inclusive), set the status code to `codes.Unknown`.  This impacts statuses created locally as well as statuses received in RPC response trailers.  See https://github.com/grpc/grpc-java/issues/10568 for evidence this may be happening in the wild.

_Previous behavior_: allowed any value to be used and set on the wire (server) or read from the wire (client).

### Client-side:

When receiving a `grpc-status-details-bin` trailer:

- If there is 1 value and it deserializes into a `google.rpc.Status`, ensure the code field matches the `grpc-status` header's code.  If it does not match, convert the code to `codes.Internal` and set a message indicating the mismatch.  If it does, the status will contain the full details of the `grpc-status-details-bin` proto.  (Note that `grpc-message` will not be checked against the proto's message field, and will be silently discarded if there is a mismatch.)

- Otherwise, the status returned to the application will use the `grpc-status` and `grpc-message` values only.

- In all cases, the raw `grpc-status-details-bin` trailer will be visible to the application via `trailer["grpc-status-details-bin"]` (where `trailer` is either obtained via the `grpc.Trailer()` `CallOption` or `grpc.ClientStream.Trailer()`).

_Previous behavior_: use the `grpc-status-details-bin`, if present, directly, ignoring `grpc-status` and `grpc-message`, and returning a different error to the application if it could not be parsed as a `google.rpc.Status`.

### Server-side:

If the user manually sets `grpc-status-details-bin` in the trailers:

- If the status returned by the method handler _does not_ include details (see `status.(*Status).WithDetails`), the transport will send the user's `grpc-status-details-bin` trailer(s) directly.

- If the status returned by the method handler _does_ include details, the transport will disregard the user's trailer(s) and replace them with a serialized `google.rpc.Status` proto version of the returned status.

_Previous behavior_: ignore any `grpc-status-details-bin` set by the user and set it automatically as a proto if details were present in the returned status.

### Internal

This change also adds a way to use the stub server with the handler transport.

RELEASE NOTES:
- status: enforce that all status codes must be a valid `code.Code`; other values will be converted to `codes.Unknown`  AND server: allow applications to send arbitrary data in the `grpc-status-details-bin` trailer  AND  client: validate `grpc-status-details-bin` trailer and pass through the trailer to the application directly

### CODE REVIEW

File: internal/stubserver/stubserver.go [hunk 1]
```diff
@@ -110,7 +111,59 @@ func RegisterServiceServerOption(f func(*grpc.Server)) grpc.ServerOption {
...
+// StartHandlerServer only starts an HTTP server with a gRPC server as the
+// handler. It does not create a client to it.  Cannot be used in a StubServer
+// that also used StartServer.
+func (ss *StubServer) StartHandlerServer(sopts ...grpc.ServerOption) error {
+	if ss.Network == "" {
+		ss.Network = "tcp"
+	}
+	if ss.Address == "" {
+		ss.Address = "localhost:0"
+	}
```
Comment (easwars) [inline internal/stubserver/stubserver.go:123]: Can we get rid of this assignment as `ss.Address` is set to `lis.Addr().String()` on line 136. The same happens in `StartServer` as well.

File: internal/stubserver/stubserver.go [hunk 2]
```diff
@@ -110,7 +111,59 @@ func RegisterServiceServerOption(f func(*grpc.Server)) grpc.ServerOption {
...
+
+	s := grpc.NewServer(sopts...)
+	for _, so := range sopts {
+		switch x := so.(type) {
+		case *registerServiceServerOption:
+			x.f(s)
+		}
+	}
+
+	testgrpc.RegisterTestServiceServer(s, ss)
```
Comment (easwars) [inline internal/stubserver/stubserver.go:146]: Everything up to this point is similar to what we have in `StartServer`. Can we factor it out and share it?

File: status/status_ext_test.go [hunk 3]
```diff
@@ -80,3 +90,161 @@ func (s) TestErrorIs(t *testing.T) {
...
+			}, {
+				name:        "basic with details discards user's trailers",
+				trailerSent: metadata.MD{"grpc-status-details-bin": []string{"will be ignored"}},
+				errSent:     detailErr(codes.Aborted, "test msg"),
+				trailerWant: []string{serialize(detailErr(codes.Aborted, "test msg"))},
+				errWant:     detailErr(codes.Aborted, "test msg"),
+			}}
+
+			for _, tc := range testCases {
+				t.Run(tc.name, func(t *testing.T) {
```
Comment (easwars) [inline status/status_ext_test.go:189]: Instead of having nested subtests, which mean that tests share a stubServer, could we instead have a single level of subtests that don't share any state with each other, and be completely hermetic. 

One option would be to have a field in the table which controls whether to spawn a regular server or a handler server, thereby getting rid of the two levels of subtests.

File: status/status_ext_test.go [hunk 4]
```diff
@@ -80,3 +90,161 @@ func (s) TestErrorIs(t *testing.T) {
...
+					trailerCh <- tc.trailerSent
+					errCh <- tc.errSent
+					trailerGot := metadata.MD{}
+					_, errGot := ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{}, grpc.Trailer(&trailerGot))
+					gsdb := trailerGot["grpc-status-details-bin"]
+					if !reflect.DeepEqual(gsdb, tc.trailerWant) {
```
Comment (easwars) [inline status/status_ext_test.go:195]: Any reason for this to not use `cmp.Equal`?

File: status/status_ext_test.go [hunk 5]
```diff
@@ -80,3 +90,161 @@ func (s) TestErrorIs(t *testing.T) {
...
+			return ss.StartServer()
+		},
+	}, {
+		name: "handler server",
+		startServerFunc: func(ss *stubserver.StubServer) error {
+			return ss.StartHandlerServer()
+		},
+	}} {
+		t.Run(serverType.name, func(t *testing.T) {
+			errWant := status.Errorf(codes.Unknown, "test msg")
```
Comment (easwars) [inline status/status_ext_test.go:231]: Nit: Move this to right before where it is used.

File: status/status_ext_test.go (hunk 3 above)
Comment (dfawley) [reply status/status_ext_test.go:171]: nested or not is independent of whether there is a different server for each test case.  I did this to share the cost of starting the server.  If you want there to be new servers for every case, I can do that although I don't think it's super important since the only real danger is if there is one failure then it could cause subsequent failures.

Moved server init inside inner-most `Run`.  This allowed me to remove the channel anyway.

Before (best of 2):
```
$ time go test -count=10 -run Test/StatusDetails ./status
ok  	google.golang.org/grpc/status	0.088s

real	0m0.515s
user	0m0.969s
sys	0m0.526s
```

After (best of 3):
```
$ time go test -count=10 -run Test/StatusDetails ./status
ok  	google.golang.org/grpc/status	0.170s

real	0m0.589s
user	0m1.151s
sys	0m0.554s
```

File: internal/stubserver/stubserver.go [hunk 6]
```diff
@@ -127,24 +127,58 @@ func (ss *StubServer) StartServer(sopts ...grpc.ServerOption) error {
...
 	for _, so := range sopts {
 		switch x := so.(type) {
 		case *registerServiceServerOption:
-			x.f(s)
+			x.f(ss.S)
+		}
+	}
+
+	testgrpc.RegisterTestServiceServer(ss.S, ss)
+	ss.cleanups = append(ss.cleanups, ss.S.Stop, func() { lis.Close() })
```
Comment (easwars) [inline internal/stubserver/stubserver.go:144]: Minor detail: Since `grpc.Server.Stop` calls `lis.Close()`, is it really required here?

File: internal/status/status.go [hunk 7]
```diff
@@ -43,9 +43,45 @@ type Status struct {
...
+			Code: int32(codes.Internal),
+			Message: fmt.Sprintf(
+				"grpc-status-details-bin mismatch: grpc-status=%v, grpc-message=%q, grpc-status-details-bin=%+v",
+				code, message, st,
+			),
+		},
+	}
+}
+
+func normalizeCode(c codes.Code) int32 {
```
[the remark this answers is not in the document]
Comment (easwars) [reply internal/status/status.go:75]: > because it would need to be public or wrapped in magic internal stuff.

Just curious. Is there a problem with making it public? There is an `UnmarshalJSON` in there which returns an error if the code is greater than the max supported value.

File: internal/status/status.go [hunk 8]
```diff
@@ -43,9 +43,45 @@ type Status struct {
...
+	}
+	st := &spb.Status{}
+	if err := proto.Unmarshal([]byte(statusProto[0]), st); err != nil {
+		// Probably not a google.rpc.Status proto; do not provide details.
+		return &Status{s: &spb.Status{Code: normalizeCode(code), Message: message}}
+	}
+	if st.Code == int32(code) {
+		// The codes match between the grpc-status header and the
+		// grpc-status-details-bin header; use the full details proto.
+		st.Code = normalizeCode(codes.Code(st.Code))
```
[the remark this answers is not in the document]
Comment (easwars) [reply internal/status/status.go:61]: > maybe only because `codes.Code` is `uint32` while the proto `Code` field here is `int32`

Holy crap. Didn't realize that.

File: internal/status/status.go [hunk 9]
```diff
@@ -43,9 +43,45 @@ type Status struct {
...
+	if c > 16 {
+		return int32(codes.Unknown)
+	}
+	return int32(c)
+}
+
 // New returns a Status representing c and msg.
 func New(c codes.Code, msg string) *Status {
-	return &Status{s: &spb.Status{Code: int32(c), Message: msg}}
+	return &Status{s: &spb.Status{Code: normalizeCode(c), Message: msg}}
```
[the remark this answers is not in the document]
Comment (easwars) [reply internal/status/status.go:84]: Ah ok, I'd read it, but missed it.

File: status/status_ext_test.go (hunk 4 above)
Comment (easwars) [reply status/status_ext_test.go:191]: > why prefer `cmp.Equal` over `reflect.DeepEqual`?

Because it is the recommended way of doing comparisons in tests.

> if there are no special equality options needed?

We shouldn't have to think about whether special comparison options are required before making the decision between the two, every time we have to make a comparison in our tests. `reflect.DeepEqual` is sensitive to changes in unexported fields. Agreed that we are only comparing a slice of strings here, but I feel more usages of `reflect.DeepEqual` will lead to more of them in our codebase (saying I'm using it to maintain consistency, or oh that test does it and why shouldn't this one do?)

File: internal/stubserver/stubserver.go (hunk 6 above)
Comment (dfawley) [reply internal/stubserver/stubserver.go]: True...it's a bit weird since the server isn't even serving on the listener in the case of the handler server.  But yeah we don't need this.

File: status/status_ext_test.go (hunk 4 above)
Comment (dfawley) [reply status/status_ext_test.go]: > Because it is the recommended way of doing comparisons in tests.

The rationale cites "reflect.DeepEqual compares unexported fields <which presumably shouldn't ever be important to your tests I guess?>"...but if unexported fields is what you want isn't `reflect.DeepEqual` much easier to use?  In this case it's comparing `[]string` so if it isn't good enough then I don't understand why.

If `cmp` is preferred why isn't it in the stdlib?  🤷 

I switched it but don't really see the rationale of always reaching for something that's often more complicated and harder to use by default over something that for simple use cases is easier to use and understand.

File: internal/status/status.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/status/status.go:75]: I just didn't want to go through the process of figuring out whether it should be a method on the type or a function or a `FromInt(int32)` or what...

File: internal/stubserver/stubserver.go (hunk 6 above)
Comment (dfawley) [reply internal/stubserver/stubserver.go]: Oh.. wait in the handler server case we never pass the listener to grpc..so we still need the close. But only on the handler path.  Added there.

File: status/status_ext_test.go (hunk 4 above)
Comment (easwars) [reply status/status_ext_test.go]: I see that commit where you switched, but for some reason github doesn't show it in the full diff.

**Review by easwars — APPROVED** [review]
