### PR TITLE
fix enabling compression by trimming whitespaces in accept encoding header

### LINKED ISSUE #6951: Response is not compressed when grpc-accept-encoding header contains spaces between values
### What version of gRPC are you using?
1.61.0

### What version of Go are you using (`go version`)?
1.21.2

### What operating system (Linux, Windows, …) and version?
macOS

### What did you do?
Call grpc-go server from https://github.com/grpc/grpc client with compression enabled.

### What did you expect to see?

[grpc-core](https://github.com/grpc/grpc/blob/58300b9d1fcce62069f793050e6d65da874a98d9/src/core/lib/compression/compression_internal.cc#L72) adds a whitespace character between values:
```
grpc-accept-encoding=identity, deflate, gzip
```
go server should accept this header.

### What did you see instead?
There is no compression happened between server and client.
The reason for that the [go code](https://github.com/grpc/grpc-go/blob/02858ee5064040458f7e3e04e10765a62814c50b/server.go#L2171) splits the value with `,` and doesn't trim the results.
The only valid header for go is the following:
```
grpc-accept-encoding=identity,deflate,gzip
```

[grpc-dotnet](https://github.com/grpc/grpc-dotnet/pull/1882) repo is has done something similar before.

### PR DESCRIPTION
**Pull request by sercand**
fixes #6951 

RELEASE NOTES: none

### CODE REVIEW

**Review by arvindbr8 — APPROVED** [review]
LGTM. Thanks for the PR @sercand

File: server.go [hunk 1]
```diff
@@ -2119,7 +2119,11 @@ func ClientSupportedCompressors(ctx context.Context) ([]string, error) {
 		return nil, fmt.Errorf("failed to fetch the stream from the given context %v", ctx)
 	}
 
-	return strings.Split(stream.ClientAdvertisedCompressors(), ","), nil
+	values := strings.Split(stream.ClientAdvertisedCompressors(), ",")
```
Comment (dfawley) [inline server.go:2122]: It seems `ClientAdvertisedCompressors()` is always used with a `strings.Split(",")`.  Can we make that return `[]string` instead and do the split/trim there, please?

**Review by dfawley — CHANGES_REQUESTED** [review]

File: server.go (hunk 1 above)
Comment (sercand) [reply server.go]: @dfawley I commited the changes you requested. Could you review again 🙏

**Review by dfawley — APPROVED** [review]
Thanks!

**Review by arvindbr8 — APPROVED** [review]

**Comment by arvindbr8** [comment]
LGTM. Thanks for the PR @sercand
