### PR TITLE
client: fix potential panic during RPC retries

### LINKED ISSUE #5315: panic: csAttempt.s nil pointer in CloseSend
### What version of gRPC are you using?
1.42.0
### What version of Go are you using (`go version`)?
1.15
### What operating system (Linux, Windows, …) and version?
Linux
### What did you do?
Call bi-directional stream client's `recv` and `send` in different goroutine, and panic during `CloseSend()` in send goroutine.

The panic stack is
```
panic(0x135ed00, 0x20eb530)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
google.golang.org/grpc/internal/transport.(*Stream).compareAndSwapState(...)
        /google.golang.org/grpc@v1.42.0/internal/transport/transport.go:310
google.golang.org/grpc/internal/transport.(*http2Client).Write(0xc341ace1e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc79d5b9fbc, 0x2, ...)
        /google.golang.org/grpc@v1.42.0/internal/transport/http2_client.go:954 +0x3e
google.golang.org/grpc.(*clientStream).CloseSend.func1(0xc32e4e4b00, 0x0, 0xc2c33e4780)
        /google.golang.org/grpc@v1.42.0/stream.go:864 +0x79
```

I think I see the problem is in `withRetry`, definition is 
```
func (cs *clientStream) withRetry(op func(a *csAttempt) error, onSuccess func()) error {
	cs.mu.Lock()
	for {
		if cs.committed {
			cs.mu.Unlock()
			// toRPCErr is used in case the error from the attempt comes from
			// NewClientStream, which intentionally doesn't return a status
			// error to allow for further inspection; all other errors should
			// already be status errors.
			return toRPCErr(op(cs.attempt))
		}
		a := cs.attempt
...
```
Bug is in `return toRPCErr(op(cs.attempt))` which is not locked, and other `recv` can modify `cs.attempt`.

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #5315

Before this change, there was a very narrow window where a stream could fail to be created on a retry attempt, and subsequent stream operations could panic when this occurred.  This change is a fairly substantial restructuring of the retry code in order to guarantee that for all clientStreams returned to the user, `cs.attempt.s` is always non-nil.  New attempts that don't yet have a stream are created in `cs.newAttempt` until they pick a transport and create a stream, at which time they are promoted to `cs.attempt`.

This also allows us to run balancer pick results through the retry code, meaning UNAVAILABLE errors can be retried by the retry policy, as intended.  It also handles drop results that should explicitly avoid the retry code.

RELEASE NOTES:
* client: fix potential panic during RPC retries

### CODE REVIEW

File: internal/transport/http2_client.go [hunk 1]
```diff
@@ -650,11 +649,11 @@ func (e NewStreamError) Error() string {
 
 // NewStream creates a stream and registers it into the transport as "active"
 // streams.  All non-nil errors returned will be *NewStreamError.
-func (t *http2Client) NewStream(ctx context.Context, callHdr *CallHdr) (_ *Stream, err error) {
+func (t *http2Client) NewStream(ctx context.Context, callHdr *CallHdr) (*Stream, error) {
 	ctx = peer.NewContext(ctx, t.getPeer())
 	headerFields, err := t.createHeaderFields(ctx, callHdr)
 	if err != nil {
-		return nil, &NewStreamError{Err: err, DoNotTransparentRetry: true}
+		return nil, &NewStreamError{Err: err, AllowTransparentRetry: false}
```
Comment (hexfusion) [inline internal/transport/http2_client.go:656]: much nicer +1

File: stream.go [hunk 2]
```diff
@@ -651,19 +658,23 @@ func (cs *clientStream) shouldRetry(err error) (bool, error) {
...
-		if err := cs.newAttemptLocked(isTransparent); err != nil {
+		attempt, err = cs.newAttemptLocked(isTransparent)
+		if err != nil {
+			// Only returns error if the clientconn is closed or the context of
+			// the stream is canceled.
+			cs.finish(err)
 			return err
 		}
-		if lastErr = cs.replayBufferLocked(); lastErr == nil {
+		if lastErr = cs.replayBufferLocked(attempt); lastErr == nil {
```
Comment (menghanl) [inline stream.go:677]: Comment that the first op will set the attempt if it gets a transport and a stream.

Comment (dfawley) [reply stream.go:681]: Done

File: stream.go [hunk 3]
```diff
@@ -303,14 +303,26 @@ func newClientStreamWithParams(ctx context.Context, desc *StreamDesc, cc *Client
...
 
-	if err := cs.newAttemptLocked(false /* isTransparent */); err != nil {
+	cs.attempt, err = cs.newAttemptLocked(false /* isTransparent */)
+	if err != nil {
 		cs.finish(err)
 		return nil, err
 	}
 
-	op := func(a *csAttempt) error { return a.newStream() }
+	// Because this operation is always called either here (while creating the
```
[the remark this answers is not in the document]
Comment (dfawley) [reply stream.go]: Done

File: stream.go [hunk 4]
```diff
@@ -303,14 +303,26 @@ func newClientStreamWithParams(ctx context.Context, desc *StreamDesc, cc *Client
...
+	// clientStream) or by the retry code while locked when replaying the
+	// operation, it is safe to access cs.attempt directly.
```
[the remark this answers is not in the document]
Comment (dfawley) [reply stream.go]: Done

**Review by dfawley — COMMENTED** [review]
Thanks for the review.  All comments addressed.

**Comment by hexfusion** [comment]
Just curious if this could get backported to 1.46.x or is the change too large.

**Comment by dfawley** [comment]
> Just curious if this could get backported to 1.46.x or is the change too large.

Yes, I believe this should be backported.

**Review by menghanl — APPROVED** [review]

**Comment by hexfusion** [comment]
Quick question: in the case of server returns `RST_STREAM` could that trigger this panic? I'm having a hard time isolating the retry logic in this scenario (> maxStreams).

**Comment by dfawley** [comment]
`RST_STREAM(REFUSED_STREAM)` at the start of the RPC will trigger a transparent retry.  If the RPC is canceled before another transport stream can be created, or if the ClientConn is closed in that window, then you could hit this panic.
