### PR TITLE
proxy: support basic authentication

### LINKED ISSUE #2422: Proxy with auth (digest) doesn't work
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Latest from master branch

### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### What operating system (Linux, Windows, …) and version?
CentOS, Production env, using a Squid Proxy (accounts.google.com and pubsub.googleapis.com:443 whitelisted)

### What did you do?
I posted this in google pubsub repo but am diverted here (https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1202#issuecomment-434710884).

I am using the GO-PubSub Package which uses this package for gRPC. 

When interacting with google pubsub, the function hangs forever. 

```
pub, err := pubsub.NewClient(ctx, projectID, option.WithCredentialsFile("file"))
if err != nil {
		fmt.Println(err.Error())
	}
cctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
defer cancel()
sub := pub.Subscription("sub")
ok, err := sub.Exists(cctx)  // <- hangs here and then after a minute deadline exceeded.  When I use sub.Receive it hangs forever and never returns even after context expires.
if err != nil {
	fmt.Println(err.Error())
	return
}
fmt.Println(ok)
```

### What did you expect to see?
Expect the function to return and consume messages or interact with pubsub as needed. 

### What did you see instead?

The receive function hangs. 

The squid proxy logs show a TCP_DENIED/407 error. 

Also here is the GRPC DEBUG LOGS:

```
WARNING: 2018/10/31 13:13:06 grpc: addrConn.createTransport failed to connect to {pubsub.googleapis.com:443 0  0}. Err :connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 407 Proxy Authentication Required\\r\\nConnection: keep-alive\\r\\nContent-Type: text/html;charset=utf-8\\r\\nDate: Wed, 31 Oct 2018 20:13:06 GMT\\r\\nMime-Version: 1.0\\r\\nProxy-Authenticate: Digest realm=\\\"outbound_proxy\\\", nonce=\\\"0gzaWwAAAACAtaIBAAAAANZpvlAAAAAA\\\", qop=\\\"auth\\\", stale=false\\r\\nProxy-Authenticate: Basic realm=\\\"outbound_proxy\\\"\\r\\nServer: squid\\r\\nVia: 1.1 (squid)\\r\\nX-Cache: MISS from \\r\\nX-Cache-Lookup: NONE from \\r\\nX-Squid-Error: ERR_CACHE_ACCESS_DENIED 0\\r\\nContent-Length: 0\\r\\n\\r\\n\"". Reconnecting...
```

### PR DESCRIPTION
**Pull request by menghanl**
Proxy-Authorization: https://tools.ietf.org/html/rfc7235#section-4.4
The 'Basic' HTTP Authentication Scheme: https://tools.ietf.org/html/rfc7617

updates #2422

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -77,9 +85,14 @@ func doHTTPConnectHandshake(ctx context.Context, conn net.Conn, addr string) (_
...
 	req := (&http.Request{
 		Method: http.MethodConnect,
-		URL:    &url.URL{Host: addr},
+		URL:    &url.URL{Host: backendAddr},
 		Header: map[string][]string{"User-Agent": {grpcUA}},
 	})
+	if t := proxyURL.User; t != nil {
+		u := t.Username()
+		p, _ := t.Password()
+		req.Header.Add(proxyAuthHeaderKey, basicAuth(u, p))
```
Comment (dfawley) [inline proxy.go]: `"Basic " + basicAuth(u, p)` ?

Comment (menghanl) [reply proxy.go]: hmm, fixed.

Manually tested and confirmed it's working.

File: proxy.go [hunk 2]
```diff
@@ -77,9 +85,14 @@ func doHTTPConnectHandshake(ctx context.Context, conn net.Conn, addr string) (_
 
 	req := (&http.Request{
```
[the remark this answers is not in the document]
Comment (menghanl) [reply proxy.go]: Done
