### PR TITLE
Release the quota taken in streamsQuota when an rpc is timeout or canceled

### LINKED ISSUE #674: Stream Quota Leak following SettingMaxConcurrentStreams
I'm happy to submit a patch if the following explanation holds.

## Background
We’ve experienced issues where gRPC clients would seem to hang after some amount of invocations have been made against the Go Bigtable API.  The problem seems to randomly occur in about 1:3 runs.  If you add logging you can make the problem go away.

We have been able to reproduce the issue via the following horrible code [snippet](https://gist.github.com/akhenakh/adb03aa05ac1a6e85611422128d2a004) and running it with 2k-3k routines.  The code creates a WithTimeout context off of the Background context.  It then proceeds to cancel the WithTimeout context and then use it in invocations to the BT API.  As expected, the BT API calls fail due to the canceled context.  However, if you try to make one more call against BT using the parent context of the WithTimeout context the call hangs on line https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.

In this hang, the code is waiting for stream quota that will never become available.  The system will sit there for about 4 minutes until the client transport is torn down which causes the BT API invocation to conclude with an error.

## Debugging
As part of tracking this issue down, logging statements were added at several locations.  It was observed that adding log lines at specific points seemed to decrease or eliminate the likelihood of occurrence.  Regardless, every time the hang occurred, the goroutine invoking BT API was stuck on https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.

Further inspection revealed that when the test starts to run the client transport is running without any restrictions to max concurrent streams.  As the code makes more and more concurrent requests the system eventually receives a request to use http2.SettingMaxConcurrentStreams setting of 100 (https://tools.ietf.org/html/rfc7540#page-22).  This places the client code into a quota driven mode which attempts to limit the max concurrent streams in use to that new value by leveraging a channel to pass the current quota value back and forth.

When the code is running in this modality, it invokes a wait method https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L499 which receives a channel (for quota among other reasons) which it monitors in a select statement.  Per the [Go Language Select Definition](https://golang.org/ref/spec#Select_statements) if multiple channels are ready, the channel is: “chosen via a uniform pseudo-random selection”.

So if you have a context that is canceled AND you have quota available, you may consume quota OR detect cancellation in a pseudo random manner.  So you could get quota via https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282 yet fail to release it because https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L291 detects the canceled stream.  

## Possible Workarounds
Part of the problem here is that the comment on line https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L292 isn’t true since not all callers of NewStream will result in a call to CloseStream (https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L390) in all cases.

A hacky solution that avoids any refactoring is to update https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L292 to release the quota if it erroneously received any in https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L282.  This appears to address our issue, but it seems that the root is an assumption around how wait works with respect to precedence.

### PR DESCRIPTION
**Pull request by iamqizhao**
Fixes #674

### CODE REVIEW

File: transport/http2_client.go [hunk 1]
```diff
@@ -289,7 +289,10 @@ func (t *http2Client) NewStream(ctx context.Context, callHdr *CallHdr) (_ *Strea
 		}
 	}
 	if _, err := wait(ctx, t.shutdownChan, t.writableChan); err != nil {
-		// t.streamsQuota will be updated when t.CloseStream is invoked.
+		// Return the quota back now because there is no stream returned to the caller.
+		if _, ok := err.(StreamError); ok && checkStreamsQuota {
```
Comment (stxmendez) [inline transport/http2_client.go]: Why does the type of error returned from the wait method matter here at all?  The wait method can also return ErrConnClosing if the shutdownChan is readable but it is not of type StreamError.

I believe that per the original description of the problem, involving the pseudo random behavior of the Go select statement, it could have been readable on the invocation on line 282 and you get unlucky and quota gets picked instead.  You could argue that in a shutdown event you will tear everything down so the inaccuracy of the quota is irrelevant, but it is probably best to have the least number of special cases.  To that end, if you are here the type of error shouldn't matter.

Perhaps I missed something?

File: test/end2end_test.go [hunk 2]
```diff
@@ -1595,6 +1595,61 @@ func testExceedMaxStreamsLimit(t *testing.T, e env) {
...
 
+func TestStreamsQuotaRecovery(t *testing.T) {
+	defer leakCheck(t)()
+	for _, e := range listTestEnv() {
+		testStreamsQuotaRecovery(t, e)
+	}
+}
+
+func testStreamsQuotaRecovery(t *testing.T, e env) {
+	te := newTest(t, e)
```
Comment (stxmendez) [inline test/end2end_test.go]: Looking over the test code, how do you know that you hit transport/http2_client.go line 294?

Comment (iamqizhao) [inline test/end2end_test.go]: There is no way to hit that case deterministically. But if you run this test many times, it may hit the line and trigger the problem if there is not this fix.

File: transport/http2_client.go (hunk 1 above)
Comment (iamqizhao) [inline transport/http2_client.go]: As you already pointed out, if the entire connection is down, we do not need to do this. It is not a special case but a common practice across the code base for better efficiency.

Comment (stxmendez) [inline transport/http2_client.go]: So long as error instances returned from wait which are not StreamErrors result in a connection teardown you are correct.  Just wanted to push on that point.

File: test/end2end_test.go (hunk 2 above)
Comment (stxmendez) [inline test/end2end_test.go]: The non-deterministic nature of the bug is key.  If you can't verify that you address the issue in the unlucky case then you can regress at a later point in time and you would not know it.

Again, not trying to block just commenting on the contents of the review.

Comment (iamqizhao) [inline test/end2end_test.go]: This is almost the only way to test the tricky race condition and something similar like this because there is no deterministic way to reproduce that. Typically, I run the tests a thousand times to detect any flakeness before submitting.

File: transport/http2_client.go (hunk 1 above)
Comment (iamqizhao) [inline transport/http2_client.go]: All the exported API in the transport package generates StreamError/ConnectionError/nil. No exceptions.
