### PR TITLE
client: fix stream creation issue with transparent retry

### LINKED ISSUE #5341: Flaky test: Test/FailFast
https://github.com/grpc/grpc-go/runs/6359093965?check_suite_focus=true

### PR DESCRIPTION
**Pull request by dfawley**
Note: I am fairly sure the comment formatting change is caused by using a preview version of Go 1.19, meaning we all will see that behavior forced by `gofmt` soon.

Fixes #5341

Description:

We need to create a brand new attempt _every time_ we retry the initial op that gets the transport and creates the stream.  Once that op is committed and added to the replay log, it is handled by the retry+replay logic, but until then, it currently does retries using the original attempt.  This was mostly OK, but leads to a potential infinite loop:

1. `getTransport()` - succeeds
2. `newStream()` - fails with a transparently retryable error, as the transport died at the exact right moment
3. Retry
4. `getTransport` - fails
5. `shouldRetry` should not allow transparent retry in this case, but it does because the original attempt had the field set.

If no transport is ever attainable after this, it will loop until the RPC's context expires.

RELEASE NOTES:
* client: fix an issue that, in the event of an unlikely race, could lead to RPCs timing out instead of failing more quickly with UNAVAILABLE

### CODE REVIEW

File: stream.go [hunk 1]
```diff
@@ -704,6 +698,18 @@ func (cs *clientStream) withRetry(op func(a *csAttempt) error, onSuccess func())
...
 		}
+		if len(cs.buffer) == 0 {
+			// For the first op, which controls creation of the stream and
+			// assigns cs.attempt, we need to create a new attempt inline
+			// before executing the first op.  On subsequent ops, the attempt
+			// is created immediately before replaying the ops.
+			var err error
+			if cs.attempt, err = cs.newAttemptLocked(false /* isTransparent */); err != nil {
+				cs.mu.Unlock()
+				cs.finish(err)
```
Comment (easwars) [inline stream.go:709]: `cs.finish()` grabs the lock again. Can something happen between us calling `Unlock()` on line 708 and `cs.finish()` calling `Lock()` that can cause trouble?

Comment (dfawley) [reply stream.go:709]: Since this is only for the first op, the `clientStream` we're using is only visible to the caller at this point (`newClientStream`).

**Review by easwars — APPROVED** [review]
