### PR TITLE
test: add test of malformed gzip payload

### LINKED ISSUE #3135: Go should verify gziped messages are correctly terminated
Gzip has a footer containing an adler32 (think CRC32). grpc-dotnet recently introduced a bug where this was missing (https://github.com/grpc/grpc/issues/20884). However, the Go client did not fail. The gzip decoder should have failed with ErrChecksum. It's unclear why this wasn't reported to the client, but seems like a bug. (I poked around a bit and rpc_util.go's decompress() looked fine. The gzip decompressor itself didn't seem to have much to it.)

### PR DESCRIPTION
**Pull request by dfawley**
Adds a regression test inspired by #3135.

Fixes #3135

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -7525,3 +7526,46 @@ func (s) TestClientCancellationPropagatesUnary(t *testing.T) {
...
+	buf = bytes.NewBuffer(bs)
+	buf.WriteTo(w)
+	return err
+}
+
+func (badGzipCompressor) Type() string {
+	return "gzip"
+}
+
+func (s) TestGzipWithoutFooter(t *testing.T) {
```
Comment (menghanl) [inline test/end2end_test.go]: Is footer same as checksum?
And is this without footer or with invalid footer?

File: test/end2end_test.go [hunk 2]
```diff
@@ -7525,3 +7526,46 @@ func (s) TestClientCancellationPropagatesUnary(t *testing.T) {
...
+
+type badGzipCompressor struct{}
+
+func (badGzipCompressor) Do(w io.Writer, p []byte) error {
+	buf := &bytes.Buffer{}
+	gzw := gzip.NewWriter(buf)
+	if _, err := gzw.Write(p); err != nil {
+		return err
+	}
+	err := gzw.Close()
```
Comment (menghanl) [inline test/end2end_test.go]: Return if err != nil?
If err is not nil, reading `buf` may panic.

File: test/end2end_test.go [hunk 3]
```diff
@@ -7525,3 +7526,46 @@ func (s) TestClientCancellationPropagatesUnary(t *testing.T) {
...
+	bs := buf.Bytes()
+	bs[len(bs)-4] -= 1 // modify checksum (big endian) at end by 1 byte
+	buf = bytes.NewBuffer(bs)
+	buf.WriteTo(w)
```
Comment (menghanl) [inline test/end2end_test.go]: Is this same as `w.Write(bs)`?
