### PR TITLE
stickiness: avoid using unsafe

### LINKED ISSUE #2022: "unsafe" dependency causing App Engine to break
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.11.3

### What version of Go are you using (`go version`)?
1.8

### What operating system (Linux, Windows, …) and version?
macOS 10.13.1

### What did you do?
First of all, I'd like to apologize if this a dumb issue, but I don't have a ton of experience with Go and its dependency management system!

I've been using the [Firebase Admin SDK](https://godoc.org/firebase.google.com/go) which has gRPC as a dependency. I ran `go get -u` earlier, which upgraded, among other things, gRPC to the [commit](https://github.com/grpc/grpc-go/commit/e8a6e2844b5d361a53025d9b27f5f7b404a50f45) made today where `unsafe` is included as a dependency. `unsafe` is not compatible with the App Engine Go Standard Environment, so this has been a massively breaking change.

### What did you expect to see?
Successful build

### What did you see instead?
`go-app-builder: Failed parsing input: parser: bad import "unsafe" in google.golang.org/grpc/backoff.go from GOPATH`

### PR DESCRIPTION
**Pull request by menghanl**
App Engine doesn't allow use of unsafe

#2022

### CODE REVIEW

File: picker_wrapper.go [hunk 1]
```diff
@@ -73,18 +72,17 @@ func (bp *pickerWrapper) connectionError() error {
...
 }
 
 func (bp *pickerWrapper) getStickinessMDKey() string {
-	mdKeyPtr := (*string)(atomic.LoadPointer(&bp.stickinessMDKey))
-	if mdKeyPtr != nil {
-		return *mdKeyPtr
-	}
-	return ""
+	// No need to check ok because mdKey == "" if ok == false.
+	mdKey, _ := bp.stickinessMDKey.Load().(string)
```
Comment (dfawley) [inline picker_wrapper.go]: `return bp.stickinessMDKey.Load().(string)`

File: picker_wrapper.go [hunk 2]
```diff
@@ -73,18 +72,17 @@ func (bp *pickerWrapper) connectionError() error {
 }
 
 func (bp *pickerWrapper) updateStickinessMDKey(newKey string) {
-	oldKeyUnsafePtr := atomic.SwapPointer(&bp.stickinessMDKey, unsafe.Pointer(&newKey))
-	if ptr := (*string)(oldKeyUnsafePtr); ptr == nil || *ptr != newKey {
+	// No need to check ok because mdKey == "" if ok == false.
+	if oldKey, _ := bp.stickinessMDKey.Load().(string); oldKey != newKey {
```
Comment (dfawley) [inline picker_wrapper.go]: drop the "`, _`"; it's cleaner.

File: picker_wrapper.go (hunk 1 above)
Comment (menghanl) [reply picker_wrapper.go]: It could be `nil`. We need `, _` otherwise it may panic.
