### PR TITLE
vet: add dependency checks

### LINKED ISSUE #7690: Add a test for dependencies of grpc package
We should add a test in `vet.sh` to confirm that the dependencies of grpc don't change without our noticing (i.e. vet should fail if they don't match the current list).

`go list` can pretty easily show dependencies.  We should only be checking our direct dependencies and not our transitive dependencies, since we have no control over the transitive ones.  We should check the `grpc` package, the `xds` package, and any other important packages that are not imported by either of those directly.

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #7690

This change adds a new GA workflow to compare dependencies before and after a PR.  If they change, it will report a red X.  We will not require this check to pass for merging, but it should be inspected to see if the change in dependencies is reasonable and expected.

RELEASE NOTES: none

### CODE REVIEW

File: scripts/vet.sh [hunk 1]
```diff
@@ -38,160 +38,172 @@ elif [[ "$#" -ne 0 ]]; then
...
-GetPrefixMatch
-GetSafeRegexMatch
-GetSuffixMatch
-GetTlsCertificateCertificateProviderInstance
-GetValidationContextCertificateProviderInstance
-XXXXX PleaseIgnoreUnused'
+# # - Ensure all source files contain a copyright message.
+# # (Done in two parts because Darwin "git grep" has broken support for compound
+# # exclusion matches.)
+# (grep -L "DO NOT EDIT" $(git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)" -- '*.go') || true) | fail_on_output
```
Comment (easwars) [inline scripts/vet.sh:44]: All of these lines are now commented out. Probably by mistake?

File: scripts/vet.sh [hunk 2]
```diff
@@ -38,160 +38,172 @@ elif [[ "$#" -ne 0 ]]; then
...
 
-# Error for violation of enabled lint rules in config excluding generated code.
-revive \
-  -set_exit_status=1 \
-  -exclude "reflection/test/grpc_testing_not_regenerate/" \
-  -exclude "**/*.pb.go" \
-  -formatter plain \
-  -config "$(dirname "$0")/revive.toml" \
-  ./...
+git status --porcelain 2>&1 | fail_on_output || \
```
Comment (easwars) [inline scripts/vet.sh:206]: Does this mean everytime the deps of any package changes, this check would fail?

File: scripts/vet.sh (hunk 1 above)
Comment (dfawley) [reply scripts/vet.sh]: Argh, sorry!

File: scripts/vet.sh (hunk 2 above)
Comment (dfawley) [reply scripts/vet.sh:206]: Yes, basically..  We can make it easy to regenerate the deps if it's not easy enough (basically just copy/paste this loop onto the commandline).

File: scripts/vet.sh [hunk 3]
```diff
@@ -194,4 +194,16 @@ revive \
...
+# Check dependencies of all non-internal and non-testing packages.
+OUTDIR="$(realpath "$(dirname "$0")")/deps"
+find . -name '*.go' | grep -v '/\(internal\|examples\|benchmark\|interop\|test\|testdata\)/' | xargs dirname | sort -u | while read d; do
+  pushd "$d"
+  pkg="$(echo "$d" | sed 's;^\./;;' | sed 's;\.;grpc;' | sed 's;/;_;g')"
+  go list -deps . | sort >| "${OUTDIR}/$pkg"
+  popd
+done
+
+git status --porcelain 2>&1 | fail_on_output || \
```
Comment (easwars) [inline scripts/vet.sh:206]: We have two places where we currently call `git status --porcelain` and fail if there is non-empty output, and this is the third one. Can/should we make a helper?

**Review by easwars — APPROVED** [review]
I'm fine with the approach here. 

Maybe:
- we just need to make enough noise for code authors and reviewers to be mindful of changes to dependencies
- put the instructions to regenerate deps somewhere accessible (for new folks on the team and for external contributors so that reviewers can point to it easily)?

**Comment by dfawley** [comment]
> put the instructions to regenerate deps somewhere accessible

I added an error message in vet and also made a separate script for generating.  PTAL!

File: scripts/vet.sh (hunk 3 above)
Comment (easwars) [reply scripts/vet.sh:203]: LGTM.

**Review by easwars — APPROVED** [review]
Thanks for making the changes.

**Comment by dfawley** [comment]
Added a new workflow for this instead that turns red when deps change in any way.  Here's what it looks like when there is a failure:

https://github.com/grpc/grpc-go/actions/runs/11489199182/job/31977501207?pr=7766#step:4:19

And here's a pass from this PR:

https://github.com/grpc/grpc-go/actions/runs/11489222235/job/31977569900?pr=7766#step:4:19

I had to temporarily copy the `gen-deps.sh` script into `/tmp` in the workflow, because `upstream/master` doesn't have it yet.  So I could do this as two changes, one that adds the script and one that adds the workflow later, or just delete the indicated lines before merging.  Let me know if you prefer the former.

File: .github/workflows/deps.yml [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: stable
```
Comment (easwars) [inline .github/workflows/deps.yml:27]: Should we explicitly specify the version instead?

File: .github/workflows/deps.yml [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+      - name: Compare dependencies
+        run: |
+          BEFORE="$(mktemp -d)"
+          AFTER="$(mktemp -d)"
+
+          cp scripts/gen-deps.sh /tmp/  # TODO: delete
+          scripts/gen-deps.sh "${AFTER}"
+          git checkout origin/master
+          cp /tmp/gen-deps.sh scripts/  # TODO: delete
+          scripts/gen-deps.sh "${BEFORE}"
```
Comment (easwars) [inline .github/workflows/deps.yml:40]: Would it make sense to add a `grpc-dir` parameter to `gen-deps.sh` that it would use if provided and if not provided, it would simply `cd` to `"${SCRIPTS_DIR}/.."`.

If we have that option, then we could replace this block with
- copy the gen-deps.sh from current branch into /tmp
- run /tmp/gen-deps.sh on `grpc-dir`
- checkout master
- run /tmp/gen-deps.sh on `grpc-dir`

**Comment by easwars** [comment]
We also need a new PR description since we have a new approach now.

File: .github/workflows/deps.yml (hunk 4 above)
Comment (dfawley) [reply .github/workflows/deps.yml:27]: This is zero-maintenance, which is why I did it this way.  I think it's fine since it uses the same version before/after.

File: .github/workflows/deps.yml (hunk 5 above)
Comment (dfawley) [reply .github/workflows/deps.yml:40]: The copying is temporary for the purposes of this PR only.  `origin/master` will have this script as soon as I submit this PR.

File: .github/workflows/deps.yml (hunk 4 above)
Comment (easwars) [reply .github/workflows/deps.yml:27]: Ack.

File: .github/workflows/deps.yml (hunk 5 above)
Comment (easwars) [reply .github/workflows/deps.yml:40]: Ack.

**Review by easwars — APPROVED** [review]
