### PR TITLE
server: add missing conn.Close if the connection dies before reading the HTTP/2 preface

### LINKED ISSUE #4833: Leaking net.Conn
### What version of gRPC are you using?
v1.41.0

### What version of Go are you using (`go version`)?
v1.17.1

### What operating system (Linux, Windows, …) and version?
GOOS=linux, GOARCH=386

### What did you do?
Wrapped the TCP listener passed to `grpc.Serve` with a [net.LimitListener](https://pkg.go.dev/golang.org/x/net/netutil#LimitListener).

### What did you expect to see?
As connections are closed the `net.Conn` returned from `Accept()` gets closed.

### What did you see instead?
Some `net.Conn` connections are not being closed. This behavior combined with a net.LimitListener means the server will eventually exhaust the connection limit and never accept any new connections.

The symptoms I'm seeing are exactly as those described in this other bug report: https://github.com/grpc/grpc-go/issues/4632

My hunch is the the gRPC server is dropping some `net.Conn` without calling `Close` on them. The stdlib net.Conns typically have a finalizer set on them so that they are closed before being garbage collected, but this is not the case for listeners returned by net.LimitListener

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #4833

RELEASE NOTES:
* server: add missing conn.Close if the connection dies before reading the HTTP/2 preface

### CODE REVIEW

File: internal/transport/http2_server.go [hunk 1]
```diff
@@ -293,7 +293,7 @@ func NewServerTransport(conn net.Conn, config *ServerConfig) (_ ServerTransport,
 		// closed immediately by the latter. Skipping the error here will help
```
Comment (menghanl) [inline internal/transport/http2_server.go:293]: Are the comments still valid? Delete them?

Comment (dfawley) [reply internal/transport/http2_server.go]: It was mostly still relevant, but not 100% accurate after the change.  Reworded.

**Review by menghanl — APPROVED** [review]
