### PR TITLE
test: fix flaky TimeoutOnDeadServer test; some cleanups

### LINKED ISSUE #4766: Flaky test: TimeoutOnDeadServer
https://github.com/grpc/grpc-go/pull/4753/checks?check_run_id=3588365780

```
--- FAIL: Test (146.14s)
    --- FAIL: Test/TimeoutOnDeadServer (0.17s)
        end2end_test.go:947: Running test in tcp-clear-v1-balancer environment...
        tlogger.go:101: clientconn.go:175 [core] Channel Created  (t=+1.236807ms)
        tlogger.go:101: clientconn.go:252 [core] parsed scheme: "passthrough"  (t=+1.387108ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:37303  <nil> 0 <nil>}] <nil> <nil>}  (t=+1.621509ms)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:37303 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+1.73871ms)
        tlogger.go:101: clientconn.go:728 [core] ClientConn switching balancer to "pick_first"  (t=+1.887411ms)
        tlogger.go:101: clientconn.go:748 [core] Channel switches to new LB policy "pick_first"  (t=+1.982812ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel Created  (t=+2.131813ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel(id:3366) created  (t=+2.168613ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+2.399514ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "localhost:37303" to connect  (t=+2.804417ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+3.124419ms)
        tlogger.go:101: picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+3.34132ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+5.289132ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to READY  (t=+5.647934ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to IDLE  (t=+9.501658ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to IDLE  (t=+9.84716ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+10.477464ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "localhost:37303" to connect  (t=+10.799666ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+11.255668ms)
        tlogger.go:101: clientconn.go:1325 [core] grpc: addrConn.createTransport failed to connect to {localhost:37303 localhost:37303 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:37303: connect: connection refused"  (t=+13.513382ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to TRANSIENT_FAILURE  (t=+13.860684ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to TRANSIENT_FAILURE  (t=+14.157086ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+63.200286ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+63.80319ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchannel Deleted  (t=+64.106991ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchanel(id:3366) deleted  (t=+64.206792ms)
        tlogger.go:101: clientconn.go:1098 [core] Channel Deleted  (t=+64.342093ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3366 from a parent (id=3364) that doesn't currently exist  (t=+64.426993ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3366 from a parent (id=3364) that doesn't currently exist  (t=+64.468894ms)
        end2end_test.go:947: Running test in tcp-tls-v1-balancer environment...
        tlogger.go:101: clientconn.go:175 [core] Channel Created  (t=+67.459712ms)
        tlogger.go:101: clientconn.go:252 [core] parsed scheme: "passthrough"  (t=+67.558812ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:46479  <nil> 0 <nil>}] <nil> <nil>}  (t=+67.675813ms)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:46479 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+67.737214ms)
        tlogger.go:101: clientconn.go:728 [core] ClientConn switching balancer to "pick_first"  (t=+67.841114ms)
        tlogger.go:101: clientconn.go:748 [core] Channel switches to new LB policy "pick_first"  (t=+67.905415ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel Created  (t=+68.096116ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel(id:3372) created  (t=+68.147316ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+68.364817ms)
        tlogger.go:101: picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+68.76302ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+68.911521ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "localhost:46479" to connect  (t=+69.133622ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+99.86821ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to READY  (t=+100.352713ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to IDLE  (t=+104.669239ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to IDLE  (t=+105.006741ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+105.558045ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "localhost:46479" to connect  (t=+105.859447ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+106.036148ms)
        tlogger.go:101: clientconn.go:1325 [core] grpc: addrConn.createTransport failed to connect to {localhost:46479 x.test.example.com <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:46479: connect: connection refused"  (t=+107.570957ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to TRANSIENT_FAILURE  (t=+107.857259ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to TRANSIENT_FAILURE  (t=+108.181361ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+157.882265ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+158.426568ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchannel Deleted  (t=+158.657469ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchanel(id:3372) deleted  (t=+158.70087ms)
        tlogger.go:101: clientconn.go:1098 [core] Channel Deleted  (t=+158.864271ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3372 from a parent (id=3371) that doesn't currently exist  (t=+158.988971ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3372 from a parent (id=3371) that doesn't currently exist  (t=+159.096572ms)
        end2end_test.go:947: Running test in tcp-clear environment...
        tlogger.go:101: clientconn.go:175 [core] Channel Created  (t=+160.188079ms)
        tlogger.go:101: clientconn.go:252 [core] parsed scheme: "passthrough"  (t=+160.35548ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{localhost:40369  <nil> 0 <nil>}] <nil> <nil>}  (t=+160.46068ms)
        tlogger.go:101: resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:localhost:40369 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+160.554081ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel Created  (t=+160.705982ms)
        tlogger.go:101: clientconn.go:789 [core] Subchannel(id:3377) created  (t=+160.768182ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+161.117784ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "localhost:40369" to connect  (t=+161.539587ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+161.739188ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+165.414611ms)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: Build called with info: {map[0xc0006095e0:{{localhost:40369  <nil> 0 <nil>}}]}  (t=+165.789313ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to IDLE  (t=+171.712549ms)
        end2end_test.go:974: TestService/EmptyCall(context.Background.WithDeadline(2021-09-13 14:49:43.165555235 +0000 UTC m=+338.765299609 [-500.009µs]), _) = _, rpc error: code = Unavailable desc = error reading from server: EOF, want _, error code: DeadlineExceeded
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+172.590454ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+173.074557ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchannel Deleted  (t=+173.238758ms)
        tlogger.go:101: clientconn.go:1496 [core] Subchanel(id:3377) deleted  (t=+173.298559ms)
        tlogger.go:101: clientconn.go:1098 [core] Channel Deleted  (t=+173.398559ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3377 from a parent (id=3376) that doesn't currently exist  (t=+173.46246ms)
        tlogger.go:101: types.go:68 [channelz] attempt to delete child with id 3377 from a parent (id=3376) that doesn't currently exist  (t=+173.53426ms)
FAIL
FAIL	google.golang.org/grpc/test	340.952s
```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #4766

- Wait for READY before stopping the server: the picker is updated before the state, so we can race and complete the RPC AND still see a not-yet-READY state from the CC even after the server is stopped.
- Add helpers for waiting for state changes.
- Employ them in all existing uses.
- Remove log noise declarations that don't even exist anymore.
- Use standardized timeouts in more places.

RELEASE NOTES: none

### CODE REVIEW

File: test/clientconn_state_transition_test.go [hunk 1]
```diff
@@ -519,3 +519,21 @@ func stayConnected(ctx context.Context, cc *grpc.ClientConn) {
 		}
 	}
 }
+
+func awaitState(ctx context.Context, t *testing.T, cc *grpc.ClientConn, stateWant connectivity.State) {
+	t.Helper()
+	for state := cc.GetState(); state != stateWant; state = cc.GetState() {
+		if !cc.WaitForStateChange(ctx, state) {
+			t.Fatalf("timed out waiting for state change.  got %v; want %v", state, stateWant)
```
Comment (arvindbr8) [inline test/clientconn_state_transition_test.go:527]: nit:
```suggestion
			t.Fatalf("timed out waiting for state change. got %v; want %v", state, stateWant)
```

File: test/clientconn_state_transition_test.go [hunk 2]
```diff
@@ -519,3 +519,21 @@ func stayConnected(ctx context.Context, cc *grpc.ClientConn) {
...
+		}
+	}
+}
+
+func awaitNotState(ctx context.Context, t *testing.T, cc *grpc.ClientConn, stateDoNotWant connectivity.State) {
+	t.Helper()
+	for state := cc.GetState(); state == stateDoNotWant; state = cc.GetState() {
+		if !cc.WaitForStateChange(ctx, state) {
+			t.Fatalf("timed out waiting for state change.  got %v; want NOT %v", state, stateDoNotWant)
```
Comment (arvindbr8) [inline test/clientconn_state_transition_test.go:536]:
```suggestion
			t.Fatalf("timed out waiting for state change. got %v; want NOT %v", state, stateDoNotWant)
```

**Review by arvindbr8 — APPROVED** [review]
LGTM overall. Only 2 nits and a question.

File: test/clientconn_state_transition_test.go (hunk 1 above)
Comment (dfawley) [reply test/clientconn_state_transition_test.go:527]: No! Two spaces after periods is the way!

File: test/clientconn_state_transition_test.go [hunk 3]
```diff
@@ -519,3 +519,21 @@ func stayConnected(ctx context.Context, cc *grpc.ClientConn) {
 		}
 	}
 }
+
+func awaitState(ctx context.Context, t *testing.T, cc *grpc.ClientConn, stateWant connectivity.State) {
+	t.Helper()
+	for state := cc.GetState(); state != stateWant; state = cc.GetState() {
```
[the remark this answers is not in the document]
Comment (dfawley) [reply test/clientconn_state_transition_test.go:525]: No need.  The WaitForStateChange checks it and returns false when it expires.
