### PR TITLE
xds_client/rds: weighted_cluster totalWeight default to 100

### LINKED ISSUE #4432: xds RDS weighted_cluster totalWeight default 100
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

latest version

https://github.com/grpc/grpc-go/blob/master/xds/internal/client/xds.go#L525

### What version of Go are you using (`go version`)?

1.16

### What operating system (Linux, Windows, …) and version?

macOS

### What did you expect to see?

not return NACK

xds weighted_cluster DOC:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=weighted_clusters#config-route-v3-weightedcluster

### What did you see instead?

`WARNING: 2021/05/13 14:57:03 [xds] [xds-client 0xc0002a6d00] Sending NACK for response type: RouteConfigResource, version: 2021-05-13T14:54:33+08:00/9, nonce: tR5YMAcCo6M=1b2e0689-8aa9-43af-9fa5-abdf340a0864, reason: error parsing "RDS" response: xxx... route:{weighted_clusters:{clusters:{name:"outbound|50002|aaaaaasssss|xxx" weight:{value:36}} clusters:{name:"outbound|50002|efwewef|xxx" weight:{value:13}} clusters:{name:"outbound|50002|efsegwsefwefwe|xxx" weight:{value:14}} clusters:{name:"outbound|50002|sdrgsfsefewf|xxx" weight:{value:31}} clusters:{name:"outbound|50002|dfefwewe|xxx" weight:{value:6}}} timeout:{} retry_policy:{retry_on:"connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes" num_retries:{value:2} retry_host_predicate:{name:"envoy.retry_host_predicates.previous_hosts"} host_selection_retry_max_attempts:5 retriable_status_codes:503}} metadata:{filter_metadata:{key:"istio" value:{fields:{key:"config" value:{string_value:"/apis/networking.istio.io/v1alpha3/namespaces/jsfns/virtual-service/xxx"}}}}} decorator:{operation:"xxx/*"}, action &{WeightedClusters:clusters:{name:"outbound|50002|aaaaaasssss|xxx" weight:{value:36}} clusters:{name:"outbound|50002|efwewef|xxx" weight:{value:13}} clusters:{name:"outbound|50002|efsegwsefwefwe|xxx" weight:{value:14}} clusters:{name:"outbound|50002|sdrgsfsefewf|xxx" weight:{value:31}} clusters:{name:"outbound|50002|dfefwewe|xxx" weight:{value:6}}}, weights of clusters do not add up to total total weight, got: 0, want 100`

If you also think this is a bug, I'm happy to commit a PR to fix it

### PR DESCRIPTION
**Pull request by alpha-baby**
Signed-off-by: alpha-baby <fujianhao1997@qq.com>

fixes #4432

### CODE REVIEW

**Comment by alpha-baby** [comment]
thx, review @menghanl

File: xds/internal/client/rds_test.go [hunk 1]
```diff
@@ -1077,6 +1077,71 @@ func (s) TestRoutesProtoToSlice(t *testing.T) {
...
+				{
+					Match: &v3routepb.RouteMatch{
+						PathSpecifier: &v3routepb.RouteMatch_Prefix{Prefix: "/a/"},
+					},
+					Action: &v3routepb.Route_Route{
+						Route: &v3routepb.RouteAction{
+							ClusterSpecifier: &v3routepb.RouteAction_WeightedClusters{
+								WeightedClusters: &v3routepb.WeightedCluster{
+									Clusters: []*v3routepb.WeightedCluster_ClusterWeight{
+										{Name: "B", Weight: &wrapperspb.UInt32Value{Value: 0}},
```
Comment (menghanl) [inline xds/internal/client/rds_test.go:1092]: Set weights to some positive numbers (like 20 and 30, as long as they don't sum to 100)?
I think `weight: 0` causes another error, so this isn't testing what we want.

File: xds/internal/client/xds.go [hunk 2]
```diff
@@ -522,7 +522,7 @@ func routesProtoToSlice(routes []*v3routepb.Route, logger *grpclog.PrefixLogger,
 				route.WeightedClusters[c.GetName()] = wc
 				totalWeight += w
 			}
-			if totalWeight != wcs.GetTotalWeight().GetValue() {
+			if totalWeight != 100 && (wcs.GetTotalWeight() == nil || totalWeight != wcs.GetTotalWeight().GetValue()) {
```
Comment (menghanl) [inline xds/internal/client/xds.go:525]: This should work. But let's change it a little bit for readability, and more accurate error message

```go
wantTotalWeight := 100
if tw := wcs.GetTotalWeight(); tw != nil {
  wantTotalWeight = tw.GetValue()
}
if totalWeight != wantTotalWeight {
  return nil, fmt.Errorf("route %+v, action %+v, weights of clusters do not add up to total total weight, got: %v, expected total weight from response: %v", r, a, totalWeight, wantTotalWeight)
}
```

**Review by menghanl — CHANGES_REQUESTED** [review]

File: xds/internal/client/xds.go (hunk 2 above)
Comment (alpha-baby) [reply xds/internal/client/xds.go]: thx, resolved

File: xds/internal/client/xds.go [hunk 3]
```diff
@@ -522,8 +522,13 @@ func routesProtoToSlice(routes []*v3routepb.Route, logger *grpclog.PrefixLogger,
 				route.WeightedClusters[c.GetName()] = wc
 				totalWeight += w
 			}
-			if totalWeight != 100 && (wcs.GetTotalWeight() == nil || totalWeight != wcs.GetTotalWeight().GetValue()) {
-				return nil, fmt.Errorf("route %+v, action %+v, weights of clusters do not add up to total total weight, got: %v, want %v", r, a, wcs.GetTotalWeight().GetValue(), totalWeight)
+			// default TotalWeight https://github.com/grpc/grpc-go/issues/4432
```
Comment (menghanl) [inline xds/internal/client/xds.go:525]: Nit: let's update the link to https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-field-config-route-v3-weightedcluster-total-weight, instead of the issue

**Review by menghanl — CHANGES_REQUESTED** [review]
Thanks for the fix. LGTM.

One last comment about the link.

**Review by menghanl — APPROVED** [review]
