### PR TITLE
Separate incoming and outgoing metadata in context

### LINKED ISSUE #1148: When a GRPC server also uses GRPC client when handling request, Metadata is handled incorrectly
If I implement a GRPC server, and the handler method also uses a GRPC client stub, bad things can happen. The are two distinct problems with how metadata is currently handled:

1. The way values are conditionally encoded/decoded causes downstream errors (`"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: 1"`).
2. Since server and client metadata use the same context key, all incoming metadata (to a server action) are automatically propagated to downstream services.

## Encoding Errors

The current `metadata.MD` has strange bimodal behavior.

1. As a client, it stores *encoded* values. When creating metadata (via `metadata.Pairs`), binary headers are properly encoded.
2. As a server, it stores *decoded* values. When processing the HTTP/2 header frame, the server calls `metadata.DecodeKeyValue`. Reading the data means just using the metadata as a map.

So, when using binary headers, having program A invoke method B which in turn invokes method C generates an error in the server hosting method C. The reason is that it ultimately tries to double-decode the header -- which means it's putting inappropriate content on the wire in the header from from method B to C, which subsequently cannot be decoded.

* A creates the metadata. The values are encoded on creation.
* GRPC client invoked by A transmits the encoded values.
* GRPC server for B receives the metadata and decodes the values.
* GRPC client invoked by B  transmits the values, *which are no longer encoded*.
* GRPC server for C receives bad headers. Boom.

I have not verified it, but I assume an analogous flow exists for response metadata going the other direction and that flow suffers from the same problem.

## Incorrect Propagation

In the above example, of A calling B calling C, I don't actually even *want* B to send the same metadata to C that it received from A (even if it didn't cause the protocol errors). Metadata are equivalent to HTTP headers. No library I know of automatically propagates incoming HTTP headers to outgoing HTTP requests, and for good reason. A piece of metadata is generally scoped to that single request.

There *are* some kinds of cross-cutting metadata that often *should* be propagated -- like tracing context and authentication tokens. But this should be explicit -- like either via a whitelist *or* by having servers use interceptors that explicitly propagate the relevant metadata.

## Solution

One cause of both of these issues is that the API for handling metadata does not distinguish between incoming request metadata (for use by server) and outgoing request metadata. Simply having different APIs (`metadata.FromServerContext` and `metadata.FromClientContext`) that use different context keys under the hood would solve both issues.

Another option that would solve both issues would be to change the actual type of `metadata.MD` so that the map keys aren't just strings but are simple tuples of both the name and a flag (e.g. `isServer`). This allows code to properly distinguish and handle appropriately, including whether or not to encode/decode for the wire and whether or not to propagate. If it is deemed appropriate to propagate server metadata to client metadata for the server's outgoing requests, the library could at least provide an option to control what is propagated (like a filter/whitelist/blacklist for what metadata names to propagate).

Another change that is orthogonal to the suggestions above would also make the API much more useful (but, alone, would only fix the encoding issue). That change is to leave all data in the metadata map decoded. Instead of having `metadata.Pairs` encode them, defer that and let the transport encode them when putting them on the wire. This removes the odd bimodal nature. This allows, for example, a client interceptor to easily examine client metadata without having to first decode the values in the map.

### PR DESCRIPTION
**Pull request by dfawley**
This will prevent the incoming RPCs' metadata from appearing in outgoing RPCs
unless it is explicitly copied, e.g.:

incomingMD, ok := metadata.FromContext(ctx)
if ok {
  ctx = metadata.NewContext(ctx, incomingMD)
}

Fixes #1148

### CODE REVIEW

**Comment by dfawley** [comment]
I would appreciate some advice for how/where to test this change.

File: metadata/metadata.go [hunk 1]
```diff
@@ -136,17 +136,31 @@ func Join(mds ...MD) MD {
 	return out
 }
 
-type mdKey struct{}
+type mdIncomingKey struct{}
+type mdOutgoingKey struct{}
 
-// NewContext creates a new context with md attached.
+// NewContext creates a new context with outgoing md attached.
```
Comment (dfawley) [inline metadata/metadata.go]: Done

**Comment by dfawley** [comment]
PTAL, thanks!

**Comment by tsuna** [comment]
This change broke backward compatibility, I filed #1178 to track the issue.

**Comment by elvizlai** [comment]
Wow, this changes broke backward compatibility, especially our trace system.

Every request has a trace-id set to ctx.

For example, service A call B, B call C and then B resp to A.

We do not need handle ctx in v1.2.1.
But now we need to get MD from ctx received in B and put it into a new ctx before we call C.

**Comment by dfawley** [comment]
This is considered a fix for a fairly serious security bug.  Automatically forwarding information between services was never intentional.  Even so, I am sorry this change caused problems for you, and I apologize for not announcing it more broadly before it was merged.  We are working to improve our communication, and we will use this as an example of things we can do better.

**Comment by peter-edge** [comment]
I can confirm this is very breaking, I had to hunt down this PR using git blame unfortunately :(

**Comment by c4milo** [comment]
This change also broke my code.
