### PR TITLE
dns: fix constant 30s backoff for re-resolution

### LINKED ISSUE #7186: Delayed dns resolve after upgrade to v1.60.0
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
1.60.0

### What version of Go are you using (`go version`)?
1.22

### What operating system (Linux, Windows, …) and version?
Ubuntu 22.04

### What did you do?
Upgrade from v1.59.0 to v1.60.0 for grpc client service.
Clients now take 30 seconds to re-resolve upstream services on connection error (server shutting down).

### What did you expect to see?
During deploy of upstream _grpc server_ I expect to see no request failing due to delayed DNS resolve in the _grpc client_. New IP should instantly be resolved after first `connection refused error: transport`.

Example (from v1.59.0):
```
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to IDLE
2024/05/02 13:45:19 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[]}
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to IDLE
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to CONNECTING
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel picks a new address "10.0.0.20:8000" to connect
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING
2024/05/02 13:45:19 WARNING: [core] [Channel #1 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.20:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.20:8000: connect: connection refused"
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.20:8000: connect: connection refused"
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to TRANSIENT_FAILURE
2024/05/02 13:45:19 INFO: [core] [Channel #1] Resolver state updated: {
"Addresses": [
{
"Addr": "10.0.0.40:8000",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
}
],
"Endpoints": [
{
"Addresses": [
{
"Addr": "10.0.0.40:8000",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
}
],
"Attributes": null
}
],
"ServiceConfig": null,
"Attributes": null
} ()
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #7] Subchannel created
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to SHUTDOWN
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #4] Subchannel deleted
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to IDLE
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #7] Subchannel Connectivity change to CONNECTING
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #7] Subchannel picks a new address "10.0.0.40:8000" to connect
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING
2024/05/02 13:45:19 INFO: [core] [Channel #1 SubChannel #7] Subchannel Connectivity change to READY
2024/05/02 13:45:19 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[SubConn(id:7):{{Addr: "10.0.0.40:8000", ServerName: "", }}]}
2024/05/02 13:45:19 INFO: [core] [Channel #1] Channel Connectivity change to READY
```

### What did you see instead?
Tested with `v1.60.0` and `v1.63.2`.

During deploy of upstream _grpc server_ it's a 30 second delay between the first failing request until the new IP is resolved (see logs below). 

I've tested this with both single and multiple instance setup for both grpc client and server. We've seen this error for services using a grpc client.

By testing each commit in `v1.60.0` I found that the patch from PR https://github.com/grpc/grpc-go/pull/6668 was the first commit that caused this behavior.

Logs output from during deploy of upstream grpc server (`v1.60.0`):
```
2024/05/02 12:42:42 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE
2024/05/02 12:42:42 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[]}
2024/05/02 12:42:42 INFO: [core] [Channel #1] Channel Connectivity change to IDLE
2024/05/02 12:42:42 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:42 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:42:42 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING
2024/05/02 12:42:42 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:42 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:42 INFO: [core] [Channel #1] Channel Connectivity change to TRANSIENT_FAILURE
2024/05/02 12:42:43 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:43 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:43 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:42:43 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:43 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:44 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:44 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:44 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:42:44 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:44 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:47 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:47 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:47 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:42:47 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:47 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:51 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:51 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:51 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:42:51 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:51 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:56 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: connect: connection refused"
2024/05/02 12:42:56 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to CONNECTING
2024/05/02 12:42:56 INFO: [core] [Channel #1 SubChannel #2] Subchannel picks a new address "10.0.0.140:8000" to connect
2024/05/02 12:43:12 INFO: [core] [Channel #1] Resolver state updated: {
"Addresses": [
{
"Addr": "10.0.0.160:8000",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
}
],
"Endpoints": [
{
"Addresses": [
{
"Addr": "10.0.0.160:8000",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
}
],
"Attributes": null
}
],
"ServiceConfig": null,
"Attributes": null
} ()
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #4] Subchannel created
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #2] Subchannel Connectivity change to SHUTDOWN
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #2] Subchannel deleted
2024/05/02 12:43:12 INFO: [core] [Channel #1] Channel Connectivity change to IDLE
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to CONNECTING
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #4] Subchannel picks a new address "10.0.0.160:8000" to connect
2024/05/02 12:43:12 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING
2024/05/02 12:43:12 WARNING: [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {Addr: "10.0.0.140:8000", ServerName: "our.interal.domain:8000", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.0.0.140:8000: operation was canceled"
2024/05/02 12:43:12 INFO: [core] [Channel #1 SubChannel #4] Subchannel Connectivity change to READY
2024/05/02 12:43:12 INFO: [roundrobin] roundrobinPicker: Build called with info: {map[SubConn(id:4):{{Addr: "10.0.0.160:8000", ServerName: "", }}]}
2024/05/02 12:43:12 INFO: [core] [Channel #1] Channel Connectivity change to READY
```

Common client setup for reference:
```go
keepAliveParameters := keepalive.ClientParameters{
  Time:                10 * time.Second,
  Timeout:             time.Second,    
  PermitWithoutStream: true,          
}
defaultServiceConfig := `{"loadBalancingConfig": [{"round_robin":{}}]}`
resolver.SetDefaultScheme("dns")
ctx := context.Background()
ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
defer cancel()
conn, err := grpc.DialContext(ctx,
  "our.interal.domain",
  grpc.WithTransportCredentials(insecure.NewCredentials()),
  grpc.WithBlock(),
  grpc.WithKeepaliveParams(grpchelper.keepAliveParameters),
  grpc.WithDefaultServiceConfig(defaultServiceConfig),
)
```

### PR DESCRIPTION
**Pull request by purnesh42H**
Fixes #7186 with a test

RELEASE NOTES:

- dns: fix bug that was causing constant 30s backoff between every resolution request

### CODE REVIEW

**Comment by purnesh42H** [comment]
```
1st resolve sent 2024-05-23 20:30:01.870812 +0530 IST m=+0.045272043
    /Users/purneshdixit/Google/Dev/grpc-go/internal/resolver/dns/resolver.go:49: testutils.ResolverClientConn: UpdateState({
          "Addresses": [
            {
              "Addr": "1.2.3.4:443",
              "ServerName": "",
              "Attributes": null,
              "BalancerAttributes": null,
              "Metadata": null
            }
          ],
          "Endpoints": null,
          "ServiceConfig": {
            "Config": {
              "Config": null,
              "Methods": {}
            },
            "Err": null
          },
          "Attributes": null
        })
1st resolve completed 2024-05-23 20:30:11.873234 +0530 IST m=+10.047680376
```

```
2nd resolve sent 2024-05-23 20:30:11.873274 +0530 IST m=+10.047720751
    /Users/purneshdixit/Google/Dev/grpc-go/internal/resolver/dns/resolver.go:49: testutils.ResolverClientConn: UpdateState({
          "Addresses": [],
          "Endpoints": null,
          "ServiceConfig": {
            "Config": {
              "Config": null,
              "Methods": {}
            },
            "Err": null
          },
          "Attributes": null
        })
2nd resolve completed 2024-05-23 20:30:11.87365 +0530 IST m=+10.048096043
```

**Comment by sebastianjonasson** [comment]
I've tested this and can confirm that it resolves the issue described in https://github.com/grpc/grpc-go/issues/7186.

File: internal/resolver/dns/dns_resolver_test.go [hunk 1]
```diff
@@ -1290,3 +1290,45 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
 	}
 }
+
+// TestMinResolutionInterval_NoExtraDelay verifies that there is no extra delay
+// between two resolution requests apart from [MinResolutionInterval]
+// i.e. if a request is made after [MinResolutionInterval], it should resolve
+// immediately. Test sets [MinResolutionInterval] to 1 second and calls
+// ResolveNow() 4 times with a wait of 1 second between each request.
+// A correct implementation should resolve all requests without timing out in
+// test duration of 5 seconds.
```
Comment (arjan-bal) [inline internal/resolver/dns/dns_resolver_test.go:1300]: nit: The implementation details of the test can be mentioned in comments inside the test, only an overview is sufficient for the doc string.

File: internal/resolver/dns/dns_resolver_test.go [hunk 2]
```diff
@@ -1290,3 +1290,45 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+func (s) TestMinResolutionInterval_NoExtraDelay(t *testing.T) {
```
Comment (arjan-bal) [inline internal/resolver/dns/dns_resolver_test.go:1301]: This is very similar to the previous test, can we combine the two?

File: internal/resolver/dns/dns_resolver_test.go [hunk 3]
```diff
@@ -1290,3 +1290,45 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+	// to make sure all 4 resolutions happen successfully
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
+
+	// We chose to make 4 requests to strike a balance between coverage and
+	// test duration. This number is sufficiently large to validate the
+	// behavior across multiple resolution attempts, while also reducing
+	// the likelihood of flakiness due to timing issues.
+	for i := 0; i < 4; i++ {
+		verifyUpdateFromResolver(ctx, t, stateCh, wantAddrs, nil, wantSC)
```
Comment (arjan-bal) [inline internal/resolver/dns/dns_resolver_test.go:1330]: Using validation is not idiomatic in go, see [best practices](https://google.github.io/styleguide/go/best-practices#leave-testing-to-the-test-function). 

>arrange the validation function so that it returns a value (typically an error) rather than taking a testing.T parameter and using it to fail the test

**Comment by purnesh42H** [comment]
No failures in 100K forge

File: internal/resolver/dns/dns_resolver_test.go (hunk 3 above)
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go:1330]: do you mean `verifyUpdateFromResolver`? It looks like its being used for all the tests

Comment (arjan-bal) [reply internal/resolver/dns/dns_resolver_test.go:1330]: Since this is an existing deviation from the style guide, [the recommendation](https://google.github.io/styleguide/go/guide#local-consistency) is to open an issue to track the fix. Since this doesn't expose the issue to more files, it should be fine to not use `verifyUpdateFromResolver` in this PR.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (arjan-bal) [reply internal/resolver/dns/dns_resolver_test.go:1300]: The following lines mention "what" the function is doing and not "why" its doing something.
>Test sets [MinResolutionInterval] to 1 second and calls ResolveNow() 4 times with a wait of 1 second between each request. A correct implementation should resolve all requests without timing out in test duration of 5 seconds.

Based on the [style guide]:
>It is also important to be aware that some attempts to provide clarity (such as adding extra commentary) can actually obscure the code’s purpose by adding clutter, restating what the code already says, contradicting the code, or adding maintenance burden to keep the comments up-to-date. Allow the code to speak for itself (e.g., by making the symbol names themselves self-describing) rather than adding redundant comments. It is often better for comments to explain why something is done, not what the code is doing.

**Comment by easwars** [comment]
@purnesh42H : This PR definitely needs a release note because we are fixing a bug that we introduced.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1300]: When I rewrote a whole bunch of tests, I eventually landed on the following approach:
- the test level comment would say at a very high level *what* the test is testing. It will also say at a very high level *what* operations the test is performing, and *what* is expects to see.
  - this helps readers of the test to get to know what is going on very quickly (and without reading the test) 
- then, i either put in comments or calls to `t.Log` for every logical block in the test
  - eg: start a management server, start test backends, configure `pick_first` LB policy on the channel, make RPC and expect it to fail with UNAVAILABLE etc
  - this approach also allows the reader to follow the test along very quickly without reading the code
  - and using `t.Logf` instead of comments sometimes can make debugging easy, since you will see those high level events in the test output when it fails

File: internal/resolver/dns/dns_resolver_test.go [hunk 4]
```diff
@@ -1290,3 +1290,45 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+		time.Sleep(1 * time.Second) // respect resolution rate of 1 second for re-resolve
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1331]: We try to avoid sleeping in our tests as much as possible. Sleeping causes the tests to unnecessarily flaky, and run for longer than actually required.

Instead, if you override `internal.TimeAfterFunc`, you can control exactly when this function pushes something on the channel read by the code. This way, you can avoid sleeping as well.

There is currently an `overrideTimeAfterFunc` helper function, but this sets the `after func` to be invoked after a set duration. Instead you can override `internal.TimeAfterFunc` to return a channel that is controlled by the test, and have it push to it whenever it wants the code under test to be unblocked.

File: internal/resolver/dns/dns_resolver_test.go (hunk 3 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1330]: We sometimes break this recommendation in the style guide asking us to not write validation functions, especially in cases where the function is going to be invoked a lot of times, and we can avoid:

```
if err := validateFoo(); err != nil {
  t.Fatal(err)
  }
```

And instead just do:
```
validateFoo(t)
```

But we do want to ensure that when we do this:
- the function is not exported, and is clearly documented
- the call site is readable, and the reader can figure out reasonably well what is happening here

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go:1300]: > the test level comment would say at a very high level what the test is testing. It will also say at a very high level what operations the test is performing, and what is expects to see.

I think the existing comments more a less follows this

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go]: I don't think we should overriding `internal.TimeAfterFunc` because we want to test the actual implementation work correctly with `MinResolutionInterval`. Here, we just want to wait outside for 1 second before making another request so I just replaced `time.Sleep` with a channel using `time.After`

**Comment by purnesh42H** [comment]
> @purnesh42H : This PR definitely needs a release note because we are fixing a bug that we introduced.

yes, i was thinking about it too. I added

**Review by arjan-bal — APPROVED** [review]

File: internal/resolver/dns/dns_resolver_test.go [hunk 5]
```diff
@@ -1290,3 +1290,55 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+
+// TestMinResolutionInterval_NoExtraDelay verifies that there is no extra delay
+// between two resolution requests apart from [MinResolutionInterval]
+// i.e. if a request is made after [MinResolutionInterval], it should resolve
+// immediately. Test sets [MinResolutionInterval] to 1 second and calls
+// ResolveNow() 4 times with a wait of 1 second between each request.
+// A correct implementation should resolve all requests without timing out in
+// test duration of 5 seconds.
+func (s) TestMinResolutionInterval_NoExtraDelay(t *testing.T) {
+	const target = "foo.bar.com"
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1302]: This const is only used in one place. Why not just inline it?

File: internal/resolver/dns/dns_resolver_test.go [hunk 6]
```diff
@@ -1290,3 +1290,55 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+
+	r, stateCh, _ := buildResolverWithTestClientConn(t, target)
+
+	wantAddrs := []resolver.Address{{Addr: "1.2.3.4" + colonDefaultPort}, {Addr: "5.6.7.8" + colonDefaultPort}}
+	wantSC := scJSON
+
+	// set context timeout to test duration of 5 seconds
+	// to make sure all 4 resolutions happen successfully
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1323]: Use `defaultTestTimeout` instead of hard coding to `5s`. Also, get rid of the comment.

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go]: No, we don't want this test to run for 4+ seconds.

Instead I suggest the following:
- Define a variable for `internal.TimeNowFunc`, just like how it is done for `internal.TimeAfterFunc` 
  - set this variable to `time.Now` in the `init` function
- Override this variable to return a time value that you control in your test
- Override `internal.TimeAfterFunc` in your test and verify that it is called with the expected duration

Let me know if this doesn't work.

Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go]: Thanks for suggestion. Modified the test to override `time.Until` to calculate remaining wait to allow resolution after 1s i.e. equivalent of making re-resolution after 1s and verify the expected wait duration is very small.

File: internal/resolver/dns/dns_resolver_test.go
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1]: This is what I'm asking for. With this approach, the test controls everything, and it does not even have to override the min resolution interval. Let me know what you think.

```
diff --git a/internal/resolver/dns/dns_resolver.go b/internal/resolver/dns/dns_resolver.go
index 8c5c75c8..7f08c5c5 100644
--- a/internal/resolver/dns/dns_resolver.go
+++ b/internal/resolver/dns/dns_resolver.go
@@ -62,6 +62,7 @@ var (
 
 func init() {
 	resolver.Register(NewBuilder())
+	internal.TimeNowFunc = time.Now
 	internal.TimeAfterFunc = time.After
 	internal.TimeUntilFunc = time.Until
 	internal.NewNetResolver = newNetResolver
@@ -215,7 +216,7 @@ func (d *dnsResolver) watcher() {
 			// Success resolving, wait for the next ResolveNow. However, also wait 30
 			// seconds at the very least to prevent constantly re-resolving.
 			backoffIndex = 1
-			nextResolutionTime = time.Now().Add(MinResolutionInterval)
+			nextResolutionTime = internal.TimeNowFunc().Add(MinResolutionInterval)
 			select {
 			case <-d.ctx.Done():
 				return
@@ -224,7 +225,7 @@ func (d *dnsResolver) watcher() {
 		} else {
 			// Poll on an error found in DNS Resolver or an error received from
 			// ClientConn.
-			nextResolutionTime = time.Now().Add(backoff.DefaultExponential.Backoff(backoffIndex))
+			nextResolutionTime = internal.TimeNowFunc().Add(backoff.DefaultExponential.Backoff(backoffIndex))
 			backoffIndex++
 		}
 		select {
diff --git a/internal/resolver/dns/dns_resolver_test.go b/internal/resolver/dns/dns_resolver_test.go
index e672c673..5cefab2f 100644
--- a/internal/resolver/dns/dns_resolver_test.go
+++ b/internal/resolver/dns/dns_resolver_test.go
@@ -1306,7 +1306,6 @@ func (s) TestMinResolutionInterval(t *testing.T) {
 // calculate remaining time to allow resolution after 1s and verifies that
 // remaining time to allow resolution is very small
 func (s) TestMinResolutionInterval_NoExtraDelay(t *testing.T) {
-	durChan, timeChan := overrideTimeAfterFuncWithChannel(t)
 	tr := &testNetResolver{
 		hostLookupTable: map[string][]string{
 			"foo.bar.com": {"1.2.3.4", "5.6.7.8"},
@@ -1316,13 +1315,31 @@ func (s) TestMinResolutionInterval_NoExtraDelay(t *testing.T) {
 		},
 	}
 	overrideNetResolver(t, tr)
-	var minResolutionInterval = 1 * time.Second
-	overrideResolutionInterval(t, minResolutionInterval)
+
+	// Override time.Now() to return a zero value for time. This will allow us
+	// to verify that the call to time.Until is made with the exact
+	// [minResolutionInterval] that we expect.
+	origTimeNowFunc := dnsinternal.TimeNowFunc
+	dnsinternal.TimeNowFunc = func() time.Time { return time.Time{} }
+	t.Cleanup(func() { dnsinternal.TimeNowFunc = origTimeNowFunc })
+
+	// Override time.Until() to push the time value passed to it, and return
+	// immediately without delay.
+	timeCh := make(chan time.Time, 1)
+	origTimeUntil := dnsinternal.TimeUntilFunc
+	dnsinternal.TimeUntilFunc = func(t time.Time) time.Duration {
+		timeCh <- t
+		return 0
+	}
+	t.Cleanup(func() { dnsinternal.TimeUntilFunc = origTimeUntil })
+
+	// Override time.After() to return immediately, without delay.
+	overrideTimeAfterFunc(t, 0)
 
 	r, stateCh, errorCh := buildResolverWithTestClientConn(t, "foo.bar.com")
 
-	ctx, ctxCancel := context.WithTimeout(context.Background(), defaultTestTimeout)
-	defer ctxCancel()
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
 	select {
 	case <-ctx.Done():
 		t.Fatal("Timeout when waiting for DNS resolver")
@@ -1331,25 +1348,21 @@ func (s) TestMinResolutionInterval_NoExtraDelay(t *testing.T) {
 	case <-stateCh:
 	}
 
-	// Make next resolution request after 1s.
-	var now = time.Now().Add(minResolutionInterval)
-	overrideTimeUntilFunc(t, now)
+	// Request re-resolution and verify that the resolver waits for
+	// [minResolutionInterval].
 	r.ResolveNow(resolver.ResolveNowOptions{})
 
-	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
-	defer cancel()
 	select {
 	case <-ctx.Done():
 		t.Fatal("Timeout when waiting for DNS resolver")
-	case dur := <-durChan:
-		if dur > 1*time.Millisecond {
-			t.Fatalf("Remaining time duration to allow next resolution is higher than expected")
+	case gotTime := <-timeCh:
+		wantTime := time.Time{}.Add(dns.MinResolutionInterval)
+		if !gotTime.Equal(wantTime) {
+			t.Fatalf("DNS resolver waits for %v time before re-resolution, want %v", gotTime, wantTime)
 		}
 	}
 
-	// Unblock the DNS resolver's backoff by pushing the current time.
-	timeChan <- time.Now()
-
+	// Ensure that the re-resolution request actually happens.
 	select {
 	case <-ctx.Done():
 		t.Fatal("Timeout when waiting for an error from the resolver")
diff --git a/internal/resolver/dns/internal/internal.go b/internal/resolver/dns/internal/internal.go
index 64cae955..35d67060 100644
--- a/internal/resolver/dns/internal/internal.go
+++ b/internal/resolver/dns/internal/internal.go
@@ -62,6 +62,9 @@ var (
 	// time for resolver to allow next resolution.
 	TimeUntilFunc func(time.Time) time.Duration
 
+	// TimeNowFunc: TBD
+	TimeNowFunc func() time.Time
+
 	// NewNetResolver returns the net.Resolver instance for the given target.
 	NewNetResolver func(string) (NetResolver, error)
 ```

File: internal/resolver/dns/dns_resolver_test.go [hunk 7]
```diff
@@ -1290,3 +1299,62 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+	case <-stateCh:
+	}
+
+	// Make next resolution request after 1s.
+	var now = time.Now().Add(minResolutionInterval)
+	overrideTimeUntilFunc(t, now)
+	r.ResolveNow(resolver.ResolveNowOptions{})
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
```
[the remark this answers is not in the document]
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go]: Done. Missed removing it after getting the test work

File: internal/resolver/dns/dns_resolver_test.go [hunk 8]
```diff
@@ -1290,3 +1299,62 @@ func (s) TestMinResolutionInterval(t *testing.T) {
...
+	tr := &testNetResolver{
+		hostLookupTable: map[string][]string{
+			"foo.bar.com": {"1.2.3.4", "5.6.7.8"},
+		},
+		txtLookupTable: map[string][]string{
+			"_grpc_config.foo.bar.com": txtRecordServiceConfig(txtRecordGood),
+		},
+	}
+	overrideNetResolver(t, tr)
+	var minResolutionInterval = 1 * time.Second
```
[the remark this answers is not in the document]
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go]: Done

File: internal/resolver/dns/dns_resolver_test.go
Comment (purnesh42H) [reply internal/resolver/dns/dns_resolver_test.go:1]: Yeah done as per suggestion. Its an improvement from my last test logic which needed small approximation in assertion of wait duration

**Review by easwars — APPROVED** [review]
