### PR TITLE
client: fix race between client-side stream cancellation and compressed server data arriving

### LINKED ISSUE #3053: Flaky test: CancelWhileRecvingWithCompression
```
    --- FAIL: Test/CancelWhileRecvingWithCompression (0.02s)
        context_canceled_test.go:153: recv failed with rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding "gzip", want Canceled
```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #3053 

`transport/Stream.RecvCompress` returns what the header contains, if present,
or empty string if a context error occurs.  However, it "prefers" the header
data even if there is a context error, to prevent a related race.  What happens
here is:

1. RPC starts.

2. Client cancels RPC.

3. `RecvCompress` tells `ClientStream.Recv` that compression used is "" because
   of the context error.  `as.decomp` is left nil, because there is no
   compressor to look up in the registry.

4. Server's header and first message hit client.

5. Client sees the header and message and allows grpc's stream to see them.
   (We only provide context errors if we need to block.)

6. Client performs a successful `Read` on the stream, receiving the gzipped
   payload, then checks `as.decomp`.

7. We have no decompressor but the payload has a bit set indicating the message
   is compressed, so this is an error.  However, when forming the error string,
   `RecvCompress` now returns "gzip" because it doesn't need to block to get
   this from the now-received header.  This leads to the confusing message
   about how "gzip" is not installed even though it is.

This change makes `RecvCompress` return an error instead of empty string (which
is also a valid response), and makes `ClientStream.Recv` return an error when
this happens.  This effectively terminates the stream and prevents subsequent
operations.  This results in 10k/10k passing runs (previously observed failure
rate of ~1/100).

### CODE REVIEW

File: internal/transport/transport.go [hunk 1]
```diff
@@ -358,28 +355,19 @@ func (s *Stream) Header() (metadata.MD, error) {
...
+	if !s.headerValid {
+		return nil, s.status.Err()
 	}
-	return nil, err
+	return s.header.Copy(), nil
 }
 
 // TrailersOnly blocks until a header or trailers-only frame is received and
 // then returns true if the stream was trailers-only.  If the stream ends
 // before headers are received, returns true, nil.  If a context error happens
```
Comment (menghanl) [inline internal/transport/transport.go]: Comment is outdated

File: test/context_canceled_test.go [hunk 2]
```diff
@@ -139,13 +139,12 @@ func (s) TestCancelWhileRecvingWithCompression(t *testing.T) {
...
 	for i := 0; i < 10; i++ {
 		ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
-		defer cancel()
 		s, err := ss.client.FullDuplexCall(ctx, grpc.UseCompressor(gzip.Name))
 		if err != nil {
 			t.Fatalf("failed to start bidi streaming RPC: %v", err)
 		}
 		// Cancel the stream while receiving to trigger the internal error.
-		time.AfterFunc(time.Millisecond*10, cancel)
+		time.AfterFunc(time.Millisecond*1, cancel)
```
Comment (menghanl) [inline test/context_canceled_test.go]: Drop `*1`

File: internal/transport/transport.go [hunk 3]
```diff
@@ -358,28 +355,19 @@ func (s *Stream) Header() (metadata.MD, error) {
...
 // first, returns it as a status error.  Client-side only.
 func (s *Stream) TrailersOnly() (bool, error) {
```
Comment (menghanl) [inline internal/transport/transport.go]: Delete `error` from return value?

File: internal/transport/transport.go [hunk 4]
```diff
@@ -251,6 +252,10 @@ type Stream struct {
 
 	headerChan       chan struct{} // closed to indicate the end of header metadata.
 	headerChanClosed uint32        // set when headerChan is closed. Used to avoid closing headerChan multiple times.
+	headerValid      bool          // set if headerChan is closed due to valid
```
Comment (menghanl) [inline internal/transport/transport.go]: Is this clearer?

`indicates whether a valid header was received. This field's value is only meaningful when headerChan is closed (always waitOnHeader() before reading it's valie)`

Comment (dfawley) [reply internal/transport/transport.go]: I changed the wording a bit using your suggestion.

File: test/context_canceled_test.go (hunk 2 above)
Comment (dfawley) [reply test/context_canceled_test.go]: Done

File: internal/transport/transport.go (hunk 1 above)
Comment (dfawley) [reply internal/transport/transport.go]: Updated

File: internal/transport/transport.go (hunk 3 above)
Comment (dfawley) [reply internal/transport/transport.go]: Done
