### PR TITLE
server: fix race between GracefulStop and new incoming connections (#1745)

### LINKED ISSUE #1737: GracefulStop races new incoming connections
When fixing #1700, I noticed that new connections can race with `GracefulStop` such that the server will accept the connection, but then close it immediately.  If a connection is accepted before `GracefulStop` has a chance to effectively cancel the listeners, the server should handle it to avoid client errors.

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #1737
Updates #1738

### CODE REVIEW

**Comment by dfawley** [comment]
"context" was imported by `goimports` instead of "x/net/context" in the new test file.  Fixed and `push -f`'d

File: server.go [hunk 1]
```diff
@@ -511,7 +516,8 @@ func (s *Server) Serve(lis net.Listener) error {
 				timer := time.NewTimer(tempDelay)
 				select {
 				case <-timer.C:
-				case <-s.ctx.Done():
+				case <-s.quit:
+					return nil
 				}
 				timer.Stop()
```
Comment (MakMukhi) [inline server.go]: Not in your PR but we can get rid of this time.Stop() now that we're here.

File: server.go [hunk 2]
```diff
@@ -641,10 +659,6 @@ var _ http.Handler = (*Server)(nil)
 //
 // conn is the *tls.Conn that's already been authenticated.
 func (s *Server) serveUsingHandler(conn net.Conn) {
-	if !s.addConn(conn) {
-		conn.Close()
-		return
-	}
 	defer s.removeConn(conn)
```
Comment (MakMukhi) [inline server.go]: Shouldn't this be deleted too?

Comment (dfawley) [reply server.go]: Yes, thanks - done.

File: test/gracefulstop_test.go [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+	go func() {
+		// 5. Allow the client to read the GoAway.  The RPC should complete
+		//    successfully.
+		<-wcch
+		fmt.Println("wrote client data; allowing reads")
+		dlis.allowClientRead()
+	}()
+
+	fmt.Println("calling RPC")
+	time.Sleep(time.Second)
```
[the remark this answers is not in the document]
Comment (dfawley) [reply test/gracefulstop_test.go]: Accidental leftover from debugging.  Also removed lots of `fmt.Print`s

File: server.go (hunk 1 above)
Comment (dfawley) [reply server.go]: Moved to the appropriate place.
