### PR TITLE
balancer: fix aggregated state to not report idle with zero subconns

### LINKED ISSUE #4740: Flaky test: Test/AddressesRemoved
https://github.com/grpc/grpc-go/pull/4737/checks?check_run_id=3536496494

```
--- FAIL: Test (1.03s)
    --- FAIL: Test/AddressesRemoved (0.52s)
        tlogger.go:101: clientconn.go:252 [core] parsed scheme: "whatever"  (t=+549.531µs)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:35011  <nil> 0 <nil>}] <nil> <nil>}  (t=+2.127622ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+6.468872ms)
        tlogger.go:101: clientconn.go:1253 [core] Subchannel picks a new address "127.0.0.1:35011" to connect  (t=+6.573078ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+6.925999ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+8.460187ms)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: newPicker called with info: {map[0x40000cd660:{{127.0.0.1:35011  <nil> 0 <nil>}}]}  (t=+8.618796ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to READY  (t=+8.698501ms)
        tlogger.go:101: resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[] <nil> <nil>}  (t=+13.72159ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to TRANSIENT_FAILURE  (t=+13.881099ms)
        tlogger.go:101: clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+14.152615ms)
        tlogger.go:101: roundrobin.go:50 [roundrobin] roundrobinPicker: newPicker called with info: {map[]}  (t=+14.385528ms)
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to IDLE  (t=+14.456532ms)
        roundrobin_test.go:245: timed out waiting for state change.  got IDLE; want TRANSIENT_FAILURE
        tlogger.go:101: clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+515.883508ms)
FAIL
FAIL	google.golang.org/grpc/balancer/roundrobin	2.115s
```

### PR DESCRIPTION
**Pull request by dfawley**
Generally, channels with zero subconns are not usable and should report `TransientFailure`.  This matches previous behavior before Idle support.

Also fix a bug that the base balancer was not accounting for newly created subchannels' idleness.  When the first subchannel transitioned from Idle to Connecting, the number of idle subconns would become `MaxUInt64` due to underflow.

Finally, fix another idleness bug that broke the logic of "stick transient failure" where a subconn that goes to TransientFailure should stay in that state until it goes Ready or Shutdown.

Fixes #4740

(No release notes since this fixes a regression introduced after the last release.)

RELEASE NOTES: none

### CODE REVIEW

**Comment by dfawley** [comment]
A little more explanation of the fix to #4740: this was a race between `UpdateSubConnState` being called on the balancer due to the removed subconn being shutdown before attempting the expected-to-fail RPC in the test.  When `UpdateSubConnState` was called before the RPC, we lost the error about "resolver produced no addresses" due to the aggregated state being `Idle` instead of `TransientFailure` when `UpdateSubConnState` was called.  Most of the time, the RPC would happen first, and the picker would report the expected error.

File: balancer/balancer.go [hunk 1]
```diff
@@ -380,7 +381,8 @@ type ConnectivityStateEvaluator struct {
 //  - If at least one SubConn in Ready, the aggregated state is Ready;
 //  - Else if at least one SubConn in Connecting, the aggregated state is Connecting;
 //  - Else if at least one SubConn is TransientFailure, the aggregated state is Transient Failure;
-//  - Else the aggregated state is Idle
+//  - Else if at least one SubConn is Idle, the aggregated state is Idle;
```
Comment (menghanl) [inline balancer/balancer.go:384]: If there's one SubConn, and it's failing, the overall state will keep switching back to Idle?

This is not a big problem for policies that use this (e.g. roundrobin).
We may still want to distinguish between the initial Idle and the Idle after transient failure. But that needs to keep track of SubConns and their states.

**Review by menghanl — CHANGES_REQUESTED** [review]

File: balancer/balancer.go (hunk 1 above)
Comment (dfawley) [reply balancer/balancer.go:384]: RR-type balancers should probably all implement the "once TF, always TF until ready" semantic.

I'm not sure what change is being requested here.

Comment (dfawley) [reply balancer/balancer.go:384]: > RR-type balancers should probably all implement the "once TF, always TF until ready" semantic.

Oof, this made me realize that our implementation of that logic is now broken with idleness, as it was not implemented via "newState != Ready/Shutdown", but "newState == Connecting".  I've updated the logic to handle that now.

**Review by menghanl — APPROVED** [review]
