### PR TITLE
grpc: prevent a nil stats handler from causing a panic

### LINKED ISSUE #5512: panic: runtime error: invalid memory address or nil pointer dereference at grpc@v1.48.0/stream.go:380
NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?
1.48.0

### What version of Go are you using (`go version`)?
1.18.4

### What operating system (Linux, Windows, …) and version?
linux (ubuntu 18.04)

### What did you do?
If possible, provide a recipe for reproducing the error.

https://chromium.googlesource.com/infra/goma/server/+/refs/heads/main/profiler/profiler.go#34
```go
               err = profiler.Start(profiler.Config{Service: target},
                        // Disallow grpc in google-api-go-client to send stats/trace of profiler grpc's api call.
                        option.WithGRPCDialOption(grpc.WithStatsHandler(nil)))
```

### What did you expect to see?

no runtime panic (as it was in 1.47.0 or prior version)

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8e9e84]

goroutine 40 [running]:
google.golang.org/grpc.(*clientStream).newAttemptLocked(0xc0000ca5a0, 0x0)
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:380 +0x744
google.golang.org/grpc.newClientStreamWithParams({0x11c51d0, 0xc00062f650}, 0x1833f40, 0xc000359c00, {0xf2fe1a, 0x3f}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:306 +0x90c
google.golang.org/grpc.newClientStream.func2({0x11c51d0?, 0xc00062f650?}, 0xc00062f650?)
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:192 +0x9f
google.golang.org/grpc.newClientStream({0x11c51d0, 0xc00062f650}, 0x1833f40, 0xc000359c00, {0xf2fe1a, 0x3f}, {0xc000046870, 0x1, 0x1})
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/stream.go:220 +0x4c2
google.golang.org/grpc.invoke({0x11c51d0?, 0xc00062f650?}, {0xf2fe1a?, 0x70?}, {0xe668e0, 0xc00044e300}, {0xe99000, 0xc0006312d0}, 0x0?, {0xc000046870, ...})
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/call.go:66 +0x7d
google.golang.org/grpc.(*ClientConn).Invoke(0x7f5fb9688108?, {0x11c51d0?, 0xc00062f650?}, {0xf2fe1a?, 0x0?}, {0xe668e0?, 0xc00044e300?}, {0xe99000?, 0xc0006312d0?}, {0xc000046870, ...})
	/workspace/pkg/mod/google.golang.org/grpc@v1.48.0/call.go:37 +0x265
google.golang.org/genproto/googleapis/devtools/cloudprofiler/v2.(*profilerServiceClient).CreateProfile(0xc000110c30, {0x11c51d0, 0xc00062f650}, 0x7f5fb9688108?, {0xc000046870, 0x1, 0x1})
	/workspace/pkg/mod/google.golang.org/genproto@v0.0.0-20220624142145-8cd45d7dbd1f/googleapis/devtools/cloudprofiler/v2/profiler.pb.go:847 +0xce
cloud.google.com/go/profiler.(*agent).createProfile.func1({0x11c51d0, 0xc00062f650}, {0xc000046860, {0x0, 0x0, 0x0}, {0x0, 0x0}})
	/workspace/pkg/mod/cloud.google.com/go/profiler@v0.3.0/profiler.go:337 +0x114
github.com/googleapis/gax-go/v2.invoke({0x11c51d0, 0xc00062f650}, 0xc00006fec8, {0xc000046860, {0x0, 0x0, 0x0}, {0x0, 0x0}}, 0xf55210)
	/workspace/pkg/mod/github.com/googleapis/gax-go/v2@v2.4.0/invoke.go:72 +0xce
github.com/googleapis/gax-go/v2.Invoke({0x11c51d0, 0xc00062f650}, 0x0?, {0xc000059eb8, 0x1, 0x0?})
	/workspace/pkg/mod/github.com/googleapis/gax-go/v2@v2.4.0/invoke.go:50 +0xa5
cloud.google.com/go/profiler.(*agent).createProfile(0xc000652400, {0x11c51d0, 0xc00062f650})
	/workspace/pkg/mod/cloud.google.com/go/profiler@v0.3.0/profiler.go:334 +0x23c
cloud.google.com/go/profiler.pollProfilerService({0x11c51d0, 0xc00062f650}, 0x1c?)
	/workspace/pkg/mod/cloud.google.com/go/profiler@v0.3.0/profiler.go:617 +0xd2
created by cloud.google.com/go/profiler.start
	/workspace/pkg/mod/cloud.google.com/go/profiler@v0.3.0/profiler.go:262 +0x6b3
```

### PR DESCRIPTION
**Pull request by dfawley**
Fix #5512

RELEASE NOTES:
* Fix a panic caused by passing a `nil` stats handler to `grpc.WithStatsHandler` or `grpc.StatsHandler`

### CODE REVIEW

File: dialoptions.go [hunk 1]
```diff
@@ -391,6 +391,11 @@ func WithDialer(f func(string, time.Duration) (net.Conn, error)) DialOption {
 // all the RPCs and underlying network connections in this ClientConn.
 func WithStatsHandler(h stats.Handler) DialOption {
 	return newFuncDialOption(func(o *dialOptions) {
+		if h == nil {
+			// Do not allow a nil stats handler, which would otherwise cause
+			// panics.
```
Comment (easwars) [inline dialoptions.go:396]: Should we throw a warning log or something to let the user know about this instead of silently ignoring it.

File: server.go [hunk 2]
```diff
@@ -442,6 +442,11 @@ func InTapHandle(h tap.ServerInHandle) ServerOption {
 // StatsHandler returns a ServerOption that sets the stats handler for the server.
 func StatsHandler(h stats.Handler) ServerOption {
 	return newFuncServerOption(func(o *serverOptions) {
+		if h == nil {
+			// Do not allow a nil stats handler, which would otherwise cause
```
Comment (easwars) [inline server.go:446]: Same here.

File: dialoptions.go (hunk 1 above)
Comment (dfawley) [reply dialoptions.go:397]: Good call!  It's a usage error, but we have no way of returning said error, so logging at error level seems appropriate.  Done.

**Review by easwars — APPROVED** [review]

**Comment by easwars** [comment]
Hope you have better luck with the tests !!

**Comment by dfawley** [comment]
> Hope you have better luck with the tests !!

Oops, the failures are caused by this change - we had a test that was unnecessarily adding a nil stats handler in order to test something unrelated.
