### PR TITLE
dns: fix flaky TestRateLimitedResolve

### LINKED ISSUE #4362: flaky test: TestRateLimitedResolve
```
--- FAIL: TestRateLimitedResolve (10.10s)
    dns_resolver_test.go:1531: Timed out waiting for 3 calls after 40ms; got 2
    leakcheck.go:110: Leaked goroutine: goroutine 152 [sleep]:
        time.Sleep(0xf4240)
        	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/time.go:193 +0xcc
        google.golang.org/grpc/internal/resolver/dns.TestRateLimitedResolve.func3(0x40000922a0, 0x385f18, 0x40000da070)
        	/home/runner/work/grpc-go/grpc-go/internal/resolver/dns/dns_resolver_test.go:1517 +0x44
        created by google.golang.org/grpc/internal/resolver/dns.TestRateLimitedResolve
        	/home/runner/work/grpc-go/grpc-go/internal/resolver/dns/dns_resolver_test.go:1510 +0x2dc
FAIL
```

https://github.com/grpc/grpc-go/pull/4356/checks?check_run_id=2422242299

Have only seen this once on the newly added `arm64` tests

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #4362.

### CODE REVIEW

File: internal/resolver/dns/dns_resolver_test.go [hunk 1]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
+	}
+
+	shouldNotHappenCtx, shouldNotHappenCtxCancel := context.WithTimeout(context.Background(), defaultTestShortTimeout)
+	defer shouldNotHappenCtxCancel()
+
+	select {
+	case <-tr.ch:
+		t.Fatalf("Should not have looked up again as DNS Min Res Rate timer has not gone off.")
+	case <-shouldNotHappenCtx.Done():
+	}
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1525]: s/shouldNotHappenCtx/sCtx

In Go, we generally prefer shorter variable names. A good rule of thumb for the length of the variable names is their scope. Shorter the scope, shorter the variable name.
See: go/go-style/decisions#variable-names

File: internal/resolver/dns/dns_resolver_test.go [hunk 2]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
-				r.ResolveNow(resolver.ResolveNowOptions{})
-				time.Sleep(1 * time.Millisecond)
-			}
-		}
-	}()
+	// of the first iteration of the for loop in watcher().
+	select {
+	case <-tr.ch:
+	case <-ctx.Done():
+		t.Fatal("Timed out waiting for lookup() call.")
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1510]: Nit: Error strings should not end with punctuation.
See: go/go-style/decisions#error-strings

Here and in other places in this PR.

File: internal/resolver/dns/dns_resolver_test.go [hunk 3]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
-	min, max := wantCalls*dnsResRate, (wantCalls+1)*dnsResRate
-	tMax := time.NewTimer(max)
-	for gotCalls != wantCalls {
-		select {
-		case <-tr.ch:
-			gotCalls++
-		case <-tMax.C:
-			t.Fatalf("Timed out waiting for %v calls after %v; got %v", wantCalls, max, gotCalls)
-		}
+	// Call Resolve Now 100 times, shouldn't continue onto next iteration of watcher, thus shouldn't lookup again.
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1513]: It's a good practice to have comment line lengths be <80. See: go/go-style/decisions#comment-line-length

File: internal/resolver/dns/dns_resolver_test.go [hunk 4]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
+		t.Fatalf("Should not have looked up again as DNS Min Res Rate timer has not gone off.")
+	case <-shouldNotHappenCtx.Done():
+	}
+
+	timer, err := timerChan.Receive(ctx)
+	if err != nil {
+		t.Fatalf("Error receiving timer from mock NewTimer call: %v", err)
+	}
+	timerPointer := timer.(*time.Timer)
+	timerPointer.Reset(0)
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1532]: `time` package's documentation for `Reset()` has the following:
```
// For a Timer created with NewTimer, Reset should be invoked only on
// stopped or expired timers with drained channels.
```

It also states that:
```
// This should not be done concurrent to other receives from the Timer's
// channel.
```

File: internal/resolver/dns/dns_resolver_test.go [hunk 5]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
 
-	if gotCalls != wantCalls {
-		t.Fatalf("resolve count mismatch for target: %q = %+v, want %+v\n", target, gotCalls, wantCalls)
+	// Resolve Now 1000 more times, shouldn't lookup again as DNS Min Res Rate timer has not gone off.
+	for i := 0; i < 1000; i++ {
+		r.ResolveNow(resolver.ResolveNowOptions{})
 	}
-	if elapsed < min {
-		t.Fatalf("elapsed time: %v, wanted it to be between {%v and %v}", elapsed, min, max)
+
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1545]: Is it not required to do the dance from lines 1518 to 1525 here? to make sure that re-resolution has not happened?

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1532]: I'm wondering what might be the best way out. One option might be as follows:

In `dns_resolver.go`
```
type timer struct {
  t *time.Timer
}

func (t *timer) Stop() {
  t.t.Stop()
}

func (t *timer) Done() <-chan time.Time {
  return t.t.C
}

type timerInterface interface {
  Stop() bool
  Done() <-chan time.Time
}

func newTimer = func(d time.Duration) *time.Timer {
  return &timer{t: time.NewTimer(d)}
}
```

In `dns_resolver_test.go` create a fake timer implementation and override `newTimer()`. Does feel like an overkill, but I'm a little concerned about violating the documentation around `timer.Reset()`.

Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1532]: @dfawley : What do you think?

File: internal/resolver/dns/dns_resolver_test.go [hunk 6]
```diff
@@ -51,6 +51,7 @@ func TestMain(m *testing.M) {
 const (
 	txtBytesLimit      = 255
 	defaultTestTimeout = 10 * time.Second
+	defaultTestShortTimeout = 10 * time.Millisecond
```
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:54]: Omg how do I do this? I spend a LOT of time (like half my swe time) on vet fmt issues.

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1532]: This timer.Reset idea was all Doug's which I implemented so defer to him.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1525]: No wonder there's so many abbreviations. Personally, I hate abbreviations. I spend so much swe time figuring out what abbreviations mean. I disagree with this style guideline.

File: internal/resolver/dns/dns_resolver.go [hunk 7]
```diff
@@ -47,8 +47,9 @@ var EnableSRVLookups = false
 
 var logger = grpclog.Component("dns")
 
-// A global to stub out in tests.
+// Globals to stub out in tests.
 var newTimer = time.NewTimer
+var newTimerDNSResRate = time.NewTimer
```
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver.go:52]: Done.

File: internal/resolver/dns/dns_resolver_test.go [hunk 8]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
 	}
 
-	// Observe the time before unblocking the lookupHost call.  The 100ms rate
-	// limiting timer will begin immediately after that.  This means the next
-	// resolution could happen less than 100ms if we read the time *after*
-	// receiving from tr.ch
-	start := time.Now()
+	ctx, ctxCancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer ctxCancel()
+
```
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1503]: Yeah, thanks, sorry lol.

File: internal/resolver/dns/dns_resolver_test.go (hunk 2 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1510]: Ugh yeah I always forget my IDE throws a grey line under it too. Thanks.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1510]: Hey can you explain this to me, I'm having a hard time partitioning what constitutes a logical error message vs. a situation (style guide describes as "logging, test failure, API Response, or other UI") to have proper capitalization and period. How is this not a "test failure"?

File: internal/resolver/dns/dns_resolver_test.go (hunk 5 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1545]: Added the "dance" here. I find Flamenco dances interesting, and same with the dances in musical theatre.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1525]: Switching a variable name from explaining what it does to sCtx (what does that mean...) will require some explanation from the "Go Readability" community contributor because I completely disagree with it.

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/resolver/dns/dns_resolver.go:52]: Personally I don't understand the reason to use a var block, except for a very long set of related global vars.  I find it doesn't improve readability, and in functions it adds 2 extra lines which is really something to be avoided IMO.

I'd say this is personal choice and should be recommended during reviews.

[the remark this answers is not in the document]
Comment (dfawley) [reply internal/resolver/dns/dns_resolver.go:52]: On this particular line, it's really unfortunate to me that we can't use just _one_ NewTimer hooking global.  How much work would it take to do that?

File: internal/resolver/dns/dns_resolver_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:54]: What IDE/editor are you using?  Surely a google search can turn up the answer. :)

File: internal/resolver/dns/dns_resolver_test.go (hunk 2 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:1510]: This is not an error string.  This can start with a capital and end with a period.  Error strings are things returned by `fmt.Errorf`, `errors.New`, etc.

File: internal/resolver/dns/dns_resolver_test.go (hunk 3 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:1513]: +1

File: internal/resolver/dns/dns_resolver_test.go [hunk 9]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
 		t.Fatalf("delegate resolver returned unexpected type: %T\n", tr)
 	}
 
-	// Observe the time before unblocking the lookupHost call.  The 100ms rate
-	// limiting timer will begin immediately after that.  This means the next
-	// resolution could happen less than 100ms if we read the time *after*
-	// receiving from tr.ch
-	start := time.Now()
+	ctx, ctxCancel := context.WithTimeout(context.Background(), defaultTestTimeout)
```
Comment (dfawley) [inline internal/resolver/dns/dns_resolver_test.go:1501]: Naming nit: `ctxCancel`->`cancel` is the preferred name.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:1525]: Don't use too many abbreviations for things in longer functions.  If the variable is declared and used completely within like 5 lines, a single letter is fine.  Otherwise more descriptive names are usually better.  I dislike `sCtx`, and also `shouldNotHappenCtx`.  Since we already have a `ctx`, how about something like `passCtx` or `continueCtx`?

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:1532]: These are "should"s.  I believe they are there to address potential race issues that might occur under normal timer usage.  In our case, we initially have an infinite timer that will never fire.  I don't think we need to be concerned about anything here.  If you want to be paranoid, you can call `Stop` first, but I really don't think that's worth it.

File: internal/resolver/dns/dns_resolver_test.go [hunk 10]
```diff
@@ -1490,55 +1498,63 @@ func TestRateLimitedResolve(t *testing.T) {
...
+	timer, err = timerChan.Receive(ctx)
+	if err != nil {
+		t.Fatalf("Error receiving timer from mock NewTimer call: %v", err)
+	}
+	timerPointer = timer.(*time.Timer)
+	timerPointer.Reset(0)
+
+	// Now that DNS Min Res Rate timer has gone off, it should lookup again.
+	select {
+	case <-tr.ch:
```
Comment (dfawley) [inline internal/resolver/dns/dns_resolver_test.go:1555]: Make `tr` a `testutils.Channel` and use its `Receive(context.Context)` function instead?

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (easwars) [reply internal/resolver/dns/dns_resolver.go:52]: We have two global var blocks in this file, and outside of that we have multiple global vars defined in a non block. And in between this, there is an `init()` function and a `const` block. Sure, it is a personal choice. But I just feel vars are sprinkled all over the place while they can be nicely grouped in a block. And I agree this PR does not touch the other blocks, so making this a block does not help overall.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1525]: If you are new to Go, shorter variable names could seem very counter intuitive. Long variable names for things which have a scope of a few lines definitely hurt over time. 

There is a long rant about why Go prefers shorter variable names in the link that I sent. On what points do you disagree? And why?

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver.go:52]: A lotttttt of work @dfawley in regards to using one rather than two, as they are logically separate ideals (exponential backoff and simply the dns min res rate).

File: internal/resolver/dns/dns_resolver_test.go (hunk 10 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1555]: +1

File: internal/resolver/dns/dns_resolver_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:54]: Google it you unindependent **** you'll never justify independence quality to perf committee at this rate :P - I Googled it!

[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:54]: Added gofmt to auto run on save!

File: internal/resolver/dns/dns_resolver_test.go (hunk 10 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1555]: Oh yeah, forgot about that, I'll switch it over.

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1532]: How about we make a helper function, something like
```golang
func waitForNewTimerAndReset(ctx context.Context, ch *testutils.Channel) error {
	t, err := ch.Receive(ctx)
	if err != nil {
		return fmt.Errorf("error receiving timer from mock timer channel: %v", err)
	}
	tp := t.(*time.Timer)
	tp.Reset(0)
	return nil
}
```

and have a comment describing exactly what we are doing.

We already have this pattern multiple times in the existing test and this PR only adds more.

File: internal/resolver/dns/dns_resolver_test.go (hunk 9 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1501]: Ah sounds good, switched.

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (easwars) [reply internal/resolver/dns/dns_resolver.go:52]: This `var` here is just a `func (d time.Duration) *time.Timer`. Only the value of `d` passed to it depends on whether it comes from a min dns res rate or from an exponential backoff. Why is it a lot of work?

File: internal/resolver/dns/dns_resolver_test.go (hunk 10 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1555]: Switched it over.

File: internal/resolver/dns/dns_resolver_test.go (hunk 2 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1510]: I agree with Doug.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1525]: Argh, I still like shouldNotHappenCtx the most. I'll switch to "continueCtx" (begrudgingly).

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1525]: I don't know @easwars, it was a (completely personal, and very unique) problem I had with Envoy as well, so many abbreviations. My philosophy about it comes from a book I read called clean code - where it has a section about explaining yourself with variable names. For example, like even if I'm in say a file called ClusterHandler with a ClusterHandler type, having the capture argument being (ch *ClusterHandler), I have to spend a few seconds figuring out what ch.X stands for. It seems to be an extremely unique ideology. I agree with keeping things clean, but I also personally think that variable names should be as verbose as possible.

File: internal/resolver/dns/dns_resolver_test.go (hunk 3 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1513]: Switched all comments to wrap to 80 characters. Thanks @menghanl for the suggestion about this wrap to column plug in.

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver.go]: It's a lot of work because you have to figure out what branch of logic it will take. Every test mocks the DNS res rate to 0 to not wait on it. I don't want to trigger exponential backoff on error conditions so I have a time.Hour return so the timer will never fire and it'll never trigger exponential backoff making tests actually deterministic. Making this a single global would require a few hours of manually going into each test and figuring out what branch of logic it takes, then mocking EACH CALL to new timer accordingly. It's a lot of work unless I'm misunderstanding it.

[the remark this answers is not in the document]
Comment (dfawley) [reply internal/resolver/dns/dns_resolver.go]: Aren't all tests testing either one or the other behavior?  I may not be fully appreciating the complexity here, but it doesn't _seem_ that bad in theory.  I won't push this since I'm not certain, but it's worth a quick check IMO.

[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver.go]: No. Look at my exponential backoff test. It returns errors (backs off), then is ok (minDNSResRate at that point). Rewriting every single test around this concept doesn't make sense to me. I think it would take a whole day at least.

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go]: I think what I said mostly agrees with it.  We have problems in our codebase of excessive abbreviation.  E.g.s: `ClientConn.sc/mkp` or `clientStream.cp`.

I wasn't a fan of `sCtx` since it's live for the entire function and what does `s` even mean?  Why not `zCtx`?  AFAIK there is no commonly established convention for contexts like `i` as integer loop counters.  Also, unlike `for v := range vThings`, it is unclear from `sCtx`'s initialization what it will be used for.  You could add a comment, but clearer variable names are better than comments that explain unclear variable names.

`shouldNotHappenCtx` is verbose _and_ potentially misleading.  What "should not happen"?  The context expiration?  Is this something that is triggered _when_ an unwanted thing happens?  Because it sounds like that to me.

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (dfawley) [reply internal/resolver/dns/dns_resolver_test.go:1537]: It seems this only saves one line, though?

```go
if err := waitForNewTimerAndReset(ctx, myChan); err != nil {
	t.Fatal(...)
}
```
vs
```go
if t, err := ch.Receive(ctx); err != nil {
	t.Fatal(...)
}
t.(*time.Timer).Reset(0)
```

File: internal/resolver/dns/dns_resolver_test.go (hunk 1 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go]: Fair point about shouldNotHappen. I'll try and be reasonable about balancing verbosity and cleanliness wrt variable naming moving forward.

File: internal/resolver/dns/dns_resolver_test.go (hunk 4 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1537]: I prefer it not as a util function but inline.

Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:1537]: My reason for having a utility function was more to do with adding a comment or two saying stuff like "alright, we are doing a Reset() with 0, this will make the timer fire immediately, and unblock the resolver waiting on this". But I'm fine either ways.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1537]: Fair point. I handled explanation in the two tests (well technically one test, and I added onto another) when I moved exponential backoff to this component this way: I put a comment in the function that I set newTimer to as follows: "// Will never fire on its own, allows this test to call timer immediately." This comment is also present in this test, when I overrode newTimerDNSResRate. I agree with your concern about no context for reader to understand what the is happening, but my view is that the comment within the overriden function is good enough if you read it from top to bottom.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1537]: Since Doug was fine with the level of explanation of my Exponential backoff tests, what I'll do is I'll add a comment to this test explaining the underlying logic, but I don't like the util function idea.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1537]: Yeah, rereading the test there's no context to what's happening there, you're right. Let me add a comment.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1541]: Added comment.

File: internal/resolver/dns/dns_resolver_test.go [hunk 11]
```diff
@@ -126,8 +127,11 @@ func (*testResolver) LookupTXT(ctx context.Context, host string) ([]string, erro
 
 func replaceNetFunc(ch chan struct{}) func() {
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:128]: I hate to ask you to change stuff unrelated to what you are trying to fix here. But `replaceNetFunc` is a super unintuitive name for a function which replaces the `defaultResolver` with a `testResolver`.

Something like `overrideDefaultResolver()` or `overrideNetResolver()` with a comment on the function describing what it is doing.

Comment (easwars) [reply internal/resolver/dns/dns_resolver_test.go:128]: Also, while you are here and since the channel in the `testResolver` has been changed to a `testutils.Channel`, the `ch` argument to this function no longer makes sense.

You could write this func as follows:
```golang
// overrideDefaultResolver overrides the defaultResolver used by the code with an instance of
// the testResolver. pushOnLookup controls whether the testResolver created here pushes
// lookupHost events on its channel.
func overrideDefaultResolver(pushOnLookup bool) func() {
	oldResolver := defaultResolver

	var ch *testutils.Channel
	if pushOnLookup {
		ch = testutils.NewChannel()
	}
	defaultResolver = &testResolver{ch: ch}

	return func() {
		defaultResolver = oldResolver
	}
}
```

File: internal/resolver/dns/dns_resolver_test.go [hunk 12]
```diff
@@ -1490,55 +1504,71 @@ func TestRateLimitedResolve(t *testing.T) {
...
+		r.ResolveNow(resolver.ResolveNowOptions{})
+	}
+
+	continueCtx, continueCancel := context.WithTimeout(context.Background(), defaultTestShortTimeout)
+	defer continueCancel()
+
+	_, err = tr.ch.Receive(continueCtx)
+
+	if err == nil {
+		t.Fatalf("Should not have looked up again as DNS Min Res Rate timer has not gone off.")
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1529]: Switch to:

```golang
	if _, err := tr.ch.Receive(continueCtx); if err == nil {
		t.Fatalf("Should not have looked up again as DNS Min Res Rate timer has not gone off.")
	}
```

File: internal/resolver/dns/dns_resolver_test.go [hunk 13]
```diff
@@ -1490,55 +1504,71 @@ func TestRateLimitedResolve(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("Error receiving timer from mock NewTimer call: %v", err)
 	}
-	if elapsed < min {
-		t.Fatalf("elapsed time: %v, wanted it to be between {%v and %v}", elapsed, min, max)
+	timerPointer := timer.(*time.Timer)
+	timerPointer.Reset(0)
+
+	// Now that DNS Min Res Rate timer has gone off, it should lookup again.
+	_, err = tr.ch.Receive(ctx)
```
Comment (easwars) [inline internal/resolver/dns/dns_resolver_test.go:1544]: Same here and all other places where the assignment and conditional statements can be combined, they should be.

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (easwars) [reply internal/resolver/dns/dns_resolver.go]: Maybe add a TODO and in some other fixit we might revisit and see if we can make that happen. Or in hacktoberfest, some kind soul might do that.

File: internal/resolver/dns/dns_resolver_test.go (hunk 11 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:128]: I agree. ReplaceNetFunc() is a weird name. Also yeah makes sense thanks for the idea about switching the argument. I didn't like passing a channel either. Switching now.

Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:128]: Switched. Thanks :).

File: internal/resolver/dns/dns_resolver_test.go (hunk 12 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1529]: Switched.

File: internal/resolver/dns/dns_resolver_test.go (hunk 13 above)
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:1544]: Switched in every place. :)

**Comment by dfawley** [comment]
Is this a flake? https://github.com/grpc/grpc-go/pull/4387/checks?check_run_id=2518496816#step:8:38

Can you try to repro with and without this change? If it was pre-existing then file a bug, otherwise, investigate further.  If you are completely unable to repro before/after, I guess file a bug and close it?

File: internal/resolver/dns/dns_resolver.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver.go]: Added a TODO.

File: internal/resolver/dns/dns_resolver_test.go [hunk 14]
```diff
@@ -106,12 +107,12 @@ type testResolver struct {
...
 	// request. Tests can rely on reading from this channel to be notified about
 	// resolution requests instead of sleeping for a predefined period of time.
-	ch chan struct{}
+	ch *testutils.Channel
 }
 
 func (tr *testResolver) LookupHost(ctx context.Context, host string) ([]string, error) {
 	if tr.ch != nil {
-		tr.ch <- struct{}{}
+		tr.ch.Send(struct{}{})
```
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:115]: Switched to nil.

File: internal/resolver/dns/dns_resolver_test.go [hunk 15]
```diff
@@ -106,12 +107,12 @@ type testResolver struct {
 	// A write to this channel is made when this resolver receives a resolution
 	// request. Tests can rely on reading from this channel to be notified about
 	// resolution requests instead of sleeping for a predefined period of time.
-	ch chan struct{}
+	ch *testutils.Channel
```
[the remark this answers is not in the document]
Comment (zasweq) [reply internal/resolver/dns/dns_resolver_test.go:110]: Great idea :). Switched over.

**Review by easwars — APPROVED** [review]
