### PR TITLE
xds/googledirectpath: fix google-c2p resolver test case involving bootstrap env config

### LINKED ISSUE #6572: xds/googledirectpath: tests fail in cloudtop
```
2023/08/22 23:37:35 WARNING: [directpath] [google-c2p-resolver]could not discover ipv6 capability: metadata server returned resp with non-OK: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[1615] Content-Type:[text/html; charset=UTF-8] Date:[Tue, 22 Aug 2023 23:37:35 GMT] Metadata-Flavor:[Google] Server:[Metadata Server for VM] X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[0]] 0xc000526020 1615 [] false false map[] 0xc000408100 <nil>}
2023/08/22 23:37:35 INFO: [xds] [xds-bootstrap] Using bootstrap file with name "does not matter"
--- FAIL: TestBuildWithBootstrapEnvSet (0.03s)
    --- FAIL: TestBuildWithBootstrapEnvSet/0 (0.03s)
        googlec2p_test.go:88: failed to build resolver: failed to start xDS client: xds: failed to read bootstrap file: xds: Failed to read bootstrap config: open does not matter: no such file or directory
    --- FAIL: TestBuildWithBootstrapEnvSet/1 (0.00s)
        googlec2p_test.go:88: failed to build resolver: failed to start xDS client: xds: failed to read bootstrap file: xds: failed to parse bootstrap config: invalid character 'd' looking for beginning of value
2023/08/22 23:37:35 INFO: [core] [Channel #1] Channel created
2023/08/22 23:37:35 INFO: [core] [Channel #1] original dial target is: "google-c2p://an-authority/resource"
2023/08/22 23:37:35 INFO: [core] [Channel #1] parsed dial target is: {URL:{Scheme:google-c2p Opaque: User: Host:an-authority Path:/resource RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}
2023/08/22 23:37:35 INFO: [core] [Channel #1] Channel authority set to "resource"
2023/08/22 23:37:35 INFO: [core] [Channel #1] Channel Connectivity change to SHUTDOWN
2023/08/22 23:37:35 INFO: [core] [Channel #1] ccBalancerWrapper: closing
2023/08/22 23:37:35 INFO: [core] [Channel #1] Channel deleted
FAIL
FAIL    google.golang.org/grpc/xds/googledirectpath     0.258s
```

### PR DESCRIPTION
**Pull request by apolcyn**
Fixes #6572

It looks like this test was originally written assuming that federation was default off.

When federation was defaulted on, the expectations changed. Update to fix expectations and make the test behave the ~same whether it's ran on GCE or not.

cc @easwars 

RELEASE NOTES: none

### CODE REVIEW

File: xds/googledirectpath/googlec2p_test.go [hunk 1]
```diff
@@ -88,25 +88,49 @@ func replaceResolvers() func() {
...
 	defer replaceResolvers()()
 	builder := resolver.Get(c2pScheme)
 
+	// make the test behave the ~same whether it's running on or off GCE
+	oldOnGCE := onGCE
+	onGCE = func() bool { return true }
+	defer func() { onGCE = oldOnGCE }()
+
+	// don't actually read the bootstrap file contents
+	tXDSClient := &testXDSClient{closed: make(chan struct{}, 1)}
```
Comment (easwars) [inline xds/googledirectpath/googlec2p_test.go:112]: Nit: `tXDSClient` is a bit hard on the eyes. Can we simply name this `xdsClient`?

**Review by easwars — APPROVED** [review]

File: xds/googledirectpath/googlec2p_test.go (hunk 1 above)
Comment (apolcyn) [reply xds/googledirectpath/googlec2p_test.go]: done

**Comment by apolcyn** [comment]
@easwars please merge if this looks good (I don't have access)
