### PR TITLE
stats/opencensus: Fix flaky metrics test

### LINKED ISSUE #6231: Flaky test: AllMetricsOneFunction
```
--- FAIL: Test (0.15s)
    --- FAIL: Test/AllMetricsOneFunction (0.07s)
        tlogger.go:116: INFO server.go:629 [core] [Server #19] Server created  (t=+1.130319ms)
        tlogger.go:116: INFO clientconn.go:177 [core] [Channel #20] Channel created  (t=+1.558427ms)
        tlogger.go:116: INFO clientconn.go:1600 [core] [Channel #20] original dial target is: "whatever:///127.0.0.1:45395"  (t=+1.668828ms)
        tlogger.go:116: INFO clientconn.go:1607 [core] [Channel #20] parsed dial target is: {Scheme:whatever Authority: URL:{Scheme:whatever Opaque: User: Host: Path:/127.0.0.1:45395 RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+1.824031ms)
        tlogger.go:116: INFO clientconn.go:1707 [core] [Channel #20] Channel authority set to "127.0.0.1:45395"  (t=+1.928833ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:196 [core] [Channel #20] Resolver state updated: {
              "Addresses": [
                {
                  "Addr": "127.0.0.1:45395",
                  "ServerName": "",
                  "Attributes": null,
                  "BalancerAttributes": null,
                  "Type": 0,
                  "Metadata": null
                }
              ],
              "ServiceConfig": null,
              "Attributes": null
            } (resolver returned new addresses)  (t=+2.188437ms)
        tlogger.go:116: INFO balancer_conn_wrappers.go:276 [core] [Channel #20] Channel switches to new LB policy "pick_first"  (t=+2.37184ms)
        tlogger.go:116: INFO clientconn.go:759 [core] [Channel #20 SubChannel #21] Subchannel created  (t=+2.5[336](https://github.com/grpc/grpc-go/actions/runs/4824796293/jobs/8595006405?pr=6228#step:8:337)43ms)
        tlogger.go:116: INFO clientconn.go:451 [core] [Channel #20] Channel Connectivity change to CONNECTING  (t=+2.629444ms)
        tlogger.go:116: INFO server.go:817 [core] [Server #19 ListenSocket #22] ListenSocket created  (t=+2.788947ms)
        tlogger.go:116: INFO clientconn.go:1141 [core] [Channel #20 SubChannel #21] Subchannel Connectivity change to CONNECTING  (t=+3.064652ms)
        tlogger.go:116: INFO clientconn.go:1255 [core] [Channel #20 SubChannel #21] Subchannel picks a new address "127.0.0.1:45395" to connect  (t=+3.254755ms)
        tlogger.go:116: INFO clientconn.go:1141 [core] [Channel #20 SubChannel #21] Subchannel Connectivity change to READY  (t=+4.581777ms)
        tlogger.go:116: INFO clientconn.go:451 [core] [Channel #20] Channel Connectivity change to READY  (t=+4.880182ms)
        e2e_test.go:1019: got unexpected viewInformation for metric grpc.io/server/completed_rpcs, diff (-got, +want):   (*opencensus.viewInformation)(
            - 	&{
            - 		aggType:    s"Count",
            - 		aggBuckets: []float64{},
            - 		desc:       "Number of completed RPCs by method and status.",
            - 		tagKeys:    []tag.Key{{name: "grpc_server_method"}, {name: "grpc_server_status"}},
            - 		rows:       []*view.Row{s"{ { {grpc_server_method grpc.testing.TestService/FullDuplexCall}"...},
            - 	},
            + 	&{
            + 		aggType:    s"Count",
            + 		aggBuckets: []float64{},
            + 		desc:       "Number of completed RPCs by method and status.",
            + 		tagKeys:    []tag.Key{{name: "grpc_server_method"}, {name: "grpc_server_status"}},
            + 		rows: []*view.Row{
            + 			s"{ { {grpc_server_method grpc.testing.TestService/UnaryCall}{grpc"...,
            + 			s"{ { {grpc_server_method grpc.testing.TestService/FullDuplexCall}"...,
            + 		},
            + 	},
              )
        tlogger.go:116: INFO clientconn.go:451 [core] [Channel #20] Channel Connectivity change to SHUTDOWN  (t=+55.584632ms)
        tlogger.go:116: INFO clientconn.go:1141 [core] [Channel #20 SubChannel #21] Subchannel Connectivity change to SHUTDOWN  (t=+55.955638ms)
        tlogger.go:116: INFO clientconn.go:1468 [core] [Channel #20 SubChannel #21] Subchannel deleted  (t=+56.110[341](https://github.com/grpc/grpc-go/actions/runs/4824796293/jobs/8595006405?pr=6228#step:8:342)ms)
        tlogger.go:116: INFO clientconn.go:1095 [core] [Channel #20] Channel deleted  (t=+56.201042ms)
        tlogger.go:116: INFO server.go:768 [core] [Server #19 ListenSocket #22] ListenSocket deleted  (t=+57.087057ms)
FAIL
FAIL	google.golang.org/grpc/stats/opencensus	0.831s
```	

https://github.com/grpc/grpc-go/actions/runs/4824796293/jobs/8595006405?pr=6228

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #6231.

This adds a sync point between Unary and Streaming RPCs recording completed RPC's Server Side and the test. The test simply waits for the RPC to finish client side, but stats.End is recorded in a defer for the Unary and Streaming RPC case after status is written to the wire. Thus, previously there was no sync point between the test and this metric being recorded. Sync at the view global level, as that is synced with exporter by Unregistering views, and will stop recording metrics after, thus has to wait for the two row emissions for Unary and Streaming RPCs at the view global level, not at the exporter level.

Verified passes over 10k runs on Forge. Previously was failing 18/10k times on Forge.

RELEASE NOTES: N/A

### CODE REVIEW

File: stats/opencensus/e2e_test.go [hunk 1]
```diff
@@ -237,6 +237,23 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
 	return nil
 }
 
+// waitForServerCompletedRPCs waits until both Unary and Streaming metric rows
+// appear for server completed RPC's view (by checking for length of rows to be
+// 2). Returns an error if both the Unary and Streaming metric not found within
+// the passed context's timeout.
+func waitForServerCompletedRPCs(ctx context.Context, fe *fakeExporter) error {
```
Comment (tobotg) [inline stats/opencensus/e2e_test.go:244]: Unused function argument: you may want to remove `fe *fakeExporter` from `waitForServerCompletedRPCs` function.

**Review by tobotg — CHANGES_REQUESTED** [review]
Thanks @zasweq 
lgtm (modulo one minor change).

File: stats/opencensus/e2e_test.go [hunk 2]
```diff
@@ -237,6 +237,23 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
...
+	for ; ctx.Err() == nil; <-time.After(time.Millisecond) {
+		rows, err := view.RetrieveData("grpc.io/server/completed_rpcs")
+		if err != nil {
+			continue
+		}
+		if len(rows) == 2 {
```
Comment (arvindbr8) [inline stats/opencensus/e2e_test.go:250]: Instead of a len check here, should we implicitly check for 1 Unary and 1 Streaming RPC metric?

File: stats/opencensus/e2e_test.go [hunk 3]
```diff
@@ -237,6 +237,23 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
 	return nil
 }
 
+// waitForServerCompletedRPCs waits until both Unary and Streaming metric rows
+// appear for server completed RPC's view (by checking for length of rows to be
+// 2). Returns an error if both the Unary and Streaming metric not found within
+// the passed context's timeout.
+func waitForServerCompletedRPCs(ctx context.Context, fe *fakeExporter) error {
+	for ; ctx.Err() == nil; <-time.After(time.Millisecond) {
+		rows, err := view.RetrieveData("grpc.io/server/completed_rpcs")
```
Comment (arvindbr8) [inline stats/opencensus/e2e_test.go:246]: Since `err` from `RetrieveData` is ignored here, why not nix the variable completely? and remove the following non-nil `err` check

File: stats/opencensus/e2e_test.go [hunk 4]
```diff
@@ -237,6 +237,23 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
 	return nil
 }
 
+// waitForServerCompletedRPCs waits until both Unary and Streaming metric rows
+// appear for server completed RPC's view (by checking for length of rows to be
+// 2). Returns an error if both the Unary and Streaming metric not found within
+// the passed context's timeout.
+func waitForServerCompletedRPCs(ctx context.Context, fe *fakeExporter) error {
+	for ; ctx.Err() == nil; <-time.After(time.Millisecond) {
```
Comment (arvindbr8) [inline stats/opencensus/e2e_test.go:245]: Nit: Does 1 ms seem like aggressive for the check?

**Review by arvindbr8 — CHANGES_REQUESTED** [review]
minor comments

File: stats/opencensus/e2e_test.go (hunk 1 above)
Comment (zasweq) [reply stats/opencensus/e2e_test.go:244]: Ah, great catch. Deleted.

File: stats/opencensus/e2e_test.go (hunk 3 above)
Comment (zasweq) [reply stats/opencensus/e2e_test.go:246]: err is not ignored. err determines whether to continue through the for.

File: stats/opencensus/e2e_test.go (hunk 4 above)
Comment (zasweq) [reply stats/opencensus/e2e_test.go:245]: This isn't checking anything. This is a polling loop, and this millisecond receive determines how fast to go to the next iteration of the for.

File: stats/opencensus/e2e_test.go (hunk 2 above)
Comment (zasweq) [reply stats/opencensus/e2e_test.go:250]: Explicitly*. But sure.

File: stats/opencensus/e2e_test.go [hunk 5]
```diff
@@ -238,16 +238,21 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
...
-		if len(rows) == 2 {
+		m := make(map[string]bool)
+		for _, row := range rows {
+			for _, tag := range row.Tags {
+				m[tag.Value] = true
+			}
+		}
+		if m["grpc.testing.TestService/UnaryCall"] && m["grpc.testing.TestService/FullDuplexCall"] {
 			return nil
 		}
```
[the remark this answers is not in the document]
Comment (zasweq) [reply stats/opencensus/e2e_test.go]: This is verified right after by the want declared having only the two rows declared separately and checked in cmp.Diff. I went ahead and switched to your second solution though.

[the remark this answers is not in the document]
Comment (zasweq) [reply stats/opencensus/e2e_test.go]: Thanks for suggestion.

File: stats/opencensus/e2e_test.go [hunk 6]
```diff
@@ -237,6 +237,36 @@ func distributionDataLatencyCount(vi *viewInformation, countWant int64, wantTags
 	return nil
 }
 
+// waitForServerCompletedRPCs waits until both Unary and Streaming metric rows
+// appear, in two seperate rows, for server completed RPC's view. Returns an
```
Comment (arvindbr8) [inline stats/opencensus/e2e_test.go:241]:
```suggestion
// appear, in two separate rows, for server completed RPC's view. Returns an
```

File: stats/opencensus/e2e_test.go (hunk 4 above)
Comment (arvindbr8) [reply stats/opencensus/e2e_test.go:245]: I meant, should we go for a longer polling loop?  Im okay this way

**Review by arvindbr8 — APPROVED** [review]

**Comment by arvindbr8** [comment]
Minor typo. LGTM

File: stats/opencensus/e2e_test.go (hunk 4 above)
Comment (zasweq) [reply stats/opencensus/e2e_test.go:245]: the polling loop is determined by the context timeout of the context passed in. In this case, that timeout is 5 seconds, the default test timeout. Thus, what this represents is within the 5 second timeout, how often to poll, which I specified as a millisecond.
