### PR TITLE
balancer/rls: Fix RLS failure mode by treating response with no targets as an error

### LINKED ISSUE #6719: rls: response with no targets should be treated as an error
According to the original design:
```
An RLS request is considered to have succeeded if it returns an OK status and the 
RLS response's targets list contains at least one non-empty entry.
```

We are currently handling the case of a response with zero targets the same way we would handle a successful response. This means that when an RPC is made, the cache entry will not have any READY child policy wrappers, and hence will be queued until the RPC context expires. Instead, we should treat this case as an error and set the cache entry in backoff. The code that handles an RLS response is here: https://github.com/grpc/grpc-go/blob/32e3ef1ed1c494e3d748b93d67a0b7ec5d089a49/balancer/rls/picker.go#L216

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #6719. Previously, the RLS Balancer would not treat an RLS response with no targets as an error. This PR makes it treat an RLS response with no targets as an error.

The relevant language from the RLS LB Design document: "An RLS request is considered to have failed if it returns a non-OK status or the RLS response's targets list is non-empty."

RELEASE NOTES:
* balancer/rls: Fix RLS failure mode by treating response with no targets as an error

### CODE REVIEW

File: balancer/rls/picker.go [hunk 1]
```diff
@@ -252,6 +252,26 @@ func (p *rlsPicker) handleRouteLookupResponse(cacheKey cacheKey, targets []strin
...
+	// status or the RLS response's targets list does not contain any non-empty
+	// entries." - RLS LB Policy design.
+	var nonEmptyTarget bool
+	for _, target := range targets {
+		if target != "" {
+			nonEmptyTarget = true
+			break
+		}
+	}
+	if !nonEmptyTarget {
```
Comment (dfawley) [inline balancer/rls/picker.go:266]: Let's try to avoid negatively named bools and especially negating negatives.  (tott/685)

E.g. name it `hasValidTarget` or reverse it:

```go
allTargetsEmpty := true
for _, target := range targets {
	if target != "" {
		allTargetsEmpty = false
		break
	}
}
if allTargetsEmpty {
```

File: balancer/rls/picker.go [hunk 2]
```diff
@@ -252,6 +252,26 @@ func (p *rlsPicker) handleRouteLookupResponse(cacheKey cacheKey, targets []strin
...
+		if err == nil {
+			err = fmt.Errorf("RLS response's target list does not contain any non-empty entries for key %+v", cacheKey)
+		} else {
+			// Can eat the status part of error since the RLS doesn't forward
+			// statuses from control plane RPCss to data plane RPCss (see Pick).
+			err = fmt.Errorf(err.Error()+"and also RLS response's target list does not contain any non-empty entries for key %+v", cacheKey)
+		}
```
Comment (dfawley) [inline balancer/rls/picker.go:273]: If err is set, don't we expect `targets` to always be empty?  I believe they should be mutually exclusive:

https://github.com/zasweq/grpc-go/blob/e853dbf004c343da4b8c6204524765ba6fbeef38/balancer/rls/control_channel.go#L216

File: balancer/rls/picker.go (hunk 1 above)
Comment (zasweq) [reply balancer/rls/picker.go:266]: Hmmmm ok noted.

File: balancer/rls/picker.go (hunk 2 above)
Comment (zasweq) [reply balancer/rls/picker.go:273]: Pinged you offline about this. Done.

File: balancer/rls/picker.go [hunk 3]
```diff
@@ -252,6 +252,25 @@ func (p *rlsPicker) handleRouteLookupResponse(cacheKey cacheKey, targets []strin
...
+	for _, target := range targets {
+		if target != "" {
+			allTargetsEmpty = false
+			break
+		}
+	}
+	if allTargetsEmpty {
+		if err == nil {
+			err = fmt.Errorf("RLS response's target list does not contain any non-empty entries for key %+v", cacheKey)
+		}
```
Comment (dfawley) [inline balancer/rls/picker.go:269]: Let's move this `if err == nil` check to surround all of this new logic?

Comment (zasweq) [reply balancer/rls/picker.go]: Done, alongside implementing offline discussion wrt just checking length of targets slice.

Comment (zasweq) [reply balancer/rls/picker.go]: Updated description.

**Review by dfawley — APPROVED** [review]
Please update the PR description further, specifically:

- It still says "no non-empty targets" in multiple places

- I think you can delete this since the input should be valid and not special?: "There's no good way to test the case where you get targets: []string{""} in my opinion. If you feel strongly about this I can try and figure out a test with the right error code/message here."

**Comment by zasweq** [comment]
Updated PR description further.
