### PR TITLE
Fix panics on balancer and resolver updates

### LINKED ISSUE #1683: Fix the behavior of addrConn with empty address list
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

git head

### What version of Go are you using (`go version`)?

1.9

### What operating system (Linux, Windows, …) and version?

linux

### What did you do?

I've written my own resolver that resolves addresses using serf. When shutting down I eventually call resolver.ClientConn.NewAddress() with an empty array. This is causing a divide by zero in clientconn.go.

### What did you see instead?

```
I1122 12:28:00.752952    5823 resolver_conn_wrapper.go:106] [GPRC] ccResolverWrapper: sending new addresses to cc: []
I1122 12:28:00.752967    5823 clientconn.go:750] [GPRC] addrConn: tryUpdateAddrs curAddr: {192.168.1.7:33570 0  <nil>}, addrs: []
I1122 12:28:00.752974    5823 clientconn.go:763] [GPRC] addrConn: tryUpdateAddrs curAddrFound: false
I1122 12:28:00.752996    5823 pickfirst.go:68] [GPRC] pickfirstBalancer: HandleSubConnStateChange: 0xc4204ccb60, CONNECTING
panic: runtime error: integer divide by zero

goroutine 3479 [running]:
swarm/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc44bb8d400, 0x2540be400, 0x0)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:920 +0xfa0
swarm/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc44bb8d400)
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:728 +0x2f
created by swarm/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/predmond/src/swarm/go/src/swarm/vendor/google.golang.org/grpc/clientconn.go:727 +0xeb
exit status 2
```

### PR DESCRIPTION
**Pull request by menghanl**
- NewAddress with empty list (addrConn with an empty address list)
 - NewServiceConfig to switch balancer before the first balancer is built

updates #1683

This makes NewSubConn() with empty list return an error, and makes UpdateAddress() with empty list tear the addrConn down. The SubConn won't be usable after this.
Eventually we want to make the SubConn with empty address list stay in TransientFailure but still usable, and balancer still can update this SubConn's address. This will be done in a follow-up PR.

### CODE REVIEW

File: balancer_conn_wrappers.go [hunk 1]
```diff
@@ -183,6 +184,9 @@ func (ccb *ccBalancerWrapper) handleResolvedAddrs(addrs []resolver.Address, err
 }
 
 func (ccb *ccBalancerWrapper) NewSubConn(addrs []resolver.Address, opts balancer.NewSubConnOptions) (balancer.SubConn, error) {
+	if len(addrs) <= 0 {
+		return nil, fmt.Errorf("grpc: cannot create SubConn with empty address list")
```
Comment (dfawley) [inline balancer_conn_wrappers.go]: Should we try to make `NewSubConn([])` do the same thing that `sc := NewSubConn([foo]); sc.UpdateAddresses([])` would do, for consistency?

File: clientconn_test.go [hunk 2]
```diff
@@ -329,6 +331,41 @@ func TestNonblockingDialWithEmptyBalancer(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("failed to dial: %v", err)
+	}
+	defer cc.Close()
+
+	// SwitchBalancer before NewAddress. There was no balancer created, this
+	// makes sure we don't call close on nil balancerWrapper.
+	r.NewServiceConfig(`{"loadBalancingPolicy": "round_robin"}`) // This should not panic.
+
+	time.Sleep(time.Second) //Sleep to make sure the service config is handled by ClientConn.
```
Comment (dfawley) [inline clientconn_test.go]: Space after `//`
