### PR TITLE
Bug fix(Issue#1141): Check if peer is nil before trying to derefer it.

### LINKED ISSUE #1141: grpc.Peer(peer) make a core dump when getTransport occur error at client side
if appoint the CallOption which name is Peer, such as  : 
```
peer := new(peer.Peer)
Call(ctx, req, grpc.Peer(peer))
```

but, when the call.invoke (call.go) return error which occur by getTransport(ctx, gopts), it will make a core dump by rpc_util.Peer (rpc_util.go) because of the c.peer is nil.
```
		t, put, err = cc.getTransport(ctx, gopts)
		if err != nil {
			// TODO(zhaoq): Probably revisit the error handling.
			if _, ok := err.(*rpcError); ok {
				return err
			}
			if err == errConnClosing || err == errConnUnavailable {
				if c.failFast {
					return Errorf(codes.Unavailable, "%v", err)
				}
				continue
			}
			// All the other errors are treated as Internal errors.
			return Errorf(codes.Internal, "%v", err)
		}
```

```
func Peer(peer *peer.Peer) CallOption {
	return afterCall(func(c *callInfo) {
		if c.peer != nil {
			*peer = *c.peer
		}
	})
}
```

### PR DESCRIPTION
**Pull request by MakMukhi**
fixes #1141

### CODE REVIEW

File: rpc_util.go [hunk 1]
```diff
@@ -189,7 +189,9 @@ func Trailer(md *metadata.MD) CallOption {
 // unary RPC.
 func Peer(peer *peer.Peer) CallOption {
 	return afterCall(func(c *callInfo) {
-		*peer = *c.peer
+		if c.peer != nil {
```
Comment (dfawley) [inline rpc_util.go]: Do we need to check c or peer also?
