### PR TITLE
test: fix raceyness check to deflake test http server

### LINKED ISSUE #4990: Flaky test: 10/10k: Test/HTTPHeaderFrameErrorHandlingNormalTrailer & Test/HTTPHeaderFrameErrorHandlingMoreThanTwoHeaders
https://github.com/grpc/grpc-go/runs/4232539138?check_suite_focus=true

```
--- FAIL: Test (45.27s)
    --- FAIL: Test/HTTPHeaderFrameErrorHandlingNormalTrailer (0.00s)
        tlogger.go:116: INFO clientconn.go:175 [core] Channel Created  (t=+344.504µs)
        tlogger.go:116: INFO clientconn.go:1623 [core] original dial target is: "127.0.0.1:35051"  (t=+365.604µs)
        tlogger.go:116: INFO clientconn.go:1628 [core] dial target "127.0.0.1:35051" parse failed: parse "127.0.0.1:35051": first path segment in URL cannot contain colon  (t=+402.405µs)
        tlogger.go:116: INFO clientconn.go:1643 [core] fallback to scheme "passthrough"  (t=+418.005µs)
        tlogger.go:116: INFO clientconn.go:1651 [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:35051 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:35051 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+438.205µs)
        tlogger.go:116: INFO clientconn.go:262 [core] Channel authority set to "127.0.0.1:35051"  (t=+451.305µs)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:35051  <nil> <nil> 0 <nil>}] <nil> <nil>}  (t=+467.705µs)
        tlogger.go:116: INFO resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:127.0.0.1:35051 ServerName: Attributes:<nil> BalancerAttributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+483.906µs)
        tlogger.go:116: INFO clientconn.go:712 [core] ClientConn switching balancer to "pick_first"  (t=+495.706µs)
        tlogger.go:116: INFO clientconn.go:732 [core] Channel switches to new LB policy "pick_first"  (t=+507.806µs)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel Created  (t=+534.706µs)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel(id:1231) created  (t=+563.906µs)
        tlogger.go:116: INFO picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+605.507µs)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to CONNECTING  (t=+654.808µs)
        tlogger.go:116: INFO clientconn.go:1254 [core] Subchannel picks a new address "127.0.0.1:35051" to connect  (t=+682.608µs)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to CONNECTING  (t=+810.509µs)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to READY  (t=+988.411µs)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to READY  (t=+1.021012ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to SHUTDOWN  (t=+1.214114ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to SHUTDOWN  (t=+1.246914ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchannel Deleted  (t=+1.260315ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchanel(id:1231) deleted  (t=+1.269615ms)
        tlogger.go:116: INFO clientconn.go:1099 [core] Channel Deleted  (t=+1.279815ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1231 from a parent (id=1230) that doesn't currently exist  (t=+1.428417ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1231 from a parent (id=1230) that doesn't currently exist  (t=+1.487917ms)
        tlogger.go:116: INFO clientconn.go:175 [core] Channel Created  (t=+1.513418ms)
        tlogger.go:116: INFO clientconn.go:1623 [core] original dial target is: "127.0.0.1:38583"  (t=+1.527718ms)
        tlogger.go:116: INFO clientconn.go:1628 [core] dial target "127.0.0.1:38583" parse failed: parse "127.0.0.1:38583": first path segment in URL cannot contain colon  (t=+1.546718ms)
        tlogger.go:116: INFO clientconn.go:1643 [core] fallback to scheme "passthrough"  (t=+1.578018ms)
        tlogger.go:116: INFO clientconn.go:1651 [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:38583 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:38583 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+1.600019ms)
        tlogger.go:116: INFO clientconn.go:262 [core] Channel authority set to "127.0.0.1:38583"  (t=+1.613319ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:38583  <nil> <nil> 0 <nil>}] <nil> <nil>}  (t=+1.629119ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:127.0.0.1:38583 ServerName: Attributes:<nil> BalancerAttributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+1.644719ms)
        tlogger.go:116: INFO clientconn.go:712 [core] ClientConn switching balancer to "pick_first"  (t=+1.680419ms)
        tlogger.go:116: INFO clientconn.go:732 [core] Channel switches to new LB policy "pick_first"  (t=+1.69482ms)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel Created  (t=+1.72962ms)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel(id:1234) created  (t=+1.75762ms)
        tlogger.go:116: INFO picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+1.784921ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to CONNECTING  (t=+1.805221ms)
        tlogger.go:116: INFO clientconn.go:1254 [core] Subchannel picks a new address "127.0.0.1:38583" to connect  (t=+1.825621ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to CONNECTING  (t=+1.898922ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to READY  (t=+2.139025ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to READY  (t=+2.164725ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to SHUTDOWN  (t=+2.321927ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to SHUTDOWN  (t=+2.338427ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchannel Deleted  (t=+2.350927ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchanel(id:1234) deleted  (t=+2.360727ms)
        tlogger.go:116: INFO clientconn.go:1099 [core] Channel Deleted  (t=+2.370727ms)
        tlogger.go:116: INFO clientconn.go:175 [core] Channel Created  (t=+2.541729ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1234 from a parent (id=1233) that doesn't currently exist  (t=+2.56013ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1234 from a parent (id=1233) that doesn't currently exist  (t=+2.59283ms)
        tlogger.go:116: INFO clientconn.go:1623 [core] original dial target is: "127.0.0.1:42691"  (t=+2.62533ms)
        tlogger.go:116: INFO clientconn.go:1628 [core] dial target "127.0.0.1:42691" parse failed: parse "127.0.0.1:42691": first path segment in URL cannot contain colon  (t=+2.646431ms)
        tlogger.go:116: INFO clientconn.go:1643 [core] fallback to scheme "passthrough"  (t=+2.680731ms)
        tlogger.go:116: INFO clientconn.go:1651 [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:42691 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:42691 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+2.703631ms)
        end2end_test.go:7418: Error at server-side while reading frame. Err: read tcp 127.0.0.1:38583->127.0.0.1:36996: read: connection reset by peer
        tlogger.go:116: INFO clientconn.go:262 [core] Channel authority set to "127.0.0.1:42691"  (t=+2.716931ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:42691  <nil> <nil> 0 <nil>}] <nil> <nil>}  (t=+2.758132ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:127.0.0.1:42691 ServerName: Attributes:<nil> BalancerAttributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+2.775732ms)
        tlogger.go:116: INFO clientconn.go:712 [core] ClientConn switching balancer to "pick_first"  (t=+2.803832ms)
        tlogger.go:116: INFO clientconn.go:732 [core] Channel switches to new LB policy "pick_first"  (t=+2.816733ms)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel Created  (t=+2.834333ms)
        tlogger.go:116: INFO clientconn.go:773 [core] Subchannel(id:1237) created  (t=+2.844733ms)
        tlogger.go:116: INFO picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+2.867533ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to CONNECTING  (t=+2.886033ms)
        tlogger.go:116: INFO clientconn.go:1254 [core] Subchannel picks a new address "127.0.0.1:42691" to connect  (t=+2.897134ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to CONNECTING  (t=+3.029735ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to READY  (t=+3.125536ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to READY  (t=+3.156337ms)
        tlogger.go:116: INFO clientconn.go:417 [core] Channel Connectivity change to SHUTDOWN  (t=+3.328339ms)
        tlogger.go:116: INFO clientconn.go:1143 [core] Subchannel Connectivity change to SHUTDOWN  (t=+3.346039ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchannel Deleted  (t=+3.358939ms)
        tlogger.go:116: INFO clientconn.go:1501 [core] Subchanel(id:1237) deleted  (t=+3.369139ms)
        tlogger.go:116: INFO clientconn.go:1099 [core] Channel Deleted  (t=+3.394439ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1237 from a parent (id=1236) that doesn't currently exist  (t=+3.49324ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 1237 from a parent (id=1236) that doesn't currently exist  (t=+3.518541ms)
FAIL
FAIL	google.golang.org/grpc/test	107.008s
```

### PR DESCRIPTION
**Pull request by arvindbr8**
The precise behavior of the test https server is subject a raceyness around the timing of when TCP packets are sent from client to server, and when we tell the server to stop, so we need to account for both of possible error messages

1. If the call to ss.S.Stop() causes the server's sockets to close while there's still in-fight data from the client on the TCP connection, then the kernel can send an RST back to the client (also see https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c). Note that while this condition is expected to be rare due to the rpcStartedOnServer synchronization, in theory it should be possible, e.g. if the client sends a BDP ping at the right time.
2. If, for example, the call to ss.S.Stop() happens after the RPC headers have been received at the server, then the TCP connection can shutdown gracefully when the server's socket closes. raceyness around checks if the error message when checking reading frames

This was accounted for in another end2end test. Had to replicate the same for the test HTTP server created in this package

Ran the test for 50K times on forge and no flakes found 

```
blaze test third_party/golang/grpc/test:test_test  --test_filter=Test/HTTPHeaderFrameErrorHandlingNormalTrailer --runs_per_test=50000 --test_env="GRPC_GO_LOG_SEVERITY_LEVEL=INFO" --test_env="GRPC_GO_LOG_VERBOSITY_LEVEL=99" --config=gotsan
Starting local Blaze server and connecting to it...
INFO: Streaming build results to: http://sponge2/d7546792-027d-449d-b60c-b89927a8c8b7
INFO: Analyzed target //third_party/golang/grpc/test:test_test (491 packages loaded, 13066 targets configured).
INFO: Found 1 test target...
Target //third_party/golang/grpc/test:test_test up-to-date:
  blaze-bin/third_party/golang/grpc/test/test_test
INFO: Elapsed time: 321.757s, Forge stats: 1847/51865 actions cached, 5.1h CPU used, 2.7m queue time, 1.53 GB ObjFS output (novel bytes: 120.3 MB), 0.0 MB local output, Critical Path: 157.26s, Remote (97.96% of the time): [queue: 0.00%, setup: 4.33%, process: 3.83%, retry: 77.95%]
//third_party/golang/grpc/test:test_test                                 PASSED in 128.9s
  Stats over 50000 runs: max = 128.9s, min = 0.4s, avg = 2.3s, dev = 7.2s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Streaming build results to: http://sponge2/d7546792-027d-449d-b60c-b89927a8c8b7
INFO: Build completed successfully, 51845 total actions
```

Fixes #4990 

RELEASE NOTES:
* test: deflake test

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -888,6 +888,23 @@ type lazyConn struct {
...
+// are sent from client to server, and when we tell the server to stop, so we need to account for both
+// of these possible error messages:
+//  1. If the call to ss.S.Stop() causes the server's sockets to close while there's still in-fight
+//     data from the client on the TCP connection, then the kernel can send an RST back to the client (also
+//     see https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c). Note that while this
+//     condition is expected to be rare due to the rpcStartedOnServer synchronization, in theory it should
+//     be possible, e.g. if the client sends a BDP ping at the right time.
+//  2. If, for example, the call to ss.S.Stop() happens after the RPC headers have been received at the
+//     server, then the TCP connection can shutdown gracefully when the server's socket closes. raceyness around checks if the error message when checking reading frames
+const possibleConnResetMsg = "connection reset by peer"
```
Comment (arvindbr8) [inline test/end2end_test.go:901]: these variables are used for error messages below. I tried  returning the error message as is from the func like ok, errMsg := errMsgContainsPossibleStopMessages.. But the other usage in `TestDetailedConnectionCloseErrorPropagatesToRpcError` starts to look ugly.. Let me know if you can think about a better way

File: test/end2end_test.go [hunk 2]
```diff
@@ -6930,14 +6947,14 @@ func (s *httpServer) start(t *testing.T, lis net.Listener) {
 		}
 		writer.Flush() // necessary since client is expecting preface before declaring connection fully setup.
 		var sid uint32
-		// Loop until conn is closed and framer returns io.EOF
+		// Loop until conn is closed and framer returns possible Stop error messages
 		for requestNum := 0; ; requestNum = (requestNum + 1) % len(s.responses) {
 			// Read frames until a header is received.
 			for {
 				frame, err := framer.ReadFrame()
 				if err != nil {
```
Comment (dfawley) [inline test/end2end_test.go:6955]: Let's move the `nil` check into `errMsgContainsPossibleStopMessages` and simplify both these call sites  (remove this `if` and remove `err == nil ||` above.

File: test/end2end_test.go [hunk 3]
```diff
@@ -888,6 +888,23 @@ type lazyConn struct {
 	beLazy int32
 }
 
+// errMsgContainsPossibleStopMessages addresses around the timing of when TCP packets
```
Comment (dfawley) [inline test/end2end_test.go:891]: This comment should be attached to the function.

The consts can be defined inside the function, too.

Also please take a look at this comment again.  The first bit reads a little awkwardly to me right now.

File: test/end2end_test.go [hunk 4]
```diff
@@ -888,6 +888,23 @@ type lazyConn struct {
...
+//     data from the client on the TCP connection, then the kernel can send an RST back to the client (also
+//     see https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c). Note that while this
+//     condition is expected to be rare due to the rpcStartedOnServer synchronization, in theory it should
+//     be possible, e.g. if the client sends a BDP ping at the right time.
+//  2. If, for example, the call to ss.S.Stop() happens after the RPC headers have been received at the
+//     server, then the TCP connection can shutdown gracefully when the server's socket closes. raceyness around checks if the error message when checking reading frames
+const possibleConnResetMsg = "connection reset by peer"
+const possibleEOFMsg = "error reading from server: EOF"
+
+func errMsgContainsPossibleStopMessages(err error) bool {
```
Comment (dfawley) [inline test/end2end_test.go:904]: Can we shorten this?  `isConnClosedErr()`?

File: test/end2end_test.go (hunk 1 above)
Comment (dfawley) [reply test/end2end_test.go:901]: No this seems fine to me.

File: test/end2end_test.go [hunk 5]
```diff
@@ -888,6 +888,23 @@ type lazyConn struct {
...
+// errMsgContainsPossibleStopMessages addresses around the timing of when TCP packets
+// are sent from client to server, and when we tell the server to stop, so we need to account for both
+// of these possible error messages:
+//  1. If the call to ss.S.Stop() causes the server's sockets to close while there's still in-fight
+//     data from the client on the TCP connection, then the kernel can send an RST back to the client (also
+//     see https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c). Note that while this
+//     condition is expected to be rare due to the rpcStartedOnServer synchronization, in theory it should
+//     be possible, e.g. if the client sends a BDP ping at the right time.
+//  2. If, for example, the call to ss.S.Stop() happens after the RPC headers have been received at the
+//     server, then the TCP connection can shutdown gracefully when the server's socket closes. raceyness around checks if the error message when checking reading frames
```
Comment (dfawley) [inline test/end2end_test.go:900]: Please wrap all block comments to 80 columns.

**Review by dfawley — COMMENTED** [review]
Looks great.  Just a few suggestions.

File: test/end2end_test.go [hunk 6]
```diff
@@ -6855,8 +6868,12 @@ func (s) TestHTTPHeaderFrameErrorHandlingNormalTrailer(t *testing.T) {
 			},
 			errCode: codes.Internal,
 		},
-	} {
-		doHTTPHeaderTest(t, test.errCode, test.responseHeader, test.trailer)
+	}
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			doHTTPHeaderTest(t, test.errCode, test.responseHeader, test.trailer)
```
Comment (easwars) [inline test/end2end_test.go:6874]: Optional: 

Test helpers, as referred to in Go, are functions which perform some setup or cleanup task associated with the test.  See [here](go/go-style/decisions#mark-test-helpers).

But here, `doHTTPHeaderTest()` is the one which runs the actual test, but is marked as test helper with a call to `t.Helper()` and directly calls `t.Error/Fatal` etc. I see that there are bunch of callers for this function (~6). You can either fix this function to not call `t.Helper()` and instead return an error and have the calling test call `t.Error/Fatal`, or add a TODO here and we will get to this at some point in the future.

File: test/end2end_test.go [hunk 7]
```diff
@@ -6930,14 +6947,14 @@ func (s *httpServer) start(t *testing.T, lis net.Listener) {
 		}
 		writer.Flush() // necessary since client is expecting preface before declaring connection fully setup.
 		var sid uint32
-		// Loop until conn is closed and framer returns io.EOF
+		// Loop until conn is closed and framer returns possible Stop error messages
```
Comment (easwars) [inline test/end2end_test.go:6950]: Nit: replace `possible Stop error messages` with something more readable and terminate with a period.

File: test/end2end_test.go [hunk 8]
```diff
@@ -1037,7 +1043,10 @@ func (s) TestDetailedConnectionCloseErrorPropagatesToRpcError(t *testing.T) {
 	// the RPC has been started on it.
 	<-rpcStartedOnServer
 	ss.S.Stop()
-	if _, err := stream.Recv(); err == nil || (!strings.Contains(err.Error(), possibleConnResetMsg) && !strings.Contains(err.Error(), possibleEOFMsg)) {
+	// The precise behavior of this test is subject to raceyness around the timing of when TCP packets
+	// are sent from client to server, and when we tell the server to stop, so we need to account for both
+	// of these possible error messages
```
Comment (easwars) [inline test/end2end_test.go:1048]: Same here: Please wrap all block comments to 80 columns.

Comment (zasweq) [reply test/end2end_test.go:1048]: From one of my earlier PRs on the team (assuming you use JetBrains IDE's which are by far the best): [menghanl](https://github.com/menghanl) [on Apr 13, 2021](https://github.com/grpc/grpc-go/pull/4332#discussion_r612653948)
I like to wrap the comments (but only the comments) to 80.

And I use this: https://plugins.jetbrains.com/plugin/7234-wrap-to-column

Comment (easwars) [reply test/end2end_test.go:1048]: > assuming you use JetBrains IDE's which are by far the best

Subjectivity !!

File: test/end2end_test.go (hunk 6 above)
Comment (arvindbr8) [reply test/end2end_test.go:6874]: done. please let me know how the changes look like @easwars

File: test/end2end_test.go [hunk 9]
```diff
@@ -888,6 +888,31 @@ type lazyConn struct {
...
+// isConnClosedErr checks the error msg for possible conn closed messages. There
+// is a raceyness in the timing of when TCP packets are sent from client to
+// server, and when we tell the server to stop, so we need to check for both of
+// these possible error messages:
+//  1. If the call to ss.S.Stop() causes the server's sockets to close while
+//     there's still in-fight data from the client on the TCP connection, then
+//     the kernel can send an RST back to the client (also see
+//     https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c).
+//     Note that while this condition is expected to be rare due to the
+//     rpcStartedOnServer synchronization, in theory it should be possible,
```
Comment (easwars) [inline test/end2end_test.go:904]: Mentioning `rpcStartedOnServer` in this comment might no longer be appropriate because it is used only `TestDetailedConnectionCloseErrorPropagatesToRpcError`. But `isConnClosedErr` is also used from other places now. So, this comment might need to updated a little to apply for all usages of this function.

File: test/end2end_test.go [hunk 10]
```diff
@@ -6855,8 +6884,14 @@ func (s) TestHTTPHeaderFrameErrorHandlingNormalTrailer(t *testing.T) {
 			},
 			errCode: codes.Internal,
 		},
-	} {
-		doHTTPHeaderTest(t, test.errCode, test.responseHeader, test.trailer)
+	}
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
```
Comment (easwars) [inline test/end2end_test.go:6889]: +1 for using `t.Run()` here.

File: test/end2end_test.go [hunk 11]
```diff
@@ -1037,7 +1051,10 @@ func (s) TestDetailedConnectionCloseErrorPropagatesToRpcError(t *testing.T) {
 	// the RPC has been started on it.
 	<-rpcStartedOnServer
 	ss.S.Stop()
-	if _, err := stream.Recv(); err == nil || (!strings.Contains(err.Error(), possibleConnResetMsg) && !strings.Contains(err.Error(), possibleEOFMsg)) {
+	// The precise behavior of this test is subject to raceyness around the timing
+	// of when TCP packets are sent from client to server, and when we tell the
+	// server to stop, so we need to account for both possible error messages.
+	if _, err := stream.Recv(); err == nil || !isConnClosedErr(err) {
```
Comment (dfawley) [inline test/end2end_test.go:1057]: I would still combine these.

`isConnClosedErr(nil)` should be false. And actually it is now.  So I think just remove the `err == nil ||` here?

Comment (dfawley) [inline test/end2end_test.go:1057]: FWIW / for future reference, this will pass if `err == io.EOF` (due to the implementation of `isConnClosedErr`), which happens when streams are terminated successfully.  But, this is impossible in this test since the handler never returns nil, so I don't think anything needs to change here.

File: test/end2end_test.go [hunk 12]
```diff
@@ -6994,11 +7031,10 @@ func (s *httpServer) start(t *testing.T, lis net.Listener) {
 	}()
 }
 
-func doHTTPHeaderTest(t *testing.T, errCode codes.Code, headerFields ...[]string) {
-	t.Helper()
+func doHTTPHeaderTest(t *testing.T, errCode codes.Code, headerFields ...[]string) error {
 	lis, err := net.Listen("tcp", "localhost:0")
 	if err != nil {
-		t.Fatalf("Failed to listen. Err: %v", err)
+		return fmt.Errorf("failed to listen. Err: %v", err)
```
Comment (easwars) [inline test/end2end_test.go:7037]: I have started making this comment very recently that we should try to make out error strings concise, but convey all the important information that it needs to contain. This means that we should try to avoid filler words like failed, error etc. 

So, I would recommend changing the error strings in this function as follows:

`return fmt.Errorf("listening on %q: %v", "localhost:0", err)`

`return fmt.Errorf("dial(%q): %v", lis.Addr().String(), err)`

`return fmt.Errorf("creating FullDuplex stream: %v", err)`

`return fmt.Errorf("stream.Recv() = %v, want error code: %v", err, errCode)`

File: test/end2end_test.go (hunk 2 above)
Comment (dfawley) [reply test/end2end_test.go:6975]: Yeah I think I misread this (the `return` outside the following `if` is important), so I think this part is fine now.  I left another comment at the other call site.

File: test/end2end_test.go (hunk 9 above)
Comment (arvindbr8) [reply test/end2end_test.go:904]: i missed that. Let me update that

File: test/end2end_test.go (hunk 11 above)
Comment (arvindbr8) [reply test/end2end_test.go:1057]: sure that makes sense

File: test/end2end_test.go (hunk 10 above)
Comment (arvindbr8) [reply test/end2end_test.go:6889]: I think there are more places to use `t.Run()` in this package. But seemed like a lot of diff for this PR

File: test/end2end_test.go (hunk 12 above)
Comment (arvindbr8) [reply test/end2end_test.go:7037]: done!

File: test/end2end_test.go (hunk 11 above)
Comment (arvindbr8) [reply test/end2end_test.go:1057]: I didnt get that. With the current the implementation, `isConnClosedErr(io.EOF)` = true. So wouldn't the check fail?

Comment (dfawley) [reply test/end2end_test.go]: Right, the check would fail and the test would pass.  But we don't want the test to pass if the RPC ends successfully, right?

Comment (arvindbr8) [reply test/end2end_test.go]: ah gotcha. 
i know you said nothing needs to change earlier. But for proper guardrails, should I remove the EOF check from `isConnClosedErr` and then add EOF check in the httpServer Start read loop?

Comment (dfawley) [reply test/end2end_test.go]: If you want to change anything, I'd _probably_ do it the other way around: adjust this call site since `stream.Recv` is probably a more "special" case:

```go
if _, err := stream.Recv(); err == io.EOF || !isConnClosedErr(err) {
```

Comment (arvindbr8) [reply test/end2end_test.go]: done

**Review by dfawley — APPROVED** [review]

**Review by easwars — APPROVED** [review]
