### PR TITLE
clusterresolver: handle EDS nacks and resource-not-found errors correctly

### LINKED ISSUE #6217: xds: fix cluster_resolver LB policy behavior upon receipt of NACKed EDS resource
Let's say the `cluster_resolver` LB policy receives two discovery mechanisms as part of its configuration: a higher priority EDS and a lower priority LOGICAL_DNS cluster. The `cluster_resolver` LB policy creates child policy configs only after both discovery mechanisms are resolved. 

Let's specifically consider the case where the first EDS response for the higher priority EDS cluster is NACKed by the xDS client. This is handled by the `edsDiscoveryMechanism` here: https://github.com/grpc/grpc-go/blob/2cd95c7514a3d02aa2d98591c013885cb44fbdeb/xds/internal/balancer/clusterresolver/resource_resolver_eds.go#L72

The error is propagated to the `cluster_resolver` LB policy by pushing it onto a channel here: https://github.com/grpc/grpc-go/blob/2cd95c7514a3d02aa2d98591c013885cb44fbdeb/xds/internal/balancer/clusterresolver/resource_resolver.go#L283

At this point, since the `cluster_resolver` has not created a child policy (because it has not received valid responses from both discovery mechanisms), it will report `TransientFailure` to its parent here: https://github.com/grpc/grpc-go/blob/2cd95c7514a3d02aa2d98591c013885cb44fbdeb/xds/internal/balancer/clusterresolver/clusterresolver.go#L256

Instead the `cluster_resolver` should treat this error from the xDS client as though it received an EDS response with a single priority and no localities. This will allow it to create the priority child (once it receives a response from the DNS mechanism as well), and will allow it to fail over to it.

Also, the `cluster_resolver` LB policy should do the same thing if the EDS watcher returns a resource-does-not-exist error. The only difference between a resource NACK error and a resource-does-not-exist error is that the former ignores the error if there was a previous result, whereas the latter does not.

### PR DESCRIPTION
**Pull request by easwars**
EDS nacks and resource-not-found errors are to be treated by the cluster_resolver LB policy as though it received an EDS update with no endpoints. This would mean that for aggregate clusters, it would result in fallback (if appropriate), and non-aggregate clusters, it would result in the channel moving to `TRANSIENT_FAILURE` (because the child policy, priority LB, will put the channel in `TRANSIENT_FAILURE` when there are no priorities in its configuration).

The only difference between how a NACK error and a resource-not-found error is handled by the cluster_resolver LB policy is that in the NACK case, the LB policy ignores the error if there was a previous result. The resource-not-found error is received by the cluster_resolver LB policy *only* when it does not have a previously received good update. This is because, the xds client will not propagate this error to its watchers (because EDS is not state-of-the-world) if it already has the resource in its cache.

Fixes #6217 

RELEASE NOTES:
- clusterresolver: handle EDS nacks and resource-not-found errors correctly

### CODE REVIEW

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go [hunk 1]
```diff
@@ -92,13 +93,39 @@ func (er *edsDiscoveryMechanism) OnError(err error) {
 		return
 	}
 
-	er.topLevelResolver.onError(err)
+	if er.logger.V(2) {
+		er.logger.Infof("EDS discovery mechanism for resource %q reported error: %v", er.nameToWatch, err)
+	}
+
+	// If a previously received good configuration exists, continue to use it.
+	// Else report an empty update that would result in the child policy
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/resource_resolver_eds.go:101]: "child priority of priority corresponding to EDS." also drop the no priorities or localities, there would still be a hierarchy of priorities, but one of them will report TF.

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go [hunk 2]
```diff
@@ -92,13 +93,39 @@ func (er *edsDiscoveryMechanism) OnError(err error) {
...
 	if er.stopped.HasFired() {
 		return
 	}
 
-	er.topLevelResolver.onError(xdsresource.NewErrorf(xdsresource.ErrorTypeResourceNotFound, "resource name %q of type Endpoints not found in received response", er.nameToWatch))
+	if er.logger.V(2) {
+		er.logger.Infof("EDS discovery mechanism for resource %q reported resource-does-not-exist error", er.nameToWatch)
+	}
+
+	// Report an empty update that would result in the child policy reporting
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/resource_resolver_eds.go:124]: Same here.

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go [hunk 3]
```diff
@@ -92,13 +93,39 @@ func (er *edsDiscoveryMechanism) OnError(err error) {
...
+	// If a previously received good configuration exists, continue to use it.
+	// Else report an empty update that would result in the child policy
+	// reporting TRANSIENT_FAILURE (as there would be no priorities or
+	// localities).
+	er.mu.Lock()
+	if er.update != nil {
+		er.mu.Unlock()
+		return
+	}
+	er.update = &xdsresource.EndpointsUpdate{}
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/resource_resolver_eds.go:109]: Actually can you move else comment here after rewriting. And can you also mention alongside what I wrote above that this empty address list plumbing behavior only applies to the *first callback being an error* (of either type), and also triggering failover.

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go [hunk 4]
```diff
@@ -771,3 +779,290 @@ func (s) TestAggregateCluster_BadEDS_BadDNS(t *testing.T) {
...
+	// with a short watch expiry timeout.
+	xdsClient, close, err := xdsclient.NewWithConfigForTesting(&bootstrap.Config{
+		XDSServer: xdstestutils.ServerConfigForAddress(t, mgmtServer.Address),
+		NodeProto: &v3corepb.Node{Id: nodeID},
+	}, defaultTestWatchExpiryTimeout, time.Duration(0))
+	if err != nil {
+		t.Fatalf("failed to create xds client: %v", err)
+	}
+	defer close()
+	defer close()
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:1010]: Only need one close call

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go [hunk 5]
```diff
@@ -771,3 +779,290 @@ func (s) TestAggregateCluster_BadEDS_BadDNS(t *testing.T) {
...
+	if err := mgmtServer.Update(ctx, resources); err != nil {
+		t.Fatal(err)
+	}
+
+	// Create an xDS client talking to the above management server, configured
+	// with a short watch expiry timeout.
+	xdsClient, close, err := xdsclient.NewWithConfigForTesting(&bootstrap.Config{
+		XDSServer: xdstestutils.ServerConfigForAddress(t, mgmtServer.Address),
+		NodeProto: &v3corepb.Node{Id: nodeID},
+	}, defaultTestWatchExpiryTimeout, time.Duration(0))
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:1005]: Optional, mainly musing. The test above polls for a second, and this requires 500 milliseconds to invoke the resource not found error. Is there a way to write this that doesn't introduce testing time as such? I don't see a way around it but curious your thoughts.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 6]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
 	}
 }
 
+// TestEDS_BadUpdateWithoutPreviousGoodUpdate tests the case where the
+// management server sends a bad update (one that is NACKed by the xDS client).
+// Since the cluster_resolver LB policy does not have a previously received good
+// update, it is expected to treat this bad update as though it received an
+// update with no endpoints. Hence RPCs are expected to fail with "all
+// priorities removed" error.
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:864]: I'm having trouble following why we want this error to be "AllPrioritiesRemoved". The priority still exists right? I.e. in the failover case where you have two children top level priority reports TF causing failover. Thus, why is it when there's only one discovery mechanism it doesn't have the same behavior, but has specifically this error? Don't we want a TF from weighted target? Or does that cause this error? Or do we just not create a priority child in one discovery mechanism, but with two you create and send down empty update?

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 7]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+		Weight:   1,
+		Backends: []e2e.BackendOptions{{Port: testutils.ParsePort(t, server.Address)}},
+	}})
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	if err := mgmtServer.Update(ctx, resources); err != nil {
+		t.Fatal(err)
+	}
+
+	// Create an xDS xdsClient for use by the cluster_resolver LB policy.
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:956]: here and elsewhere: double xDS prefix

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 8]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+// server and the test verifies that RPCs are successful. Then, a bad update is
+// received from the management server (one that is NACKed by the xDS client).
+// The test verifies that the previously received good update is still being
+// used and that RPCs are still successful.
+func (s) TestEDS_BadUpdateWithPreviousGoodUpdate(t *testing.T) {
+	// Spin up a management server to receive xDS resources from.
+	mgmtServer, nodeID, bootstrapContents, _, cleanup1 := e2e.SetupManagementServer(t, e2e.ManagementServerOptions{})
+	defer cleanup1()
+
+	// Start a backend server that implementats the TestService.
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:940]: same here

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 9]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+	// the xDS client. But since the cluster_resolver LB policy has a previously
+	// received good EDS update, it should continue using it.
+	resources.Endpoints[0].Endpoints[0].LbEndpoints[0].LoadBalancingWeight = &wrapperspb.UInt32Value{Value: 0}
+	if err := mgmtServer.Update(ctx, resources); err != nil {
+		t.Fatal(err)
+	}
+
+	// Ensure that RPCs continue to succeed for the next second.
+	for end := time.Now().Add(time.Second); time.Now().Before(end); <-time.After(defaultTestShortTimeout) {
+		if _, err := client.EmptyCall(ctx, &testpb.Empty{}); err != nil {
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:1006]: Verify rr or just check the address list? This just asserts it continues to work, but I think it'd make sense to keep the assertion on it only routing to the one address.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 10]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+	// balancing weight of 0. This will result in the resource being NACKed by
+	// the xDS client. But since the cluster_resolver LB policy has a previously
+	// received good EDS update, it should continue using it.
+	resources.Endpoints[0].Endpoints[0].LbEndpoints[0].LoadBalancingWeight = &wrapperspb.UInt32Value{Value: 0}
+	if err := mgmtServer.Update(ctx, resources); err != nil {
+		t.Fatal(err)
+	}
+
+	// Ensure that RPCs continue to succeed for the next second.
+	for end := time.Now().Add(time.Second); time.Now().Before(end); <-time.After(defaultTestShortTimeout) {
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:1005]: Same thing here wrt 1 second additional polling time.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 11]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+		Backends: []e2e.BackendOptions{{Port: testutils.ParsePort(t, server.Address)}},
+	}})
+	resources.Endpoints[0].Endpoints[0].LbEndpoints[0].LoadBalancingWeight = &wrapperspb.UInt32Value{Value: 0}
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	if err := mgmtServer.Update(ctx, resources); err != nil {
+		t.Fatal(err)
+	}
+
+	// Create an xDS xdsClient for use by the cluster_resolver LB policy.
```
Comment (zasweq) [inline xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:890]: Here as well.

**Review by zasweq — CHANGES_REQUESTED** [review]
Looks good overall just minor nits :). Spurred some interesting discussion with Eric.

**Review by zasweq — APPROVED** [review]
going to approve since overall this looked good to me, and I'm taking leave. Please get to the comments though :).

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go [hunk 12]
```diff
@@ -771,3 +779,290 @@ func (s) TestAggregateCluster_BadEDS_BadDNS(t *testing.T) {
...
+		NodeID: nodeID,
+		Clusters: []*v3clusterpb.Cluster{
+			makeAggregateClusterResource(clusterName, []string{edsClusterName, dnsClusterName}),
+			e2e.DefaultCluster(edsClusterName, "", e2e.SecurityLevelNone),
+			makeLogicalDNSClusterResource(dnsClusterName, dnsHostName, dnsPort),
+		},
+		Endpoints:      []*v3endpointpb.ClusterLoadAssignment{e2e.DefaultEndpoint(edsClusterName, "localhost", []uint32{uint32(ports[0])})},
+		SkipValidation: true,
+	}
+
```
[the remark this answers is not in the document]
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:918]: Everything up to this point is already some sort of a helper function. So grouping them all into another helper for the sake of two tests does not seem like a good idea to me. Also, the number of return values from such a helper would be huge making the test not very readable.

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go (hunk 5 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:1005]: > The test above polls for a second.

I don't understand what you are referring to here.

> Is there a way to write this that doesn't introduce testing time as such?

For RDS/EDS, the only way to force a resource-not-found error is by the watch timer firing. And since this is an e2e test, there is no way for us to inject such an event other than actually waiting for it to happen. And the only thing we can do here is to pass a really low value for the watch timeout.

Also, the code towards the end of this test, where it verifies fallback does not actually depend on any timings. It simply verifies that an RPC gets routed to a backend in the DNS cluster before the test context expires.

> I don't see a way around it but curious your thoughts.

I don't see a way either :)

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go (hunk 4 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:1010]: Done.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 6 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:864]: In this case, the EDS discovery mechanism sends an empty `xdsresource.EndpointsUpdate` to the cluster_resolver LB policy, and this results in a configuration that does not contain priorities. When such a configuration is sent to the priority LB policy, this is error that we expect.

Do you see any downsides to doing this? Or do you see any advantages of sending a configuration with one priority (but no endpoints) to the priority LB policy and letting weighted_target set the channel to TRANSIENT_FAILURE. I don't see any benefits of doing so, but would like to hear your opinion on it.

> Or do we just not create a priority child in one discovery mechanism, but with two you create and send down empty update?

That is not true. Even in the aggregate case, if the EDS discovery mechanism returns an emoty `xdsresource.Endpoints` update, the generated config will not have a priority child for the EDS discovery mechanism. (Note that , it will continue to have the EDS child if there was a previously received good response).

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go [hunk 13]
```diff
@@ -852,6 +856,225 @@ func (s) TestEDS_ClusterResourceUpdates(t *testing.T) {
...
+// Since the cluster_resolver LB policy does not have a previously received good
+// update, it is expected to treat this bad update as though it received an
+// update with no endpoints. Hence RPCs are expected to fail with "all
+// priorities removed" error.
+func (s) TestEDS_BadUpdateWithoutPreviousGoodUpdate(t *testing.T) {
+	// Spin up a management server to receive xDS resources from.
+	mgmtServer, nodeID, bootstrapContents, _, cleanup1 := e2e.SetupManagementServer(t, e2e.ManagementServerOptions{})
+	defer cleanup1()
+
+	// Start a backend server that implementats the TestService.
```
[the remark this answers is not in the document]
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:870]: Done.

😵‍💫

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 11 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:890]: Done.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 8 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:940]: Done.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 7 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:956]: Done.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 9 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:1006]: Done, switched to checking for RR.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 10 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:1005]: Again, this being an e2e test, there is no way for us to ensure that the update we pushed to the management server was received by the xDS client and the configuration plumbed all the way down to all the LB policies, and the picker updated etc. So, we have to rely on some heuristic. We have been using this model a lot in these e2e tests, and yes, it does add a second of delay to the test, but it does ensure that the test is not flaky (because it was initially before I resorted to this model).

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go (hunk 1 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/resource_resolver_eds.go:101]: As mentioned in the other review comment, an empty update would result in that child not being created. I updated the comment anyways, making it reflect reality more than it was previously doing.

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go (hunk 3 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/resource_resolver_eds.go:109]: Updated.

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go (hunk 2 above)
Comment (easwars) [reply xds/internal/balancer/clusterresolver/resource_resolver_eds.go:124]: Done. Same as previous. Rewrote it, but not exactly how you wrote it.

**Review by easwars — COMMENTED** [review]
Thanks for the review.

**Review by easwars — COMMENTED** [review]
Thanks for the review.

File: xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go (hunk 5 above)
Comment (zasweq) [reply xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go:1005]: Wrt timer...could do something like: https://github.com/grpc/grpc-go/blob/master/xds/internal/balancer/outlierdetection/balancer.go#L50 for time.AfterFunc, or https://github.com/grpc/grpc-go/pull/4270/files#diff-cfb871b425a217deb8602c43a41b39ed1378776d5a40bebee381fec0f231a011R51 for a newTimer. But yeah, prob not worth it in this scenario. I also was thinking setting the 500 ms to something like 10ms since I don't think it matters the length.

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 10 above)
Comment (zasweq) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:1005]: Alright, sgtm.

File: xds/internal/balancer/clusterresolver/resource_resolver_eds.go (hunk 1 above)
Comment (zasweq) [reply xds/internal/balancer/clusterresolver/resource_resolver_eds.go]: Oh ok I see, I just remember having to add TF back from weighted target if addr list is zero in UpdateClientConnState. That's prob why I was under the impression the system was two children with top priority child and second priority child, and first sends TF back. The first one just not being created makes sense too haha :).

File: xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go (hunk 6 above)
Comment (zasweq) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:864]: Haha, right. As per my other reply, I was under the impression that the system was "Or do you see any advantages of sending a configuration with one priority (but no endpoints) to the priority LB policy and letting weighted_target set the channel to TRANSIENT_FAILURE". Thus, I made this comment as the error did not make sense to me. The explanation of how the system works sgtm and is cleaner, and the error makes sense. Curious though, is this scoped in a gRFC? Or just an implementation detail per language not explicitly defined. We should I think shoot for implementation consistency between other languages.

Comment (easwars) [reply xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go:864]: We can discuss this in the chat room to see what the other languages do and whether this is scoped out in any gRFC.
