### PR TITLE
clientconn: override authority with address's ServerName, if set

### LINKED ISSUE #3038: Use a custom authority for each connection in a single ClientConn
Issue was originally reported in https://github.com/kubernetes/kubernetes/issues/83028 and is also tracked in etcd via https://github.com/etcd-io/etcd/issues/11180.

### What version of gRPC are you using?

grpc v1.23.1

### What version of Go are you using (`go version`)?

go1.12.2

### What operating system (Linux, Windows, …) and version?

debian linux

### What did you do?

Created 3 etcd servers, each with its own hostname as the Subject Alternative Name in its cert, e.g.:

```
Certificate:
    Data:
    ...
    X509v3 extensions:
        X509v3 Subject Alternative Name: 
                DNS:member1.etcd.local
```

And attempt to load balance across them with an etcd client that uses the grpc load balancer and has the correct CA cert.

The etcd issue is reproduced by: https://github.com/jpbetz/etcd/blob/etcd-lb-dnsname-failover/reproduction.md

But if we can come up with a grpc example that solves the problem, we can apply that to etcd. So we created the [load_balancing example with TLS](https://github.com/jpbetz/grpc-go/blob/lb-with-tls/examples/features/load_balancing/README.md#try-it-this-has-been-modified-to-include-tls) to highlight the grpc issue in isolation.

### What did you expect to see?

Client load balances across the servers.

### What did you see instead?

For the case of kubernetes and etcd case:

> W0924 14:42:29.368784 248333 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://member3.etcd.local:32379 0 }. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for member3.etcd.local, not member1.etcd.local"

For the grpc load balancer example with TLS enabled:

```
--- calling helloworld.Greeter/SayHello with pick_first ---
2019/09/24 17:58:49 could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for member2.etcd.local, not lb.example.grpc.io"
exit status 1
```

cc @gyuho @liggitt

### PR DESCRIPTION
**Pull request by jpbetz**
Fixes #3038

By default it is not set and the dialed target is used as the authority for all load balanced endpoints. This enables load balanced clients to use per-endpoint authorities when the address's ServerName is set.

### CODE REVIEW

**Comment by dfawley** [comment]
Thanks for the PR @jpbetz.  LGTM, but we should also document the new behavior on `resolver.Address.ServerName`, including a warning about being careful when using the field, e.g. don't use any untrusted I/O to populate this field or it could effectively defeat any security provided by TLS.

**Comment by jpbetz** [comment]
@dfawley godoc add to `ServerName`.

I've also downstream tested this change with etcd and it works as expected.

File: resolver/resolver.go [hunk 1]
```diff
@@ -86,9 +86,15 @@ type Address struct {
 	// Type is the type of this address.
 	Type AddressType
 	// ServerName is the name of this address.
+	// If non-empty, the ServerName is used as the transport certification authority for.
```
Comment (dfawley) [inline resolver/resolver.go]: Typo: remove "." after "for"

File: resolver/resolver.go [hunk 2]
```diff
@@ -86,9 +86,15 @@ type Address struct {
...
+	// the address.
```
Comment (dfawley) [inline resolver/resolver.go]: Let's also add: ", instead of the hostname from the Dial target string.  In most cases, this should not be set."

**Comment by jpbetz** [comment]
Feedback applied
