### PR TITLE
xdsclient: stop batching writes on the ADS stream

### LINKED ISSUE #8125: xdsclient: race around resource subscriptions and unsubscsriptions
We are seeing a race with the xDS client when the application has multiple grpc channels being created and shutdown at the same time, repeatedly. One possible way to get this race to happen is for an application to open multiple grpc channels to the same target (around the same time), make one RPC in each channel, and shut it down, and do this process over and over again.

The sequence of events that trigger the race is as follows:
- Channel `1` is created to target `foo`. It goes through the whole xDS flow successfully and is being shut down.
- At around the same time, Channel `2` is created to the same target `foo`.
- As part of Channel `1` shutdown, it starts unsubscribing to the xDS resources.
- The xDS client function to unsubscribe schedules a callback on the serializer. The function returns early, but the actual work of sending the ADS request to effect the unsubscription happens asynchronously. See: https://github.com/grpc/grpc-go/blob/aa629e0ef3e78483883a55ea25c1da17236c97e6/xds/internal/xdsclient/authority.go#L680
- When the scheduled callback runs, two things happens:
  - the internal state in the ADS stream implementation though is updated to reflect the fact that the resource is no longer subscribed to. See: https://github.com/grpc/grpc-go/blob/aa629e0ef3e78483883a55ea25c1da17236c97e6/xds/internal/xdsclient/transport/ads/ads_stream.go#L217
  - the resource is also removed from the xDS client cache because there are no more watchers. See: https://github.com/grpc/grpc-go/blob/aa629e0ef3e78483883a55ea25c1da17236c97e6/xds/internal/xdsclient/authority.go#L715
- Channel `2` starts out and gets a reference to the existing xDS client (when it attempts to create a new one). It registers a watch for the same LDS resource as channel `1`.
- The watch function in the xDS client sees that there is no such LDS resource in the cache (because it was deleted as part of the unsubscription by channel `1`). So, it updates the cache and creates a placeholder for this resource. See: https://github.com/grpc/grpc-go/blob/aa629e0ef3e78483883a55ea25c1da17236c97e6/xds/internal/xdsclient/authority.go#L625.
- The actual ADS request for the subscription will be sent out asynchronously through the ADS stream implementation.
- By the time the ADS stream implementation gets around to write the LDS request on the wire (both for the unsubscription by channel `1` and the subscription by channel `2`), it sees there there is a single LDS resource to be requested, and it also sees a nonce and a version for that resource type. This is the same nonce and version that was received when the same resource was requested as part of channel 1. So, such a request is sent out, the management server does not send a response back, because it already responded to the same request name with the same version and nonce on the same ADS stream.

At this point channel `2` is stuck until the LDS resource-not-found timer fires after `15s` and from that point on RPCs on the channel start to fail.

The fundamental reason behind this race is that the resource is deleted from the xDS client cache even before it is sent out of the ADS stream. Also important to note is that some resource state is maintained in the ADS stream implementation, while some is maintained in the xDS client and these both can go out of sync.

### PR DESCRIPTION
**Pull request by easwars**
Fixes https://github.com/grpc/grpc-go/issues/8125

#### The original race in the xDS client:
- Resource watch is cancelled by the user of the xdsClient (e.g. xdsResolver) 
- xdsClient removes the resource from its cache and queues an unsubscribe request to the ADS stream.
- A watch for the same resource is registered immediately, and the xdsClient instructs the ADS stream to subscribe (as it's not in cache).
- The ADS stream sends a redundant request (same resources, version, nonce) which the management server ignores.
- The new resource watch sees a "resource-not-found" error once the watch timer fires.

#### The original fix:
Delay the resource's removal from the cache until the unsubscribe request was transmitted over the wire, a change implemented in https://github.com/grpc/grpc-go/pull/8369. However, this solution introduced new complications:
- The resource's removal from the xdsClient's cache became an asynchronous operation, occurring while the unsubscribe request was being sent.
- This asynchronous behavior meant the state maintained within the ADS stream could still diverge from the cache's state.
- A critical section was absent between the ADS stream's message transmission logic and the xdsClient's cache access, which is performed during subscription/unsubscription by its users.

#### The root cause of the previous seen races can be put down two things:
- Batching of writes for subscribe and unsubscribe calls
  - After batching, it may appear that nothing has changed in the list of subscribed resources, even though a resource was removed and added again, and therefore the management server would not send any response. It is important that the management server see the exact sequence of subscribe and unsubscribe calls.
- State maintained in the ADS stream going out of sync with the state maintained in the resource cache

#### How does this PR address the above issue?
This PR simplifies the implementation of the ADS stream by removing two pieces of functionality
- Stop batching of writes on the ADS stream
  -  If the user registers multiple watches, e.g. resource `A`, `B`, and `C`, the stream would now send three requests: `[A]`, `[A B]`, `[A B C]`.
- Queue the exact request to be sent out based on the current state
  - As part of handling a subscribe/unsubscribe request, the ADS stream implementation will queue the exact request to be sent out. When asynchronously sending the request out, it will not use the current state, but instead just write the queued request on the wire.
- Don't buffer writes when waiting for flow control
  - Flow control is already blocking reads from the stream. Blocking writes as well during this period might provide some additional flow control, but not much, and removing this logic simplifies the stream implementation quite a bit.

RELEASE NOTES:
- xdsclient: fix a race in the xdsClient that could lead to resource-not-found errors

### CODE REVIEW

**Comment by easwars** [comment]
@danielzhaotongliu

**Comment by arjan-bal** [comment]
Could you explain how the new logic prevents the following race condition that can cause a channel to briefly enter `TRANSIENT_FAILURE`?
I'm thinking of this specific scenario:

1.  Channel 0, which is watching LDS resource `L0`, is closed. The xDS client queues an unsubscribe request for `L0` to be sent to the management server.
2.  Immediately after, a new channel (Channel 1) starts and its xDS resolver registers a watch for the exact same resource, `L0`. The client now queues a new subscription request for `L0`.
3.  Before the management server processes the new subscription for `L0`, it sends a `DiscoveryResponse` based on the previous state (where the client had unsubscribed). This response therefore excludes `L0`.
4. The xDS client receives this response and notifies the active watcher for `L0` (belonging to Channel 1) that the resource is missing. This causes Channel 1 to enter `TRANSIENT_FAILURE` until the next update from the server includes `L0`.

How does this PR ensure that the watcher for Channel 1 isn't incorrectly notified of a missing resource in this situation?

**Comment by easwars** [comment]
The above condition that you mention will not lead to Channel 1 entering `TRANSIENT_FAILURE`. This case is taken care of explicitly here: https://github.com/grpc/grpc-go/blob/8110884be128afca96c21ca7ff15a490993f9a7b/internal/xds/clients/xdsclient/authority.go#L444

In fact this is case that can happen even without any of the race conditions involving the xDS client and this is also explicitly mentioned in the envoy xDS documentation here: https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#knowing-when-a-requested-resource-does-not-exist

Hope this helps.

File: internal/xds/clients/internal/buffer/unbounded.go [hunk 1]
```diff
@@ -114,3 +115,23 @@ func (b *Unbounded) Close() {
...
+// relevant, and needs to be cleared.
+func (b *Unbounded) Reset() {
+	b.mu.Lock()
+	defer b.mu.Unlock()
+
+	if b.closing {
+		return
+	}
+
+	b.backlog = nil
```
Comment (arjan-bal) [inline internal/xds/clients/internal/buffer/unbounded.go]: nit: Will setting `b.backlog = b.backlog[:0]` be better since it avoids re-allocation?

File: internal/xds/clients/xdsclient/ads_stream.go [hunk 2]
```diff
@@ -172,26 +177,22 @@ func (s *adsStreamImpl) subscribe(typ ResourceType, name string) {
...
-	s.requestCh.Put(typ)
+	s.requestCh.Put(request{typ: typ, resourceNames: resourceNames(state.subscribedResources)})
 }
 
 // Unsubscribe cancels the subscription to the given resource. It is a no-op if
 // the given resource does not exist. The watch expiry timer associated with the
 // resource is stopped if one is active. A discovery request is sent out on the
-// stream for the resource type when there is sufficient flow control quota.
+// stream for the resource type with the updated set of resource names.
 func (s *adsStreamImpl) Unsubscribe(typ ResourceType, name string) {
```
Comment (arjan-bal) [inline internal/xds/clients/xdsclient/ads_stream.go]: nit: I noticed that the `subscribe` method is unexported, while `Unsubscribe` is exported. Maybe we should unexport `Unsubscribe` too?

**Review by arjan-bal — APPROVED** [review]
LGTM

**Comment by arjan-bal** [comment]
> The above condition that you mention will not lead to Channel 1 entering `TRANSIENT_FAILURE`. This case is taken care of explicitly here:
> 
> https://github.com/grpc/grpc-go/blob/8110884be128afca96c21ca7ff15a490993f9a7b/internal/xds/clients/xdsclient/authority.go#L444
> 
> In fact this is case that can happen even without any of the race conditions involving the xDS client and this is also explicitly mentioned in the envoy xDS documentation here: https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#knowing-when-a-requested-resource-does-not-exist
> 
> Hope this helps.

I see. The difference in the scenario I asked about and the problem caused by the initial fix is the presence of the LDS resource in the cache. If L0 is present in the cache but not in the latest update from the management server, the channel is put in TF. However, if L0 is not present in the cache, we wait for the expiry timer to expire.

**Comment by arjan-bal** [comment]
Though the PR description doesn't explicitly call out how the change addresses the race condition, my understanding is that the race is caused because the writes for subscribe and unsubscribe calls are batched. After batching, it may appear that nothing has changed in the list of subscribed resources, even though a resource was removed and added again. By removing batching of writes, the management server will see the unsubscription and re-subscription of the resource and send the necessary update.

File: internal/xds/clients/internal/buffer/unbounded.go (hunk 1 above)
Comment (easwars) [reply internal/xds/clients/internal/buffer/unbounded.go]: Done. Thanks.

File: internal/xds/clients/xdsclient/ads_stream.go (hunk 2 above)
Comment (easwars) [reply internal/xds/clients/xdsclient/ads_stream.go]: Done.

**Comment by easwars** [comment]
> If L0 is present in the cache but not in the latest update from the management server, the channel is put in TF. However, if L0 is not present in the cache, we wait for the expiry timer to expire.

That is true.

And the first part about the resource being in the cache, but not in a response from the management server resulting in the channel moving to TF applies only to LDS and CDS. For RDS and EDS, if a similar scenario happens, we would simply continue using the resource in the cache.

**Comment by easwars** [comment]
> Though the PR description doesn't explicitly call out how the change addresses the race condition, my understanding is that the race is caused because the writes for subscribe and unsubscribe calls are batched. After batching, it may appear that nothing has changed in the list of subscribed resources, even though a resource was removed and added again. By removing batching of writes, the management server will see the unsubscription and re-subscription of the resource and send the necessary update.

Your understanding is correct and I've clarified the exact underlying issue causing the race and how the change addresses them in the PR description. Thanks.

File: internal/xds/clients/internal/buffer/unbounded.go [hunk 3]
```diff
@@ -114,3 +115,23 @@ func (b *Unbounded) Close() {
 		close(b.c)
 	}
 }
+
+// Reset clears all buffered data in the unbounded buffer. This does not close
+// the buffer, and new data may be Put() into it after a call to this method.
+//
+// It's expected to be used in scenarios where the buffered data is no longer
+// relevant, and needs to be cleared.
+func (b *Unbounded) Reset() {
```
Comment (dfawley) [inline internal/xds/clients/internal/buffer/unbounded.go]: This is inherently racy with other calls to `Put()` (and `Load()`, of course).  I hope we are using it correctly! :)  And if we have an external lock that is used for all things that call Put and Reset, I wonder if a different data structure might be more efficient?

File: internal/xds/clients/xdsclient/ads_stream.go [hunk 4]
```diff
@@ -311,22 +310,16 @@ func (s *adsStreamImpl) sendNew(stream clients.Stream, typ ResourceType) error {
...
-	state := s.resourceTypeState[typ]
-	bufferRequest := func() {
-		select {
-		case state.bufferedRequests <- struct{}{}:
-		default:
-		}
+	state, ok := s.resourceTypeState[typ]
+	if !ok {
+		// State is created when the first subscription for this type is made.
+		panic(fmt.Sprintf("no state exists for resource type %v", typ))
```
Comment (dfawley) [inline internal/xds/clients/xdsclient/ads_stream.go]: Do we want a production panic?  Or should this be `log.Errorf()` (which fails all tests) and a `return <some error>` (or `nil` since the stream is still usable, depending on what it means to return an error?)?  The latter feels safer.

File: internal/xds/clients/xdsclient/ads_stream.go [hunk 5]
```diff
@@ -337,6 +330,10 @@ func (s *adsStreamImpl) sendExisting(stream clients.Stream) error {
 	s.mu.Lock()
 	defer s.mu.Unlock()
 
+	// Clear any queued requests. Previously subscribed to resources will be
+	// resent below.
+	s.requestCh.Reset()
```
Comment (dfawley) [inline internal/xds/clients/xdsclient/ads_stream.go]: Do we need to mandate that `s.mu` is held when calling `Put` or `Reset`?

Maybe we should wrap accesses to it somehow to guarantee that?

File: internal/xds/clients/xdsclient/ads_stream.go (hunk 4 above)
Comment (easwars) [reply internal/xds/clients/xdsclient/ads_stream.go]: Interestingly, we were not even checking if the value existed in the map before. We were blindly using it. So, the potential for a real panic seems almost non-existent. Literally, the ADS stream implementation adds the entry to the map when it first sees a subscribe request for this resource type and then queues the request. So, we are definitely going to have the entry in the map. I'll remove the `panic`, so it doesn't cause confusion to the reader.

Comment (easwars) [reply internal/xds/clients/xdsclient/ads_stream.go]: And we never remove entries from this map. So, we are safe.

File: internal/xds/clients/internal/buffer/unbounded.go (hunk 3 above)
Comment (arjan-bal) [reply internal/xds/clients/internal/buffer/unbounded.go]: > This is inherently racy with other calls to Put() (and Load(), of course). I hope we are using it correctly!

I had the same question. My understanding is that Reset acts as an optimization to avoid redundant requests, but it isn't required for correctness.

Even so, you're right about the potential for races. I think adding a godoc comment to warn about this is a good idea.

**Comment by dfawley** [comment]
(Whoops, forgot to reassign after reviewing.)

File: internal/xds/clients/internal/buffer/unbounded.go (hunk 3 above)
Comment (easwars) [reply internal/xds/clients/internal/buffer/unbounded.go]: I've ended up using a list type from the stdlib for the implementation of the request queue, which will now be guarded by the `adsStreamImpl`s mutex.

While this eliminates the possibility of the race (which existed in the previous approach), the use of a condition variable to know when the request queue is empty (and blocking until it becomes non-empty), and the fact that `sync.Cond` doesn't allow blocking in a `select` with other ways of getting unblocked, the code has become a bit uglier and more complicated in my opinion.

Another option would be to create a new type like `SynchronizedUnboundedBuffer` that takes a `sync.Locker` and guards access to all of its methods with given lock. But even in that case, since `Get` returns a channel, it is not a viable option I believe.

Another reason I went with the stdlib list instead of trying to synchronize access to the unbounded buffer (while also supporting a `Reset` method) was that the unbounded buffer is currently thread-safe and adding a new method which moves the responsibility of synchronization to the caller didn't seem very appealing.

Would like to hear your thoughts on these.

File: internal/xds/clients/xdsclient/ads_stream.go (hunk 5 above)
Comment (easwars) [reply internal/xds/clients/xdsclient/ads_stream.go]: Replied on the other comment.

**Review by easwars — COMMENTED** [review]
Apologies for the rebase and the force push. I had to do that since I had to import the changes here to google3 to ensure that the new changes don't introduce any flakiness and since a whole bunch of changes have gone into the repo since i first sent this PR out, it was untenable to do that.

File: internal/xds/clients/internal/buffer/unbounded.go (hunk 3 above)
Comment (arjan-bal) [reply internal/xds/clients/internal/buffer/unbounded.go]: I thought of a similar approach that uses a channel instead of a `sync.Cond`.

Add the following fields in `adsStreamImpl`:

1.  `notifySender: make(chan struct{}, 1)`. This channel will be used by `subscribe` and `unsubscribe` to inform the `send` goroutine that there "may" be buffered requests in the queue.
2.  `pendingRequests: []request{}`. This will be protected by `mu`.

`subscribe()` and `unsubscribe` will do the following:

1.  Acquire the `mu` lock.
2.  Append to the `pendingRequests` slice.
3.  Release the `mu` lock.
4.  Send to the `notifySender` channel (with a `default` case to avoid blocking).

The `send` goroutine will do the following:

1.  Run a `select` statement waiting on `s.streamCh` and `s.notifySender`.
    1.  If the `s.streamCh` case is selected: Call `sendExisting`, which will acquire the `mu` lock and swap out `pendingRequests` with an empty slice.
    2.  If the `s.notifySender` case is selected: Acquire the `mu` lock, swap out `pendingRequests` keeping the original slice, release the `mu` lock, and then call `sendNew` for each request in the original slice.

Notice that sending on the `notifySender` channel is done after appending to the `pendingRequests` slice. This ensures that the `send` goroutine doesn't miss any notifications. This is because if there's an object in the `notifySender` channel, it's guaranteed that at some point in the future, the `send` goroutine will read from the `notifySender` channel, acquire `mu`, and see the new elements in the `pendingRequests` slice.

Do you think this makes the implementation simpler, and still correct?

Comment (easwars) [reply internal/xds/clients/internal/buffer/unbounded.go]: Thanks for the idea, this is great. This will definitely work and will make things simpler. The godoc on the sync package *does* say that for most simple cases, you can get away with a channel instead of a condition variable. And when I was trying to make things work with a channel instead of a condition variable, I had already changed the structure of the sending goroutine quite a bit (compared to its earlier version) and I couldn't find a way to use the channel without holding the lock.

File: internal/xds/clients/internal/buffer/unbounded.go [hunk 6]
```diff
@@ -114,3 +115,23 @@ func (b *Unbounded) Close() {
...
+	b.mu.Lock()
+	defer b.mu.Unlock()
+
+	if b.closing {
```
Comment (danielzhaotongliu) [inline internal/xds/clients/internal/buffer/unbounded.go]: would we also need to consider (return early) for the case when `b.closed` is true? 
Although this unbound package and method is exported, but it is internal, so I think there would be little room for misuse.

File: internal/xds/clients/xdsclient/ads_stream.go [hunk 7]
```diff
@@ -280,53 +288,44 @@ func (s *adsStreamImpl) send(ctx context.Context) {
...
+			//   and in this case, we rely on the `sendExisting` to send out
+			//   requests for all subscriptions when the stream is recreated.
+			s.mu.Lock()
+			if err := s.sendNewLocked(stream, s.pendingRequests); err != nil {
 				stream = nil
-				continue
 			}
+			s.pendingRequests = nil
+			s.mu.Unlock()
 		}
```
Comment (danielzhaotongliu) [inline internal/xds/clients/xdsclient/ads_stream.go:310]: for my education, there is no need for a `default` condition here?

File: internal/xds/clients/internal/buffer/unbounded.go (hunk 6 above)
Comment (easwars) [reply internal/xds/clients/internal/buffer/unbounded.go]: I'm getting rid of this method since it is not needed anymore.

File: internal/xds/clients/xdsclient/ads_stream.go (hunk 7 above)
Comment (easwars) [reply internal/xds/clients/xdsclient/ads_stream.go:310]: The `default` condition works very differently in a `select` statement compared to how it works in a `switch` statement. If we had a `default` case here, we would end up busy looping in the `for` loop because for most of the time the other reads from the three channels are going to be blocked.

**Review by arjan-bal — APPROVED** [review]
LGTM!
