### PR TITLE
transport: Fix deadlock in transport caused by GOAWAY race with new stream creation

### LINKED ISSUE #5644: Deadlock on grpc transport
### What version of gRPC are you using?
1.49

### What version of Go are you using (`go version`)?
1.19

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
I do not have a reproducible scenario.
Since we switched to grpc-go 1.49 in our application, we see sometimes that our application is hanging on grpc requests. 
From the extracted stack traces, I could clearly see that there is a deadlock in transport caused by the recent PR https://github.com/grpc/grpc-go/pull/5494
In this PR this is mentioned on the http2_client mutex:
```
	// Do not access controlBuf with mu held.
	mu            sync.Mutex // guard the following variables
```
But that is exactly what is happening very infrequently in our case.
Cause is https://github.com/grpc/grpc-go/blob/a094a1095c07d37362f7ab37b92a6aa46c2d8b07/internal/transport/http2_client.go#L1237
This closeStream request is done while holding the http2_client mutex.
And the implementation of closeStream is calling controlBuf at line: 
https://github.com/grpc/grpc-go/blob/a094a1095c07d37362f7ab37b92a6aa46c2d8b07/internal/transport/http2_client.go#L870
This violates the assumption of mutex.  In this case the http2_client mutex is acquired while trying to acquire the controlbuf mutex.

And in another goroutine in parallel, the controlbuf mutex is acquired while trying to acquire the http2_client mutex.
Reason is the added mutex lock at line: https://github.com/grpc/grpc-go/blob/a094a1095c07d37362f7ab37b92a6aa46c2d8b07/internal/transport/http2_client.go#L723

Relevant stack traces:
```
goroutine 4163 [semacquire, 437 minutes]:
runtime.gopark(0xc000a5ab58?, 0x470de0?, 0x40?, 0xcb?, 0xc000a5aa58?)
   /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000a5aa50 sp=0xc000a5aa30 pc=0x4389f6
runtime.goparkunlock(...)
   /usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc000b7d3c4, 0xd8?, 0x3, 0x1)
   /usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc000a5aab8 sp=0xc000a5aa50 pc=0x448efe
sync.runtime_SemacquireMutex(0x20?, 0xde?, 0x0?)
   /usr/local/go/src/runtime/sema.go:77 +0x25 fp=0xc000a5aae8 sp=0xc000a5aab8 pc=0x462ea5
sync.(*Mutex).lockSlow(0xc000b7d3c0)
   /usr/local/go/src/sync/mutex.go:171 +0x165 fp=0xc000a5ab38 sp=0xc000a5aae8 pc=0x4709c5
sync.(*Mutex).Lock(...)
   /usr/local/go/src/sync/mutex.go:90
google.golang.org/grpc/internal/transport.(*controlBuffer).executeAndPut(0xc000b7d3b0, 0xc000a5aba8?, {0x10e38c0, 0xc00076c3a8})
   /workspace/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:331 +0x52 fp=0xc000a5ab80 sp=0xc000a5ab38 pc=0x8e6db2
google.golang.org/grpc/internal/transport.(*http2Client).closeStream(0xc00038e780, 0xc000e7e000, {0x10e3840?, 0xc0000120f0?}, 0x0, 0x0, 0x8000?, 0xc000d537a0?, 0x0)
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:870 +0x1fc fp=0xc000a5abc8 sp=0xc000a5ab80 pc=0x8f629c
google.golang.org/grpc/internal/transport.(*http2Client).handleGoAway(0xc00038e780, 0xc000d0f530)
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1237 +0x53d fp=0xc000a5ad90 sp=0xc000a5abc8 pc=0x8f883d
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00038e780)
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1546 +0x9cd fp=0xc000a5afc8 sp=0xc000a5ad90 pc=0x8fbbed
google.golang.org/grpc/internal/transport.newHTTP2Client.func7()
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:367 +0x26 fp=0xc000a5afe0 sp=0xc000a5afc8 pc=0x8f14e6
runtime.goexit()
   /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000a5afe8 sp=0xc000a5afe0 pc=0x466aa1
created by google.golang.org/grpc/internal/transport.newHTTP2Client
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:367 +0x18ff

goroutine 4934 [semacquire, 437 minutes]:
runtime.gopark(0xc000f89470?, 0xc000a986c0?, 0xc0?, 0x0?, 0xc00004517f?)
   /usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc0006964a0 sp=0xc000696480 pc=0x4389f6
runtime.goparkunlock(...)
   /usr/local/go/src/runtime/proc.go:369
runtime.semacquire1(0xc00038e8e4, 0x28?, 0x3, 0x1)
   /usr/local/go/src/runtime/sema.go:150 +0x1fe fp=0xc000696508 sp=0xc0006964a0 pc=0x448efe
sync.runtime_SemacquireMutex(0xc0005e6390?, 0x0?, 0x203000?)
   /usr/local/go/src/runtime/sema.go:77 +0x25 fp=0xc000696538 sp=0xc000696508 pc=0x462ea5
sync.(*Mutex).lockSlow(0xc00038e8e0)
   /usr/local/go/src/sync/mutex.go:171 +0x165 fp=0xc000696588 sp=0xc000696538 pc=0x4709c5
sync.(*Mutex).Lock(...)
   /usr/local/go/src/sync/mutex.go:90
google.golang.org/grpc/internal/transport.(*http2Client).NewStream.func3({0xe0a980?, 0xc0006aec30?})
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:723 +0x12a fp=0xc0006965d0 sp=0xc000696588 pc=0x8f5bea
google.golang.org/grpc/internal/transport.(*http2Client).NewStream.func5({0xe0a980, 0xc0006aec30})
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:755 +0x4c fp=0xc0006965f8 sp=0xc0006965d0 pc=0x8f58cc
google.golang.org/grpc/internal/transport.(*controlBuffer).executeAndPut(0xc000b7d3b0, 0x10ec540?, {0x10e3940, 0xc0006aec30})
   /workspace/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:337 +0xc3 fp=0xc000696640 sp=0xc0006965f8 pc=0x8e6e23
google.golang.org/grpc/internal/transport.(*http2Client).NewStream(0xc00038e780, {0x10ec540, 0xc000f89350}, 0xc0010023c0)
   /workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:754 +0x438 fp=0xc000696828 sp=0xc000696640 pc=0x8f51f8
google.golang.org/grpc.(*csAttempt).newStream(0xc0001a4c00)
   /workspace/vendor/google.golang.org/grpc/stream.go:441 +0x4a fp=0xc000696860 sp=0xc000696828 pc=0x983aca
google.golang.org/grpc.newClientStreamWithParams.func2(0xc0001a4c00)
   /workspace/vendor/google.golang.org/grpc/stream.go:312 +0x3a fp=0xc000696880 sp=0xc000696860 pc=0x982f9a
google.golang.org/grpc.(*clientStream).withRetry(0xc0005685a0, 0xc0007bf370, 0xc000696a08)
   /workspace/vendor/google.golang.org/grpc/stream.go:715 +0x144 fp=0xc0006968f0 sp=0xc000696880 pc=0x984a84
google.golang.org/grpc.newClientStreamWithParams({0x10ec540, 0xc000f89260}, 0x17b7ea0, 0xc000443500, {0xfa02df, 0x31}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
   /workspace/vendor/google.golang.org/grpc/stream.go:321 +0x9ac fp=0xc000696a38 sp=0xc0006968f0 pc=0x9829ac
google.golang.org/grpc.newClientStream.func2({0x10ec540?, 0xc000f89260?}, 0xc000f89260?)
   /workspace/vendor/google.golang.org/grpc/stream.go:192 +0x9f fp=0xc000696ac8 sp=0xc000696a38 pc=0x981f7f
google.golang.org/grpc.newClientStream({0x10ec540, 0xc000f89260}, 0x17b7ea0, 0xc000443500, {0xfa02df, 0x31}, {0x0, 0x0, 0x0})
   /workspace/vendor/google.golang.org/grpc/stream.go:220 +0x4c2 fp=0xc000696ba0 sp=0xc000696ac8 pc=0x981b62
google.golang.org/grpc.invoke({0x10ec540?, 0xc000f89260?}, {0xfa02df?, 0x4?}, {0xf0b1a0, 0xc0006aea50}, {0xf41840, 0xc000c407e0}, 0x0?, {0x0, ...})
   /workspace/vendor/google.golang.org/grpc/call.go:66 +0x7d fp=0xc000696c08 sp=0xc000696ba0 pc=0x96473d
```

### What did you expect to see?
no deadlock

### What did you see instead?
deadlock

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #5644.

RELEASE NOTES:
* transport: Fix deadlock in transport caused by GOAWAY race with new stream creation (add add'l comment about how it only occurs with a non-well-behaved HTTP/2 server implementation)

### CODE REVIEW

File: internal/transport/http2_client.go [hunk 1]
```diff
@@ -1232,16 +1232,23 @@ func (t *http2Client) handleGoAway(f *http2.GoAwayFrame) {
 	if upperLimit == 0 { // This is the first GoAway Frame.
 		upperLimit = math.MaxUint32 // Kill all streams after the GoAway ID.
 	}
+
+	activeStreams := make(map[uint32]*Stream)
 	for streamID, stream := range t.activeStreams {
+		activeStreams[streamID] = stream
+	}
```
Comment (dfawley) [inline internal/transport/http2_client.go:1239]: Use a slice; only add streams to be closed to it.  Early exit if `t.activeStreams` is zero?

```go
t.prevGoAwayID = id

if len(t.activeStreams) == 0 {
	t.mu.Unlock()
	t.Close(...)
	return
}

streamsToClose := make([]*Stream, 0, len(t.activeStreams))
for streamID, stream := range t.activeStreams {
	if streamID > id && streamID <= upperLimit {
		streamsToClose = append(streamsToClose, stream)
	}
}
t.mu.Unlock()
for _, stream := range(streamsToClose) {
	atomic.StoreUint32()
	t.closeStream()
}
```

Comment (zasweq) [reply internal/transport/http2_client.go:1239]: Actually, sorry, I tried this way and for some reason it still induced deadlock. I'm going to keep it as is. I couldn't figure out why your way wouldn't work.

**Review by zasweq — COMMENTED** [review]
Thanks for the comment. Sorry I couldn't get your solution working. The e2e test with the new helper class that actually induced it took everything out of me.

File: internal/transport/http2_client.go (hunk 1 above)
Comment (zasweq) [reply internal/transport/http2_client.go:1239]: Done. Verified on my e2e_test I checked in and also on the transport test which I didn't check in since it wrote directly to framer.

File: internal/transport/http2_client.go [hunk 2]
```diff
@@ -1232,18 +1232,27 @@ func (t *http2Client) handleGoAway(f *http2.GoAwayFrame) {
...
 	}
+
+	t.prevGoAwayID = id
+	if len(t.activeStreams) == 0 {
+		t.mu.Unlock()
+		t.Close(connectionErrorf(true, nil, "received goaway and there are no active streams"))
+		return
+	}
+
+	streamsToClose := make([]*Stream, 0)
```
Comment (dfawley) [inline internal/transport/http2_client.go:1243]: `var streamsToClose []*Stream`

Or delete the `,0` but `make` is unnecessary for a slice either way if you aren't allocating anything.

File: internal/transport/http2_client.go [hunk 3]
```diff
@@ -1232,18 +1232,27 @@ func (t *http2Client) handleGoAway(f *http2.GoAwayFrame) {
...
+				streamsToClose = append(streamsToClose, stream)
+			}
 		}
 	}
-	t.prevGoAwayID = id
-	active := len(t.activeStreams)
 	t.mu.Unlock()
-	if active == 0 {
-		t.Close(connectionErrorf(true, nil, "received goaway and there are no active streams"))
+	for _, stream := range streamsToClose {
```
Comment (dfawley) [inline internal/transport/http2_client.go:1254]: Please add a comment about why this is called outside `t.mu`.

File: test/clienttester.go [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+	t    *testing.T
+	conn net.Conn
+	fr   *http2.Framer
+}
+
+// greet() performs the necessary steps for http2 connection establishment on
+// the server side.
+func (ct *clientTester) greet() {
+	ct.wantClientPreface()
+	ct.wantSettingsFrame()
```
Comment (dfawley) [inline test/clienttester.go:51]: What if the client doesn't send a settings frame?  I don't think this is a requirement, but it is something our client might always do.  Can this be handled as optional in the loop below?

File: test/end2end_test.go [hunk 5]
```diff
@@ -8130,3 +8129,62 @@ func (s) TestRecvWhileReturningStatus(t *testing.T) {
...
+	}
+
+	ctCh := testutils.NewChannel()
+	go func() {
+		conn, err := lis.Accept()
+		if err != nil {
+			t.Errorf("error in lis.Accept(): %v", err)
+		}
+		ct := newClientTester(t, conn)
+		ct.greet()
```
Comment (dfawley) [inline test/end2end_test.go:8150]: Fold this into `new`?

File: test/end2end_test.go [hunk 6]
```diff
@@ -8130,3 +8129,62 @@ func (s) TestRecvWhileReturningStatus(t *testing.T) {
...
+	defer cancel()
+
+	val, err := ctCh.Receive(ctx)
+	if err != nil {
+		t.Fatalf("timeout waiting for client transport (should be given after http2 creation)")
+	}
+	ct, ok := val.(*clientTester)
+	if !ok {
+		t.Fatalf("value received not a clientTester")
+	}
```
Comment (dfawley) [inline test/end2end_test.go:8170]: Just let it panic and keep the code simpler.  This is just a test and the panic is as informative as this error, and it's a coding error if it happens.  `ct := val.(*clientTester)`

File: test/end2end_test.go [hunk 7]
```diff
@@ -8130,3 +8129,62 @@ func (s) TestRecvWhileReturningStatus(t *testing.T) {
...
+
+	tc := testpb.NewTestServiceClient(cc)
+	someStreamsCreated := grpcsync.NewEvent()
+	goAwayWritten := grpcsync.NewEvent()
+	go func() {
+		for i := 0; i < 20; i++ {
+			if i == 10 {
+				<-goAwayWritten.Done()
+			}
```
Comment (dfawley) [inline test/end2end_test.go:8179]: What does this do that is different from blocking on `<-goAwayWritten.Done()` immediately after `someStreamsCreate.Fire()` instead?

**Review by dfawley — COMMENTED** [review]
LGTM, thanks!  Just a few really small things.

File: internal/transport/http2_client.go (hunk 2 above)
Comment (zasweq) [reply internal/transport/http2_client.go:1243]: Switched. You initially suggested make for the capacity length. Why was that?

File: test/end2end_test.go (hunk 6 above)
Comment (zasweq) [reply test/end2end_test.go:8170]: Done.

File: test/end2end_test.go (hunk 7 above)
Comment (zasweq) [reply test/end2end_test.go:8179]: I honestly was just playing around with this until it induced deadlock, it was hard to induce on master. This allows it to induce it because the only way to induce it is to concurrently create a stream (controlBuf.mu then transport.mu), where the closeStream was (transport.mu then controlBuf.mu). If I block where you suggested, there are no concurrent streams trying to be created while the goAway is being sent from server.

File: test/end2end_test.go (hunk 5 above)
Comment (zasweq) [reply test/end2end_test.go:8150]: Sure, but I'm doing this very begrudingly. ServerTester is done this way, and I feel like it' made a lot clearer to the user of the clientTester struct that it gets to the point where the client is happy with it's HTTP2 connection establisment.

File: test/clienttester.go (hunk 4 above)
Comment (zasweq) [reply test/clienttester.go:51]: "That is, the connection preface starts with the string PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n). This sequence MUST be followed by a [SETTINGS](https://httpwg.org/specs/rfc7540.html#SETTINGS) frame ([Section 6.5](https://httpwg.org/specs/rfc7540.html#SETTINGS)), which MAY be empty." - this is what the HTTP/2 spec test says? This is also specifically testing the gRPC specific http2_client, (this is a testing util which lives in our own library). The HTTP2 client sends a settings frame in the constructor: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_client.go#L397.

File: internal/transport/http2_client.go (hunk 3 above)
Comment (zasweq) [reply internal/transport/http2_client.go:1254]: Done.

**Review by zasweq — COMMENTED** [review]
Thanks for the comments :D!

File: internal/transport/http2_client.go (hunk 2 above)
Comment (dfawley) [reply internal/transport/http2_client.go:1243]: If you specify the capacity then it won't need to do reallocations as you add to it.  In this case, since we don't have any idea how many active streams are before/after the ID (and it isn't worth computing it first) then this should be fine.  It will need reallocations (Go doubles the slice capacity as you add so it's O(logN)), but this is a rare case and not worth optimizing.

File: test/clienttester.go (hunk 4 above)
Comment (dfawley) [reply test/clienttester.go:52]: Nevermind! :D

**Review by dfawley — APPROVED** [review]

**Comment by hexfusion** [comment]
@zasweq can we get this cherry-picked into 1.50.x ? Seems to be missing.

**Comment by zasweq** [comment]
I clearly see this in the 1.50.x commit history: https://github.com/grpc/grpc-go/commits/v1.50.x. Scroll to 29 days ago.
