### PR TITLE
otel: Segregate client and server RPCInfo used for metrics and traces

### LINKED ISSUE #9053: grpc Server Metrics rpcInfo gets overwritten by grpc client invocations
### What version of gRPC are you using?
google.golang.org/grpc v1.80.0 

### What version of Go are you using (`go version`)?

go1.25.0 linux/amd64

### What operating system (Linux, Windows, …) and version?
Linux Debian

### What did you do?

I have a server that makes a grpc call as part of serving a request. The call goes to a completely different server. However, I propagate the incoming server context to better propagate deadlines and other metadata. This is however resulting in the server grpc metrics getting modified -- instad of reporting the server method, the metrics are attributed to the client method instead.

I have this demo to illustrate the issue:
```golang
func TestOpenTelemetrySharedContextBug(t *testing.T) {
	ctx := context.Background()

	// 1. Set up an OpenTelemetry Manual Reader to inspect the recorded metrics in-memory.
	reader := metric.NewManualReader()
	meterProvider := metric.NewMeterProvider(metric.WithReader(reader))

	otelOptions := opentelemetry.Options{
		MetricsOptions: opentelemetry.MetricsOptions{
			MeterProvider: meterProvider,
		},
	}

	// 2. Define a minimal gRPC Service without requiring protoc generation.
	dummyServiceDesc := grpc.ServiceDesc{
		ServiceName: "test.DummyService",
		HandlerType: (*any)(nil),
		Methods: []grpc.MethodDesc{
			{
				MethodName: "ServerMethod",
				Handler: func(srv any, incomingCtx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
					// Inside the server method, construct an outgoing client connection.
					cc, err := grpc.NewClient(
						"passthrough:///localhost:12345",
						grpc.WithTransportCredentials(insecure.NewCredentials()),
						opentelemetry.DialOption(otelOptions),
					)
					if err != nil {
						return nil, err
					}
					defer cc.Close()

					// BUG TRIGGER: Make the outgoing client RPC using the incoming server context.
					_ = cc.Invoke(incomingCtx, "/test.DummyService/ClientMethod", nil, nil)

					return nil, nil
				},
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "dummy.proto",
	}

	// 3. Start the gRPC Server with the ServerOption configured.
	lis := bufconn.Listen(1024 * 1024)
	server := grpc.NewServer(opentelemetry.ServerOption(otelOptions))
	server.RegisterService(&dummyServiceDesc, nil)
	go server.Serve(lis)
	defer server.Stop()

	// 4. Trigger the server method via an external client.
	dialer := func(context.Context, string) (net.Conn, error) {
		return lis.Dial()
	}
	cc, err := grpc.NewClient(
		"passthrough:///bufnet",
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithContextDialer(dialer),
	)
	if err != nil {
		t.Fatalf("Failed to dial server: %v", err)
	}
	defer cc.Close()

	_ = cc.Invoke(ctx, "/test.DummyService/ServerMethod", nil, nil)

	// 5. Collect and inspect the OpenTelemetry metrics.
	var rm metricdata.ResourceMetrics
	if err := reader.Collect(ctx, &rm); err != nil {
		t.Fatalf("Failed to collect metrics: %v", err)
	}

	var found bool
	for _, sm := range rm.ScopeMetrics {
		for _, m := range sm.Metrics {
			if m.Name == "grpc.server.call.duration" {
				data, ok := m.Data.(metricdata.Histogram[float64])
				if !ok {
					continue
				}
				for _, dp := range data.DataPoints {
					found = true
					gotAttrs := dp.Attributes.ToSlice()
					fmt.Printf("Recorded attributes for grpc.server.call.duration: %v\n", gotAttrs)

					var methodVal string
					for _, kv := range gotAttrs {
						if string(kv.Key) == "grpc.method" {
							methodVal = kv.Value.AsString()
						}
					}
					if methodVal != "test.DummyService/ClientMethod" {
						t.Errorf("Expected bug to mutate method to test.DummyService/ClientMethod, got %q", methodVal)
					}
				}
			}
		}
	}

	if !found {
		t.Fatalf("Metric grpc.server.call.duration not found in recorded metrics")
	}
}
```

### What did you expect to see?

I expected to see the grpc.server.call.duration recording with grpc.method test.DummyService/ServerMethod.

I don't want to be forced to create a child context for every single RPC call if possible.

### What did you see instead?

Metric gets recorded with the ClientMethod instead.

```
Recorded attributes for grpc.server.call.duration: [{grpc.method {4 0 test.DummyService/ClientMethod <nil>}} {grpc.status {4 0 OK <nil>}}]
```

From what I can tell, this is because both the server and client interceptors use the same contextKey so the outbound client call overwrites `aiInfo.method`

### PR DESCRIPTION
**Pull request by mbissa**
Fixes #9053 
Client and Server metrics and traces handling code during RPC was using the same RPCInfo. This lead to overwriting of context when an application was acting as server and then initiating other grpc call as a client. This PR segregates the rpcInfoKey context key into clientRPCInfoKey and serverRPCInfoKey so that it is not reused/overwritten between server and client code.

RELEASE NOTES:
* otel: Segregate client and server RPCInfo used for metrics and traces.

### CODE REVIEW

File: stats/opentelemetry/client_metrics.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func (h *clientMetricsHandler) initializeMetrics() {
 // or creates and attaches a new one.
 func getOrCreateCallInfo(ctx context.Context, cc *grpc.ClientConn, method string, opts ...grpc.CallOption) (context.Context, *callInfo) {
 	ci := getCallInfo(ctx)
-	if ci == nil {
+	if ci == nil || ci.target != cc.CanonicalTarget() {
 		ci = &callInfo{
 			target: cc.CanonicalTarget(),
 			method: determineMethod(method, opts...),
```
[the remark this answers is not in the document]
Comment (mbissa) [reply stats/opentelemetry/client_metrics.go]: These checks are not needed as the context ideally for different targets used by the client should be different. This does not fail when tested without this check.

**Review by arjan-bal — COMMENTED** [review]
I noticed you went with the first approach using separate client and server keys. Just wanted to quickly circle back to the second option: updating the logic from `getOrCreateRPCAttemptInfo` to `createRPCAttemptInfo`. 

Did you run into any specific issues or blockers when looking into that second approach? I just want to make sure we've fully explored or ruled out that path since it avoids relying on the context chain restrictions.

**Comment by arjan-bal** [comment]
Please update the release notes to describe user visible behaviour, omitting the internal implementation. For e.g: `Fix bug causing ....`.

**Comment by mbissa** [comment]
> I noticed you went with the first approach using separate client and server keys. Just wanted to quickly circle back to the second option: updating the logic from `getOrCreateRPCAttemptInfo` to `createRPCAttemptInfo`.
> 
> Did you run into any specific issues or blockers when looking into that second approach? I just want to make sure we've fully explored or ruled out that path since it avoids relying on the context chain restrictions.

The general principle here is that we need segregated rpcInfo on opposite sides of an RPC (Server vs. Client), but we must allow sibling stats handlers (like metrics and tracing) on the same side to share that state.

Furthermore, in cases of relay scenarios, we need both states to coexist in the context without risking one corrupting or shadowing the other when we have these RPCs running in parallel.

Using segregated context keys intuitively solves both requirements. Also in the discussion with leads, the inclination was towards this approach, as it aligns much better with our existing patterns for handling metadata.

File: stats/opentelemetry/opentelemetry.go [hunk 2]
```diff
@@ -200,19 +200,49 @@ type rpcInfo struct {
...
+func setClientRPCInfo(ctx context.Context, ri *rpcInfo) context.Context {
+	return context.WithValue(ctx, clientRPCInfoKey{}, ri)
 }
 
-// getRPCInfo returns the rpcInfo stored in the context, or nil
+// getClientRPCInfo returns the rpcInfo stored in the context for client, or nil
 // if there isn't one.
-func getRPCInfo(ctx context.Context) *rpcInfo {
-	ri, _ := ctx.Value(rpcInfoKey{}).(*rpcInfo)
+func getClientRPCInfo(ctx context.Context) *rpcInfo {
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: style: Please omit the `get` prefix. See go/go-style/decisions#getters

File: stats/opentelemetry/opentelemetry.go [hunk 3]
```diff
@@ -181,16 +181,16 @@ type callInfo struct {
 	nameResolutionEventAdded atomic.Bool
 }
 
-type callInfoKey struct{}
+type clientCallInfoKey struct{}
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: I don't think we need the `client` prefix here since calls are only on the client side.

File: stats/opentelemetry/opentelemetry.go [hunk 4]
```diff
@@ -181,16 +181,16 @@ type callInfo struct {
...
 
 func setCallInfo(ctx context.Context, ci *callInfo) context.Context {
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: There's only one caller for this function. Can you inline this function? Since that caller requires a `ClientConn` parameter, the compiler would enforce that only client interceptors can set the call info.

File: stats/opentelemetry/opentelemetry.go [hunk 5]
```diff
@@ -200,19 +200,49 @@ type rpcInfo struct {
...
 
-type rpcInfoKey struct{}
+type clientRPCInfoKey struct{}
+type serverRPCInfoKey struct{}
 
-func setRPCInfo(ctx context.Context, ri *rpcInfo) context.Context {
-	return context.WithValue(ctx, rpcInfoKey{}, ri)
+func setClientRPCInfo(ctx context.Context, ri *rpcInfo) context.Context {
+	return context.WithValue(ctx, clientRPCInfoKey{}, ri)
 }
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: Since there's only one caller and the function is a single line, can you please inline it? Please also inline the server version of this function.

File: stats/opentelemetry/opentelemetry.go [hunk 6]
```diff
@@ -200,19 +200,49 @@ type rpcInfo struct {
...
+func getOrCreateClientRPCAttemptInfo(ctx context.Context) (context.Context, *attemptInfo) {
+	ri := getClientRPCInfo(ctx)
+	if ri != nil {
+		return ctx, ri.ai
+	}
+	ri = &rpcInfo{ai: &attemptInfo{}}
+	return setClientRPCInfo(ctx, ri), ri.ai
+}
+
+func getOrCreateServerRPCAttemptInfo(ctx context.Context) (context.Context, *attemptInfo) {
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: Since all the other `get` and `set` functions are working on `rpcInfo`, do you think it makes sense to have these `getOrCreate` APIs also return `rpcInfo`? The caller can access the `attemptInfo` field later.

File: stats/opentelemetry/opentelemetry.go [hunk 7]
```diff
@@ -200,19 +200,49 @@ type rpcInfo struct {
...
+}
+
+// getServerRPCInfo returns the rpcInfo stored in the context for server, or nil
+// if there isn't one.
+func getServerRPCInfo(ctx context.Context) *rpcInfo {
+	ri, _ := ctx.Value(serverRPCInfoKey{}).(*rpcInfo)
+	return ri
+}
+
+func getOrCreateClientRPCAttemptInfo(ctx context.Context) (context.Context, *attemptInfo) {
```
Comment (arjan-bal) [inline stats/opentelemetry/opentelemetry.go]: Can we shorten the name without loss in meaning? E.g. `ensureClientAttemptInfo`.

File: stats/opentelemetry/e2e_test.go [hunk 8]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+	if _, err := ssB.Client.UnaryCall(ctx, &testpb.SimpleRequest{}); err != nil {
+		t.Fatalf("Unexpected UnaryCall error: %v", err)
+	}
+
+	// Verify Server Metric Identity is retained
+	pollForMetricWithMethod(ctx, t, readerB, "grpc.server.call.started", "grpc.testing.TestService/UnaryCall")
+
+	// Verify Client Metric Identity correctly resolved to "other" (Proves
+	// collision is fixed)
+	pollForMetricWithMethod(ctx, t, readerB, "grpc.client.attempt.started", "other")
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Do we need to poll? All other tests are calling `reader.Collect()` and verifying the metrics.

File: stats/opentelemetry/e2e_test.go [hunk 9]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+}
+
+// TestRelayContextCollisionTracing verifies that span context is correctly
+// propagated from incoming server requests to outgoing client requests without
+// the client span accidentally adopting the server's identity or breaking the
+// trace chain.
+func (s) TestRelayContextCollisionTracing(t *testing.T) {
+	toC, _ := defaultTraceOptions(t)
+	ssC := setupStubServer(t, nil, toC)
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Please use more descriptive names since it's not immediately clear what C, B suffixes represent.

File: stats/opentelemetry/e2e_test.go [hunk 10]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+
+	relayCC, err := grpc.NewClient(
+		ssC.Address,
+		grpc.WithTransportCredentials(insecure.NewCredentials()),
+		opentelemetry.DialOption(otelOpts),
+	)
+	if err != nil {
+		t.Fatalf("Failed to create relay client: %v", err)
+	}
+	defer relayCC.Close()
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Can we move the declaration of relayCC creation inside `UnaryCallF` to make it clearer that it makes an outbound call from a server?

File: stats/opentelemetry/e2e_test.go [hunk 11]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+
+	ssB := &stubserver.StubServer{
+		UnaryCallF: func(ctx context.Context, in *testpb.SimpleRequest) (*testpb.SimpleResponse, error) {
+			err := relayCC.Invoke(ctx, "/grpc.testing.TestService/UnregisteredCall", in, &testpb.SimpleResponse{})
+			if status.Code(err) != codes.Unimplemented {
+				t.Errorf("Expected Unimplemented error, got: %v", err)
+			}
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Why do we need a second server in this test case? In the first test case the call is made to the same server.

File: stats/opentelemetry/e2e_test.go [hunk 12]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+
+	if _, err := ssB.Client.UnaryCall(ctx, &testpb.SimpleRequest{}); err != nil {
+		t.Fatalf("Unexpected UnaryCall error: %v", err)
+	}
+
+	// Verify Server Metric Identity is retained
+	pollForMetricWithMethod(ctx, t, readerB, "grpc.server.call.started", "grpc.testing.TestService/UnaryCall")
+
+	// Verify Client Metric Identity correctly resolved to "other" (Proves
+	// collision is fixed)
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Please omit the last part `(Proves collision is fixed)`. The readers don't need to know about the the bug.

File: stats/opentelemetry/e2e_test.go [hunk 13]
```diff
@@ -2204,3 +2204,144 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+	}
+
+	if srvTraceID != cliTraceID {
+		t.Errorf("Trace continuity broken: Server TraceID %s != Client TraceID %s", srvTraceID, cliTraceID)
+	}
+}
+
+// pollForMetricWithMethod polls the metric reader until it finds a metric with
+// the specified name that contains a data point matching the target grpc.method.
+func pollForMetricWithMethod(ctx context.Context, t *testing.T, reader *metric.ManualReader, metricName, method string) metricdata.DataPoint[int64] {
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: If polling is necessary, can the existing `pollForWantMetrics` helper be re-used?

File: stats/opentelemetry/e2e_test.go (hunk 11 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: In both tests, A second server is needed to simulate a realistic relay (proxy) scenario. The flow is: Test Client -> Relay Server (ssB) -> Backend Server (ssC). If we used only one server, we wouldn't be testing the context propagation across a hop correctly without potential self-contamination.

File: stats/opentelemetry/e2e_test.go (hunk 12 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

File: stats/opentelemetry/e2e_test.go (hunk 8 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: changed.

File: stats/opentelemetry/e2e_test.go (hunk 9 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

File: stats/opentelemetry/e2e_test.go (hunk 10 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

File: stats/opentelemetry/e2e_test.go (hunk 13 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: removed polling - added check instead.

File: stats/opentelemetry/opentelemetry.go (hunk 3 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: done.

File: stats/opentelemetry/opentelemetry.go (hunk 4 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: done.

File: stats/opentelemetry/opentelemetry.go (hunk 5 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: done.

File: stats/opentelemetry/opentelemetry.go (hunk 2 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: done.

File: stats/opentelemetry/opentelemetry.go (hunk 7 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: I think getOrCreate is more explicit and makes more sense than ensure - I will prefer to keep it more explicit - easier to read and understand without having to look at the code. WDYT?

File: stats/opentelemetry/opentelemetry.go (hunk 6 above)
Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: done.

File: stats/opentelemetry/opentelemetry.go (hunk 7 above)
Comment (arjan-bal) [reply stats/opentelemetry/opentelemetry.go]: Okay, I don't feel too strongly about this. Can we drop `RPC` from the name?

Comment (mbissa) [reply stats/opentelemetry/opentelemetry.go]: Name has been changed to getOrCreateClientRPCInfo since we are aligning everything to RPCInfo and not attempt info.

File: stats/opentelemetry/e2e_test.go (hunk 11 above)
Comment (arjan-bal) [reply stats/opentelemetry/e2e_test.go]: Ah, I misunderstood the first test! I thought the relay server was calling a different method on itself. Thanks for the clarification.

File: stats/opentelemetry/e2e_test.go [hunk 14]
```diff
@@ -2204,3 +2204,135 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+			relayCC, err := grpc.NewClient(
+				backendServer.Address,
+				grpc.WithTransportCredentials(insecure.NewCredentials()),
+				opentelemetry.DialOption(otelOpts),
+			)
+			if err != nil {
+				return nil, fmt.Errorf("failed to create relay client: %v", err)
+			}
+			defer relayCC.Close()
+			err = relayCC.Invoke(ctx, "/grpc.testing.TestService/UnregisteredCall", in, &testpb.SimpleResponse{})
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: Is there a specific reason for using the low-level `Invoke` method instead of creating a test service client to call `UnaryCall` or `EmptyCall`? Typically, `Invoke` is reserved for generated code.

File: stats/opentelemetry/e2e_test.go [hunk 15]
```diff
@@ -2204,3 +2204,135 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+	}
+	defer relayServer.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+
+	_, _ = relayServer.Client.UnaryCall(ctx, &testpb.SimpleRequest{})
+
+	wantSpans := []traceSpanInfo{
+		{name: "Recv.", spanKind: "server"},
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go:2309]: This name seems incomplete. Usually the format is `Recv.<Method Name>`.  Is this a bug?

File: stats/opentelemetry/e2e_test.go [hunk 16]
```diff
@@ -2204,3 +2204,135 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+	defer relayServer.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+
+	if _, err := relayServer.Client.UnaryCall(ctx, &testpb.SimpleRequest{}); err != nil {
+		t.Fatalf("Unexpected UnaryCall error: %v", err)
+	}
+
+	// Verify Server Metric Identity is retained
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: nit: Comments should be complete sentences and end with a period (`.`). Please fix throughout.

File: stats/opentelemetry/e2e_test.go [hunk 17]
```diff
@@ -2204,3 +2204,135 @@ func runDisconnectScenario(t *testing.T, name, wantLabel string, action func(*st
...
+	if m, ok := metrics[metricName]; ok {
+		if sum, ok := m.Data.(metricdata.Sum[int64]); ok {
+			for _, dp := range sum.DataPoints {
+				if val, ok := dp.Attributes.Value("grpc.method"); ok && val.AsString() == method {
+					return // Found
+				}
+			}
+		}
+	}
+	t.Errorf("Metric %q with method %q not found", metricName, method)
```
Comment (arjan-bal) [inline stats/opentelemetry/e2e_test.go]: style: Instead of logging an error here, the helper should return a value and allow the main test function to log the error. See go/go-style/decisions#assert

File: stats/opentelemetry/e2e_test.go (hunk 14 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: The intent was just to have a different method name for the outbound call to easily detect attribute leakage. I can switch the outbound call to use the generated client to call EmptyCall (or another available method) instead of using Invoke with an unregistered name. That would keep the names distinct while using the generated client.

File: stats/opentelemetry/e2e_test.go (hunk 16 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

File: stats/opentelemetry/e2e_test.go (hunk 15 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go:2309]: Yes, this is a bug, I think when both metrics and tracing handlers are present, the metric handler populates it in the TagRPC for the metrics and since the RPCInfo is shared it works. 

This is same for client side tracing as well.

File: stats/opentelemetry/e2e_test.go (hunk 17 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

File: stats/opentelemetry/e2e_test.go (hunk 15 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go:2309]: Filed a bug for it - will address that separately : https://github.com/grpc/grpc-go/issues/9097

File: stats/opentelemetry/e2e_test.go (hunk 14 above)
Comment (arjan-bal) [reply stats/opentelemetry/e2e_test.go]: I would suggest using `EmptyCall` and `UnaryCall`. Since both are unary methods, the implementation size would remain the same.

There are other tests using `Invoke` in this file, most probably because they're testing the case where the server doesn't have a handler for method being invoked by the client.

File: stats/opentelemetry/e2e_test.go (hunk 15 above)
Comment (arjan-bal) [reply stats/opentelemetry/e2e_test.go:2309]: Sounds good, thanks!

**Comment by arjan-bal** [comment]
In the release notes, you can omit internal details and focus only on the user visible impact, i.e. "prevent outbound client calls from overwriting telemetry metadata in relay scenarios".

File: stats/opentelemetry/e2e_test.go (hunk 14 above)
Comment (mbissa) [reply stats/opentelemetry/e2e_test.go]: done.

**Review by arjan-bal — APPROVED** [review]
LGTM. We can cherry-pick this into the 1.81.x branch.
