### PR TITLE
transport: prevent deadlock in transport Close when GoAway write hangs

### LINKED ISSUE #7606: Flaky test: Test/ClientCloseReturnsEarlyWhenGoAwayWriteHangs
Sample failure: https://github.com/grpc/grpc-go/actions/runs/10780783629/job/29897278416?pr=7498

Logs
```
panic: test timed out after 7m0s
running tests:
	Test (6m40s)
	Test/ClientCloseReturnsEarlyWhenGoAwayWriteHangs (6m38s)

goroutine 2385 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/opt/hostedtoolcache/go/1.22.6/x64/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive, 6 minutes]:
testing.(*T).Run(0xc000162340, {0xc548bb, 0x4}, 0xc929a0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc000162340)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc000162340, 0xc000e61b10)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc00019e228, {0x10ea020, 0x4, 0x4}, {0xc00026dbb8?, 0xc00026dc00?, 0x10f3200?})
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc0001a4fa0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:57 +0x2be

goroutine 2285 [chan receive, 6 minutes]:
testing.(*T).Run(0xc0001624e0, {0xb8ebc2, 0x2b}, 0xc0000444a0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1750 +0x851
google.golang.org/grpc/internal/grpctest.RunSubTests(0xc0001624e0, {0xd4aba0, 0x1154000})
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:114 +0x3d8
google.golang.org/grpc/internal/transport.Test(0xc0001624e0)
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:60 +0x35
testing.tRunner(0xc0001624e0, 0xc929a0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1742 +0x826

goroutine 2367 [sync.Mutex.Lock, 6 minutes]:
sync.runtime_SemacquireMutex(0x72ca2d?, 0x0?, 0xc00020aa00?)
	/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000202870)
	/opt/hostedtoolcache/go/1.22.6/x64/src/sync/mutex.go:171 +0x213
sync.(*Mutex).Lock(0xc000202870)
	/opt/hostedtoolcache/go/1.22.6/x64/src/sync/mutex.go:90 +0x55
google.golang.org/grpc/internal/transport.(*http2Client).GetGoAwayReason(0xc0002026c8)
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:1418 +0x55
google.golang.org/grpc/internal/transport.(*http2Client).Close(0xc0002026c8, {0xd49120, 0xc00003a9f0})
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:1031 +0x7b2
google.golang.org/grpc/internal/transport.s.TestClientCloseReturnsEarlyWhenGoAwayWriteHangs({{}}, 0xc0001e0680)
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:2846 +0x7e7
google.golang.org/grpc/internal/grpctest.RunSubTests.func1(0xc0001e0680)
	/home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:122 +0x10e
testing.tRunner(0xc0001e0680, 0xc0000444a0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 2285
	/opt/hostedtoolcache/go/1.22.6/x64/src/testing/testing.go:1742 +0x826

goroutine 2368 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x7fe83f328c80, 0x72)
	/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00020a120, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.22.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00020a100)
	/opt/hostedtoolcache/go/1.22.6/x64/src/internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00020a100)
	/opt/hostedtoolcache/go/1.22.6/x64/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000446c0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc0000446c0)
	/opt/hostedtoolcache/go/1.22.6/x64/src/net/tcpsock.go:327 +0x65
google.golang.org/grpc/internal/transport.(*server).start(0xc0000242d0, 0xc0001e0680, 0x0, 0xc000000[180](https://github.com/grpc/grpc-go/actions/runs/10780783629/job/29897278416?pr=7498#step:8:181), 0x0)
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:362 +0x522
created by google.golang.org/grpc/internal/transport.setUpServerOnly in goroutine 2367
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:453 +0x325

goroutine 2392 [sync.Mutex.Lock, 6 minutes]:
sync.runtime_SemacquireMutex(0x4b6229?, 0x78?, 0xb66c05?)
	/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000202870)
	/opt/hostedtoolcache/go/1.22.6/x64/src/sync/mutex.go:171 +0x213
sync.(*Mutex).Lock(0xc000202870)
	/opt/hostedtoolcache/go/1.22.6/x64/src/sync/mutex.go:90 +0x55
google.golang.org/grpc/internal/transport.(*http2Client).Close(0xc0002026c8, {0xd491c0, 0xc0000b8de0})
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:989 +0xe5
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0002026c8, 0xc000408f00)
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:1672 +0xcf5
created by google.golang.org/grpc/internal/transport.newHTTP2Client in goroutine 2367
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:412 +0x33ab

goroutine 2393 [chan receive, 6 minutes]:
google.golang.org/grpc/internal/transport.(*hangingConn).Write(0xc000044780, {0xc000124040, 0x2a, 0x40})
	/home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:2796 +0xb5
google.golang.org/grpc/internal/transport.(*bufWriter).Write(0xc000024aa0, {0xc000124040, 0x2a, 0x40})
	/home/runner/work/grpc-go/grpc-go/internal/transport/http_util.go:325 +0x1da
golang.org/x/net/http2.(*Framer).endWrite(0xc00015e540)
	/home/runner/go/pkg/mod/golang.org/x/net@v0.28.0/http2/frame.go:371 +0x19d
golang.org/x/net/http2.(*Framer).WriteGoAway(0xc00015e540, 0x1, 0x0, {0xc0001d4380, 0x19, 0x47928e?})
	/home/runner/go/pkg/mod/golang.org/x/net@v0.28.0/http2/frame.go:924 +0x599
google.golang.org/grpc/internal/transport.(*http2Client).outgoingGoAwayHandler(0xc000[202](https://github.com/grpc/grpc-go/actions/runs/10780783629/job/29897278416?pr=7498#step:8:203)6c8, 0xc00017e440)
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:531 +0x177
google.golang.org/grpc/internal/transport.(*loopyWriter).goAwayHandler(0xc00024c180, 0xc00017e440)
	/home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:852 +0x67
google.golang.org/grpc/internal/transport.(*loopyWriter).handle(0xc00024c180, {0xbbf300, 0xc00017e440})
	/home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:886 +0x7dc
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00024c180)
	/home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:579 +0x17c
google.golang.org/grpc/internal/transport.newHTTP2Client.func6()
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:470 +0x250
created by google.golang.org/grpc/internal/transport.newHTTP2Client in goroutine 2367
	/home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:468 +0x3df4
FAIL	google.golang.org/grpc/internal/transport	420.030s
```

### PR DESCRIPTION
**Pull request by aranjans**
Fixes #7606.

Couple of recent changes worth noting here:
- https://github.com/grpc/grpc-go/pull/7015 added logic to send a GOAWAY frame on client transport shutdown. Unfortunately the handler responsible for writing the GOAWAY frame was holding on to the client transport mutex when attempting to write the GOAWAY frame.
- https://github.com/grpc/grpc-go/pull/7371  introduced a timeout in the client transport shutdown handler to wait for `loopyWriter` to exit (after enqueueing the above GOAWAY frame on the `controlbuf`). This was done to ensure that the client transport shutdown can complete in the face of a hanging network connection that blocks forever when attempting to write the above GOAWAY frame

Description of the deadlock:
- During client transport shutdown, after enqueueing the GOAWAY frame on the `controlbuf`, `http2Client.Close` calls `http2Client.GetGoAwayReason` to fetch the last GOAWAY's debug message, and the latter attempts to grab `http2Client.mu`.
- `http2Client.outgoingGoAwayHandler` holds `http2Client.mu` when it is attempting to write the GOAWAY frame. So, if the underlying network connection is hanging, this method will not release the mutex, and therefore `http2Client.GetGoAwayReason` will not be able to grab the same mutex, and thereby `http2Client.Close` will deadlock.

RELEASE NOTES: 
- transport: prevent deadlock in client transport shutdown when writing the GOAWAY frame hangs.

### CODE REVIEW

**Comment by purnesh42H** [comment]
Is there an existing issue filed which needs to be linked?

**Comment by aranjans** [comment]
@purnesh42H yes, added it in description.

**Comment by easwars** [comment]
Some general comments here:
- Can you please use bullet points in the PR description to make it more readable. Also, use backticks wherever appropriate to highlight code symbols
- The release note (and the PR title) needs to be more descriptive. Saying that a deadlock is happening due to `http2Client.mu` does not provide any useful information for the user.

File: internal/transport/http2_client.go [hunk 1]
```diff
@@ -1010,6 +1010,18 @@ func (t *http2Client) Close(err error) {
 	}
 	t.mu.Unlock()
 
+	// Append info about previous goaways if there were any, since this may be important
+	// for understanding the root cause for this connection to be closed.
+	_, goAwayDebugMessage := t.GetGoAwayReason()
```
Comment (easwars) [inline internal/transport/http2_client.go:1015]: `GetGoAwayReason` is implemented as follows:

```golang
func (t *http2Client) GetGoAwayReason() (GoAwayReason, string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.goAwayReason, t.goAwayDebugMessage
}
```

This means that the instead of unlocking `t.mu` on line 1011, we can instead do the following:
```golang
// Don't unlock on line 1011
goAwayDebugMessage := t.goAwayDebugMessage
t.mu.Unlock()
...
```

File: internal/transport/http2_client.go [hunk 2]
```diff
@@ -1010,6 +1010,18 @@ func (t *http2Client) Close(err error) {
...
+
```
Comment (easwars) [inline internal/transport/http2_client.go:1016]: The current implementation of `http2Client.outgoingGoAwayHandler` holds `t.mu` when calling `WriteGoAway` on the underlying framer, i.e. it is performing I/O when holding the lock. Is this the correct thing to do?

Can/should this be replaced with the following:
```golang
// OutgoingGoAwayHandler writes a GOAWAY to the connection.  Always returns
// (false, err) as we want the GoAway to be the last frame loopy writes to the
// transport.
func (t *http2Client) outgoingGoAwayHandler(g *goAway) (bool, error) {
	t.mu.Lock()
	nextID := t.nextID - 2
	t.mu.Unlock()
	if err := t.framer.fr.WriteGoAway(nextID, http2.ErrCodeNo, g.debugData); err != nil {
		return false, err
	}
	return false, g.closeConn
}
```

File: internal/transport/http2_client.go (hunk 1 above)
Comment (aranjans) [reply internal/transport/http2_client.go:1015]: You're right, we could do that.

File: internal/transport/http2_client.go (hunk 2 above)
Comment (aranjans) [reply internal/transport/http2_client.go:1016]: Yeah that'd be a useful optimization. We could define `maxStreamID` as `t.nextID - 2` and use it to write goAway frame as `t.framer.fr.WriteGoAway(maxStreamID, http2.ErrCodeNo, g.debugData)`.

File: internal/transport/http2_client.go (hunk 1 above)
Comment (purnesh42H) [reply internal/transport/http2_client.go]: wait, may be I am getting confused with line number but `t.controlBuf.put()` aquire a lock as well so we need to unlock before that. I think we need to make sure that we unlock in case of timeout as well

File: internal/transport/http2_client.go (hunk 2 above)
Comment (easwars) [reply internal/transport/http2_client.go:1017]: The call to `t.mu.Unlock()`, currently on line 1012, needs to be moved to be after this line because `t.goAwayDebugMessage` is guarded by that mutex.

Comment (easwars) [reply internal/transport/http2_client.go:1017]: > Yeah that'd be a useful optimization and hence minimize acquiring the mutex

I don't think this is a useful optimization. This is the root of the deadlock. I don't think we need to move code around in `http2Client.Close` at all if we don't hold the lock in `outgoingGoAwayHandler` when performing the actual write. Can you please confirm that?

File: internal/transport/http2_client.go (hunk 1 above)
Comment (aranjans) [reply internal/transport/http2_client.go]: @purnesh42H `t.controlBuf.put()` has a separate `mu` lock and is accessed with `t.controlBuf.mu` for control buffers resources, and here we are dealing with `t.mu` for htt2Client.

File: internal/transport/http2_client.go (hunk 2 above)
Comment (aranjans) [reply internal/transport/http2_client.go]: Interesting, yeah but we would need to release `t.mu` before we sent out goAway frame over to cbuf, bcz `outgoingGoAwayHandler` also needs to acquire `t.mu` to get the `maxStreamID` and we are waiting for t.writerDone with the timer. We can do something like


    goAwayDebugMessage := t.goAwayDebugMessage
	t.mu.Unlock()

	// Per HTTP/2 spec, a GOAWAY frame must be sent before closing the
	// connection. See https://httpwg.org/specs/rfc7540.html#GOAWAY. It
	// also waits for loopyWriter to be closed with a timer to avoid the
	// long blocking in case the connection is blackholed, i.e. TCP is
	// just stuck.
	t.controlBuf.put(&goAway{code: http2.ErrCodeNo, debugData: []byte("client transport shutdown"), closeConn: err})
	timer := time.NewTimer(goAwayLoopyWriterTimeout)
	defer timer.Stop()
	select {
	case <-t.writerDone: // success
	case <-timer.C:
		t.logger.Infof("Failed to write a GOAWAY frame as part of connection close after %s. Giving up and closing the transport.", goAwayLoopyWriterTimeout)
	}
	t.cancel()
	t.conn.Close()
	channelz.RemoveEntry(t.channelz.ID)
	var st *status.Status
	if len(goAwayDebugMessage) > 0 {
		st = status.Newf(codes.Unavailable, "closing transport due to: %v, received prior goaway: %v", err, goAwayDebugMessage)
		err = st.Err()
	} else {
		st = status.New(codes.Unavailable, err.Error())
	}

WDYT?

File: internal/transport/http2_client.go (hunk 1 above)
Comment (purnesh42H) [reply internal/transport/http2_client.go]: but `outgoingGoAwayHandler` is acquiring lock on `t.mu` which is followed by `t.controlBuf.put()`. We need to just make sure we unlock the  `outgoingGoAwayHandler` lock in case of timeout as well

Comment (aranjans) [reply internal/transport/http2_client.go]: exactly, please refer to this comment.
https://github.com/grpc/grpc-go/pull/7662#discussion_r1787209735

**Review by easwars — APPROVED** [review]

File: internal/transport/http2_client.go (hunk 2 above)
Comment (easwars) [reply internal/transport/http2_client.go]: Yes, that was my suggestion.

**Review by purnesh42H — APPROVED** [review]
lgtm
