### PR TITLE
fix the grpc website url

### LINKED ISSUE #561: https://godoc.org/google.golang.org/grpc reffers incorent github repository
```vim
package grpc

import "google.golang.org/grpc"

Package grpc implements an RPC system called gRPC.

See https://github.com/grpc/grpc for more information about gRPC.
```

Correct link is ``https://github.com/grpc/grpc-go``

### PR DESCRIPTION
**Pull request by iamqizhao**
fixes #561

### CODE REVIEW

File: doc.go [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /*
 Package grpc implements an RPC system called gRPC.
 
-See https://github.com/grpc/grpc for more information about gRPC.
+See www.grpc.io for more information about gRPC.
```
Comment (tamird) [inline doc.go]: wow, there is no TLS on that website? that's surprising.

**Comment by iamqizhao** [comment]
yup, a known issue for github hosting pages.
