### PR TITLE
Use user context instead of creating new context for client side stream

### LINKED ISSUE #888: Client transport leaks contexts
There is a leak in the client side of the HTTP/2 transport. `context.WithCancel` is called [here](https://github.com/grpc/grpc-go/blob/28707e14b1d2b2f5da81474dea2790d71e526987/transport/http2_client.go#L256), but the cancel function is never actually called (it is called in `http2_server.go`, but never in the client side). This leaks if the parent context is both long-lived and cancelable (but not actually canceled), since `context.WithCancel` sets up bidirectional references between the parent and child contexts until one or the other is canceled. 

The simplest fix is to change the line linked above to simply assign `s.ctx = ctx` without calling `WithCancel`. Alternately, the client could ensure that the cancelation function is called at some point, although I'm not sure exactly when that would be. 

The following program demonstrates the leak. Run it with

```
$ go build -o leak . && ./leak && go tool pprof --inuse_objects --top ./leak heap.pprof
352824 of 354100 total (99.64%)
Dropped 69 nodes (cum <= 1770)
      flat  flat%   sum%        cum   cum%
    174777 49.36% 49.36%     178055 50.28%  context.WithCancel
     98307 27.76% 77.12%     352824 99.64%  google.golang.org/grpc/transport.(*http2Client).NewStream
     76462 21.59% 98.71%      76462 21.59%  context.WithValue
      3278  0.93% 99.64%       3278  0.93%  context.propagateCancel
```

```
package main

import (
	"log"
	"net"
	"os"
	"runtime"
	"runtime/pprof"

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/examples/helloworld/helloworld"
)

type server struct{}

func (*server) SayHello(ctx context.Context, in *helloworld.HelloRequest) (*helloworld.HelloReply, error) {
	return &helloworld.HelloReply{Message: "Hello"}, nil
}

func main() {
	lis, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	helloworld.RegisterGreeterServer(s, &server{})
	go s.Serve(lis)

	conn, err := grpc.Dial(lis.Addr().String(), grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := helloworld.NewGreeterClient(conn)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	for i := 0; i < 100000; i++ {
		_, err := c.SayHello(ctx, &helloworld.HelloRequest{})
		if err != nil {
			log.Fatalf("failed to send: %v", err)
		}
	}
	runtime.GC()
	f, err := os.Create("heap.pprof")
	if err != nil {
		log.Fatal(err)
	}
	pprof.WriteHeapProfile(f)
	f.Close()
}
```

Original analysis in https://github.com/cockroachdb/cockroach/issues/9252#issuecomment-246102539

### PR DESCRIPTION
**Pull request by menghanl**
fixes #888

### CODE REVIEW

File: transport/http2_client.go [hunk 1]
```diff
@@ -252,8 +252,7 @@ func (t *http2Client) newStream(ctx context.Context, callHdr *CallHdr) *Stream {
 	s.windowHandler = func(n int) {
 		t.updateWindow(s, uint32(n))
 	}
-	// Make a stream be able to cancel the pending operations by itself.
-	s.ctx, s.cancel = context.WithCancel(ctx)
+	s.ctx = ctx
```
Comment (tschottdorf) [inline transport/http2_client.go]: No comment here? Seems brittle.
