### PR TITLE
Fix race between activeStreams and bdp window size

### LINKED ISSUE #5358: gRPC connection closing with unexpected EOF on high-latency connections
### What version of gRPC are you using?
1.46.2

### What version of Go are you using (`go version`)?
go version go1.18 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Client is running MacOs:
  ProductName: macOS
  ProductVersion: 11.6
  BuildVersion: 20G165

Server is running Linux (CentOS 7)

### What did you do?

Note: I have posted a small repo that can be used to reproduce this bug, please check it out here:
[https://github.com/brianneville/grpcbug](https://github.com/brianneville/grpcbug)

-------

For high-latency connections, I noticed that RPCs were having their connection terminated with an internal error: 
`code = Internal desc = unexpected EOF`

This hits on both unary and streaming RPCs, and the ease with which this can be reproduced seems to vary with the client-server latency.
For high-latency connections (such 150ms ping), this error hits pretty much every time an RPC is called.
For low-latency connections (<2ms ping) this error is much more infrequent, and hundreds of thousands of messages may be streamed over this connection before the error is hit even once.

I did a bit of digging through the grpc library code, and found two ways that the error can be prevented:

#### 1.  Client side - configure window sizes
The error can be prevented from the client side by disabling the dynamic window and BDP estimation for flow control when dialing the grpc server. 
That is, setting the DialOptions on the client side to use:
```
    opts := []grpc.DialOption{
       grpc.WithInitialWindowSize(largerWindowSize),
       grpc.WithInitialConnWindowSize(largerWindowSize),
    }
```
Where both: 
 - `largerWindowSize` is greater than 65535 (so that dynamic window/flow estimation is turned off)
 - `largerWindowSize` is greater than the size of the largest RPC response messages (with a bit of overhead for some reason).

#### 2.  Server-side - delay ending the stream
The error can be prevented by delaying the calls that write the `StatusOk` into the transport. Specifically, if the END_STREAM header is delayed from being put into the `controlBuf` at [`google.golang.org/grpc/internal/transport/http2_server.go#finishStream`](https://github.com/grpc/grpc-go/blob/db79903af928ca8307700d83123a7702881c4e3c/internal/transport/http2_server.go#L1269). 
That is, you can make any of the following changes to `*http2Server.finishStream`, and the error will not be present:
```
    time.Sleep(1 * time.Second) // <-- sleeping before put = EOF error is prevented
    t.controlBuf.put(hdr)
```
or   
```
    go func() {         // <-- allowing finishStream to progress and sleep before put = EOF error is prevented
      time.Sleep(1 * time.Second)
      t.controlBuf.put(hdr)
    }()
```

When the `t.controlBuf.put(hdr)` line is delayed in this way, the RPC is allowed to complete normally, and the client will see the response as intended.

Note if you add the sleep after the `t.controlBuf.put(hdr)`, then the error will still be present (i.e. delaying the finishStream function is not what causes the error to be prevented)
```
    t.controlBuf.put(hdr)
    time.Sleep(1 * time.Second) // <-- sleeping after put = EOF error still occurs 
```

Would anyone know what might be going on here, or be able to give me some insight/advice for continuing to debug this issue?

### What did you expect to see?
Connection latency does not affect RPCs

### What did you see instead?
High-latency connection (such as ~150ms ping) reliably hit the error `code = Internal desc = unexpected EOF`

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #5358.

The test case I added based off the issue test would successfully fail unexpected.EOF. This was caused by a race between when a stream was created and when updateFlowControl() was called. This fix makes sure any created streams has the correct window size on creation.

RELEASE NOTES:
* Fixed dynamic BDP estimation causing unexpected EOF error by fixing race between activeStreams and bdp window size

### CODE REVIEW

File: internal/transport/http2_client.go [hunk 1]
```diff
@@ -744,10 +748,10 @@ func (t *http2Client) NewStream(ctx context.Context, callHdr *CallHdr) (*Stream,
...
 		success, err := t.controlBuf.executeAndPut(func(it interface{}) bool {
-			if !checkForStreamQuota(it) {
+			if !checkForHeaderListSize(it) {
 				return false
 			}
-			if !checkForHeaderListSize(it) {
+			if !checkForStreamQuota(it) {
 				return false
 			}
 			return true
```
Comment (dfawley) [inline internal/transport/http2_client.go:757]: This can all be simply `return checkForHeaderListSize(it) && checkForStreamQuota(it)`

File: test/end2end_test.go [hunk 2]
```diff
@@ -8041,3 +8041,44 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	for i := 0; i < 10; i++ {
+		// exceeds grpc.DefaultMaxRecvMessageSize, this should error with
+		// RESOURCE_EXHAUSTED error.
+		_, err := ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{ResponseSize: 4194304})
+		if err != nil {
+			if e, ok := status.FromError(err); ok {
+				if e.Code() != codes.ResourceExhausted {
```
Comment (dfawley) [inline test/end2end_test.go:8072]: This is simpler:

```go
if code := status.Code(err); code != codes.ResourceExhausted {
	...
}
```

Note also that your test fails to detect if the returned error from `UnaryCall` is a non-status error (this isn't ever expected, of course, but is technically possible).

File: internal/transport/http2_client.go (hunk 1 above)
Comment (zasweq) [reply internal/transport/http2_client.go]: Switched.

File: test/end2end_test.go (hunk 2 above)
Comment (zasweq) [reply test/end2end_test.go]: Switched and wrote a comment about your note.

File: test/end2end_test.go [hunk 3]
```diff
@@ -8041,3 +8041,45 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+	}
+	defer ss.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	for i := 0; i < 10; i++ {
+		// exceeds grpc.DefaultMaxRecvMessageSize, this should error with
+		// RESOURCE_EXHAUSTED error.
+		_, err := ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{ResponseSize: 4194304})
+		if err != nil {
```
Comment (easwars) [inline test/end2end_test.go:8070]: Nit: combine the assignment and the conditional statements.

**Review by easwars — COMMENTED** [review]
We also probably need a better release note. Else, we will get back to this when we make the release.

File: test/end2end_test.go [hunk 4]
```diff
@@ -8041,3 +8041,45 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+			// This check doesn't fail on a non status error. However, the main
+			// this is testing for is an unexpected EOF with a status code
+			// INTERNAL so this is fine.
+			if code := status.Code(err); code != codes.ResourceExhausted {
+				t.Fatalf("unexpected err in UnaryCall: %v", err)
```
[the remark this answers is not in the document]
Comment (dfawley) [reply test/end2end_test.go:8075]: Printing the whole error is better than only printing the code, as there might be status message info that's useful:

```go
		t.Fatalf("UnaryCall RPC returned error: %v, want status code %v", err, want)
```

File: test/end2end_test.go (hunk 3 above)
Comment (zasweq) [reply test/end2end_test.go:8070]: Done.

File: test/end2end_test.go [hunk 5]
```diff
@@ -8041,3 +8041,45 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+			}
+		}
+		// Larger response that doesn't exceed DefaultMaxRecvMessageSize, this
+		// should work normally.
+		_, err = ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{ResponseSize: 275075})
+		if err != nil {
```
[the remark this answers is not in the document]
Comment (zasweq) [reply test/end2end_test.go:8081]: Done.

File: test/end2end_test.go [hunk 6]
```diff
@@ -8041,3 +8041,45 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+			t.Fatalf("unexpected err in UnaryCall: %v", err)
```
[the remark this answers is not in the document]
Comment (zasweq) [reply test/end2end_test.go:8082]: Switched.

File: test/end2end_test.go (hunk 2 above)
Comment (zasweq) [reply test/end2end_test.go]: Oh duh true lol.

File: test/end2end_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (zasweq) [reply test/end2end_test.go]: Switched to this:
`if code := status.Code(err); code != codes.ResourceExhausted {
t.Fatalf("UnaryCall RPC returned error: %v, want status code %v", err, codes.ResourceExhausted)
}`

**Review by zasweq — COMMENTED** [review]
Thanks for the comments :D! I'm sure some tests will fail from this stream change though give it a second to look at again.

File: internal/transport/http2_client.go [hunk 7]
```diff
@@ -1215,7 +1217,7 @@ func (t *http2Client) handleGoAway(f *http2.GoAwayFrame) {
 	default:
 		t.setGoAwayReason(f)
 		close(t.goAway)
-		t.controlBuf.put(&incomingGoAway{})
+		defer t.controlBuf.put(&incomingGoAway{})
```
Comment (dfawley) [inline internal/transport/http2_client.go:1220]: Please add a comment explaining that we defer because `t.mu` is held

File: test/end2end_test.go [hunk 8]
```diff
@@ -8041,3 +8041,43 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	for i := 0; i < 10; i++ {
+		// exceeds grpc.DefaultMaxRecvMessageSize, this should error with
+		// RESOURCE_EXHAUSTED error.
+		if _, err := ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{ResponseSize: 4194304}); err != nil {
+			// This check doesn't fail on a non status error. However, the main
+			// this is testing for is an unexpected EOF with a status code
+			// INTERNAL so this is fine.
```
Comment (dfawley) [inline test/end2end_test.go:8072]: Delete now.  It does fail on a non-status error since code would be Unknown in that case.

File: test/end2end_test.go [hunk 9]
```diff
@@ -8041,3 +8041,43 @@ func (s) TestServerClosesConn(t *testing.T) {
...
+		t.Fatalf("Error starting endpoint server: %v", err)
+	}
+	defer ss.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	for i := 0; i < 10; i++ {
+		// exceeds grpc.DefaultMaxRecvMessageSize, this should error with
+		// RESOURCE_EXHAUSTED error.
+		if _, err := ss.Client.UnaryCall(ctx, &testpb.SimpleRequest{ResponseSize: 4194304}); err != nil {
```
Comment (dfawley) [inline test/end2end_test.go:8069]:
```go
_, err := ss.Client.UnaryCall()
if got := status.Code(err); got != codes.ResourceExhausted {
	t.Fatal
}
```

This way you catch the case where the call _doesn't_ fail (code will be OK), unexpectedly.

File: test/end2end_test.go (hunk 8 above)
Comment (zasweq) [reply test/end2end_test.go]: Whoops forgot deleted.

File: test/end2end_test.go (hunk 9 above)
Comment (zasweq) [reply test/end2end_test.go]: Ah good point switched.

File: internal/transport/http2_client.go (hunk 7 above)
Comment (zasweq) [reply internal/transport/http2_client.go]: Added "Defer as t.mu is currently held".

**Review by zasweq — COMMENTED** [review]
Thanks for the comments :D!

**Review by dfawley — APPROVED** [review]
