### PR TITLE
xds: report drops by circuit breaking

### LINKED ISSUE #4138: Drops by circuit breaking are not reported to LRS
The circuit breaking PR missed a feature from the design: https://github.com/grpc/proposal/blob/master/A32-xds-circuit-breaking.md#detailed-design

> Such failed calls will not be retried, but they will be recorded to the `total_dropped_requests` counts in cluster-level load reports and reported to the load reporting server.

### PR DESCRIPTION
**Pull request by menghanl**
Those drops will be reported to store with category "".  When reported via LRS,
they will only be counted in total_drops, but not in per category.

fixes #4138

### CODE REVIEW

File: xds/internal/client/client_requests_counter.go [hunk 1]
```diff
@@ -87,3 +87,16 @@ func (c *ServiceRequestsCounter) StartRequest() error {
 func (c *ServiceRequestsCounter) EndRequest() {
 	atomic.AddUint32(&c.numRequests, ^uint32(0))
 }
+
+// ClearCounterForTesting clears the counter for the service. Should be only
+// used in tests.
+func ClearCounterForTesting(serviceName string) {
```
Comment (easwars) [inline xds/internal/client/client_requests_counter.go:93]: Should this return an error if `serviceName` is not found in the map?

File: xds/internal/balancer/edsbalancer/eds_impl.go [hunk 2]
```diff
@@ -515,6 +515,11 @@ func (d *dropPicker) Pick(info balancer.PickInfo) (balancer.PickResult, error) {
 	}
 	if d.counter != nil {
 		if err := d.counter.StartRequest(); err != nil {
+			// Drops by circuit breaking are reported with empty category. They
+			// will be reported only in total drops, but not in per category.
+			if d.loadStore != nil {
+				d.loadStore.CallDropped("")
```
Comment (easwars) [inline xds/internal/balancer/edsbalancer/eds_impl.go:521]: Why do we report these with an empty category instead of using a category which makes it clear that these calls were dropped because of circuit-breaking?

File: xds/internal/client/client_requests_counter.go (hunk 1 above)
Comment (menghanl) [reply xds/internal/client/client_requests_counter.go:93]: I think this doesn't matter.
Or are you suggesting that we should fail the test if this cleanup can't find the counter?

File: xds/internal/balancer/edsbalancer/eds_impl.go (hunk 2 above)
Comment (menghanl) [reply xds/internal/balancer/edsbalancer/eds_impl.go:521]: This is defined in the design doc.
And I believe the reason behind is that envoy doesn't report those with category.

File: xds/internal/client/load/store.go [hunk 3]
```diff
@@ -283,7 +283,12 @@ func (ls *perClusterStore) stats() *Data {
 			return true
 		}
 		sd.TotalDrops += d
-		sd.Drops[key.(string)] = d
+		keyStr := key.(string)
+		if keyStr != "" {
+			// Skip drops without category. They are counted in total_drops, but
+			// not in per category. One example is drops by circuit breaking.
+			sd.Drops[key.(string)] = d
```
Comment (dfawley) [inline xds/internal/client/load/store.go:290]: `keyStr`

**Review by dfawley — APPROVED** [review]

File: xds/internal/client/load/store.go (hunk 3 above)
Comment (menghanl) [reply xds/internal/client/load/store.go:290]: Done
