### PR TITLE
fix stats flaky test

### LINKED ISSUE #1615: TestServerStatsServerStreamRPCError failed
```
--- FAIL: TestServerStatsServerStreamRPCError (0.01s)
	stats_test.go:710: - 0, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc820019f50), LocalAddr:(*net.TCPAddr)(0xc8200197d0)})
	stats_test.go:710: - 1, *stats.ConnEnd = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc820019f50), LocalAddr:(*net.TCPAddr)(0xc8200197d0)})
	stats_test.go:710: - 2, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8201e24b0), LocalAddr:(*net.TCPAddr)(0xc8201e2480)})
	stats_test.go:710: - 3, *stats.ConnBegin = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8205f02a0), LocalAddr:(*net.TCPAddr)(0xc8205f0270)})
	stats_test.go:710: - 4, *stats.ConnEnd = &{Client:false}, ctx: context.Background.WithCancel.WithValue(stats_test.connCtxKey{}, &stats.ConnTagInfo{RemoteAddr:(*net.TCPAddr)(0xc8205f02a0), LocalAddr:(*net.TCPAddr)(0xc8205f0270)})
	stats_test.go:712: got 5 stats, want even positive number
```

### PR DESCRIPTION
**Pull request by menghanl**
1. Call transport Close if newHTTP2Server returns non-nil error.
Handle ConnBegin was called before this error, and handle ConnEnd is not called (because Close() is not called), which caused ConnStats check to fail.

2. Skip stats test in go1.6.
go1.6 doesn't have DialContext (we use Dialer(Cancel: ctx.Done()) instead). When the give context is canceled, this function sometimes returns canceled error, while the server side still gets the conn. This caused the server blocking on reading the preface (which will eventually timeout, but the tests are too short for that), and there will be a missing ConnEnd.

fixes #1615

### CODE REVIEW

File: transport/http2_server.go [hunk 1]
```diff
@@ -231,18 +231,21 @@ func newHTTP2Server(conn net.Conn, config *ServerConfig) (_ ServerTransport, err
 	// Check the validity of client preface.
 	preface := make([]byte, len(clientPreface))
 	if _, err := io.ReadFull(t.conn, preface); err != nil {
```
Comment (dfawley) [inline transport/http2_server.go]: Shouldn't we do the preface checks before we even create the `http2Server`?

How about this:

1. check preface
2. create http2Server
3. `defer func () { if err != nil { t.Close() } }()`

so we protect ourselves from this type of problem in the future.

Comment (menghanl) [reply transport/http2_server.go]: Added a defer close, but kept the order of preface and create transport.
