### PR TITLE
client: fix ForceCodec to set content-type header appropriately

### LINKED ISSUE #4278: Observed ForceCodec behaviour for content-subtype does not match documentation
### What version of gRPC are you using?

1.36.0

### What version of Go are you using (`go version`)?

1.15.6

### What operating system (Linux, Windows, …) and version?

Darwin amd64 10.15.7

### What did you do?
The documented behaviour of the `ForceCodec` call option does not match the behaviour observed on the wire. Steps to reproduce:

- Define a custom codec and set it using the `grpc.ForceCodec` call option in a call to a remote server
- Dispatch the call

Admittedly the call option is declared as experimental, however the currently implemented behaviour does not match the documented experimental behaviour.

### What did you expect to see?

The call on the wire has a `content-type` header of `application/grpc+<name>` where `<name>` is the string value returned from the custom codec's `Name()` method.

### What did you see instead?

The call on the wire has a `content-type` header of `application/grpc`.

---

The behaviour is actually advantageous for us in this circumstance, as we need to serialise a message in a client in a custom way that needs to be (and is) compatible with the native `proto` codec. However, the documentation for the `ForceCodec` option reads:

> The result of calling String() will be used as the content-subtype in a case-insensitive manner. 

This documentation is inconsistent with:

1. The `encoding.Codec` interface does not have a `String()` method; it has a `Name()` method instead. (The old `grpc.Codec` interface has a `String` method.)
2. The `(encoding.Codec).Name()` method is documented as follows:
   > The returned string will be used as part of content type in transmission.
3. The `CallContentSubtype` call option (not marked experimental) also reports that: 
   > If ForceCodec is also used, that Codec will be used for all request and response messages, with the content-subtype set to the given contentSubtype here for requests.

   This weakly implies that `ForceCodec` is expected to override the `content-subtype` unless the latter is explicitly overridden with the `CallContentSubtype` call option.

This is clearly internally inconsistent with itself among the various docs, and does not match the implemented behaviour observed in practice.

We can contribute a fix to this, but it is not clear to @nickgooding or me what the desired intent is: is the documentation wrong or is the implementation is wrong?

For our current purpose, we can also specify the `CallContentSubtype` call option to explicitly force the content-subtype as `proto` to ensure the proper value is sent to the client. As `CustomContentSubtype` is not experimental and explicitly documents that it overrides any content-type returned from `ForceCodec`'s overridden codec, this seems to provide the required guarantees.

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #4278

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -5284,6 +5284,53 @@ func (s) TestGRPCMethod(t *testing.T) {
...
+	if err := ss.Start([]grpc.ServerOption{grpc.ForceServerCodec(encoding.GetCodec("proto"))}); err != nil {
+		t.Fatalf("Error starting endpoint server: %v", err)
+	}
+	defer ss.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+	defer cancel()
+
+	codec := &renameProtoCodec{Codec: protoCodec, name: "some-test-name"}
+	wantContentTypeCh <- "application/grpc+some-test-name"
```
Comment (zasweq) [inline test/end2end_test.go:5322]: Nit: on potential blocking sends wait on a timeout context (or a timer) with defaultTestShortTimeout too so tests don't potentially block for 10 minutes if behavior change within codebase/test is flaky.

File: test/end2end_test.go [hunk 2]
```diff
@@ -5284,6 +5284,53 @@ func (s) TestGRPCMethod(t *testing.T) {
...
+	wantContentTypeCh := make(chan string, 1)
+	defer close(wantContentTypeCh)
+
+	ss := &stubserver.StubServer{
+		EmptyCallF: func(ctx context.Context, in *testpb.Empty) (*testpb.Empty, error) {
+			md, ok := metadata.FromIncomingContext(ctx)
+			if !ok {
+				return nil, status.Errorf(codes.Internal, "no metadata in context")
+			}
+			if got, want := md["content-type"], <-wantContentTypeCh; len(got) != 1 || got[0] != want {
```
Comment (zasweq) [inline test/end2end_test.go:5306]: Nit: I don't like this much logic on a single line of code. However, this seems to be very consistent with go style and previous discussions I've had with the team (making a lot of conditional validation checks less verbose where verbose means lots of lines).

File: test/end2end_test.go [hunk 3]
```diff
@@ -5284,6 +5284,53 @@ func (s) TestGRPCMethod(t *testing.T) {
...
+// renameProtoCodec is an encoding.Codec wrapper that allows customizing the
+// Name() of another codec.
+type renameProtoCodec struct {
+	encoding.Codec
+	name string
+}
+
+func (r *renameProtoCodec) Name() string { return r.name }
+
+func (s) TestForceCodecName(t *testing.T) {
```
Comment (zasweq) [inline test/end2end_test.go:5296]: Add a top level comment describing this test.

File: test/end2end_test.go (hunk 1 above)
Comment (zasweq) [reply test/end2end_test.go:5322]: I know probably this will probably never timeout on this send, but I like always accounting for the possibility.

**Review by zasweq — CHANGES_REQUESTED** [review]
A few nits.

File: test/end2end_test.go (hunk 3 above)
Comment (dfawley) [reply test/end2end_test.go:5319]: Done

File: test/end2end_test.go (hunk 2 above)
Comment (zasweq) [reply test/end2end_test.go]: Yeah I like that better.

**Review by zasweq — APPROVED** [review]
LGTM!
