### PR TITLE
weightedtarget: return a more meaningful error when no child policy is reporting READY (#5391)

### LINKED ISSUE #5391: weightedtarget: return a more meaningful error when no child policy is reporting READY
Currently, if none of the children of the `weightedtarget` LB policy are reporting `READY`, the parent policy simply returns a picker which returns an error all the time with a message of "all subConns are in TransientFailure".

https://github.com/grpc/grpc-go/blob/70a80552d51f74bd2fb313cff7fea68cde4c2612/balancer/weightedtarget/weightedaggregator/aggregator.go#L234

This does not provide the user with any actionable information to fix the underlying problem. Surfacing the status message from the failing child pickers would give actionable information to the user to fix the underlying problem.

Java returns a [weighted picker of all failing pickers](https://github.com/grpc/grpc-java/pull/7989) in this scenario and C-core is planning to do the same. We should also do something similar.

### PR DESCRIPTION
**Pull request by arvindbr8**
When all the child policies are in `TRANSIENT_FAILURE`, the `weightedtarget` LB policy currently sends a picker which always returns `balancer.ErrTransientFailure` error message. This error does not provide any info to the user regarding the underlying issue for the failure. With this change we are surfacing the underlying error by sending back the error picker.

Fixes #5391 

RELEASE NOTES:
* xds/weightedtarget: return an error picker to surface a more meaningful error when all children are in transient failure

### CODE REVIEW

File: balancer/weightedtarget/weightedtarget_test.go [hunk 1]
```diff
@@ -569,7 +575,9 @@ func (s) TestWeightedTarget_TwoSubBalancers_MoreBackends(t *testing.T) {
 	}
 
 	// Turn sc1's connection down.
-	wtb.UpdateSubConnState(sc1, balancer.SubConnState{ConnectivityState: connectivity.TransientFailure})
+	wtb.UpdateSubConnState(sc1, balancer.SubConnState{
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:578]: Instead of declaring the errors as globals, prefer declaring them here. And use error values directly instead of strings.

```golang
errSC1 := errors.New("error from sc1")
wtb.UpdateSubConnState(sc1, balancer.SubConnState{
	ConnectivityState: connectivity.TransientFailure,
	ConnectionError:  errSC1,
})
```

Similarly define an errSC4 for sc4. And when doing the pick, you could do:
```golang
for i := 0; i < 5; i++ {
	_, err := p.Pick(balancer.PickInfo{}); 
	if err == nil || (!strings.Contains(err.Error(), errSC1.Error()) &&  !strings.Contains(err.Error(), errSC4.Error()) {
		t.Fatalf("Pick() returned error: %v, want error: %v or %v",err, errSC1, errSC4)
	}
}
```

Note that in the above error message passed to `t.Fatalf()`, we specify got before want. See: go/go-style/decisions#got-before-want

Also, with this approach, we are concerned about the `last connection error`. That is actually coming from the base balancer and we dont want to rely on that here. As long as the returned error contains the error message that our picker returned, we should be good.

Comment (easwars) [reply balancer/weightedtarget/weightedtarget_test.go:578]: Also, please follow the same pattern for the other tests that you have modified as well.

Comment (easwars) [reply balancer/weightedtarget/weightedtarget_test.go:578]: We generally prefer `errors.New()` when the error message does not contain any formatting directive.

**Review by easwars — CHANGES_REQUESTED** [review]

File: balancer/weightedtarget/weightedaggregator/aggregator.go [hunk 2]
```diff
@@ -245,6 +245,7 @@ func (wbsa *Aggregator) build() balancer.State {
 	// state.
 	var readyN, connectingN, idleN int
 	readyPickerWithWeights := make([]weightedPickerState, 0, len(m))
+	errorPickers := make([]weightedPickerState, 0, len(m))
 	for _, ps := range m {
```
[the remark this answers is not in the document]
Comment (arvindbr8) [reply balancer/weightedtarget/weightedaggregator/aggregator.go:249]: yup, the m seemed confusing to me as well. updating it

File: balancer/weightedtarget/weightedtarget_test.go (hunk 1 above)
Comment (arvindbr8) [reply balancer/weightedtarget/weightedtarget_test.go:578]: makes sense. updating this in the revision

File: balancer/weightedtarget/weightedaggregator/aggregator.go [hunk 3]
```diff
@@ -245,6 +245,7 @@ func (wbsa *Aggregator) build() balancer.State {
 	// state.
 	var readyN, connectingN, idleN int
 	readyPickerWithWeights := make([]weightedPickerState, 0, len(m))
+	errorPickers := make([]weightedPickerState, 0, len(m))
```
[the remark this answers is not in the document]
Comment (arvindbr8) [reply balancer/weightedtarget/weightedaggregator/aggregator.go:248]: The reason why I chose `errorPickers` w/o `WithWeights` is cuz it seemed like we are not technically using weights here. Im updating `readyPickerWithWeights ` to `readyPickers`

File: balancer/weightedtarget/weightedtarget_test.go [hunk 4]
```diff
@@ -568,8 +575,12 @@ func (s) TestWeightedTarget_TwoSubBalancers_MoreBackends(t *testing.T) {
 		t.Fatalf("want %v, got %v", want, err)
 	}
 
+	scConnErr := errors.New("this is definitely a connection error. please check your wiring")
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:578]: Nit: could you please use a simpler error message. something like `subConn connection error`. And move this definition to be after the comment on line 580. So, it would be:

```golang
	// Turn sc1's connection down.
	scConnErr := errors.New("subConn connection error")
	wtb.UpdateSubConnState(sc1, balancer.SubConnState{
		ConnectivityState: connectivity.TransientFailure,
		ConnectionError:   scConnErr,
	})
```

Although the Go style guide doesn't differentiate between:
```golang
	wtb.UpdateSubConnState(sc1, balancer.SubConnState{
		ConnectivityState: connectivity.TransientFailure,
		ConnectionError:   scConnErr})
```
and
```golang
	wtb.UpdateSubConnState(sc1, balancer.SubConnState{
		ConnectivityState: connectivity.TransientFailure,
		ConnectionError:   scConnErr,
	})
```
I have seen the latter form used much more widely and I would recommend it as well.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 5]
```diff
@@ -586,11 +597,13 @@ func (s) TestWeightedTarget_TwoSubBalancers_MoreBackends(t *testing.T) {
 	}
 
 	// Turn all connections down.
-	wtb.UpdateSubConnState(sc4, balancer.SubConnState{ConnectivityState: connectivity.TransientFailure})
+	wtb.UpdateSubConnState(sc4, balancer.SubConnState{
+		ConnectivityState: connectivity.TransientFailure,
+		ConnectionError:   scConnErr})
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:602]: Same comment here.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 6]
```diff
@@ -586,11 +597,13 @@ func (s) TestWeightedTarget_TwoSubBalancers_MoreBackends(t *testing.T) {
...
 	p = <-cc.NewPickerCh
 	for i := 0; i < 5; i++ {
-		if _, err := p.Pick(balancer.PickInfo{}); err != balancer.ErrTransientFailure {
-			t.Fatalf("want pick error %v, got %v", balancer.ErrTransientFailure, err)
+		if _, err := p.Pick(balancer.PickInfo{}); !strings.Contains(err.Error(), scConnErr.Error()) {
+			t.Fatalf("want pick error '%v', got error '%v'", scConnErr, err)
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:606]: You don't have to quote the formatting directive `%v`. If you want the error message to appear quoted in the output, you can use `%q` instead.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 7]
```diff
@@ -792,8 +805,12 @@ func (s) TestWeightedTarget_ThreeSubBalancers_RemoveBalancer(t *testing.T) {
 		t.Fatalf("want %v, got %v", want, err)
 	}
 
+	scConnErr := errors.New("this is definitely a connection error. please check your wiring")
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:808]: Same comments made above apply here as well.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 8]
```diff
@@ -1062,17 +1079,22 @@ func (s) TestBalancerGroup_SubBalancerTurnsConnectingFromTransientFailure(t *tes
 	sc1 := scs["cluster_1"][0].sc
 	sc2 := scs["cluster_2"][0].sc
 
+	scConnErr := errors.New("this is definitely a connection error. please check your wiring")
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:1082]: Same here as well.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 9]
```diff
@@ -1062,17 +1079,22 @@ func (s) TestBalancerGroup_SubBalancerTurnsConnectingFromTransientFailure(t *tes
...
+		ConnectivityState: connectivity.TransientFailure,
+		ConnectionError:   scConnErr})
 	p := <-cc.NewPickerCh
 
 	for i := 0; i < 5; i++ {
-		r, err := p.Pick(balancer.PickInfo{})
-		if err != balancer.ErrTransientFailure {
-			t.Fatalf("want pick to fail with %v, got result %v, err %v", balancer.ErrTransientFailure, r, err)
+		if _, err := p.Pick(balancer.PickInfo{}); !strings.Contains(err.Error(), scConnErr.Error()) {
+			t.Fatalf("want pick error '%s', got error '%v'", scConnErr, err)
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:1097]: Please use consistent formatting directives for both errors.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 10]
```diff
@@ -1086,8 +1108,8 @@ func (s) TestBalancerGroup_SubBalancerTurnsConnectingFromTransientFailure(t *tes
 
 	for i := 0; i < 5; i++ {
 		r, err := p.Pick(balancer.PickInfo{})
-		if err != balancer.ErrTransientFailure {
-			t.Fatalf("want pick to fail with %v, got result %v, err %v", balancer.ErrTransientFailure, r, err)
+		if !strings.Contains(err.Error(), scConnErr.Error()) {
+			t.Fatalf("want pick error '%s', got result %v, err %v", scConnErr, r, err)
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:1112]: Please use consistent formatting directives for both errors.

File: xds/internal/balancer/clusterresolver/priority_test.go [hunk 11]
```diff
@@ -247,7 +247,9 @@ func (s) TestEDSPriority_SwitchPriority(t *testing.T) {
 	}
 
 	// Turn down 1, use 2
-	edsb.UpdateSubConnState(sc1, balancer.SubConnState{ConnectivityState: connectivity.TransientFailure})
+	edsb.UpdateSubConnState(sc1, balancer.SubConnState{
+		ConnectivityState: connectivity.TransientFailure,
+		ConnectionError:   fmt.Errorf("this is definitely a connection issue")})
```
Comment (easwars) [inline xds/internal/balancer/clusterresolver/priority_test.go:252]: Same as the other test. Please define an error variable using `errors.New()` and change the comparison in line 279 to be similar to that in the weightedtarget tests.

File: xds/internal/balancer/clusterresolver/priority_test.go [hunk 12]
```diff
@@ -274,7 +276,7 @@ func (s) TestEDSPriority_SwitchPriority(t *testing.T) {
 	}
 
 	// Should get an update with 1's old picker, to override 2's old picker.
-	if err := testErrPickerFromCh(cc.NewPickerCh, balancer.ErrTransientFailure); err != nil {
+	if err := testErrPickerFromCh(cc.NewPickerCh, fmt.Errorf("last connection error: this is definitely a connection issue")); err != nil {
```
Comment (easwars) [inline xds/internal/balancer/clusterresolver/priority_test.go:279]: And here.

File: xds/internal/balancer/clusterresolver/priority_test.go [hunk 13]
```diff
@@ -305,10 +307,12 @@ func (s) TestEDSPriority_HigherDownWhileAddingLower(t *testing.T) {
...
 	sc1 := <-cc.NewSubConnCh
 	// Turn down 1, pick should error.
-	edsb.UpdateSubConnState(sc1, balancer.SubConnState{ConnectivityState: connectivity.TransientFailure})
+	edsb.UpdateSubConnState(sc1, balancer.SubConnState{
+		ConnectivityState: connectivity.TransientFailure,
+		ConnectionError:   fmt.Errorf("this is definitely a connection issue")})
 
 	// Test pick failure.
-	if err := testErrPickerFromCh(cc.NewPickerCh, balancer.ErrTransientFailure); err != nil {
+	if err := testErrPickerFromCh(cc.NewPickerCh, fmt.Errorf("last connection error: this is definitely a connection issue")); err != nil {
```
Comment (easwars) [inline xds/internal/balancer/clusterresolver/priority_test.go:315]: And this one.

**Review by easwars — CHANGES_REQUESTED** [review]

File: balancer/weightedtarget/weightedtarget_test.go (hunk 4 above)
Comment (arvindbr8) [reply balancer/weightedtarget/weightedtarget_test.go:578]: sure. ill make this update. I didnt look at how the styling looks like in other places for this one.

File: balancer/weightedtarget/weightedtarget_test.go [hunk 14]
```diff
@@ -586,11 +592,14 @@ func (s) TestWeightedTarget_TwoSubBalancers_MoreBackends(t *testing.T) {
...
-	wtb.UpdateSubConnState(sc4, balancer.SubConnState{ConnectivityState: connectivity.TransientFailure})
+	wtb.UpdateSubConnState(sc4, balancer.SubConnState{
+		ConnectivityState: connectivity.TransientFailure,
+		ConnectionError:   scConnErr,
+	})
 	p = <-cc.NewPickerCh
 	for i := 0; i < 5; i++ {
-		if _, err := p.Pick(balancer.PickInfo{}); err != balancer.ErrTransientFailure {
-			t.Fatalf("want pick error %v, got %v", balancer.ErrTransientFailure, err)
+		if _, err := p.Pick(balancer.PickInfo{}); !strings.Contains(err.Error(), scConnErr.Error()) {
```
Comment (easwars) [inline balancer/weightedtarget/weightedtarget_test.go:601]: Also check, `err == nil`. Otherwise this will panic when the test fails with `Pick()` returning a `nil` error.

```golang
if _, err := p.Pick(balancer.PickInfo{}); err == nil || !strings.Contains(err.Error(), scConnErr.Error()) {...}
```

Same comment applies for other similar checks in this test as well.

File: xds/internal/balancer/clusterresolver/priority_test.go [hunk 15]
```diff
@@ -274,7 +279,8 @@ func (s) TestEDSPriority_SwitchPriority(t *testing.T) {
 	}
 
 	// Should get an update with 1's old picker, to override 2's old picker.
-	if err := testErrPickerFromCh(cc.NewPickerCh, balancer.ErrTransientFailure); err != nil {
+	want := errors.New("last connection error: subConn connection error")
+	if err := testErrPickerFromCh(cc.NewPickerCh, want); err != nil {
```
Comment (easwars) [inline xds/internal/balancer/clusterresolver/priority_test.go:283]: I was about to make the same comment as I did on the other file for here, but realized that `testErrPickerFromCh` performs a `reflect.DeepEqual()` on the got and want errors, instead of doing a `strings.Contains()`. Would you mind fixing the implementation of `testErrPickerFromCh` to do the latter instead. It doesn't have to be done in this PR. You can send another PR for that after this is merged. Thanks.

**Review by easwars — APPROVED** [review]
