### PR TITLE
client: fix "unix" scheme handling for some corner cases

### LINKED ISSUE #3990: Handle "unix" type when custom dialer is set
https://github.com/grpc/grpc-go/pull/3890 changed the way "unix" scheme is handled
 - **before:** the dialer (default or user-provided) gets the original dial target (`unix:///a/b/c`)
   - the dialer needs to split and find the network type
 - **after:** gRPC's [default dialer](https://github.com/grpc/grpc-go/blob/e8e22874d164e14311334b4c118d11fd311f915e/internal/transport/http2_client.go#L141) gets network type from `address.Attributes`

This is a behavior change for user's custom dialers, because they no longer get `unix:///a/b/c`, and will only get the unix path `/a/b/c`

The result is, `unix:///a/b/c` or `unix:/a/b/c` doesn't work if a custom dialer is specified, because the network type handling in default dialer will be bypassed.

Options
1. pass network type in `context`, so [WithContextDialer](https://pkg.go.dev/google.golang.org/grpc#WithContextDialer) can handle it
1. new `WithDialer` API, with `resolver.Address` as the address type, instead of string
   - add `resolver.Address.NetworkType`, as type string
   - users will need to handle network type, as `net.Dial(addr.NetworkType, addr.Addr)`
1. interceptor style API, which takes gRPC's default dialer as input, and returns a new wrapped dialer
   - Con: doesn't work if user's dialer needs to do TCP level changes thus cannot use gRPC's default dialer
1. don't call user's if network type is "unix"
   - Con: breaks cases where user wants to install a hook (e.g. wrap `net.Conn.Close`)
1. re-attach "unix:///" to addresses before calling custom dialer
   - Con: doesn't play nicely users with their own unix resolver; requires uses to do the extra parsing for the network type
1. register dialers by network types

### PR DESCRIPTION
**Pull request by GarrettGutierrez1**
Fixes #3990 .

### CODE REVIEW

File: internal/grpcutil/target.go [hunk 1]
```diff
@@ -60,9 +60,17 @@ func ParseTarget(target string, skipUnixColonParsing bool) (ret resolver.Target)
 		return resolver.Target{Endpoint: target}
 	}
 	if ret.Scheme == "unix" {
+		// Prevents behavior change in "unix:///[...]" case.
+		if skipUnixColonParsing && ret.Authority == "" {
```
Comment (dfawley) [inline internal/grpcutil/target.go:64]: Why does this check `skipUnixColonParsing`?  That only impacts `unix:<path>`, right?

File: internal/grpcutil/target_test.go [hunk 2]
```diff
@@ -70,17 +70,21 @@ func TestParseTargetString(t *testing.T) {
...
-		{targetStr: "unix:/domain", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/domain"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:/domain"}},
+		// unix:[local_path], unix:[/absolute], and unix://[/absolute] have different
+		// behaviors with a custom dialer, to prevent behavior changes with custom dialers.
+		{targetStr: "unix:a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "a/b/c"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:a/b/c"}},
+		{targetStr: "unix:/a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:/a/b/c"}},
+		{targetStr: "unix:///a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:///a/b/c"}},
+
+		{targetStr: "passthrough:///unix:///a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}, wantWithDialer: resolver.Target{Scheme: "passthrough", Authority: "", Endpoint: "unix:///a/b/c"}},
```
Comment (dfawley) [inline internal/grpcutil/target_test.go:87]: I think this should always be `Scheme: "passthrough", Endpoint: "unix:///a/b/c"`

**Review by dfawley — COMMENTED** [review]
This appears to be missing one case: `passthrough:///unix:///a/b/c` needs to be handled by the transport's default dialer (i.e. it sees `unix:` at the start and behaves as it used to before #3890)

File: internal/grpcutil/target_test.go (hunk 2 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target_test.go]: Fixed this, that is what it is in both cases now.

File: internal/grpcutil/target.go (hunk 1 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target.go]: The check is still there just moved (and'd with the =="unix" check). This is so I don't append a "/" to the address when it isn't going to the resolver, since that is only so the resolver gets the right address.

File: internal/grpcutil/target_test.go (hunk 2 above)
Comment (dfawley) [reply internal/grpcutil/target_test.go]: It looks like you have omitted `wantWithDialer` now.

Comment (GarrettGutierrez1) [reply internal/grpcutil/target_test.go]: With `wantWithDialer` omitted, the test sets it to `want` and just expects the same thing in both cases.

File: internal/grpcutil/target.go [hunk 3]
```diff
@@ -60,9 +61,45 @@ func ParseTarget(target string, skipUnixColonParsing bool) (ret resolver.Target)
...
-		// Add the "/" back in the unix case, so the unix resolver receives the
-		// actual endpoint.
-		ret.Endpoint = "/" + ret.Endpoint
+		if !skipUnixColonParsing {
+			// Add the "/" back in the unix case, so the unix resolver receives the
+			// actual endpoint.
+			ret.Endpoint = "/" + ret.Endpoint
+		} else {
+			// Custom dialer should receive "unix:///[...]".
+			return resolver.Target{Endpoint: target}
```
Comment (dfawley) [inline internal/grpcutil/target.go:70]: This should not be here; instead make the transport invoke the user's dialer after prepending "unix://" to the address string.

**Review by dfawley — CHANGES_REQUESTED** [review]

File: internal/grpcutil/target.go [hunk 4]
```diff
@@ -59,18 +60,41 @@ func ParseTarget(target string, skipUnixColonParsing bool) (ret resolver.Target)
...
 	}
-	// Prevents behavior change in "passthrough:///unix:///a/b/c" case.
-	if !skipUnixColonParsing && ret.Scheme == "passthrough" && strings.HasPrefix(ret.Endpoint, "unix:") {
-		return ParseTarget(ret.Endpoint, false)
-	}
 	return ret
 }
+
+// ParseDialTarget returns the network and address to pass to dialer
+func ParseDialTarget(target string) (string, string) {
```
[the remark this answers is not in the document]
Comment (GarrettGutierrez1) [reply internal/grpcutil/target.go]: Moved that to transport.

File: internal/grpcutil/target.go (hunk 3 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target.go]: Removed that part and am now appending to the address in transport.

File: internal/grpcutil/target_test.go [hunk 5]
```diff
@@ -70,7 +70,7 @@ func TestParseTargetString(t *testing.T) {
 		// If we can only parse part of the target.
 		{targetStr: "://", want: resolver.Target{Scheme: "", Authority: "", Endpoint: "://"}},
 		{targetStr: "unix://domain", want: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix://domain"}},
-		{targetStr: "unix://a/b/c", want: resolver.Target{Scheme: "unix", Authority: "a", Endpoint: "/b/c"}, wantWithDialer: resolver.Target{Scheme: "unix", Authority: "a", Endpoint: "b/c"}},
+		{targetStr: "unix://a/b/c", want: resolver.Target{Scheme: "unix", Authority: "a", Endpoint: "b/c"}},
```
Comment (dfawley) [inline internal/grpcutil/target_test.go:73]: This should be `Endpoint: "/b/c"` since we have the 3-slashes form.  It doesn't matter in practice since the authority is non-empty, so it will be an error either way, but that's how it should be.

File: internal/transport/http2_client.go [hunk 6]
```diff
@@ -139,15 +139,19 @@ type http2Client struct {
...
-	if fn != nil {
-		return fn(ctx, addr.Addr)
-	}
 	networkType := "tcp"
 	address := addr.Addr
-	if n, ok := networktype.Get(addr); ok {
+	n, ok := networktype.Get(addr)
+	if fn != nil {
+		if ok && n == "unix" {
+			return fn(ctx, "unix:///"+address)
```
Comment (dfawley) [inline internal/transport/http2_client.go:147]: This deserves a comment.  Something like: `For backward compatibility, if the user dialed "unix:///path", the passthrough resolver would be used and the user's custom dialer would see "unix:///path".  Re-add "unix://" here since we now support the "unix" scheme by default, which strips this prefix.`

File: internal/transport/http2_client.go [hunk 7]
```diff
@@ -139,15 +139,19 @@ type http2Client struct {
...
 func dial(ctx context.Context, fn func(context.Context, string) (net.Conn, error), addr resolver.Address, useProxy bool, grpcUA string) (net.Conn, error) {
-	if fn != nil {
-		return fn(ctx, addr.Addr)
-	}
 	networkType := "tcp"
 	address := addr.Addr
-	if n, ok := networktype.Get(addr); ok {
+	n, ok := networktype.Get(addr)
+	if fn != nil {
+		if ok && n == "unix" {
```
Comment (dfawley) [inline internal/transport/http2_client.go:146]: `ok` is redundant - if `!ok`, `n` will be `""`

File: internal/transport/http2_client.go [hunk 8]
```diff
@@ -139,15 +139,19 @@ type http2Client struct {
 }
 
 func dial(ctx context.Context, fn func(context.Context, string) (net.Conn, error), addr resolver.Address, useProxy bool, grpcUA string) (net.Conn, error) {
-	if fn != nil {
-		return fn(ctx, addr.Addr)
-	}
 	networkType := "tcp"
 	address := addr.Addr
-	if n, ok := networktype.Get(addr); ok {
+	n, ok := networktype.Get(addr)
```
Comment (dfawley) [inline internal/transport/http2_client.go:144]: `networkType, ok := ...` - the `"tcp"` default is no longer used (see below `if !ok`).

File: internal/grpcutil/target.go [hunk 9]
```diff
@@ -59,9 +60,9 @@ func ParseTarget(target string, skipUnixColonParsing bool) (ret resolver.Target)
 	if !ok {
 		return resolver.Target{Endpoint: target}
 	}
-	if ret.Scheme == "unix" {
-		// Add the "/" back in the unix case, so the unix resolver receives the
-		// actual endpoint.
+	if ret.Scheme == "unix" && !skipUnixColonParsing && ret.Authority == "" {
```
Comment (dfawley) [inline internal/grpcutil/target.go:63]: Did this need to change?  I think this can be reverted.

**Review by dfawley — CHANGES_REQUESTED** [review]
Please add an end-to-end test that uses a custom dialer with "unix:///" and "passthrough:///unix:///" to confirm everything is working correctly ("unix:///" appears in the address passed to the dialer for both).

**Review by dfawley — CHANGES_REQUESTED** [review]
Please add an end-to-end test that uses a custom dialer with "unix:///" and "passthrough:///unix:///" to confirm everything is working correctly ("unix:///" appears in the address passed to the dialer for both).

File: internal/grpcutil/target.go (hunk 9 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target.go]: Reverted this.

File: internal/transport/http2_client.go (hunk 8 above)
Comment (GarrettGutierrez1) [reply internal/transport/http2_client.go]: Made this change.

File: internal/transport/http2_client.go (hunk 7 above)
Comment (GarrettGutierrez1) [reply internal/transport/http2_client.go]: Got rid of redundant ok

File: internal/transport/http2_client.go (hunk 6 above)
Comment (GarrettGutierrez1) [reply internal/transport/http2_client.go]: Added this comment.

File: internal/grpcutil/target_test.go (hunk 5 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target_test.go]: It's "/b/c" now due to the revert of the +"/" change.

**Comment by GarrettGutierrez1** [comment]
> Please add an end-to-end test that uses a custom dialer with "unix:///" and "passthrough:///unix:///" to confirm everything is working correctly ("unix:///" appears in the address passed to the dialer for both).

End-to-end test added. Only oddity is authority in "passthrough:///unix:///path" case is "unix:///path" which I confirmed is the case before the change. This is because the result of the target parsing is `{Scheme: "passthrough", Authority: "", Endpoint: "unix:///path"}` and then `DialContext()` executes an else condition that sets the authority to the endpoint.

File: internal/grpcutil/target_test.go [hunk 10]
```diff
@@ -70,17 +70,21 @@ func TestParseTargetString(t *testing.T) {
...
-		// a custom dialer, to prevent behavior changes with custom dialers.
-		{targetStr: "unix:domain", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "domain"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:domain"}},
-		{targetStr: "unix:/domain", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/domain"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:/domain"}},
+		// unix:[local_path], unix:[/absolute], and unix://[/absolute] have different
+		// behaviors with a custom dialer, to prevent behavior changes with custom dialers.
+		{targetStr: "unix:a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "a/b/c"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:a/b/c"}},
+		{targetStr: "unix:/a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}, wantWithDialer: resolver.Target{Scheme: "", Authority: "", Endpoint: "unix:/a/b/c"}},
+		{targetStr: "unix:///a/b/c", want: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}, wantWithDialer: resolver.Target{Scheme: "unix", Authority: "", Endpoint: "/a/b/c"}},
```
Comment (dfawley) [inline internal/grpcutil/target_test.go:85]: Delete `wantWithDialer`?

File: test/authority_test.go [hunk 11]
```diff
@@ -80,15 +80,16 @@ func runUnixTest(t *testing.T, address, target, expectedAuthority string, dialer
...
-	}{
+type authorityTest struct {
+	name           string
+	address        string
+	target         string
+	authority      string
+	expectedTarget string
+}
+
+func tests() []authorityTest {
```
Comment (dfawley) [inline test/authority_test.go:91]: Use a variable not a function.  Also, need a better name than `tests` since this is package-global.

OR, make this non-global and put it in `TestUnix`, with a `runUnixCustomDialerTest` or something for the other tests.

File: test/authority_test.go [hunk 12]
```diff
@@ -80,15 +80,16 @@ func runUnixTest(t *testing.T, address, target, expectedAuthority string, dialer
...
-		address   string
-		target    string
-		authority string
-	}{
+type authorityTest struct {
+	name           string
+	address        string
+	target         string
+	authority      string
+	expectedTarget string
```
Comment (dfawley) [inline test/authority_test.go:88]: Go uses "want".  How about `dialTargetWant`?

File: internal/grpcutil/target_test.go (hunk 10 above)
Comment (GarrettGutierrez1) [reply internal/grpcutil/target_test.go]: Made this change.

File: test/authority_test.go (hunk 11 above)
Comment (GarrettGutierrez1) [reply test/authority_test.go]: Made it a variable named `authorityTests`

File: test/authority_test.go (hunk 12 above)
Comment (GarrettGutierrez1) [reply test/authority_test.go]: Changed it to `dialTargetWant`

**Review by dfawley — APPROVED** [review]

**Comment by stanhu** [comment]
Thanks, I tried to update to grpc-go v1.34.0, but tests were failing due to https://github.com/grpc/grpc-go/issues/3990. I verified that c456688b18606b43dcc5a817a05b7585614932d8 verified fixed the problem. Would you mind tagging an update with this?
