### PR TITLE
Fix possible data loss; Only let reader goroutine handle connection errors.

### LINKED ISSUE #1738: Client can lose data when connection ends
Consider the following scenario:
1. Client sends request, server writes full response and trailers and ends the stream.
2. Server closes connection.  (E.g. a graceful stop was in progress.)
3. Client sends a flow control window update back to the server, but receives an error from the conn because it is closed.
4. If the client closes the transport here (which it currently does), even though it has the response data in the conn, it cannot then retrieve that data:

https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L305

We should delay closing the transport (and the conn) for as long as possible.

In debugging a fix for `GracefulStop` behavior (#1737), I noticed that closing `t.conn` instead of `t` appears to fix a race.  I'm not sure why, yet, because closing the connection makes future reads from that conn fail.  At this point I believe it is still racy, just less so.

### PR DESCRIPTION
**Pull request by MakMukhi**
fixes #1738

### CODE REVIEW

File: transport/controlbuf.go [hunk 1]
```diff
@@ -357,10 +357,9 @@ func newLoopyWriter(s side, fr *framer, cbuf *controlBuffer, bdpEst *bdpEstimato
 const minBatchSize = 1000
 
 // run should be run in a separate goroutine.
-func (l *loopyWriter) run() {
+func (l *loopyWriter) run() (err error) {
```
Comment (dfawley) [inline transport/controlbuf.go]: Even though `err` is a named return variable, please don't use bare `return`s to avoid potential problems.  You can then remove these explicit variable declarations entirely by using `:=` where `it` and `isEmpty` are assigned below, which is usually worth doing.

File: test/gracefulstop_test.go [hunk 2]
```diff
@@ -148,10 +149,16 @@ func TestGracefulStop(t *testing.T) {
 		allowCloseCh: make(chan struct{}),
```
Comment (dfawley) [inline test/gracefulstop_test.go]: Are the "steps of this test" still valid after these changes?

Does the intent of this test change at all?  (Should this be a new test case instead of a modification to this one?)

Comment (MakMukhi) [reply test/gracefulstop_test.go]: Yes the steps remain the same. The idea is to eliminate a race; previously we'd allow the client to read goaway after it sends something on the wire(not necessarily headers). Now, we allow it to read goaway only after the server has received the headers.

File: transport/controlbuf.go (hunk 1 above)
Comment (MakMukhi) [reply transport/controlbuf.go]: Updated the return statements but can't using `:=` for vars since there's a logging call in defer that needs `err`.
