### PR TITLE
transport: fix error handling on Stream deletion

### LINKED ISSUE #1293: ClientConn.Close() doesn't always make Recv() end
Hi.

I'm having trouble with implementing the following logic with gRPC streams:
I have a client that sometimes calls Recv() on a gRPC stream and this invocation of Recv() should block until a message is received from the server.
However, sometimes I want the client to abort the Recv() invocation.
In order to do so, I have implemented another call that runs from a different goroutine, and simply calls Close() on the connection that the client stream was created with.
I've noticed that sometimes (although rarely) - the Recv() method gets stuck even though Close() was called after.

I had success with reproducing this issue in the attached link.

Could it be that closing the connection isn't supposed to make the Recv() method return, and the "right" way to do it is with **context.WithCancel** ? 

### What version of gRPC are you using?
Not sure, the commit hash is:
commit 4acc9108c18937815db3306a66990869d22aa980

### What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64

### What operating system (Linux, Windows, …) and version?
Description:	Ubuntu 14.04.5 LTS

### What did you do?
Provided a test that from 1 goroutine calls Recv() and then after 500ms calls Close() on the underlying connection.
Sometimes, the Recv() method doesn't return after the Close() is called. 
https://gist.github.com/yacovm/a39409305056fa36abb9ed849b6b9770

### What did you expect to see?
I expect Recv() to always return when Close() is called
### What did you see instead?
Sometimes Recv() is stuck.

### PR DESCRIPTION
**Pull request by gyuho**
This patch writes client-side error before closing the active stream
to fix blocking `RecvMsg` issue on `grpc.ClientStream` [1].

Previous gRPC client stream just exits on `ClientTransport.Error` [2].
And latest gRPC added another select case on client connection context
cancel [3]. Now when client stream closes from client connection context
cancel, it calls `CloseStream` with `ErrClientConnClosing` error. And then
the stream gets deleted from `*http2Client.activeStreams`, without processing
the error [4]. Then in-flight `RecvMsg` call on this client will block on
`*parser.Reader.recvMsg` [5].

In short,

1. `ClientConn.Close`.
2. in-flight streams will receive case `<-cc.ctx.Done()` https://github.com/grpc/grpc-go/blob/master/stream.go#L253-L255.
3. `cs.closeTransportStream(ErrClientConnClosing)` calls `cs.t.CloseStream(cs.s, err)`.
4. `CloseStream(cs.s, err)` calls `delete(t.activeStreams, s.id)` without handling the error.
5. in-flight streams will never receive error, left hanging.

I can reproduce in etcd tests with in-flight `recvMsg` calls to `Observe` RPC.

---
[1] https://github.com/coreos/etcd/pull/7896#issuecomment-305241742
[2] https://github.com/grpc/grpc-go/blob/v1.2.x/stream.go#L235-L238
[3] https://github.com/grpc/grpc-go/pull/1136
[4] https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L569
[5] https://github.com/grpc/grpc-go/blob/master/rpc_util.go#L280

/cc @xiang90 @heyitsanthony 

fixes #1293

### CODE REVIEW

**Comment by MakMukhi** [comment]
So I understand that this issue comes up when the code exits from this path: https://github.com/grpc/grpc-go/blob/master/stream.go#L253

Does this happen when the user application calls Close() on client conn and doesn't cancel the the stream's context?

**Comment by gyuho** [comment]
> Does this happen when the user application calls Close() on client conn and doesn't cancel the the stream's context?

Yes.

If I understand your question correctly, we get the server stream context first, and launch the `Recv` call on the stream [1]. And since the `Recv` call blocks, the `cancel` function never got called, while we still close the client connection when terminating the cluster.

```go
func (ep *electionProxy) Observe(req *v3electionpb.LeaderRequest, s v3electionpb.Election_ObserveServer) error {
	conn := ep.client.ActiveConnection()
	ctx, cancel := context.WithCancel(s.Context())
	_ = cancel
	sc, err := v3electionpb.NewElectionClient(conn).Observe(ctx, req)
	if err != nil {
		return err
	}
	for {
                // blocks here...
		rr, err := sc.Recv()
                ...
```

---
[1] https://github.com/coreos/etcd/blob/master/proxy/grpcproxy/election.go#L46-L53

**Comment by MakMukhi** [comment]
I see. Thanks for link to the code. I want to discuss this with the team a bit (possible other ways to tackle the problem). Let's try and wrap this is up by tomorrow.

**Comment by MakMukhi** [comment]
So this is in someway related to [code changes](https://github.com/grpc/grpc-go/pull/766/commits/0f1aeede97b7a43ed8943a35210340d835e39893#diff-3081f1aaaf958d7d5e00ccec7a62ea6fR422) made in the past. Looking at which your change does make sense. However, this also requires some more thought.

We all are in meetings all day today. This will have to go to Monday. Hope that's alright.

**Comment by MakMukhi** [comment]
Hey,
So we agreed on the change that you're proposing. Can you also please add a test for it?

**Comment by gyuho** [comment]
@MakMukhi Sure. I will try to write a test for it. Thanks.

**Comment by gyuho** [comment]
@MakMukhi I added a test, selecting on `GoAway` channel on stream close. I think setting `s.rstStream` early (before stream deletion) is safe. Otherwise the active stream that's being deleted will never receive GoAway from server. Please correct me if I am wrong. Thanks.

File: transport/http2_client.go [hunk 1]
```diff
@@ -551,6 +551,16 @@ func (t *http2Client) CloseStream(s *Stream, err error) {
...
 		return
 	}
+	if err != nil {
+		// notify in-flight streams, before the deletion
+		s.write(recvMsg{err: err})
+
+		if _, ok := err.(StreamError); ok {
+			// trigger server to send GoAway
+			s.rstStream = true
+			s.rstError = http2.ErrCodeCancel
```
Comment (MakMukhi) [inline transport/http2_client.go]: This doesn't trigger the server to send GoAway. Moreover, what's the rationale behind triggering it? It is a connection level concept; closing of a stream with some error shouldn't trigger closing of a connection, right?

We liked your original change, any specific reasons for updating it?

File: transport/transport_test.go [hunk 2]
```diff
@@ -382,6 +382,45 @@ func setUpWithNoPingServer(t *testing.T, copts ConnectOptions, done chan net.Con
 	return tr
 }
 
+// TestInflightStreamClosing tests that closing in-flight stream trigger a server
+// to send GoAway to the client with in-flight stream.
+func TestInflightStreamClosing(t *testing.T) {
+	serverConfig := &ServerConfig{
+		KeepaliveParams: keepalive.ServerParameters{
+			MaxConnectionIdle: 2 * time.Second,
+		},
```
Comment (MakMukhi) [inline transport/transport_test.go]: If we rely on keepalive related goaways, we don't test the code you wrote `s.write(recvMsg{err: err}) `.
The test should be a simple reproduction of your prod issue; a goroutine is blocked on stream.Read() while clientconn.Close() is called, with your change in place this goroutine should unblock.

Comment (gyuho) [inline transport/transport_test.go]: Agree. Let me rework on the test with original change. Thanks.

**Comment by gyuho** [comment]
@MakMukhi All fixed.

File: transport/transport_test.go [hunk 3]
```diff
@@ -382,6 +382,47 @@ func setUpWithNoPingServer(t *testing.T, copts ConnectOptions, done chan net.Con
 	return tr
 }
 
+// TestInflightStreamClosing ensures that closing in-flight stream
+// sends StreamError to concurrent stream reader.
+func TestInflightStreamClosing(t *testing.T) {
+	serverConfig := &ServerConfig{
+		InitialWindowSize:     defaultWindowSize,
+		InitialConnWindowSize: defaultWindowSize,
+	}
```
Comment (MakMukhi) [inline transport/transport_test.go]: For this test, we don't really need to set custom window sizes.

File: transport/transport_test.go [hunk 4]
```diff
@@ -382,6 +382,47 @@ func setUpWithNoPingServer(t *testing.T, copts ConnectOptions, done chan net.Con
 	return tr
 }
 
+// TestInflightStreamClosing ensures that closing in-flight stream
+// sends StreamError to concurrent stream reader.
+func TestInflightStreamClosing(t *testing.T) {
```
Comment (MakMukhi) [inline transport/transport_test.go]: The test looks good. I was expecting an end2end test with clientconn.Close() being called(like your prod issue) but this is essentially the same thing. 
Can you make sure that this test fails without your changes in place.

Comment (gyuho) [inline transport/transport_test.go]: All fixed.

I can confirm this test fails without the patch.
Our production blocking issue is fixed by this as well.

Thanks!

Comment (MakMukhi) [inline transport/transport_test.go]: Looks good. Thanks for your time and effort @gyuho

**Comment by gyuho** [comment]
@MakMukhi 

Could we have another release with this patch?
Just cut from master branch would work for us.
We will wait if there are other pending PRs.

Thanks!

**Comment by menghanl** [comment]
We can backport this PR to the 1.4 branch and do a 1.4.1 release.

**Comment by menghanl** [comment]
@gyuho Just release 1.4.1 with this change.

**Comment by gyuho** [comment]
@menghanl Thanks!
