### PR TITLE
test: fix Test/GracefulStop by not removing activeStreams too aggresivelly

### LINKED ISSUE #2703: unflake GracefulStop
```
[...]
E0318 19:34:25.685218    6841 clientconn.go:1186] Subchannel health check is unimplemented at server side, thus health check is disabled
E0318 19:34:37.816342    6841 http2_server.go:818] transport: failed to marshal rpc status: code:13 message:"\377\376\375" details:<type_url:"type.googleapis.com/grpc.testing.Empty" > , error: proto: field "google.rpc.Status.Message" contains invalid UTF-8
E0318 19:36:01.792418    6841 clientconn.go:1186] Subchannel health check is unimplemented at server side, thus health check is disabled
E0318 19:36:10.233347    6841 http2_server.go:818] transport: failed to marshal rpc status: code:13 message:"\377\376\375" details:<type_url:"type.googleapis.com/grpc.testing.Empty" > , error: proto: field "google.rpc.Status.Message" contains invalid UTF-8
--- FAIL: Test (91.39s)
    --- FAIL: Test/GracefulStop (0.00s)
    	gracefulstop_test.go:223: stream.Recv() = _, rpc error: code = Unavailable desc = transport is closing, want _, io.EOF
FAIL
```

### PR DESCRIPTION
**Pull request by menghanl**
Before this fix, stream is removed from activeStreams in finishStream,
which happens when the service handler returns status, without waiting
for the status to be sent by loopyWriter. If GracefulStop() is called in
between, it will close the connection (because activeStreams is empty),
which causes the RPC to fail with "transport is closing". This change
moves the activeStreams cleanup into loopyWriter, after sending status
on wire.

fixes #2703

### CODE REVIEW

File: internal/transport/http2_server.go [hunk 1]
```diff
@@ -1020,17 +1020,6 @@ func (t *http2Server) Close() error {
...
-	oldState = s.swapState(streamDone)
-	if oldState == streamDone {
-		// If the stream was already done, return.
-		return oldState
-	}
-
-	// In case stream sending and receiving are invoked in separate
-	// goroutines (e.g., bi-directional streaming), cancel needs to be
-	// called to interrupt the potential blocking on other goroutines.
-	s.cancel()
```
Comment (canguler) [inline internal/transport/http2_server.go]: I think we need to keep `s.cancel()` in `deleteStream`.

File: internal/transport/http2_server.go [hunk 2]
```diff
@@ -1020,17 +1020,6 @@ func (t *http2Server) Close() error {
 
 // deleteStream deletes the stream s from transport's active streams.
 func (t *http2Server) deleteStream(s *Stream, eosReceived bool) (oldState streamState) {
```
Comment (canguler) [inline internal/transport/http2_server.go]: We no longer need to return anything.

Comment (menghanl) [reply internal/transport/http2_server.go]: Done

File: internal/transport/http2_server.go (hunk 1 above)
Comment (menghanl) [reply internal/transport/http2_server.go]: Good catch. Done.

File: test/stream_cleanup_test.go [hunk 3]
```diff
@@ -55,3 +57,66 @@ func (s) TestStreamCleanup(t *testing.T) {
...
+	<-serverReturnedStatus
+
+	// 3. GracefulStop (besides sending goaway) checks the number of
+	// activeStreams.
+	//
+	// It will close the connection if there's no active streams. This won't
+	// happen because of the pending stream. But if there's a bug in stream
+	// cleanup that causes stream to be removed too aggressively, the connection
+	// will be closd and the stream will be broken.
+	go ss.s.GracefulStop()
```
Comment (easwars) [inline test/stream_cleanup_test.go]: Shouldn't we also make sure that GracefulStop() returns within a reasonable time? Because if it doesn't return by the end of the test, I'm wondering if the test would fail citing "hanging goroutines".

Comment (menghanl) [reply test/stream_cleanup_test.go]: Done.

Comment (easwars) [reply test/stream_cleanup_test.go]: LGTM
