### PR TITLE
test: add option to make httpServer wait for END_STREAM; fix RetryStats race

### LINKED ISSUE #4808: Flaky test: Test/RetryStats
```
--- FAIL: Test (132.29s)
    --- FAIL: Test/RetryStats (0.07s)
        tlogger.go:116: INFO clientconn.go:175 [core] Channel Created  (t=+877.105µs)
        tlogger.go:116: INFO clientconn.go:252 [core] parsed scheme: ""  (t=+1.064006ms)
        tlogger.go:116: INFO clientconn.go:258 [core] scheme "" not registered, fallback to default scheme  (t=+1.171306ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:33815  <nil> 0 <nil>}] <nil> <nil>}  (t=+1.239107ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:127.0.0.1:33815 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+1.315407ms)
        tlogger.go:116: INFO clientconn.go:728 [core] ClientConn switching balancer to "pick_first"  (t=+1.384808ms)
        tlogger.go:116: INFO clientconn.go:748 [core] Channel switches to new LB policy "pick_first"  (t=+1.591409ms)
        tlogger.go:116: INFO clientconn.go:789 [core] Subchannel Created  (t=+1.79561ms)
        tlogger.go:116: INFO clientconn.go:789 [core] Subchannel(id:2669) created  (t=+1.88151ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+2.238412ms)
        tlogger.go:116: INFO clientconn.go:1253 [core] Subchannel picks a new address "127.0.0.1:33815" to connect  (t=+2.675915ms)
        tlogger.go:116: INFO picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+3.188118ms)
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+3.49202ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+4.058423ms)
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to READY  (t=+4.476325ms)
        retry_test.go:604: Handler received frames:
            *stats.Begin - &{true 2021-09-22 23:53:07.696314257 +0000 UTC m=+294.826907066 true false false false}
            *stats.OutHeader - &{true  map[user-agent:[grpc-go/1.42.0-dev]] /grpc.testing.TestService/EmptyCall 127.0.0.1:33815 127.0.0.1:52078}
            *stats.OutPayload - &{true  [] 0 5 2021-09-22 23:53:07.698925672 +0000 UTC m=+294.829518381}
            *stats.End - &{true 2021-09-22 23:53:07.696314257 +0000 UTC m=+294.826907066 2021-09-22 23:53:07.699691276 +0000 UTC m=+294.830284085 map[] rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM}
            *stats.Begin - &{true 2021-09-22 23:53:07.699734076 +0000 UTC m=+294.830326785 true false false true}
            *stats.OutHeader - &{true  map[user-agent:[grpc-go/1.42.0-dev]] /grpc.testing.TestService/EmptyCall 127.0.0.1:33815 127.0.0.1:52078}
            *stats.OutPayload - &{true <nil> [] 0 5 2021-09-22 23:53:07.700072178 +0000 UTC m=+294.830664887}
            *stats.InTrailer - &{true 73 map[content-type:[application/grpc] grpc-retry-pushback-ms:[10]]}
            *stats.End - &{true 2021-09-22 23:53:07.699734076 +0000 UTC m=+294.830326785 2021-09-22 23:53:07.700773782 +0000 UTC m=+294.831366591 map[content-type:[application/grpc] grpc-retry-pushback-ms:[10]] rpc error: code = Unavailable desc = unavailable retry}
            *stats.Begin - &{true 2021-09-22 23:53:07.711544443 +0000 UTC m=+294.842137152 true false false false}
            *stats.OutHeader - &{true  map[user-agent:[grpc-go/1.42.0-dev]] /grpc.testing.TestService/EmptyCall 127.0.0.1:33815 127.0.0.1:52078}
            *stats.InHeader - &{true 14  map[content-type:[application/grpc]]  <nil> <nil>}
            *stats.InTrailer - &{true 12 map[]}
            *stats.OutPayload - &{true <nil> [] 0 5 2021-09-22 23:53:07.712593649 +0000 UTC m=+294.843186358}
            *stats.InPayload - &{true  [] 0 5 2021-09-22 23:53:07.71275705 +0000 UTC m=+294.843349859}
            *stats.End - &{true 2021-09-22 23:53:07.711544443 +0000 UTC m=+294.842137152 2021-09-22 23:53:07.71280705 +0000 UTC m=+294.843399859 map[] <nil>}
            ---
            want:
            *stats.Begin - &{false 0001-01-01 00:00:00 +0000 UTC false false false false}
            *stats.OutHeader - &{false  map[] /grpc.testing.TestService/EmptyCall <nil> <nil>}
            *stats.OutPayload - &{false <nil> [] 0 5 0001-01-01 00:00:00 +0000 UTC}
            *stats.End - &{false 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC map[] <nil>}
            *stats.Begin - &{false 0001-01-01 00:00:00 +0000 UTC false false false true}
            *stats.OutHeader - &{false  map[] /grpc.testing.TestService/EmptyCall <nil> <nil>}
            *stats.OutPayload - &{false <nil> [] 0 5 0001-01-01 00:00:00 +0000 UTC}
            *stats.InTrailer - &{false 0 map[content-type:[application/grpc] grpc-retry-pushback-ms:[10]]}
            *stats.End - &{false 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC map[] <nil>}
            *stats.Begin - &{false 0001-01-01 00:00:00 +0000 UTC false false false false}
            *stats.OutHeader - &{false  map[] /grpc.testing.TestService/EmptyCall <nil> <nil>}
            *stats.OutPayload - &{false <nil> [] 0 5 0001-01-01 00:00:00 +0000 UTC}
            *stats.InHeader - &{false 0  map[]  <nil> <nil>}
            *stats.InPayload - &{false <nil> [] 0 5 0001-01-01 00:00:00 +0000 UTC}
            *stats.InTrailer - &{false 0 map[]}
            *stats.End - &{false 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC map[] <nil>}
        retry_test.go:628: at position 11: got *stats.InHeader; want *stats.OutPayload
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+20.612116ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+20.968918ms)
        tlogger.go:116: INFO clientconn.go:1504 [core] Subchannel Deleted  (t=+21.18772ms)
        tlogger.go:116: INFO clientconn.go:1504 [core] Subchanel(id:2669) deleted  (t=+21.24462ms)
        tlogger.go:116: INFO clientconn.go:1098 [core] Channel Deleted  (t=+21.391721ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 2669 from a parent (id=2668) that doesn't currently exist  (t=+22.813729ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 2669 from a parent (id=2668) that doesn't currently exist  (t=+23.721134ms)
FAIL
FAIL	google.golang.org/grpc/test	307.110s
```

https://github.com/grpc/grpc-go/pull/4807/checks?check_run_id=3681386419

### PR DESCRIPTION
**Pull request by dfawley**
cc #4808 

RELEASE NOTES: none

### CODE REVIEW

**Comment by dfawley** [comment]
> github: set a shorter timeout on testing jobs

Whoops I had branched off of that branch and hadn't fetched master, either.  Everything should be fine now.

File: test/end2end_test.go [hunk 1]
```diff
@@ -7416,8 +7419,19 @@ func (s *httpServer) start(t *testing.T, lis net.Listener) {
...
-					sid = hframe.Header().StreamID
+				sid = 0
+				switch fr := frame.(type) {
+				case *http2.HeadersFrame:
+					if !s.waitForEndStream || fr.StreamEnded() {
+						sid = fr.Header().StreamID
+					}
+
+				case *http2.DataFrame:
+					if s.waitForEndStream && fr.Header().Flags.Has(http2.FlagDataEndStream) {
```
Comment (menghanl) [inline test/end2end_test.go:7430]: Why doesn't this also call `fr.StreamEnded()`?

Comment (menghanl) [reply test/end2end_test.go:7430]: And this if looks like a bug to me at first, then I realized that we don't care about DataFrame if `waitForEndStream==false`.

Add more comments?
Or maybe rename the var to `waitForRPCToFinish`?

**Review by menghanl — CHANGES_REQUESTED** [review]

File: test/end2end_test.go (hunk 1 above)
Comment (dfawley) [reply test/end2end_test.go]: > Why doesn't this also call fr.StreamEnded()?

Because this is how we do it in our transport and I didn't even check to see if this method exists on data frames.  :)

Added comments.

> maybe rename the var to `waitForRPCToFinish`?

But...the RPC isn't finished until the server does its end.  The server is waiting for the client's end stream.  `waitForEndStream` seems like a better name, but if you have other suggestions LMK.

File: test/end2end_test.go [hunk 2]
```diff
@@ -7416,8 +7419,23 @@ func (s *httpServer) start(t *testing.T, lis net.Listener) {
...
+				switch fr := frame.(type) {
+				case *http2.HeadersFrame:
+					// Respond after this if we are not waiting for an end
+					// stream or if this frame ends it.
+					if !s.waitForEndStream || fr.StreamEnded() {
+						sid = fr.Header().StreamID
+					}
+
+				case *http2.DataFrame:
+					// Respond after this if we were waiting for an end stream
```
Comment (menghanl) [inline test/end2end_test.go:7432]: Explain this more?
`If we were not waiting for an end stream, this RPC was handled already when the header frame was received, and there's no need to do it again`.

**Review by menghanl — APPROVED** [review]

File: test/end2end_test.go (hunk 2 above)
Comment (dfawley) [reply test/end2end_test.go:7432]: Done!
