### PR TITLE
transport/server: flush GOAWAY before closing conn due to max age

### LINKED ISSUE #4859: Flaky test: 22/10k: Test/DetailedGoawayErrorOnGracefulClosePropagatesToRPCError
https://github.com/grpc/grpc-go/runs/3862151035

```
    --- FAIL: Test/DetailedGoawayErrorOnGracefulClosePropagatesToRPCError (0.11s)
        tlogger.go:116: INFO clientconn.go:175 [core] Channel Created  (t=+2.603014ms)
        tlogger.go:116: INFO clientconn.go:252 [core] parsed scheme: "whatever"  (t=+2.936816ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:100 [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:33339  <nil> 0 <nil>}] <nil> <nil>}  (t=+3.62802ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:183 [core] Resolver state updated: {Addresses:[{Addr:127.0.0.1:33339 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} (resolver returned new addresses)  (t=+3.989522ms)
        tlogger.go:116: INFO clientconn.go:728 [core] ClientConn switching balancer to "pick_first"  (t=+4.117122ms)
        tlogger.go:116: INFO clientconn.go:748 [core] Channel switches to new LB policy "pick_first"  (t=+4.186123ms)
        tlogger.go:116: INFO clientconn.go:789 [core] Subchannel Created  (t=+4.356524ms)
        tlogger.go:116: INFO clientconn.go:789 [core] Subchannel(id:788) created  (t=+4.413724ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to CONNECTING  (t=+4.641225ms)
        tlogger.go:116: INFO clientconn.go:1253 [core] Subchannel picks a new address "127.0.0.1:33339" to connect  (t=+4.837026ms)
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to CONNECTING  (t=+5.381029ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to READY  (t=+7.522741ms)
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to READY  (t=+7.973744ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to IDLE  (t=+106.870086ms)
        end2end_test.go:1407: &{0xc00039e000}.Recv() = _, rpc error: code = Unavailable desc = error reading from server: EOF, want _, rpc error containing substring: "received prior goaway: code: NO_ERROR"
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to IDLE  (t=+108.100793ms)
        tlogger.go:116: INFO clientconn.go:436 [core] Channel Connectivity change to SHUTDOWN  (t=+108.676996ms)
        tlogger.go:116: INFO clientconn.go:1142 [core] Subchannel Connectivity change to SHUTDOWN  (t=+109.156499ms)
        tlogger.go:116: INFO clientconn.go:1504 [core] Subchannel Deleted  (t=+109.3799ms)
        tlogger.go:116: INFO clientconn.go:1504 [core] Subchanel(id:788) deleted  (t=+109.4613ms)
        tlogger.go:116: INFO clientconn.go:1098 [core] Channel Deleted  (t=+109.595501ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 788 from a parent (id=786) that doesn't currently exist  (t=+109.651801ms)
        tlogger.go:116: INFO types.go:68 [channelz] attempt to delete child with id 788 from a parent (id=786) that doesn't currently exist  (t=+109.757102ms)
```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #4859

By changing the grace period in the test, I was able to stimulate this bug much more reliably, and can confirm this fix makes it pass in 100% of subsequent runs.

~This PR currently includes a 5s sleep before an eventual hard close in case the TCP connection is completely stuck.  It's unclear to me whether this is necessary or desirable, or if it should be a shorter time.  (cc @ejona86)~

RELEASE NOTES: none

### CODE REVIEW

**Comment by dfawley** [comment]
Per @ejona86 I removed the 5s sleep & hard close, as this only happens when the TCP connection is broken, which the OS will figure out eventually anyway.

Also, it would be more ideal to begin the grace timer after the second GOAWAY is sent, but is probably not worth the trouble to change.

File: internal/transport/http2_server.go [hunk 1]
```diff
@@ -1153,7 +1153,7 @@ func (t *http2Server) keepalive() {
 				if logger.V(logLevel) {
 					logger.Infof("transport: closing server transport due to maximum connection age.")
 				}
-				t.Close()
+				t.controlBuf.put(closeConnection{})
```
Comment (easwars) [inline internal/transport/http2_server.go:1156]: `loopyWriter.closeConnectionHandler()` flushes the buffer and returns an error leading to `loopyWriter.run()` to return. But how and when does the actual transport get closed?

Would it be better to instead add a controlbuf operation to flush the buffer, and continue to call `t.Close()` here?

Comment (dfawley) [reply internal/transport/http2_server.go:1156]: We can't call `t.Close` here, because that won't wait for the controlBuf to exit, which is what we need.

This is how the transport will close now:

1. Loopy's run() will exit due to `closeConnection`, and get to here:

https://github.com/grpc/grpc-go/blob/110ed9e6ccbd391a691b24b6b918ce0991f7588f/internal/transport/http2_server.go#L339

2. That only closes the conn, not the transport.  The reader goroutine is responsible for closing the transport.  Closing the conn will lead to read errors in the reader goroutine, and that will lead to:

https://github.com/grpc/grpc-go/blob/110ed9e6ccbd391a691b24b6b918ce0991f7588f/internal/transport/http2_server.go#L632-L639

Comment (dfawley) [reply internal/transport/http2_server.go:1156]: This mirrors what we do in the client.  In the client, it's very important to read everything from the conn when it is closed (loopy may error before then), as it's possible the server sent response trailers for an RPC and immediately closed the connection; any RPCs that have messages/trailers that were written to the conn before closure must have those items read into their streams before the transport is closed.  On the server side, however, this seems less important to ensure, since the server would be unable to respond to any data on any remaining streams when the conn is closed.  Even though it's not as important, we probably should still do this, so the server application still has access to all the information we received, and it keeps things consistent between the two sides.

Comment (easwars) [reply internal/transport/http2_server.go:1156]: Can we document this in `closeConnectionHandler()` or some place else?

**Review by easwars — APPROVED** [review]

File: internal/transport/http2_server.go (hunk 1 above)
Comment (easwars) [reply internal/transport/http2_server.go:1156]: I think we had a race. My ask was for documenting how the transport eventually gets closed from `closeConnectionHandler`.

Comment (dfawley) [reply internal/transport/http2_server.go:1156]: Done!

Comment (easwars) [reply internal/transport/http2_server.go:1156]: Thank you !! LGTM.

[the remark this answers is not in the document]
Comment (easwars) [reply internal/transport/http2_server.go:1156]: I tried reading through the keepalive specs for the [client](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) and [server](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md). There is no mention of implementations having to gracefully terminate the connection when the _keepalive timeout_ expires. The spec **does** talk about sending `GOAWAYs` in cases where the _idle timeout_ or _connection timeout + grace_ expire. So, I'm guessing we are doing the right thing here. But agree with you that the log statement can be improved.

[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_server.go:1156]: @ejona86 mentioned to me recently that we should always _try_ to disconnect cleanly by writing a GOAWAY.  I assume that applies here, too (and he may have mentioned this exact case, but I'm not fully remembering at this point).

[the remark this answers is not in the document]
Comment (ejona86) [reply internal/transport/http2_server.go:1156]: I think I was mentioning it in the context of abrupt failures after protocol errors and the like, because that's where we had the 1s timer in grpc java okhttp.

I think this case is more wishy-washy, because you _have_ sent GOAWAY well before this point. So I don't think HTTP/2 requires a third GOAWAY here. But you could do it for your own benefit. If the receiver sees GOAWAY with max_age_grace, it could be easier to debug what is going on. I think for Netty we just RST_STREAM the remaining streams, which is semi-clear that the closure is on purpose and hard to mistake for other things. We don't have GRACE behavior yet in the OkHttp server.

[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_server.go:1156]: > I think this case is more wishy-washy, because you have sent GOAWAY well before this point.

The case we are discussing now is the one where the client fails to respond to the server's keepalive ping, so there has not been a GOAWAY written at all yet.

[the remark this answers is not in the document]
Comment (zasweq) [reply internal/transport/http2_server.go:1156]: I'm adding logs for easier debugging throughout http2_client and http2_server. Changed that error message to ""transport: closing server transport due to keep alive ping not being acked within timeout %v.", t.kp.Time.String()", will be out in a future PR.

[the remark this answers is not in the document]
Comment (zasweq) [reply internal/transport/http2_server.go:1156]: See https://github.com/grpc/grpc-go/pull/5840/files#diff-4058722211b8d52e2d5b0c0b7542059ed447a04017b69520d767e94a9493409eR1179.
