### PR TITLE
transport: limit AccountCheck tests to fewer streams and iterations to avoid flakes

### LINKED ISSUE #5283: Flaky test: 6/10k data race in TestAccountCheckWindowSizeWithSmallWindow
https://github.com/grpc/grpc-go/runs/5744477531?check_suite_focus=true

```
==================
WARNING: DATA RACE
Read at 0x00c0001ae930 by goroutine 160:
  runtime.mapaccess1_fast32()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/map_fast32.go:13 +0x0
  google.golang.org/grpc/internal/transport.testFlowControlAccountCheck()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:1571 +0xc06
  google.golang.org/grpc/internal/transport.s.TestAccountCheckWindowSizeWithSmallWindow()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:1478 +0x55
  google.golang.org/grpc/internal/transport.(*s).TestAccountCheckWindowSizeWithSmallWindow()
      <autogenerated>:1 +0x1d
  runtime.call16()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:701 +0x48
  reflect.callMethod()
      <autogenerated>:1 +0x64
  reflect.methodValueCall()
      /opt/hostedtoolcache/go/1.18.0/x64/src/reflect/asm_amd64.s:76 +0x79
  testing.tRunner()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1486 +0x47

Previous write at 0x00c0001ae930 by goroutine 190:
  runtime.mapdelete_fast32()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/map_fast32.go:273 +0x0
  google.golang.org/grpc/internal/transport.(*loopyWriter).cleanupStreamHandler()
      /home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:757 +0x145
  google.golang.org/grpc/internal/transport.(*loopyWriter).handle()
      /home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:829 +0x272
  google.golang.org/grpc/internal/transport.(*loopyWriter).run()
      /home/runner/work/grpc-go/grpc-go/internal/transport/controlbuf.go:538 +0x13b
  google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
      /home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:415 +0x105

Goroutine 160 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1486 +0x724
  google.golang.org/grpc/internal/grpctest.RunSubTests()
      /home/runner/work/grpc-go/grpc-go/internal/grpctest/grpctest.go:99 +0x507
  google.golang.org/grpc/internal/transport.Test()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:57 +0x3c
  testing.tRunner()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1486 +0x47

Goroutine 190 (running) created at:
  google.golang.org/grpc/internal/transport.newHTTP2Client()
      /home/runner/work/grpc-go/grpc-go/internal/transport/http2_client.go:[413](https://github.com/grpc/grpc-go/runs/5744477531?check_suite_focus=true#step:8:413) +0x3128
  google.golang.org/grpc/internal/transport.NewClientTransport()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport.go:577 +0x386
  google.golang.org/grpc/internal/transport.setUpWithOptions()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:453 +0x1f7
  google.golang.org/grpc/internal/transport.testFlowControlAccountCheck()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:1498 +0x165
  google.golang.org/grpc/internal/transport.s.TestAccountCheckWindowSizeWithSmallWindow()
      /home/runner/work/grpc-go/grpc-go/internal/transport/transport_test.go:1478 +0x55
  google.golang.org/grpc/internal/transport.(*s).TestAccountCheckWindowSizeWithSmallWindow()
      <autogenerated>:1 +0x1d
  runtime.call16()
      /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:701 +0x48
  reflect.callMethod()
      <autogenerated>:1 +0x64
  reflect.methodValueCall()
      /opt/hostedtoolcache/go/1.18.0/x64/src/reflect/asm_amd64.s:76 +0x79
  testing.tRunner()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1486 +0x47
==================
--- FAIL: Test (107.41s)
    --- FAIL: Test/AccountCheckWindowSizeWithSmallWindow (10.06s)
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:145: Error on server while reading message: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:138: Error on server while reading data header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1544: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1544: Error on client while reading data frame header: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:145: Error on server while reading message: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1550: Error on client while reading data: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        transport_test.go:1580: Client expected an EOF from the server. Got: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        testing.go:1312: race detected during execution of test
    testing.go:1312: race detected during execution of test
FAIL
FAIL	google.golang.org/grpc/internal/transport	208.[422](https://github.com/grpc/grpc-go/runs/5744477531?check_suite_focus=true#step:8:422)s
```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #5283

It seems the tests were always making progress, and were mostly nearly done after 10s.  Most test runs finished in 2-3s, so 10s is a bit of an outlier, but I think it's more important to fix the flaky test at this point than identify the cause of the long tail and potentially redesign the transport to mitigate it.

RELEASE NOTES: none

### CODE REVIEW

File: internal/transport/transport_test.go [hunk 1]
```diff
@@ -1599,26 +1601,27 @@ func testFlowControlAccountCheck(t *testing.T, msgSize int, wc windowSizeConfig)
 			binary.BigEndian.PutUint32(buf[1:], uint32(msgSize))
 			opts := Options{}
 			header := make([]byte, 5)
-			for i := 1; i <= 10; i++ {
+			for i := 1; i <= 5; i++ {
```
Comment (arvindbr8) [inline internal/transport/transport_test.go:1604]: nit: did we want to update this to a 5 as well. I understand that the test is not that flow control works as expected in 10 tries. Since we are only trying to contain the timeout flakes by this diff, would just reducing the number of clientStreams fix it?

**Review by arvindbr8 — APPROVED** [review]
LGTM with a small nit

File: internal/transport/transport_test.go (hunk 1 above)
Comment (dfawley) [reply internal/transport/transport_test.go:1604]: Lowering only clientStreams was not sufficient enough to get the flakiness rate down to 0/50k; lowering both gets it done, and we're still doing a _lot_ of window updates during the test, which is the main point of this step.
