### PR TITLE
Server shouldn't Fatalf in case it fails to encode.

### LINKED ISSUE #532: Server nil returns cause problems
In Go it is pretty idiomatic to return `nil, err` from a func when we encounter an error when the return values are a pointer and an error. The servers fail to marshal this `nil` while sending back a response to the client; and fatal logs. I think it might be better to do `new(T)` for the user before marshaling.

### PR DESCRIPTION
**Pull request by MakMukhi**
fixes #532

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -4109,3 +4116,46 @@ func testPerRPCCredentialsViaDialOptionsAndCallOptions(t *testing.T, e env) {
...
+
+func testEncodeDoesntPanic(t *testing.T, e env) {
+	te := newTest(t, e)
+	erc := &errCodec{}
+	te.customCodec = erc
+	te.startServer(&testServer{security: e.security})
+	defer te.tearDown()
+	te.customCodec = nil
+	tc := testpb.NewTestServiceClient(te.clientConn())
+	// Failure case.
```
Comment (menghanl) [inline test/end2end_test.go]: Add comment like "should not panic"

File: test/end2end_test.go [hunk 2]
```diff
@@ -4109,3 +4116,46 @@ func testPerRPCCredentialsViaDialOptionsAndCallOptions(t *testing.T, e env) {
...
+	}
+	return nil, fmt.Errorf("3987^12 + 4365^12 = 4472^12")
+}
+
+func (c *errCodec) Unmarshal(data []byte, v interface{}) error {
+	return nil
+}
+
+func (c *errCodec) String() string {
+	return "proto"
```
Comment (menghanl) [inline test/end2end_test.go]: return "near-misses"
