### PR TITLE
xds: use locality from the connected address for load reporting

### LINKED ISSUE #7339: If a priority contains multiple localities with pick_first, load is reported incorrectly
This should resolve when dual stack is fully implemented (#6472).  Until then, a partial implementation should be possible without requiring much throwaway work.

- [x] Create a reproduction test case for this scenario and confirm that load is not reported correctly.
- [ ] Change pick_first to have one subchannel per address.  Probably skip implementing happy eyeballs for now.
- [ ] Set an attribute on every subchannel creation operation (for outlier detection to read).
- [ ] Disable outlier detection if pick_first is used (detected via address attribute).  (See C++ version of this change here: https://github.com/grpc/grpc/pull/33336)

That should be all we need to correct this issue.

### PR DESCRIPTION
**Pull request by townba**
* Add `SubConnState.connectedAddress` field.
* Add `internal.GetConnectedAddress` and `internal.SetConnectedAddress` accessor function `var`s to get and set `SubConnState.connectedAddress`.
* Set the connected address in `acBalancerWrapper.updateState` when connectivity state is `Ready`.
* Read the connected address in the subconn `StateListener` and call `updateLocalityID()` based on that address's locality.
* Modify `addrConn` to store the full `resolver.Address` rather than one with `BalancerAttributes` removed.
* Modify a test to check for the new correct behavior.

Fixes #7339

RELEASE NOTES:
- TBD

### CODE REVIEW

**Review by easwars — COMMENTED** [review]
I still haven't finished reviewing the changes in clientconn.go

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 1]
```diff
@@ -366,14 +367,27 @@ func (b *clusterImplBalancer) NewSubConn(addrs []resolver.Address, opts balancer
...
+		}
+	}
 	sc, err := b.ClientConn.NewSubConn(newAddrs, opts)
 	if err != nil {
 		return nil, err
 	}
-	// Wrap this SubConn in a wrapper, and add it to the map.
-	ret := &scWrapper{SubConn: sc}
+	ret.SubConn = sc
 	ret.updateLocalityID(lID)
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:391]: I'd be a little worried about that particular change in behavior. We can revisit it later.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 2]
```diff
@@ -31,6 +31,7 @@ import (
 
 	"google.golang.org/grpc/balancer"
 	"google.golang.org/grpc/connectivity"
+	grpcinternal "google.golang.org/grpc/internal"
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:34]: (I didn't know that's how Go handles possible name collisions.)

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 3]
```diff
@@ -366,14 +367,27 @@ func (b *clusterImplBalancer) NewSubConn(addrs []resolver.Address, opts balancer
...
+	ret := &scWrapper{}
 	oldListener := opts.StateListener
-	opts.StateListener = func(state balancer.SubConnState) { b.updateSubConnState(sc, state, oldListener) }
+	opts.StateListener = func(state balancer.SubConnState) {
+		b.updateSubConnState(sc, state, oldListener)
+		// Read connected address and call updateLocalityID() based on the connected address's locality.
+		// https://github.com/grpc/grpc-go/issues/7339
+		if GetConnectedAddress, ok := grpcinternal.GetConnectedAddress.(func(state balancer.SubConnState) (resolver.Address, bool)); ok {
+			if addr, ok := GetConnectedAddress(state); ok {
+				// TODO: Why is lID empty when running the test? The locality info is being lost somehow.
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:378]: This `TODO` should not have been left there.

File: clientconn.go [hunk 4]
```diff
@@ -812,16 +814,26 @@ func (cc *ClientConn) applyFailingLBLocked(sc *serviceconfig.ParseResult) {
...
+	a.BalancerAttributes = nil
+	return a
+}
+
+// Makes a copy of the input addresses slice and optionally clears out the
+// balancer attributes field. Addresses are passed during subconn creation and
+// address update operations. In both cases, we may clear the balancer
+// attributes by calling this function, which would therefore allow us to use
+// the Equal method provided by the resolver.Address type for comparison.
+func copyAddresses(in []resolver.Address, includeBalancerAttributes bool) []resolver.Address {
```
Comment (easwars) [inline clientconn.go:829]: I'm not sure if this complexity is worth it. We can just have a `copyAddresses` function that copies all fields, and have an `equalAddress(es)` that ignores balancer attributes.

File: clientconn.go [hunk 5]
```diff
@@ -939,15 +957,15 @@ func equalAddresses(a, b []resolver.Address) bool {
...
 // connections or connection attempts.
 func (ac *addrConn) updateAddrs(addrs []resolver.Address) {
-	addrs = copyAddressesWithoutBalancerAttributes(addrs)
+	addrs = copyAddresses(addrs, withBalancerAttributes)
 	limit := len(addrs)
 	if limit > 5 {
 		limit = 5
 	}
-	channelz.Infof(logger, ac.channelz, "addrConn: updateAddrs addrs (%d of %d): %v", limit, len(addrs), addrs[:limit])
+	channelz.Infof(logger, ac.channelz, "addrConn: updateAddrs addrs (%d of %d): %v", limit, len(addrs), copyAddresses(addrs[:limit], withoutBalancerAttributes))
```
Comment (easwars) [inline clientconn.go:965]: Why is it important to skip balancer attributes here?

File: clientconn.go [hunk 6]
```diff
@@ -1347,6 +1365,7 @@ func (ac *addrConn) tryAllAddrs(ctx context.Context, addrs []resolver.Address, c
 // new transport.
 func (ac *addrConn) createTransport(ctx context.Context, addr resolver.Address, copts transport.ConnectOptions, connectDeadline time.Time) error {
 	addr.ServerName = ac.cc.getServerName(addr)
+	addrWithoutBalancerAttributes := addressWithoutBalancerAttributes(addr)
```
Comment (easwars) [inline clientconn.go:1368]: Same here. Why is it important to skip balancer attributes?

File: clientconn.go [hunk 7]
```diff
@@ -1381,14 +1400,14 @@ func (ac *addrConn) createTransport(ctx context.Context, addr resolver.Address,
...
+	newTr, err := transport.NewClientTransport(connectCtx, ac.cc.ctx, addrWithoutBalancerAttributes, copts, onClose)
 	if err != nil {
 		if logger.V(2) {
-			logger.Infof("Creating new client transport to %q: %v", addr, err)
+			logger.Infof("Creating new client transport to %q: %v", addrWithoutBalancerAttributes, err)
 		}
 		// newTr is either nil, or closed.
 		hcancel()
-		channelz.Warningf(logger, ac.channelz, "grpc: addrConn.createTransport failed to connect to %s. Err: %v", addr, err)
+		channelz.Warningf(logger, ac.channelz, "grpc: addrConn.createTransport failed to connect to %s. Err: %v", addrWithoutBalancerAttributes, err)
```
Comment (easwars) [inline clientconn.go:1410]: And here.

File: xds/internal/balancer/clusterimpl/clusterimpl.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:391]: Trying this breaks [this test](https://github.com/grpc/grpc-go/blob/master/xds/internal/balancer/clusterimpl/balancer_test.go#L582). I opted to add a `TODO` for now.

File: clientconn.go (hunk 5 above)
Comment (townba) [reply clientconn.go:965]: Only because it changes the information sent to `channelz.Infof` and I wasn't sure if that would affect anything. Sounds like it's not important.

File: clientconn.go (hunk 6 above)
Comment (townba) [reply clientconn.go:1368]: Changed. I was trying to change ancillary behavior as little as possible.

File: balancer_wrapper.go [hunk 8]
```diff
@@ -25,6 +25,7 @@ import (
 
 	"google.golang.org/grpc/balancer"
 	"google.golang.org/grpc/connectivity"
+	grpcinternal "google.golang.org/grpc/internal"
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer_wrapper.go:28]: Changed. (Didn't realize that's how Go imports worked.)

File: balancer/balancer.go [hunk 9]
```diff
@@ -410,6 +422,9 @@ type SubConnState struct {
 	// ConnectionError is set if the ConnectivityState is TransientFailure,
 	// describing the reason the SubConn failed.  Otherwise, it is nil.
 	ConnectionError error
+	// connectedAddr contains the connected address when ConnectivityState is Ready. Otherwise, it is
+	// indeterminate.
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer/balancer.go:426]: Done. I missed this one.

File: balancer_wrapper.go [hunk 10]
```diff
@@ -252,15 +253,21 @@ type acBalancerWrapper struct {
...
 		if ctx.Err() != nil || acbw.ccb.balancer == nil {
 			return
 		}
 		// Even though it is optional for balancers, gracefulswitch ensures
 		// opts.StateListener is set, so this cannot ever be nil.
 		// TODO: delete this comment when UpdateSubConnState is removed.
-		acbw.stateListener(balancer.SubConnState{ConnectivityState: s, ConnectionError: err})
+		scs := balancer.SubConnState{ConnectivityState: s, ConnectionError: err}
+		if s == connectivity.Ready {
+			if SetConnectedAddress, ok := grpcinternal.SetConnectedAddress.(func(state *balancer.SubConnState, addr resolver.Address)); ok {
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer_wrapper.go:266]: Shortened the name but kept the sanity check.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 11]
```diff
@@ -366,14 +367,27 @@ func (b *clusterImplBalancer) NewSubConn(addrs []resolver.Address, opts balancer
...
 	}
 	var sc balancer.SubConn
+	ret := &scWrapper{}
 	oldListener := opts.StateListener
-	opts.StateListener = func(state balancer.SubConnState) { b.updateSubConnState(sc, state, oldListener) }
+	opts.StateListener = func(state balancer.SubConnState) {
+		b.updateSubConnState(sc, state, oldListener)
+		// Read connected address and call updateLocalityID() based on the connected address's locality.
+		// https://github.com/grpc/grpc-go/issues/7339
+		if GetConnectedAddress, ok := grpcinternal.GetConnectedAddress.(func(state balancer.SubConnState) (resolver.Address, bool)); ok {
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:376]: Done.

File: balancer/balancer.go [hunk 12]
```diff
@@ -72,8 +72,20 @@ func unregisterForTesting(name string) {
 	delete(m, name)
 }
 
+// getConnectedAddress returns the connected address for a SubConnState.
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer/balancer.go:75]: Done.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 13]
```diff
@@ -366,14 +367,27 @@ func (b *clusterImplBalancer) NewSubConn(addrs []resolver.Address, opts balancer
...
+			if addr, ok := GetConnectedAddress(state); ok {
+				// TODO: Why is lID empty when running the test? The locality info is being lost somehow.
+				lID := xdsinternal.GetLocalityID(addr)
+				if !lID.Equal(xdsinternal.LocalityID{}) {
+					ret.updateLocalityID(lID)
+				}
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:382]: Done.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 14]
```diff
@@ -366,14 +367,27 @@ func (b *clusterImplBalancer) NewSubConn(addrs []resolver.Address, opts balancer
 		lID = xdsinternal.GetLocalityID(newAddrs[i])
 	}
 	var sc balancer.SubConn
+	ret := &scWrapper{}
```
[the remark this answers is not in the document]
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:370]: Done.

File: clientconn.go (hunk 4 above)
Comment (townba) [reply clientconn.go:829]: Done.

File: clientconn.go (hunk 7 above)
Comment (townba) [reply clientconn.go:1410]: Done.

**Comment by townba** [comment]
PTAL

File: clientconn.go [hunk 15]
```diff
@@ -924,12 +918,18 @@ func (ac *addrConn) connect() error {
...
 func equalAddresses(a, b []resolver.Address) bool {
 	if len(a) != len(b) {
 		return false
 	}
 	for i, v := range a {
-		if !v.Equal(b[i]) {
+		if !equalAddress(v, b[i]) {
 			return false
 		}
 	}
```
Comment (easwars) [inline clientconn.go:935]: This could be replaced with a call to:
 `slices.Equal(a, b, func(a, b resolver.Address) bool { return equalAddress(a, b)})`

File: clientconn.go [hunk 16]
```diff
@@ -924,12 +918,18 @@ func (ac *addrConn) connect() error {
 	return nil
 }
 
+func equalAddress(a, b resolver.Address) bool {
```
Comment (easwars) [inline clientconn.go:921]: Probably makes sense to add a function level comment here saying why we are not using the `resolver.Address.Equal` and instead defining our own. Something as simple as:

```
// equalAddress returns true is a and b are considered equal.
// This is different from the Equal method on the resolver.Address type 
// which considers all fields to determine equality. Here, we only consider
// fields that are meaningful to the subConn.
func equalAddress(a, b resolver.Address) bool { ... }
```

File: internal/internal.go [hunk 17]
```diff
@@ -208,6 +208,13 @@ var (
 	// ShuffleAddressListForTesting pseudo-randomizes the order of addresses.  n
 	// is the number of elements.  swap swaps the elements with indexes i and j.
 	ShuffleAddressListForTesting any // func(n int, swap func(i, j int))
+
+	// GetConnectedAddress returns the connected address for a SubConnState and
```
Comment (easwars) [inline internal/internal.go:212]: Same here. This can be simply `ConnectedAddress`.

File: internal/internal.go [hunk 18]
```diff
@@ -208,6 +208,13 @@ var (
...
+	// whether the address is valid based on the state.
```
Comment (easwars) [inline internal/internal.go:213]: And be explicit that the address is only valid when the returned state is `READY`.

File: xds/internal/internal.go [hunk 19]
```diff
@@ -55,6 +55,11 @@ func (l LocalityID) Equal(o any) bool {
 	return l.Region == ol.Region && l.Zone == ol.Zone && l.SubZone == ol.SubZone
 }
 
+// Empty returns whether or not the locality ID is empty.
+func (l LocalityID) Empty() bool {
+	return len(l.Region) == 0 && len(l.Zone) == 0 && len(l.SubZone) == 0
```
Comment (easwars) [inline xds/internal/internal.go:60]: Checking `len(string) == 0` *works* to check if the string is empty or not. But for better clarity, I think `string == ""` is better.

File: internal/testutils/balancer.go [hunk 20]
```diff
@@ -76,6 +77,21 @@ func (tsc *TestSubConn) UpdateState(state balancer.SubConnState) {
 	}
 }
 
+// UpdateStateAndConnectedAddress saves the connected address to state if the
```
Comment (easwars) [inline internal/testutils/balancer.go:80]: I'm not convinced that we need this method on the `TestSubConn` type. It only increases the API surface for something that is only used by one test. Instead I would manually set the connected address from the test under question, and use the existing `UpdateState` method with the SubConnState object that contains the connected address.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 21]
```diff
@@ -360,22 +361,33 @@ func (scw *scWrapper) localityID() xdsinternal.LocalityID {
...
+		b.updateSubConnState(sc, state, oldListener)
+		// Read connected address and call updateLocalityID() based on the connected
+		// address's locality. https://github.com/grpc/grpc-go/issues/7339
+		if gca, ok := internal.GetConnectedAddress.(func(balancer.SubConnState) (resolver.Address, bool)); ok {
+			if addr, ok := gca(state); ok {
+				lID := xdsinternal.GetLocalityID(addr)
+				if !lID.Empty() {
+					scw.updateLocalityID(lID)
+				} else if b.logger.V(2) {
+					b.logger.Infof("Locality ID for %v unexpectedly empty", addr)
```
Comment (easwars) [inline xds/internal/balancer/clusterimpl/clusterimpl.go:380]: I would replace the `%v` here with a `%s`. The `resolver.Address` type implements a `String()` method which satisfies the `stringer` interface and therefore can used directly with the `%s` formatting directive.

**Review by easwars — COMMENTED** [review]
Looks good. Mostly minor nits this time around.

Also, please don't mark the comments as resolved. We leave that to the reviewer who posted the original comment. That way the reviewer is not required to click "show resolved" on every comment to see if they are satisfactorily addressed. Thanks.

File: balancer/balancer.go [hunk 22]
```diff
@@ -72,8 +72,21 @@ func unregisterForTesting(name string) {
 	delete(m, name)
 }
 
+// getConnectedAddress returns the connected address for a SubConnState and
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer/balancer.go:75]: Done.

File: internal/internal.go (hunk 17 above)
Comment (townba) [reply internal/internal.go:212]: Done.

File: internal/internal.go (hunk 18 above)
Comment (townba) [reply internal/internal.go:213]: Done.

File: clientconn.go (hunk 16 above)
Comment (townba) [reply clientconn.go:921]: Done.

File: clientconn.go (hunk 15 above)
Comment (townba) [reply clientconn.go:935]: Done.

File: xds/internal/internal.go (hunk 19 above)
Comment (townba) [reply xds/internal/internal.go:60]: Done.

File: xds/internal/balancer/clusterimpl/clusterimpl.go (hunk 21 above)
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:380]: Done.

File: internal/testutils/balancer.go (hunk 20 above)
Comment (townba) [reply internal/testutils/balancer.go:80]: Done.

File: balancer/balancer.go [hunk 23]
```diff
@@ -410,6 +423,15 @@ type SubConnState struct {
...
 	ConnectionError error
+	// connectedAddr contains the connected address when ConnectivityState is
+	// Ready. Otherwise, it is indeterminate.
+	connectedAddress resolver.Address
+}
+
+func (lhs SubConnState) Equal(rhs SubConnState) bool {
+	return lhs.ConnectivityState == rhs.ConnectivityState &&
+		lhs.ConnectionError == rhs.ConnectionError &&
+		lhs.connectedAddress.Addr == rhs.connectedAddress.Addr
```
[the remark this answers is not in the document]
Comment (townba) [reply balancer/balancer.go:435]: Done.

**Comment by townba** [comment]
PTAL

**Review by easwars — APPROVED** [review]

File: balancer/balancer.go [hunk 24]
```diff
@@ -410,6 +424,15 @@ type SubConnState struct {
 	// ConnectionError is set if the ConnectivityState is TransientFailure,
 	// describing the reason the SubConn failed.  Otherwise, it is nil.
 	ConnectionError error
+	// connectedAddr contains the connected address when ConnectivityState is
+	// Ready. Otherwise, it is indeterminate.
+	connectedAddress resolver.Address
+}
+
+func (lhs SubConnState) Equal(rhs SubConnState) bool {
```
Comment (dfawley) [inline balancer/balancer.go:432]: Will we delete this entirely when `connectedAddress` is removed?  If so, ignore.  If not, then should this accept pointers instead?

File: clientconn.go [hunk 25]
```diff
@@ -924,22 +919,24 @@ func (ac *addrConn) connect() error {
 	return nil
 }
 
+// equalAddress returns true is a and b are considered equal.
+// This is different from the Equal method on the resolver.Address type which
+// considers all fields to determine equality. Here, we only consider fields
+// that are meaningful to the subConn.
+func equalAddress(a, b resolver.Address) bool {
```
Comment (dfawley) [inline clientconn.go:926]: These should probably be pointers to avoid the copy.

File: clientconn.go (hunk 16 above)
Comment (dfawley) [reply clientconn.go:926]: Renaming the function might be an even nicer improvement.  `equalIgnoringBalAttributes`?

File: balancer_wrapper.go [hunk 26]
```diff
@@ -252,15 +253,21 @@ type acBalancerWrapper struct {
...
 		if ctx.Err() != nil || acbw.ccb.balancer == nil {
 			return
 		}
 		// Even though it is optional for balancers, gracefulswitch ensures
 		// opts.StateListener is set, so this cannot ever be nil.
 		// TODO: delete this comment when UpdateSubConnState is removed.
-		acbw.stateListener(balancer.SubConnState{ConnectivityState: s, ConnectionError: err})
+		scs := balancer.SubConnState{ConnectivityState: s, ConnectionError: err}
+		if s == connectivity.Ready {
+			if sca, ok := internal.SetConnectedAddress.(func(*balancer.SubConnState, resolver.Address)); ok {
```
Comment (dfawley) [inline balancer_wrapper.go:266]: Please define this as a global instead.

```go
var setConnectedAddress = internal.SetConnectedAddress.(func(*.........))
```

That way we don't have a conditional here and a runtime unknown.  Instead it's an init time assertion.

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 27]
```diff
@@ -360,22 +361,33 @@ func (scw *scWrapper) localityID() xdsinternal.LocalityID {
...
 	}
 	var sc balancer.SubConn
+	scw := &scWrapper{}
 	oldListener := opts.StateListener
-	opts.StateListener = func(state balancer.SubConnState) { b.updateSubConnState(sc, state, oldListener) }
+	opts.StateListener = func(state balancer.SubConnState) {
+		b.updateSubConnState(sc, state, oldListener)
+		// Read connected address and call updateLocalityID() based on the connected
+		// address's locality. https://github.com/grpc/grpc-go/issues/7339
+		if gca, ok := internal.ConnectedAddress.(func(balancer.SubConnState) (resolver.Address, bool)); ok {
```
Comment (dfawley) [inline xds/internal/balancer/clusterimpl/clusterimpl.go:374]: Same comment here -- remove the conditional and make this global, please.

File: balancer/balancer.go [hunk 28]
```diff
@@ -72,8 +72,22 @@ func unregisterForTesting(name string) {
 	delete(m, name)
 }
 
+// connectedAddress returns the connected address for a SubConnState.
+// The second return value is set to to false if the state is not READY, and the
+// first return value is meaningless in this case.
```
Comment (dfawley) [inline balancer/balancer.go:77]: Why is anyone even calling this if the state isn't ready?  Can we just say it's only valid if READY to simplify things a bit?

File: xds/internal/balancer/clusterimpl/clusterimpl.go [hunk 29]
```diff
@@ -360,22 +361,33 @@ func (scw *scWrapper) localityID() xdsinternal.LocalityID {
...
+			if addr, ok := gca(state); ok {
+				lID := xdsinternal.GetLocalityID(addr)
+				if !lID.Empty() {
+					scw.updateLocalityID(lID)
```
Comment (dfawley) [inline xds/internal/balancer/clusterimpl/clusterimpl.go:378]: Go style: let's try to avoid all this nesting:

```go
StateListener = func... {
	b.updateSubConnState(...)
	if state != Ready {
		return
	}
	locality := xdsinternal.GetLocalityID(getConnectedAddress(state))
	if locality.Empty() {
		if logger.V(2) { log }
		return
	}
	scw.updateLocalityID(locality)
}
```

**Review by dfawley — COMMENTED** [review]
Looks good overall, just a few minor style things.

File: balancer/balancer.go (hunk 24 above)
Comment (townba) [reply balancer/balancer.go:432]: Done.

Comment (townba) [reply balancer/balancer.go:432]: Removed entirely.

This was only added to get [this single check in `xds/internal/balancer/outlierdetection/balancer_test.go`](https://github.com/grpc/grpc-go/blob/45d44a736ec6cdcb73f9411bf6a1c2d1abea1956/xds/internal/balancer/outlierdetection/balancer_test.go#L854-L859) to pass, but that doesn't work if it uses pointers. I've removed this in favor of adding `balancer.SubConnState{}` to the `cmp.AllowUnexported`.

File: clientconn.go (hunk 16 above)
Comment (townba) [reply clientconn.go:926]: Done.

File: clientconn.go (hunk 25 above)
Comment (townba) [reply clientconn.go:926]: Done.

File: balancer/balancer.go (hunk 28 above)
Comment (townba) [reply balancer/balancer.go:77]: Done.

File: balancer_wrapper.go (hunk 26 above)
Comment (townba) [reply balancer_wrapper.go:266]: Done.

File: xds/internal/balancer/clusterimpl/clusterimpl.go (hunk 27 above)
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:374]: Done.

File: xds/internal/balancer/clusterimpl/clusterimpl.go (hunk 29 above)
Comment (townba) [reply xds/internal/balancer/clusterimpl/clusterimpl.go:378]: Done.

**Review by dfawley — APPROVED** [review]

**Review by easwars — APPROVED** [review]
