### PR TITLE
Fix settings ack race

### LINKED ISSUE #1626: Race in applying settings and acking
The way it works right now, we aren't applying any settings until right as we send the ack. This can result in a race:

1. Server and client are in steady state with maximum streams = 5
2. Client receives a settings frame with a limit of 1. It appends the ack to the control buffer in response.
3. Client initiates 5 new streams and pushes their headers onto the control buffer, which it thinks is fine because the settings are not applied yet.
4. Client applies settings and sends settings ack, promising not to initiate more than one stream.
5. Client sends headers for 5 new streams.

We need to make sure settings are applied before queuing the ack message if the settings are more restrictive than they were before. On the other hand, we should queue the ack message and then apply the settings if they are more permissive.

### PR DESCRIPTION
**Pull request by MakMukhi**
fixes #1626 #1564

### CODE REVIEW

File: transport/http2_client.go [hunk 1]
```diff
@@ -1258,12 +1286,15 @@ func (t *http2Client) itemHandler(i item) error {
...
+		err = t.framer.fr.WriteSettings(i.ss...)
+	case *settingsAck:
+		if i.rs == nil && i.ps == nil {
 			err = t.framer.fr.WriteSettingsAck()
-		} else {
-			err = t.framer.fr.WriteSettings(i.ss...)
+			break
 		}
+		t.applySettings(i.rs)
+		t.controlBuf.put(&settingsAck{})
```
Comment (dfawley) [inline transport/http2_client.go]: Why not apply settings before enqueuing the ack the first time?

This results in more delay in processing the ack (it has to make it through the control buffer twice), and it splits up the code that handles settings, which makes it harder to reason about.

If there's some reason we have to do it this way, that's fine but we should put comments in to explain it.

Comment (MakMukhi) [reply transport/http2_client.go]: I was in fact thinking about that last night. The code sort of evolved to be this way and you're right it makes more sense to apply the settings in the settings handler itself.

File: transport/http2_client.go [hunk 2]
```diff
@@ -922,26 +921,51 @@ func (t *http2Client) handleSettings(f *http2.SettingsFrame, isFirst bool) {
...
+	switch s.ID {
+	case http2.SettingMaxConcurrentStreams:
+		t.mu.Lock()
+		if int(s.Val) < t.maxStreams {
+			res = true
+		}
+		t.mu.Unlock()
+	case http2.SettingInitialWindowSize:
+		t.mu.Lock()
+		if s.Val < t.streamSendQuota {
```
Comment (dfawley) [inline transport/http2_client.go]: Shouldn't we be comparing this to `t.initialWindowSize`?

Also, do we have to take a lock for this field or `t.maxStreams`?  I was thinking the only thing that should be changing these fields is the handling of a settings frame (so, this code here)...

Comment (MakMukhi) [reply transport/http2_client.go]: `t.initialWindowSize` controls our inbound window size while `t.streamSendQuota` controls our outbound window size. So, when we get a settings frame to update our initial window size( the outbound one) we update this variable.

You're right about `t.maxStreams`; updating it never required a lock. I copied the original code and made the same mistake!

File: transport/http2_client.go [hunk 3]
```diff
@@ -922,26 +921,48 @@ func (t *http2Client) handleSettings(f *http2.SettingsFrame, isFirst bool) {
...
-	t.controlBuf.put(&settings{ack: true, ss: ss})
+	t.applySettings(rs)
+	t.controlBuf.put(&settingsAck{})
+	t.applySettings(ps)
+}
+
+func (t *http2Client) isRestrictive(s http2.Setting) bool {
+	switch s.ID {
+	case http2.SettingMaxConcurrentStreams:
+		if int(s.Val) < t.maxStreams {
```
Comment (dfawley) [inline transport/http2_client.go]: Optional (but recommended): `return int(s.Val) < t.maxStreams`

File: transport/http2_client.go [hunk 4]
```diff
@@ -922,26 +921,48 @@ func (t *http2Client) handleSettings(f *http2.SettingsFrame, isFirst bool) {
...
 		}
-		ss = append(ss, s)
+		if t.isRestrictive(s) {
+			rs = append(rs, s)
+		} else {
+			ps = append(ps, s)
+		}
 		return nil
 	})
 	if isFirst && isMaxConcurrentStreamsMissing {
```
Comment (dfawley) [inline transport/http2_client.go]: Optional, maybe for a later refactor:

The code might be cleaner with two implementations: `handleSettings` and `handleInitialSettings`.  `handleInitialSettings` doesn't need to check restrictive/permissive -- just apply all the settings and write the ack.  Then the special-case code checking for max concurrent streams is removed from the ongoing `handleSettings` function.

Comment (MakMukhi) [reply transport/http2_client.go]: The same logic, acking after applying restrictive settings and before applying permissive settings, holds for handleInitialSettings. The client doesn't wait for the server to send initial settings before starting streams. 
We'll still need to check if `http2.SettingMaxConcurrentStreams` is present or not in the initial settings. So we will only be able to save one conditional check by creating this other function.
