### PR TITLE
rpc_util: Fix `RecvBufferPool` deactivation issues

### LINKED ISSUE #6578: For unary methods, received messages are put into buffer from the pool, but buffer is never returned back to pool.
### What version of gRPC are you using?
1.57.0

### What version of Go are you using (`go version`)?
1.20.6

### What operating system (Linux, Windows, …) and version?
MacOS

### What did you do?
added buffer pool support and I expect that the number of allocations in the application will decrease

### What did you expect to see?
I expect to see a decrease in allocations to the query (processUnaryRPC -> recvAndDecompress -> recvMsg)

### What did you see instead?
after adding the buffer pool, the number of allocations has not changed (objects are not returned to the pool anywhere else, but they are always taken from it 616 line figure 2)

#### figure 1:
image

#### figure 2:
image

### PR DESCRIPTION
**Pull request by hueypark**
Fixes #6578

- Resolved unintended deactivation scenarios:
  - During unary RPC calls.
  - When compression is enabled.

- Also corrected missing `payInfo.uncompressedBytes` in `Server.processUnaryRPC`.

RELEASE NOTES:

- rpc_util: The `RecvBufferPool` option is now active during unary RPC and in compression is enabled.
- stats: The stats handler now accurately tracks `uncompressedBytes` during unary RPC calls.

### CODE REVIEW

**Comment by hueypark** [comment]
This PR will fix https://github.com/grpc/grpc-go/issues/6578.

**Review by dfawley — APPROVED** [review]

File: experimental/shared_buffer_pool_test.go [hunk 1]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
+					ctx,
+					&testgrpc.SimpleRequest{
+						Payload: &testgrpc.Payload{
+							Body: make([]byte, largeSize),
+						},
+					},
+					tc.callOpts...,
+				)
+				if err != nil {
+					t.Fatalf("ss.Client.UnaryCall failed: %f", err)
```
Comment (zasweq) [inline experimental/shared_buffer_pool_test.go:186]: Nit: here and above/elsewhere, prefer %v to %f.

File: experimental/shared_buffer_pool_test.go [hunk 2]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
+				}
+			}
+
+			const bufferCount = reqCount * 2 // req + resp
+			if len(pool.puts) != bufferCount {
+				t.Fatalf("Expected 10 buffers to be returned to the pool, got %d", len(pool.puts))
```
Comment (zasweq) [inline experimental/shared_buffer_pool_test.go:192]: bufferCount is 20. Should this say 20?

File: experimental/shared_buffer_pool_test.go [hunk 3]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
-		}
-		buf.Write(reply.GetPayload().GetBody())
-	}
-	if want := 10; ngot != want {
-		t.Errorf("Got %d replies, want %d", ngot, want)
-	}
-	if got, want := buf.String(), "0,1,2,3,4,5,6,7,8,9"; got != want {
-		t.Errorf("Got replies %q; want %q", got, want)
+			pool := &checkBufferPool{}
+
```
Comment (zasweq) [inline experimental/shared_buffer_pool_test.go:163]: Nit: Drop newline here too

File: rpc_util.go [hunk 4]
```diff
@@ -778,6 +794,8 @@ func decompress(compressor encoding.Compressor, d []byte, maxReceiveMessageSize
 			// size is used as an estimate to size the buffer, but we
 			// will read more data if available.
 			// +MinRead so ReadFrom will not reallocate if size is correct.
+			//
+			// TODO: If we ensure that the buffer size is the same as the DecompressedSize, we can also utilize the recv buffer pool here.
```
Comment (zasweq) [inline rpc_util.go:798]: Super minor nit: please wrap this comment to 80 chars.

**Review by zasweq — CHANGES_REQUESTED** [review]
Thanks for the contribution, overall this LGTM, super minor style nits.

**Review by zasweq — APPROVED** [review]

File: experimental/shared_buffer_pool_test.go (hunk 2 above)
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go:188]: Yes, and it's exactly twice the reqCount.

File: experimental/shared_buffer_pool_test.go [hunk 5]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
+					for i := 0; i < reqCount; i++ {
+						preparedMsg := &grpc.PreparedMsg{}
+						err := preparedMsg.Encode(stream, &testgrpc.StreamingOutputCallResponse{
+							Payload: &testgrpc.Payload{
+								Body: []byte{'0' + uint8(i)},
+							},
+						})
+						if err != nil {
+							return err
+						}
```
[the remark this answers is not in the document]
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: experimental/shared_buffer_pool_test.go [hunk 6]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
+						stream.SendMsg(preparedMsg)
+					}
+					return nil
+				},
+			}
+
+			pool := &checkBufferPool{}
+
```
[the remark this answers is not in the document]
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: experimental/shared_buffer_pool_test.go [hunk 7]
```diff
@@ -44,59 +44,165 @@ func Test(t *testing.T) {
...
+				_, err := ss.Client.UnaryCall(
+					ctx,
+					&testgrpc.SimpleRequest{
+						Payload: &testgrpc.Payload{
+							Body: make([]byte, largeSize),
+						},
+					},
+					tc.callOpts...,
+				)
+				if err != nil {
```
[the remark this answers is not in the document]
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: experimental/shared_buffer_pool_test.go (hunk 1 above)
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: experimental/shared_buffer_pool_test.go (hunk 3 above)
Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: rpc_util.go (hunk 4 above)
Comment (hueypark) [reply rpc_util.go]: Done. 4282fd5419fcaad11ceeb52586eabe98fd887e67

File: experimental/shared_buffer_pool_test.go (hunk 2 above)
Comment (zasweq) [reply experimental/shared_buffer_pool_test.go:188]: Right, but the error message says 10 :). Switch to 20?

Comment (zasweq) [reply experimental/shared_buffer_pool_test.go:188]: Last one before merging :)

Comment (hueypark) [reply experimental/shared_buffer_pool_test.go]: > Right, but the error message says 10 :). Switch to 20?

Got it! 389c89e7d21e1d43c14e034d0492799a23fca2d6

Comment (zasweq) [reply experimental/shared_buffer_pool_test.go]: Thanks :)!
