### PR TITLE
test: fix GoAwayThenClose by wait for cc state change

### LINKED ISSUE #2822: unflake TestGoAwayThenClose
On `upstream/master` branch, run this:
```
go test -race -count 10000 ./test -run 'Test/GoAwayThenClose'
```
You may get this:
```
end2end_test.go:7169: UnaryCall(_) = _, rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:40911: connect: connection refused"; want _, nil
```

### PR DESCRIPTION
**Pull request by menghanl**
In the end of the test, 10 RPCs are made to make sure data is sent to
the second server. The first RPC of these 10 is made right after the
second server's listener receives a connection. But at this time, the
connectivity state on the client side is not set to READY yet (though
ac's state should be either connecting or ready, the race between ac
and balancer could cause cc to still be in transient failure). So the
first RPC fails due to transient failure, but the following 9 will
succeed.

fixes #2822

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -7165,7 +7165,7 @@ func (s) TestGoAwayThenClose(t *testing.T) {
 
 	// Do a bunch of RPCs, make sure it stays stable. These should go to connection 2.
```
Comment (dfawley) [inline test/end2end_test.go]: `cc.WaitForStateChange(ctx, connectivity.TransientFailure)` then use fail-fast RPCs.

Comment (menghanl) [reply test/end2end_test.go]: done
