### PR TITLE
fix TestServerCredsDispatch

### LINKED ISSUE #1552: Flaky test: TestServerCredsDispatch
<details><summary>Log data</summary><p>

```
=== RUN   TestServerCredsDispatch
==================
WARNING: DATA RACE
Write by goroutine 177:
  google.golang.org/grpc/test.(*serverDispatchCred).ServerHandshake()
      /home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:4161 +0x5b
  google.golang.org/grpc.(*Server).useTransportAuthenticator()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:431 +0x128
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:502 +0x5a

Previous write by goroutine 183:
  google.golang.org/grpc/test.(*serverDispatchCred).ServerHandshake()
      /home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:4161 +0x5b
  google.golang.org/grpc.(*Server).useTransportAuthenticator()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:431 +0x128
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:502 +0x5a

Goroutine 177 (running) created at:
  google.golang.org/grpc.(*Server).Serve()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:495 +0x8a7

Goroutine 183 (finished) created at:
  google.golang.org/grpc.(*Server).Serve()
      /home/travis/gopath/src/google.golang.org/grpc/server.go:495 +0x8a7

==================

panic: close of closed channel

goroutine 34954 [running]:
panic(0xab88c0, 0xc820230650)
	/home/travis/.gimme/versions/go1.6.4.linux.amd64/src/runtime/panic.go:481 +0x3ff
google.golang.org/grpc/test.(*serverDispatchCred).ServerHandshake(0xc820358700, 0x2adc57acb998, 0xc8203aa0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/test/end2end_test.go:4162 +0x9b
google.golang.org/grpc.(*Server).useTransportAuthenticator(0xc8202652c0, 0x2adc57acb998, 0xc8203aa0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:431 +0x129
google.golang.org/grpc.(*Server).handleRawConn(0xc8202652c0, 0x2adc57acb998, 0xc8203aa0a0)
	/home/travis/gopath/src/google.golang.org/grpc/server.go:502 +0x5b
created by google.golang.org/grpc.(*Server).Serve
	/home/travis/gopath/src/google.golang.org/grpc/server.go:495 +0x8a8
FAIL
```
</details>

### PR DESCRIPTION
**Pull request by menghanl**
fixes #1552

### CODE REVIEW

File: test/end2end_test.go [hunk 1]
```diff
@@ -4192,8 +4192,10 @@ func TestServerCredsDispatch(t *testing.T) {
 	}
 	defer cc.Close()
 
+	rawConn := cred.getRawConn()
+	time.Sleep(100 * time.Millisecond)
```
Comment (dfawley) [inline test/end2end_test.go]: Why 100ms?  Sleeps make me nervous.

Comment (menghanl) [reply test/end2end_test.go]: In the normal cases, when `handshake` returns an error, `rawConn` gets closed.
In this test, `handshake` returns a special error, which tells gRPC to not close the connection.
This is to sleep and wait for gRPC to see the error, and then test if the connection was closed.
`100ms` is picked randomly...

Comment (dfawley) [reply test/end2end_test.go]: :disappointed: OK.  Maybe a comment here that says "give grpc a chance to see the error and potentially close the connection"?
