### PR TITLE
xds/ringhash: make reconnection logic work for a single subConn

### LINKED ISSUE #5594: XDS - client connection failure and retries
### What did you do?
My setup details:
Istio-XDS with Traffic policy - Load balancer with consistent hash to route to server.
Client and Server running as separate pods on k8s cluster.

Issue:
1. Server side does xds.NewGRPCServer()
2. Client side connects using URI - xds:///chatservice:<port>
3. Client and server are able to exchange messages.
4. Server is terminated manually.
5. Client side loses the connection and retries once, but that attempt fails and then it never retries again. 
6. Server side is restarted and now available. 
7. Client side does not retry and never connects.
8. If Client calls Dial again, then it is able to reconnect. But not automatically. 
9. It is observed that if I turn off XDS, the GRPC client is able to reconnect automatically to the server. 

Am I missing any configuration which would let client retry ?  Without any configuration, when XDS is disabled, plain GRPC client does retry on its own and gets connected again successfully. 

Thanks.
 -kartik.

Logs of client side for reference:
2022/08/17 12:04:38 INFO: [core] [Channel #1 SubChannel #5] Subchannel Connectivity change to IDLE

2022/08/17 12:04:38 INFO: [transport] transport: loopyWriter.run returning. connection error: desc = "transport is closing"

2022/08/17 12:04:38 INFO: [xds] [ring-hash-lb 0xc000839880] handle SubConn state change: 0xc00007fb20, IDLE

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] Balancer state update from locality priority-0-0, new state: {ConnectivityState:IDLE Picker:0xc000840960}

2022/08/17 12:04:38 WARNING: [xds] ciu, cn, cu: priority-0-0, priority-0-0, priority-0-0

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Balancer state update from locality cluster:outbound|16000||chatservice.default.svc.cluster.local, new state: {Connec

tivityState:IDLE Picker:0xc000840960}

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Child pickers: map[cluster:outbound|16000||chatservice.default.svc.cluster.local:picker:0xc000840960,state:IDLE,state

ToAggregate:IDLE]

2022/08/17 12:04:38 INFO: [core] [Channel #1] Channel Connectivity change to IDLE

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] switching to ("priority-0-0", 0) in syncPriority

2022/08/17 12:04:38 Send -  Msg-3

2022/08/17 12:04:38 INFO: [core] [Channel #1 SubChannel #5] Subchannel Connectivity change to CONNECTING

2022/08/17 12:04:38 INFO: [core] [Channel #1 SubChannel #5] Subchannel picks a new address "[172.20.0.170:16000](http://172.20.0.170:16000/)" to connect

2022/08/17 12:04:38 INFO: [xds] [ring-hash-lb 0xc000839880] handle SubConn state change: 0xc00007fb20, CONNECTING

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] Balancer state update from locality priority-0-0, new state: {ConnectivityState:CONNECTING Picker:0xc00004f1d0}

2022/08/17 12:04:38 WARNING: [xds] ciu, cn, cu: priority-0-0, priority-0-0, priority-0-0

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Balancer state update from locality cluster:outbound|16000||chatservice.default.svc.cluster.local, new state: {ConnectivityState:CONNECTING Picker:0xc00004f1d0}

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Child pickers: map[cluster:outbound|16000||chatservice.default.svc.cluster.local:picker:0xc00004f1d0,state:CONNECTING,stateToAggregate:CONNECTING]

2022/08/17 12:04:38 INFO: [core] [Channel #1] Channel Connectivity change to CONNECTING

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] switching to ("priority-0-0", 0) in syncPriority

2022/08/17 12:04:38 WARNING: [core] [Channel #1 SubChannel #5] grpc: addrConn.createTransport failed to connect to {

  "Addr": "[172.20.0.170:16000](http://172.20.0.170:16000/)",

  "ServerName": "chatservice:16000",

  "Attributes": {},

  "BalancerAttributes": {},

  "Type": 0,

  "Metadata": null

}. Err: connection error: desc = "transport: Error while dialing dial tcp [172.20.0.170:16000](http://172.20.0.170:16000/): connect: connection refused"

2022/08/17 12:04:38 INFO: [core] [Channel #1 SubChannel #5] Subchannel Connectivity change to TRANSIENT_FAILURE

2022/08/17 12:04:38 INFO: [xds] [ring-hash-lb 0xc000839880] handle SubConn state change: 0xc00007fb20, TRANSIENT_FAILURE

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] Balancer state update from locality priority-0-0, new state: {ConnectivityState:TRANSIENT_FAILURE Picker:0xc00004f3b0}

2022/08/17 12:04:38 WARNING: [xds] ciu, cn, cu: priority-0-0, priority-0-0, priority-0-0

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Balancer state update from locality cluster:outbound|16000||chatservice.default.svc.cluster.local, new state: {ConnectivityState:TRANSIENT_FAILURE Picker:0xc00004f3b0}

2022/08/17 12:04:38 INFO: [xds] [xds-cluster-manager-lb 0xc0003efb00] Child pickers: map[cluster:outbound|16000||chatservice.default.svc.cluster.local:picker:0xc00004f3b0,state:TRANSIENT_FAILURE,stateToAggregate:TRANSIENT_FAILURE]

2022/08/17 12:04:38 INFO: [core] [Channel #1] Channel Connectivity change to TRANSIENT_FAILURE

2022/08/17 12:04:38 INFO: [xds] [priority-lb 0xc000495490] switching to ("priority-0-0", 0) in syncPriority

2022/08/17 12:04:38 Error when calling SayHello: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp [172.20.0.170:16000](http://172.20.0.170:16000/): connect: connection refused"

2022/08/17 12:04:39 INFO: [core] [Channel #1 SubChannel #5] Subchannel Connectivity change to IDLE

2022/08/17 12:04:39 INFO: [xds] [ring-hash-lb 0xc000839880] handle SubConn state change: 0xc00007fb20, IDLE

### PR DESCRIPTION
**Pull request by easwars**
Summary of changes:
- Always send a picker update (even if the ring hasn't changed) when the LB policy receives a subConn update. 
  - Earlier, we were only sending a picker update when the effective state of the subConn changed. Current change helps with re-queueing RPCs in cases where:
    - there is a single subConn, and/or
    - subConn move from TRANSIENT_FAILURE to a non READY state.
- Regenerate the picker when the subConn moves to READY. This is required when the aggregate state of the channel is changing from TRANSIENT_FAILURE to READY, and we need to overwrite the earlier error picker that we had pushed.
- Ensure that the LB policy is attempting to reconnect (when the aggregate state of the channel is TRANSIENT_FAILURE), even if there is a single subConn.

Fixes #5594

RELEASE NOTES:
- xds/ringhash: fix a bug which sometimes prevents the LB policy from retrying connection attempts

### CODE REVIEW

**Comment by dfawley** [comment]
> Always send a picker update

On the other hand, this will cause RPC churn if the effective state of the ring hash hasn't changed as a result of the subconn state change.  I.e. if the transition is from TF to IDLE, we can kick the subconn into CONNECTING (presumably that's the right thing to do) but not produce a new picker, because sticky-TF means that nothing has changed.  If it doesn't add too much complexity to the code and isn't too much work, it would be nice to suppress updates where we know they are unnecessary.

File: xds/internal/balancer/ringhash/ringhash.go [hunk 1]
```diff
@@ -161,11 +163,13 @@ func (sc *subConn) queueConnect() {
 	defer sc.mu.Unlock()
 	sc.attemptingToConnect = true
 	if sc.state == connectivity.Idle {
+		sc.logger.Infof("Executing a queued connect for subConn in state: %v", sc.state)
```
Comment (dfawley) [inline xds/internal/balancer/ringhash/ringhash.go:166]: Logging the exact same text here could make it hard to distinguish which operation is occurring.  Did we just queue the connect attempt, or was it queued when the subconn went IDLE?  Maybe this distinction is unimportant?

File: xds/internal/balancer/ringhash/ringhash.go [hunk 2]
```diff
@@ -216,10 +220,11 @@ func (b *ringhashBalancer) updateAddresses(addrs []resolver.Address) bool {
 		if val, ok := b.subConns.Get(addr); !ok {
 			sc, err := b.cc.NewSubConn([]resolver.Address{addr}, balancer.NewSubConnOptions{HealthCheckEnabled: true})
 			if err != nil {
-				logger.Warningf("base.baseBalancer: failed to create new SubConn: %v", err)
+				b.logger.Warningf("Failed to create new SubConn: %v", err)
```
Comment (dfawley) [inline xds/internal/balancer/ringhash/ringhash.go:223]: Given that the logger is adding a prefix, isn't it inappropriate to capitalize this on the same grounds as not capitalizing error strings?

File: xds/internal/balancer/ringhash/ringhash.go [hunk 3]
```diff
@@ -328,49 +333,37 @@ func (b *ringhashBalancer) ResolverError(err error) {
 //   for some RPCs.
 func (b *ringhashBalancer) UpdateSubConnState(sc balancer.SubConn, state balancer.SubConnState) {
 	s := state.ConnectivityState
-	b.logger.Infof("handle SubConn state change: %p, %v", sc, s)
+	b.logger.Infof("Handle SubConn state change: %p, %v", sc, s)
```
Comment (dfawley) [inline xds/internal/balancer/ringhash/ringhash.go:336]: Hide this behind a verbosity check?  This seems unnecessarily chatty for most debugging.  (And below)

File: xds/internal/balancer/ringhash/ringhash.go [hunk 4]
```diff
@@ -328,49 +333,37 @@ func (b *ringhashBalancer) ResolverError(err error) {
...
-		sendUpdate = true
-	}
 
 	switch s {
-	case connectivity.Idle:
-		// No need to send an update. No queued RPC can be unblocked. If the
-		// overall state changed because of this, sendUpdate is already true.
-	case connectivity.Connecting:
-		// No need to send an update. No queued RPC can be unblocked. If the
-		// overall state changed because of this, sendUpdate is already true.
```
Comment (dfawley) [inline xds/internal/balancer/ringhash/ringhash.go:354]: Can you explain the scenario where not sending an update in these cases was wrong?

Comment (easwars) [reply xds/internal/balancer/ringhash/ringhash.go]: Undid these changes after an offline discussion.

**Comment by easwars** [comment]
> > Always send a picker update
> 
> On the other hand, this will cause RPC churn if the effective state of the ring hash hasn't changed as a result of the subconn state change. I.e. if the transition is from TF to IDLE, we can kick the subconn into CONNECTING (presumably that's the right thing to do) but not produce a new picker, because sticky-TF means that nothing has changed. If it doesn't add too much complexity to the code and isn't too much work, it would be nice to suppress updates where we know they are unnecessary.

Undid these changes after an offline discussion.

**Review by easwars — COMMENTED** [review]
Thanks for the review.

File: xds/internal/balancer/ringhash/ringhash.go (hunk 2 above)
Comment (dfawley) [reply xds/internal/balancer/ringhash/ringhash.go:223]: Yes, it's probably best to capitalize if the prefix isn't "blah blah:".

**Review by dfawley — APPROVED** [review]

File: xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+
+	// Stopping the server listener will close the transport on the client,
+	// which will lead to the channel eventually moving to IDLE. The ring_hash
+	// LB policy is not expected to reconnect by itself at this point.
+	lis.Stop()
+	for ; ctx.Err() == nil; <-time.After(defaultTestShortTimeout) {
+		if cc.GetState() == connectivity.Idle {
+			break
+		}
+	}
```
[the remark this answers is not in the document]
Comment (easwars) [reply xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go]: Done.
