### PR TITLE
xds/googlec2p: remove legacy `SetFallbackBootstrapConfig` and fix tests.

### LINKED ISSUE #8661: xds/googlec2p: cleanup in googlec2p resolver.
The xdsclient package contains legacy support for a "fallback" bootstrap configuration, which was originally used by the googlec2p resolver via `SetFallbackBootstrapConfig`.
This global fallback mechanism has been superseded by the changes in PR #8648. The googlec2p resolver now uses this new, explicit approach to create a xdsClient in googlec2p resolver.

To simplify the API and prevent confusion, the legacy fallback logic should be removed.
- Deprecate and remove the exported `xdsclient.SetFallbackBootstrapConfig` function.
- Remove the internal `fallbackConfig` field from the `xdsclient.Pool` and all associated logic that applies it during client creation.

### PR DESCRIPTION
**Pull request by Pranjali-2501**
Fixes #8661 

This PR removes the deprecated `SetFallbackBootstrapConfig` API and the internal `fallbackConfig` field from `xdsclient.Pool`. This cleanup follows PR #8648 which introduced channel-specific bootstrap configuration, rendering the global fallback mechanism obsolete.

RELEASE NOTES: N/A

### CODE REVIEW

File: internal/xds/xdsclient/pool.go [hunk 1]
```diff
@@ -47,9 +47,8 @@ type Pool struct {
 	// Note that mu should ideally only have to guard clients. But here, we need
 	// it to guard config as well since SetFallbackBootstrapConfig writes to
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Here and elsewhere in comments, please get rid of references to `SetFallbackBootstrapConfig`

File: internal/xds/xdsclient/pool.go [hunk 2]
```diff
@@ -47,9 +47,8 @@ type Pool struct {
...
 	// config.
-	mu             sync.Mutex
-	clients        map[string]*clientImpl
-	fallbackConfig *bootstrap.Config // TODO(i/8661): remove fallbackConfig.
+	mu      sync.Mutex
+	clients map[string]*clientImpl
 	// getConfiguration is a sync.OnceValues that attempts to read the bootstrap
 	// configuration from environment variables once.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: While you are here, can you please update this comment as well. 

It is not necessary that this func attempts to read the configuration from the environment variables. That happens only when this is set to `bootstrap.GetConfiguration` as in the case of the `DefaultPool`. If a `Pool` is created that specifies a config, then there is no attempt to read from environment variables.

File: internal/xds/xdsclient/pool.go
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: This comment needs to be updated to say that if a `nil` config is passed, then the caller is expected to pass the config when creating the xDS client by using `NewClientWithConfig` instead of `NewClient`. If they specify a `nil` config and use `NewClient`, client creation will fail.

Comment (easwars) [inline internal/xds/xdsclient/pool.go]: While you are here, please fix the docstring for this to indicate that the `config` passed to this function take precedence over any config passed during pool creation.

Comment (easwars) [reply internal/xds/xdsclient/pool.go]: It looks like this docstring is simply a copy of the docstring for `NewClient`. We need to indicate when it makes sense to use this over `NewClient`.

File: internal/xds/xdsclient/pool.go [hunk 3]
```diff
@@ -215,7 +204,7 @@ func (p *Pool) BootstrapConfigForTesting() *bootstrap.Config {
 	if cfg != nil {
 		return cfg
 	}
-	return p.fallbackConfig
+	return nil
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Can this simply be:

```golang
	cfg, _ := p.getConfiguration()
    return cfg
```

File: internal/xds/xdsclient/pool.go
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Can we ensure that this function is never called with a `nil` config?

Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Then we need to move the logic to fetch the config set by env variable in NewClient function.
Do you want me to make those changes?

File: internal/xds/xdsclient/pool.go (hunk 3 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 2 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 1 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go [hunk 4]
```diff
@@ -44,14 +44,13 @@ var (
 // Pool represents a pool of xDS clients that share the same bootstrap
 // configuration.
 type Pool struct {
-	// Note that mu should ideally only have to guard clients. But here, we need
-	// it to guard config as well since SetFallbackBootstrapConfig writes to
-	// config.
-	mu             sync.Mutex
-	clients        map[string]*clientImpl
-	fallbackConfig *bootstrap.Config // TODO(i/8661): remove fallbackConfig.
+	// clients will be protected by mu.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: `mu` has to guard `getConfiguration` as well since we support resetting the configuration for testing purposes. So, you might as well get rid of this comment, or say that it guards all the fields.

File: internal/xds/xdsclient/pool.go
Comment (easwars) [reply internal/xds/xdsclient/pool.go]: Yes please.

Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: I have made the changes.
But now it first loads the config from env variable and then check whether the xdsClient with same name exists or not.

File: internal/xds/xdsclient/pool.go (hunk 4 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go [hunk 5]
```diff
@@ -96,31 +94,62 @@ func NewPool(config *bootstrap.Config) *Pool {
 	}
 }
 
-// NewClientWithConfig returns an xDS client with the given name from the pool. If the
-// client doesn't already exist, it creates a new xDS client and adds it to the
-// pool.
+// getBootstrapConfiguration returns the bootstrap configuration loaded from
+// the environment variables.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: It is *not* necessary that this loads configuration from env vars, right? If the pool was created with config (as every non-default pool is), then this method simply returns that configuration.

So, I would simply say
// getBootstrapConfiguration returns the config specified at pool creation time.

File: internal/xds/xdsclient/pool.go [hunk 6]
```diff
@@ -96,31 +94,62 @@ func NewPool(config *bootstrap.Config) *Pool {
...
+func (p *Pool) getBootstrapConfiguration() (*bootstrap.Config, error) {
+	p.mu.Lock()
+	defer p.mu.Unlock()
+	config, err := p.getConfiguration()
+	if err != nil {
+		return nil, fmt.Errorf("xds: failed to read xDS bootstrap config from env vars:  %v", err)
+	}
+	if config == nil {
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: I don't see a need for `bootstrap.GetConfiguration` to return `(nil, nil)` if none of the env vars are set. It can instead return an error indicating that none of expected env vars were set. That will simplify the handling here. We wont have to handle the `nil, nil` case specifically.

File: internal/xds/xdsclient/pool.go [hunk 7]
```diff
@@ -96,31 +94,62 @@ func NewPool(config *bootstrap.Config) *Pool {
...
-// client doesn't already exist, it creates a new xDS client and adds it to the
-// pool.
+// getBootstrapConfiguration returns the bootstrap configuration loaded from
+// the environment variables.
+func (p *Pool) getBootstrapConfiguration() (*bootstrap.Config, error) {
+	p.mu.Lock()
+	defer p.mu.Unlock()
+	config, err := p.getConfiguration()
+	if err != nil {
+		return nil, fmt.Errorf("xds: failed to read xDS bootstrap config from env vars:  %v", err)
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Again, here, please avoid the use of env vars, because there is no guarantee that we are reading from env vars here.

File: internal/xds/xdsclient/pool.go [hunk 8]
```diff
@@ -44,14 +44,13 @@ var (
 // Pool represents a pool of xDS clients that share the same bootstrap
 // configuration.
 type Pool struct {
-	// Note that mu should ideally only have to guard clients. But here, we need
-	// it to guard config as well since SetFallbackBootstrapConfig writes to
-	// config.
-	mu             sync.Mutex
-	clients        map[string]*clientImpl
-	fallbackConfig *bootstrap.Config // TODO(i/8661): remove fallbackConfig.
+	// mu guards the following.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Since `mu` guards everything, we may as well omit this comment.

File: internal/xds/xdsclient/pool.go [hunk 9]
```diff
@@ -96,31 +94,62 @@ func NewPool(config *bootstrap.Config) *Pool {
...
+// non-default config is required. If the provided config is nil, it attempts
+// to load the configuration from the environment variables.
 //
 // The second return value represents a close function which the caller is
 // expected to invoke once they are done using the client.  It is safe for the
 // caller to invoke this close function multiple times.
 func (p *Pool) NewClientWithConfig(name string, metricsRecorder estats.MetricsRecorder, config *bootstrap.Config) (XDSClient, func(), error) {
+	if config == nil {
+		var err error
+		config, err = p.getBootstrapConfiguration()
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: This and the similar code down below don't handle the case where `p.getBootstrapConfiguration()` could return `nil, nil`, which is exactly why I think it makes sense to change `bootstrap.GetConfiguration` to return an error in that case instead.

File: internal/xds/xdsclient/pool.go [hunk 10]
```diff
@@ -142,7 +171,17 @@ func (p *Pool) NewClientForTesting(opts OptionsForTesting) (XDSClient, func(), e
...
-	c, cancel, err := p.newRefCounted(opts.Name, opts.MetricsRecorder, opts.WatchExpiryTimeout, opts.Config)
+
+	config := opts.Config
+	if config == nil {
+		var err error
+		config, err = p.getBootstrapConfiguration()
+		if err != nil {
+			return nil, nil, err
+		}
+	}
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Code like this is repeated three times. I don't know if there is a good way to create a small function/method that could be shared. I wouldn't try spending too much time on it, but if you can think of something nice in a short amount of time, go for it.

File: internal/xds/xdsclient/pool.go [hunk 11]
```diff
@@ -268,32 +293,17 @@ func (p *Pool) clientRefCountedClose(name string) {
...
-		if err != nil {
-			return nil, nil, fmt.Errorf("xds: failed to read xDS bootstrap config from env vars:  %v", err)
-		}
-		if config == nil {
-			// If the environment variables are not set, then fallback bootstrap
-			// configuration should be set before attempting to create an xDS client,
-			// else xDS client creation will fail.
-			config = p.fallbackConfig
-		}
+		return nil, nil, fmt.Errorf("xds: bootstrap config cannot be nil")
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: I thought the whole point was to ensure that this is never called with a `nil` config and therefore not handle the `nil` case here at all. You could mention this in the docstring as well.

File: internal/xds/xdsclient/pool.go (hunk 5 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 6 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: I have modified `bootstrap.GetConfiguration` to return error if none of the env variables are set. Also modified the `NewPool` API.

File: internal/xds/xdsclient/pool.go (hunk 7 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 8 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 9 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Done.

File: internal/xds/xdsclient/pool.go (hunk 10 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Added a  small function to get rid of `config==nil` checks.

File: internal/xds/xdsclient/pool.go (hunk 11 above)
Comment (Pranjali-2501) [reply internal/xds/xdsclient/pool.go]: Right, remove this check.

File: internal/xds/bootstrap/bootstrap_test.go [hunk 12]
```diff
@@ -897,10 +896,12 @@ func (s) TestGetConfiguration_CertificateProviders(t *testing.T) {
 
 			name:       "allUnknownCertProviders",
 			wantConfig: configWithGoogleDefaultCredsAndV3,
+			wantErr:    false,
```
Comment (easwars) [inline internal/xds/bootstrap/bootstrap_test.go]: Any specific reason for adding `wantErr: false` here and in the next sub-test? The default value for `bool` is `false` and it is common practice to not specify fields that are to contain their zero values (unless it improves readability).

File: internal/xds/xdsclient/pool.go [hunk 13]
```diff
@@ -82,45 +79,80 @@ type OptionsForTesting struct {
...
+		return nil, nil, err
+	}
 	return p.newRefCounted(name, metricsRecorder, defaultWatchExpiryTimeout, config)
 }
 
 // NewClient returns an xDS client with the given name from the pool. If the
-// client doesn't already exist, it creates a new xDS client and adds it to the
-// pool.
+// client doesn't already exist, it loads the configuration from the
+// environment variables, creates a new xDS client and adds it to the pool.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: Again, this *need not* load from environment variables. It *could* simply use the configuration provided at pool creation time. The only time configuration is loaded from env vars is for the default pool.

File: internal/xds/xdsclient/pool.go [hunk 14]
```diff
@@ -82,45 +79,80 @@ type OptionsForTesting struct {
...
+		return nil, nil, err
+	}
+	return p.newRefCounted(name, metricsRecorder, defaultWatchExpiryTimeout, config)
 }
 
 // NewClientForTesting returns an xDS client configured with the provided
 // options from the pool. If the client doesn't already exist, it creates a new
 // xDS client and adds it to the pool.
+// If the config in options is nil, it attempts to load the configuration from
+// the environment variables.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go]: And here too.

File: internal/xds/xdsclient/pool.go [hunk 15]
```diff
@@ -82,45 +79,80 @@ type OptionsForTesting struct {
...
+	config, err := p.getConfig(nil)
+	if err != nil {
+		return nil, nil, err
+	}
+	return p.newRefCounted(name, metricsRecorder, defaultWatchExpiryTimeout, config)
 }
 
 // NewClientForTesting returns an xDS client configured with the provided
 // options from the pool. If the client doesn't already exist, it creates a new
 // xDS client and adds it to the pool.
```
Comment (easwars) [inline internal/xds/xdsclient/pool.go:153]: Nit: Please add a newline to separate the paragraphs.
