### PR TITLE
server: handle context errors returned by service handler

### LINKED ISSUE #5155: Server sometimes returns "rpc error: code = Unknown" instead of "code = codees.DeadlineExceeded"
### What version of gRPC are you using?

Tested on 1.41.0 and master commit f93e8e6737.

### What version of Go are you using (`go version`)?

1.17.2

### What operating system (Linux, Windows, …) and version?

Linux, Ubuntu 20.04 LTS

### What did you do?

I discovered a flaky unit test in a private code base. The test performs the following steps:

1. Starts a GRPC Server.
2. Initializes a GRPC Client that connects to this server.
3. Client calls a method with `ctx, _ = context.WithTimeout(context.Background(), 50 * time.Millisecond)`. This method returns a `stream`.
4.  Client keeps calling `stream.Recv` in a loop until it receives an error.

### What did you expect to see?

In >99% of the cases we can successfully assert that `status.Code(err) == codes.DeadlineExceeded`.

The error string is: `rpc error: code = DeadlineExceeded desc = context deadline exceeded`.

### What did you see instead?

In <1% of the cases we see `status.Code(err)` is equal to `codes.Unknown`.

The error string is: `rpc error: code = Unknown desc = context deadline exceeded`.

---

It's very hard to reproduce this bug, I think it's because there are a few different places where the errors are handled concurrently, and it probably also depends on the Go's scheduler.

However, I believe I was able to track down the cause in the code. After I replace one single line I'm no longer able to reproduce this issue, even after over 1000 test runs:

```
diff --git a/server.go b/server.go
index eadf9e05..330154b2 100644
--- a/server.go
+++ b/server.go
@@ -1549,7 +1549,7 @@ func (s *Server) processStreamingRPC(t transport.ServerTransport, stream *transp
 	if appErr != nil {
 		appStatus, ok := status.FromError(appErr)
 		if !ok {
-			appStatus = status.New(codes.Unknown, appErr.Error())
+			appStatus, _ = status.FromError(toRPCErr(appErr))
 			appErr = appStatus.Err()
 		}
 		if trInfo != nil {
```

https://github.com/grpc/grpc-go/blob/f93e8e673710b7765c8f29e78ba3b97c238e1de8/server.go#L1552

### PR DESCRIPTION
**Pull request by menghanl**
fixes #5155

RELEASE NOTES:
* server: convert context errors returned by service handlers to status with the correct status code (`Canceled` or `DeadlineExceeded`), instead of `Unknown`

### CODE REVIEW

File: test/server_test.go [hunk 1]
```diff
@@ -32,6 +32,41 @@ import (
...
+	if err := ss.Start(nil); err != nil {
+		t.Fatalf("Error starting endpoint server: %v", err)
+	}
+	defer ss.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+	_, err := ss.Client.EmptyCall(ctx, &testpb.Empty{})
+	if s, ok := status.FromError(err); !ok || s.Code() != codes.DeadlineExceeded {
+		t.Fatalf("ss.Client.EmptyCall(ctx, _) = _, %v; want _, <status with Code()=DeadlineExceeded>", err)
```
Comment (easwars) [inline test/server_test.go:56]: Can we avoid underscores in these error message. They make them really hard to read and add no value. I know this is the way many existing tests report errors, but do we need to continue doing it.

Comment (menghanl) [reply test/server_test.go:56]: Are you suggesting deleting `_,`?

Comment (easwars) [reply test/server_test.go]: Yes, thanks :)

Comment (dfawley) [reply test/server_test.go]: > add no value

I have to disagree on this a bit.  They show the parameter/return signature of the function being called accurately.  If a function accepts 3 values and returns 3, but you only show 1 or 2 of each of them, how do you know what the values represent?

If you want to remove them here then don't imply the function only returns one value.  Do something like this instead:

```
t.Fatalf("ss.Client.EmptyCall() got error %v; want status with Code()=DeadlineExceeded", err)
```

Comment (menghanl) [reply test/server_test.go]: Done

**Review by dfawley — COMMENTED** [review]
Please update the docstrings here:

https://github.com/grpc/grpc-go/blob/14c11384b76b67f7b1b32a5d18f865762634c0ae/stream.go#L48-L52

and here:

https://github.com/grpc/grpc-go/blob/14c11384b76b67f7b1b32a5d18f865762634c0ae/interceptor.go#L74-L77

**Comment by menghanl** [comment]
Done

**Review by dfawley — APPROVED** [review]
