### PR TITLE
transport: Fix closing a closed channel panic in handlePing

### LINKED ISSUE #5786: Multiple GOAWAY frames on graceful shutdown leads to crash when Swift clients are connected
### What version of gRPC are you using?
`google.golang.org/grpc v1.50.1`

### What version of Go are you using (`go version`)?
`go 1.19`

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
NOTE: Copied from an issue for the swift client since we don't know what is the correct behaviour: https://github.com/grpc/grpc-swift/issues/1520

We use a server implemented with [grpc-go](https://github.com/grpc/grpc-go) This server may gracefully shutdown the connection before shutting down itself. In the repository of [grpc-go](https://github.com/grpc/grpc-go) it is documented that the server sends two GOAWAY frames to circumvent a http2 race condition:

'''
// A client can receive multiple GoAways from the server (see
// https://github.com/grpc/grpc-go/issues/1387). The idea is that the first
// GoAway will be sent with an ID of MaxInt32 and the second GoAway will be
// sent after an RTT delay with the ID of the last stream the server will
// process.
'''

The grpc-swift-client responds to both GOAWAY frames with GOAWAY frames which leads the grpc-go-server to crash. E.g. the client implementation of grpc-go checks for already received GOAWAY frames and their stream ids which prevents two following GOAWAY frames by the client ([Implementation](https://github.com/grpc/grpc-go/blob/81db25066bf395f3f49a8a8125eb199547d03469/internal/transport/http2_client.go#L1244-L1271)).

Since the behavior of the grpc-swift-client causes other servers to crash we expect grpc-swift to change the behavior.

To reproduce
Steps to reproduce the bug you've found:

1. Initiate connection
2. Make a bidirectional RPC to the server (grpc-go)
3. Invoke gracefullShutdown on the server
4. Clients sends two GOAWAY frames
5. Server crashes due to close of closed channel

We could reproduce the behaviour utilising the client from [RouteGuide-Example](https://github.com/grpc/grpc-swift/tree/main/Sources/Examples/RouteGuide) and implementing a go-server using the example proto file.

### What did you expect to see?
The server doesn't crash.

### What did you see instead?
The server crashes due to closing a channel twice.

### PR DESCRIPTION
**Pull request by zasweq**
Partially addresses #5786. Two GoAway pings were previously closing a closed channel, this PR adds protection with respect to the drainChan closing (used as a signal to write second GoAway frame). We still to derive the underlying root cause as to why two goaway ping acks are being sent from the Swift client.

RELEASE NOTES:
* transport: Fixed closing a closed channel panic in handlePing

### CODE REVIEW

File: test/goaway_test.go [hunk 1]
```diff
@@ -707,3 +709,58 @@ func (s) TestGoAwayStreamIDSmallerThanCreatedStreams(t *testing.T) {
...
+// TestTwoGoAwayPingFrames tests the scenario where you get two go away ping
+// frames from the client during graceful shutdown. This should not crash the
+// server.
+func (s) TestTwoGoAwayPingFrames(t *testing.T) {
+	lis, err := net.Listen("tcp", "localhost:0")
+	if err != nil {
+		t.Fatalf("Failed to listen: %v", err)
+	}
+	defer lis.Close()
+	s := grpc.NewServer()
```
Comment (dfawley) [inline test/goaway_test.go:722]: I think this needs to `defer s.Stop()` just in case `GracefulStop()` does hang (otherwise the leak detector hangs).

File: test/servertester.go [hunk 2]
```diff
@@ -273,3 +273,9 @@ func (st *serverTester) writeRSTStream(streamID uint32, code http2.ErrCode) {
 		st.t.Fatalf("Error writing RST_STREAM: %v", err)
 	}
 }
+
+func (st *serverTester) writeGoAwayPing(ack bool, data [8]byte) {
```
Comment (dfawley) [inline test/servertester.go:277]: `writePing`?  There's nothing about this ping that implies any relation to goaway besides the payload which is parameterized in `data`.

**Review by dfawley — COMMENTED** [review]
LGTM modulo a couple nits.  And also go/cl-descriptions style please.

I would also like to get a definitive root cause before we call this done, because it could be papering over another bug.

File: test/goaway_test.go (hunk 1 above)
Comment (zasweq) [reply test/goaway_test.go:722]: Oh interesting added.

File: test/servertester.go (hunk 2 above)
Comment (zasweq) [reply test/servertester.go:277]: Oh lol fair point good catch. Changed.

**Review by dfawley — APPROVED** [review]
