### PR TITLE
xds/client: notify the resource watchers of xDS errors

### LINKED ISSUE #4121: xds: client should notify the callback of the error if a response is NACK'ed
This is similar as service config error handling.
The resolver can decide what to do with this error.
If there was a good response, it can keep using it. Otherwise, it should start to fail RPCs.

### PR DESCRIPTION
**Pull request by menghanl**
Including
- NACK error
- Connection error (from stream.Recv())

fixes #4121, also fixes part of #3823

RELEASE NOTES: N/A

### CODE REVIEW

File: xds/internal/xdsclient/client.go [hunk 1]
```diff
@@ -141,6 +141,9 @@ type UpdateHandler interface {
 	// NewEndpoints handles updates to xDS ClusterLoadAssignment (or tersely
 	// referred to as Endpoints) resources.
 	NewEndpoints(map[string]EndpointsUpdate, UpdateMetadata)
+	// NewConnectionError handles connection error from the xDS stream. The
```
Comment (dfawley) [inline xds/internal/xdsclient/client.go:144]: Nit: "a connection error"

**Review by dfawley — COMMENTED** [review]
Can you add a test case in the xds e2e tests that contains a bad resource and expects appropriate RPC failures (propagated to the RPC status via the xds resolver)?

**Review by menghanl — COMMENTED** [review]
The e2e test didn't work, because go-control-plane has problems (it sends the bad config again after the client NACKs it)

**Review by dfawley — APPROVED** [review]
