### PR TITLE
client: fix race between transport draining and new RPCs

### LINKED ISSUE #2767: Unavailable error when MaxConnectionAge and MaxConnectionAgeGrace is enabled on the server
### What version of gRPC are you using?
v1.18.0/v1.19.1

### What version of Go are you using (`go version`)?
1.11

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
I tried to enable MaxConnectionAge on a C++ server and call from a Go client. When the connection age was reached, the rpcs in the Go client failed with the unavailable error and the "transport is closing" message. 

### What did you expect to see?
No unavailable errors.

### What did you see instead?
I test with both age and grace time set to one minute, and the Go client reported lots of errors. Each rpc takes a few seconds to complete, within the one minute grace period.

```
grpc-go v1.18.0/v1.19.1
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
rpc error: code = Unavailable desc = the connection is draining
rpc error: code = Unavailable desc = transport is closing
```

Reference: https://github.com/grpc/grpc/issues/12295#issuecomment-479308577

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #2767

Before these fixes, it was possible to see errors on new RPCs after a
connection began draining, and before establishing a new connection.  There is
an inherent race between choosing a SubConn and attempting to creating a stream
on it.  We should be able to avoid application-visible RPC errors due to this
with transparent retry.  However, several bugs were preventing this from
working correctly:

1. Non-wait-for-ready RPCs were skipping transparent retry, though the retry
design calls for retrying them.

2. The transport closed itself (and would consequently error new RPCs) before
notifying the SubConn that it was draining.

3. The SubConn wasn't synchronously updating itself once it was notified about
the closing or draining state.

4. The SubConn would go into the TRANSIENT_FAILURE state instantaneously,
causing RPCs to fail instead of queue.

### CODE REVIEW

File: test/goaway_test.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	testpb "google.golang.org/grpc/test/grpc_testing"
+)
+
+// TestGracefulClientOnGoAway attempts to ensure that when the server sends a
+// goaway, a client will never see an error.  This requires that the client is
+// appraised of the GOAWAY and updates its state accordingly before the
+// transport stops accepting new streams.  If a subconn is chosen by a picker
+// and receives the goaway before creating the stream, an error will occur, but
+// upon transparent retry, the clientconn will ensure a ready subconn is
+// chosen.
```
Comment (menghanl) [inline test/goaway_test.go]: The comment says what this test is for, but doesn't say how.
Mention that GOAWAY is triggered by max connection age? Either here or in the test body.

**Comment by gyuho** [comment]
@dfawley Can we confirm 1.23 release date? https://github.com/grpc/grpc-go/milestone/21 says August 13. etcd is using 1.22. Would like to use 1.23 with this fix for our 3.4 release. Thanks!

/cc @jpbetz

**Comment by menghanl** [comment]
@gyuho The milestone has the right date. Release 1.23 is scheduled for August 13.

**Comment by gyuho** [comment]
@menghanl Thanks for the confirmation!
