### PR TITLE
service config: add default method config support

### LINKED ISSUE #3473: service config: allow default method config
- Ignore methodConfig entries with no name instead of failing.
- For the service and method fields in the methodConfig name, treat null and empty string as unset instead of failing.
- Add support for a methodConfig that specifies the default for all services and all methods.
- Reject the config if there are multiple methodConfig entries with the same name.

https://github.com/grpc/grpc-proto/pull/75
https://github.com/grpc/grpc/pull/22232

### PR DESCRIPTION
**Pull request by amenzhinsky**
Fixes #3473

### CODE REVIEW

File: clientconn.go [hunk 1]
```diff
@@ -871,12 +871,14 @@ func (cc *ClientConn) GetMethodConfig(method string) MethodConfig {
...
-		m = cc.sc.Methods[method[:i+1]]
+	if m, ok := cc.sc.Methods[method]; ok {
+		return m
 	}
-	return m
+	i := strings.LastIndex(method, "/")
+	if m, ok := cc.sc.Methods[method[:i+1]]; ok {
+		return m
+	}
+	return cc.sc.Methods[""]
```
Comment (menghanl) [inline clientconn.go:881]: Can you also update the function comments?

File: service_config.go [hunk 2]
```diff
@@ -229,15 +230,24 @@ type jsonName struct {
 	Method  *string
 }
 
-func (j jsonName) generatePath() (string, bool) {
+var errIgnoreName = errors.New("ignore name")
```
Comment (menghanl) [inline service_config.go:233]: Can you add more information to the error message?

File: service_config.go [hunk 3]
```diff
@@ -229,15 +230,24 @@ type jsonName struct {
...
+
+func (j jsonName) generatePath() (string, error) {
 	if j.Service == nil {
-		return "", false
+		return "", errIgnoreName
```
Comment (menghanl) [inline service_config.go:237]: What if j.Service is nil, but j.Method is set to non-empty string?

File: service_config.go [hunk 4]
```diff
@@ -321,10 +333,23 @@ func parseServiceConfig(js string) *serviceconfig.ParseResult {
...
+			if err != nil {
+				if err == errIgnoreName {
+					continue
+				}
+				grpclog.Warningf("grpc: parseServiceConfig error unmarshaling %s due to methodConfig[%d]: %v", js, i, err)
+				return &serviceconfig.ParseResult{Err: err}
+			}
+
+			if _, ok := paths[path]; ok {
+				err = errors.New("duplicated name")
```
Comment (menghanl) [inline service_config.go:347]: Move this error next to `errIgnoreName`

File: service_config.go (hunk 3 above)
Comment (amenzhinsky) [reply service_config.go:237]: `errIgnoreName` will make it simply ignore the name just like the current implementation does.

https://github.com/grpc/grpc-proto/blob/dd2dca318eb197b96b60f22297871fb1ed862800/grpc/service_config/service_config.proto#L67 states `service` is required, so probably we should return the corresponding error instead of skipping malformed names, but I was afraid to introduce breaking changes.

File: service_config.go (hunk 2 above)
Comment (amenzhinsky) [reply service_config.go]: changed it to `errMissingService`

File: service_config.go (hunk 3 above)
Comment (amenzhinsky) [reply service_config.go]: https://github.com/grpc/grpc-go/pull/3684/commits/ef23d5c8d3ff225335aa39165e56ae0f3b2eae00#diff-bd49846390d90e2bd0f528a7a4c1e533R339-R341

I removed this block in the latest patch, let me know if it's not something you wanted me to do.

File: service_config.go [hunk 5]
```diff
@@ -321,10 +337,20 @@ func parseServiceConfig(js string) *serviceconfig.ParseResult {
 				mc.MaxRespSize = newInt(int(*m.MaxResponseMessageBytes))
 			}
 		}
-		for _, n := range *m.Name {
-			if path, valid := n.generatePath(); valid {
-				sc.Methods[path] = mc
+		for i, n := range *m.Name {
+			path, err := n.generatePath()
+			if err != nil {
+				grpclog.Warningf("grpc: parseServiceConfig error unmarshaling %s due to methodConfig[%d]: %v", js, i, err)
```
Comment (menghanl) [inline service_config.go:343]: Use `logger.Warningf`
(logger is a logging component: `var logger = grpclog.Component("core")`)

File: service_config.go [hunk 6]
```diff
@@ -229,15 +230,28 @@ type jsonName struct {
...
+var (
+	errMissingService             = errors.New("'service' is missing")
+	errDuplicatedName             = errors.New("duplicated name")
+	errEmptyServiceNonEmptyMethod = errors.New("cannot combine empty 'service' and non-empty 'method'")
+)
+
+func (j jsonName) generatePath() (string, error) {
 	if j.Service == nil {
-		return "", false
+		return "", errMissingService
```
Comment (menghanl) [inline service_config.go:241]: I think there's some inconsistency in `service_config.proto`.
`service` shouldn't be marked as required, and [this](https://github.com/grpc/grpc-proto/blob/dd2dca318eb197b96b60f22297871fb1ed862800/grpc/service_config/service_config.proto#L61) line says `not present` is considered the same as `""`.

(Does the json library handle `null` correctly? Can you add a test? Thanks!)

`j.Service == nil` should be considered the same as `*j.Service == ""`, and we check if `method` is set, as in the following `if`.

---
On whether this is a breaking change, this only affect configs where service is not set, and method is set to non-empty string. This is not an valid config anyway, I think failing those would be OK.

Comment (amenzhinsky) [reply service_config.go:241]: https://github.com/grpc/grpc-go/pull/3684/files#diff-656c5a93bda2544d9c7c7ea6f4a37af3R376
test is already there

Comment (menghanl) [reply service_config.go:240]: Oh, right, that's great!

Did you fix this
> j.Service == nil should be considered the same as *j.Service == "", and we check if method is set, as in the following if.

I saw you force pushed, but I can't find the fix for it.

Comment (amenzhinsky) [reply service_config.go]: I think I finally got it, was a bit comfused. Please check out the latest commit
