### PR TITLE
server: wait to close connection until incoming socket is drained (with timeout)

### LINKED ISSUE #5358: gRPC connection closing with unexpected EOF on high-latency connections
### What version of gRPC are you using?
1.46.2

### What version of Go are you using (`go version`)?
go version go1.18 darwin/amd64

### What operating system (Linux, Windows, …) and version?
Client is running MacOs:
  ProductName: macOS
  ProductVersion: 11.6
  BuildVersion: 20G165

Server is running Linux (CentOS 7)

### What did you do?

Note: I have posted a small repo that can be used to reproduce this bug, please check it out here:
[https://github.com/brianneville/grpcbug](https://github.com/brianneville/grpcbug)

-------

For high-latency connections, I noticed that RPCs were having their connection terminated with an internal error: 
`code = Internal desc = unexpected EOF`

This hits on both unary and streaming RPCs, and the ease with which this can be reproduced seems to vary with the client-server latency.
For high-latency connections (such 150ms ping), this error hits pretty much every time an RPC is called.
For low-latency connections (<2ms ping) this error is much more infrequent, and hundreds of thousands of messages may be streamed over this connection before the error is hit even once.

I did a bit of digging through the grpc library code, and found two ways that the error can be prevented:

#### 1.  Client side - configure window sizes
The error can be prevented from the client side by disabling the dynamic window and BDP estimation for flow control when dialing the grpc server. 
That is, setting the DialOptions on the client side to use:
```
    opts := []grpc.DialOption{
       grpc.WithInitialWindowSize(largerWindowSize),
       grpc.WithInitialConnWindowSize(largerWindowSize),
    }
```
Where both: 
 - `largerWindowSize` is greater than 65535 (so that dynamic window/flow estimation is turned off)
 - `largerWindowSize` is greater than the size of the largest RPC response messages (with a bit of overhead for some reason).

#### 2.  Server-side - delay ending the stream
The error can be prevented by delaying the calls that write the `StatusOk` into the transport. Specifically, if the END_STREAM header is delayed from being put into the `controlBuf` at [`google.golang.org/grpc/internal/transport/http2_server.go#finishStream`](https://github.com/grpc/grpc-go/blob/db79903af928ca8307700d83123a7702881c4e3c/internal/transport/http2_server.go#L1269). 
That is, you can make any of the following changes to `*http2Server.finishStream`, and the error will not be present:
```
    time.Sleep(1 * time.Second) // <-- sleeping before put = EOF error is prevented
    t.controlBuf.put(hdr)
```
or   
```
    go func() {         // <-- allowing finishStream to progress and sleep before put = EOF error is prevented
      time.Sleep(1 * time.Second)
      t.controlBuf.put(hdr)
    }()
```

When the `t.controlBuf.put(hdr)` line is delayed in this way, the RPC is allowed to complete normally, and the client will see the response as intended.

Note if you add the sleep after the `t.controlBuf.put(hdr)`, then the error will still be present (i.e. delaying the finishStream function is not what causes the error to be prevented)
```
    t.controlBuf.put(hdr)
    time.Sleep(1 * time.Second) // <-- sleeping after put = EOF error still occurs 
```

Would anyone know what might be going on here, or be able to give me some insight/advice for continuing to debug this issue?

### What did you expect to see?
Connection latency does not affect RPCs

### What did you see instead?
High-latency connection (such as ~150ms ping) reliably hit the error `code = Internal desc = unexpected EOF`

### PR DESCRIPTION
**Pull request by dfawley**
Replaces #6957

Fixes #5358 (A modified version of the test in that issue runs for 5+ minutes without failing with these changes.  On a broken branch it fails reliably within 30s, and often much faster.)

See also https://github.com/grpc/grpc-java/issues/9566 and https://github.com/golang/net/commit/cd69bc3fc700721b709c3a59e16e24c67b58f6ff / https://github.com/golang/go/issues/18701

This change also adjusts the ping timer after sending the initial GOAWAY from 1 minute to 5 seconds at @ejona86's recommendation.

RELEASE NOTES:
* server: wait to close connection until incoming socket is drained (with timeout) to prevent data loss on client-side

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]

**Review by arvindbr8 — APPROVED** [review]
Nice! LGTM

**Comment by ash2k** [comment]
Can we get a release with this fix please? Keen to try and see if it fixes our troubles.

**Comment by dfawley** [comment]
It will be in 1.62.0 next week.  I'll see if it's easy to backport to 1.61.x and push a 1.61 patch release if so.

**Comment by dfawley** [comment]
I pushed a patch release with the fix, v1.61.1: https://github.com/grpc/grpc-go/releases/tag/v1.61.1

**Comment by ash2k** [comment]
Thank you!

File: internal/transport/http2_server.go [hunk 1]
```diff
@@ -322,8 +322,24 @@ func NewServerTransport(conn net.Conn, config *ServerConfig) (_ ServerTransport,
...
+			// second before closing the connection, or when the reader is done
+			// (i.e. the client already closed the connection or a connection
+			// error occurred).  This avoids the potential problem where there
+			// is unread data on the receive side of the connection, which, if
+			// closed, would lead to a TCP RST instead of FIN, and the client
+			// encountering errors.  For more info:
+			// https://github.com/grpc/grpc-go/issues/5358
+			select {
+			case <-t.readerDone:
+			case <-time.After(time.Second):
```
Comment (mtekeli) [inline internal/transport/http2_server.go:339]: Note that no one can stop this scheduled timer when the reader is done first (which would probably happen most of the times). I would suggest to change it to a `timer` object so it can be stopped manually (and therefore released) when the reader is done first.

In a scenario where this happens with many clients (or the same client) repeatedly wouldn't you just schedule many timers that cannot be stopped until they fire (i.e a temporary memory leak).

Comment (dfawley) [reply internal/transport/http2_server.go:339]: True that it isn't stopped, but it is fixed for 1 second, so I don't believe this could be a real problem for anyone.

Comment (dfawley) [reply internal/transport/http2_server.go:339]: I think the key here is that it's a non-I/O error, which means it would be initiated by the server itself.  If the server is terminating already-handshaked connections at a rate of >1 per second, then that seems like a real problem.

That said, I think it's OK to just forbid the use of `time.After` in our repo (outside of tests) since it's always a potential concern.  I'll add a `vet.sh` check for this and change it on master.
