### PR TITLE
balancer/base: keep address attributes for pickers

### LINKED ISSUE #4276: The attributes of the address is removed when passing to the picker.
I am using  my own balancer.PickerBuilder  in my program.  I attach some info to the address with the func SetAddrInfo in weightedroundrobin.go and read it from `Build(info PickerBuildInfo) balancer.Picker`.

 It works well in grpc-go@v1.34.0, but failed in grpc-go@v1.35.0. 

I read the release note and find this [strip attributes from addresses](https://github.com/grpc/grpc-go/pull/4024).  

In the function 

```golang 
func (b *baseBalancer) regeneratePicker() {
	if b.state == connectivity.TransientFailure {
		b.picker = NewErrPicker(b.mergeErrors())
		return
	}
	readySCs := make(map[balancer.SubConn]SubConnInfo)

	// Filter out all ready SCs from full subConn map.
	for addr, sc := range b.subConns {
		if st, ok := b.scStates[sc]; ok && st == connectivity.Ready {
			readySCs[sc] = SubConnInfo{Address: addr}
		}
	}
	b.picker = b.pickerBuilder.Build(PickerBuildInfo{ReadySCs: readySCs})
}
```
It uses b.subConns to pass ready connections to the picker. But the key in b.subConns contains no attributes now. So I got 

empty  attributes and my program failed.

It is a feature or a bug? What should I do?

### PR DESCRIPTION
**Pull request by longXboy**
#4024 caused the Addresses.Attributes of readySCs obtained by pickerBuilder to be nil when regeneratePicker.

1.add subConnInfo struct which contains subConn and attributes.
2.add attributes to aNoAttrs when generate readySCs.

fixes #4276

### CODE REVIEW

**Review by menghanl — CHANGES_REQUESTED** [review]
Thanks for the fix. And sorry for the delay.

This fix looks good to me.
Can you add a test to make sure that the pickers can get the attributes?
Thanks!

**Comment by longXboy** [comment]
> Thanks for the fix. And sorry for the delay.
> 
> This fix looks good to me.
> Can you add a test to make sure that the pickers can get the attributes?
> Thanks!

ok,I will add some tests

**Comment by longXboy** [comment]
@menghanl  test cases added!

File: balancer/base/balancer_test.go [hunk 1]
```diff
@@ -64,7 +77,46 @@ func TestBaseBalancerStripAttributes(t *testing.T) {
...
+
+func TestBaseBalancerReserveAttributes(t *testing.T) {
+	var v = func(info PickerBuildInfo) {
+		for _, sc := range info.ReadySCs {
+			if sc.Address.Addr == "1.1.1.1" {
+				if sc.Address.Attributes == nil {
+					t.Errorf("in picker.validate, got address %+v with nil attributes, want not nil", sc.Address)
+				}
+				foo, ok := sc.Address.Attributes.Value("foo").(string)
+				if !ok || foo != "2233niang" {
```
Comment (menghanl) [inline balancer/base/balancer_test.go:93]: :man_facepalming:

**Review by menghanl — APPROVED** [review]
LGTM. Thanks for the fix!
