### PR TITLE
internal: fix Dial_OneBackoffPerRetryGroup

### LINKED ISSUE #2687: Flaky test: Test/Dial_OneBackoffPerRetryGroup
```
==================
WARNING: DATA RACE
Write at 0x00000102a9b8 by goroutine 56:
  google.golang.org/grpc.s.TestDial_OneBackoffPerRetryGroup()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn_test.go:618 +0x166
  google.golang.org/grpc.(*s).TestDial_OneBackoffPerRetryGroup()
      <autogenerated>:1 +0x49
  runtime.call32()
      /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:522 +0x3a
  reflect.methodValueCall()
      /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/reflect/asm_amd64.s:35 +0x41
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x162
Previous read at 0x00000102a9b8 by goroutine 61:
  [failed to restore the stack]
Goroutine 56 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:878 +0x659
  google.golang.org/grpc/internal/grpctest.RunSubTests()
      /home/travis/gopath/src/google.golang.org/grpc/internal/grpctest/grpctest.go:62 +0x3a9
  google.golang.org/grpc.Test()
      /home/travis/gopath/src/google.golang.org/grpc/grpc_test.go:53 +0x50
  testing.tRunner()
      /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x162
Goroutine 61 (finished) created at:
  google.golang.org/grpc.(*addrConn).connect()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn.go:685 +0xfb
  google.golang.org/grpc.(*acBalancerWrapper).Connect()
      /home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:321 +0x88
  google.golang.org/grpc.(*pickfirstBalancer).HandleResolvedAddrs()
      /home/travis/gopath/src/google.golang.org/grpc/pickfirst.go:65 +0x4b4
  google.golang.org/grpc.(*ccBalancerWrapper).watcher()
      /home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:139 +0x553
==================
```
https://travis-ci.org/lyuxuan/grpc-go/jobs/505558388

### PR DESCRIPTION
**Pull request by jadekler**
Adds a mutex around getMinConnectTimeout to guard against races. See
https://travis-ci.org/lyuxuan/grpc-go/jobs/505558388 for an example
race.

Fixes #2687.

### CODE REVIEW

**Comment by jadekler** [comment]
> Can you add a(n unexported) DialOption instead, and make this per-ClientConn instead of global? 

Done. That's much nicer. I know you mentioned this to me before - sorry for forgetting that approach.

File: clientconn.go [hunk 1]
```diff
@@ -973,7 +968,11 @@ func (ac *addrConn) resetTransport() {
 		backoffFor := ac.dopts.bs.Backoff(ac.backoffIdx)
 
 		// This will be the duration that dial gets to finish.
-		dialDuration := getMinConnectTimeout()
+		dialDuration := minConnectTimeout
+		if ac.dopts.getMinConnectTimeoutFunc != nil {
```
Comment (dfawley) [inline clientconn.go]: Nit: you can probably leave out "get" and "Func".

File: dialoptions.go [hunk 2]
```diff
@@ -500,3 +502,14 @@ func defaultDialOptions() dialOptions {
 		},
 	}
 }
+
+// withGetMinConnectDeadline specifies the function that clientconn uses to
+// get minConnectDeadline. This can be used to make connection attempts happen
+// faster/slower.
+//
+// For testing purpose only.
+func withGetMinConnectDeadline(f func() time.Duration) DialOption {
```
Comment (dfawley) [inline dialoptions.go]: Similar: consider s/Get//

Comment (jadekler) [reply dialoptions.go]: Done

File: clientconn.go (hunk 1 above)
Comment (jadekler) [reply clientconn.go]: Done

**Comment by dfawley** [comment]
@jadekler can you check out the travis failures and see if they're preexisting flakes?  If so, we can just re-run them.

**Comment by jadekler** [comment]
@dfawley Done, and filed bugs for the flakes (they seem to be unrelated).
