### PR TITLE
Automatic WriteStatus for RecvMsg/SendMsg error on server side

### LINKED ISSUE #1334: Triggering MaxSendMsgSize limit on response streaming RPC does not raise exception on client side
For more context: https://github.com/grpc/grpc/issues/11586

The golang server properly sends back an error response for Unary RPC when this limit is exceeded, but for the streaming RPC it does not. The client side hangs until the server finishes its response, and no responses are actually returned client side.

The golang server should send back an error in the streaming RPC case so that clients don't erroneously believe there is no response.

### PR DESCRIPTION
**Pull request by lyuxuan**
- Automatically sending final status if error occurred in RecvMsg/SendMsg on server side.

- Increasing defaultClientMaxSendMessageSize/defaultServerMaxSendMessageSize to math.MaxInt32 to be consistent with C++/Java.

should resolve #1334.

### CODE REVIEW

**Comment by lyuxuan** [comment]
ping

File: transport/handler_server.go [hunk 1]
```diff
@@ -172,6 +176,9 @@ func (ht *serverHandlerTransport) do(fn func()) error {
 }
 
 func (ht *serverHandlerTransport) WriteStatus(s *Stream, st *status.Status) error {
+	if ht.streamDone {
```
Comment (MakMukhi) [inline transport/handler_server.go]: What do you think about something like?
```go
select {
case <-ht.writes:
return
default:
}
```

**Comment by lyuxuan** [comment]
@MakMukhi @dfawley this PR is ready for review again. Thanks!

File: stream.go [hunk 2]
```diff
@@ -599,6 +599,19 @@ func (ss *serverStream) SendMsg(m interface{}) (err error) {
 			}
 			ss.mu.Unlock()
 		}
+		if err != nil && err != io.EOF {
+			st, ok := status.FromError(err)
+			if !ok {
```
Comment (dfawley) [inline stream.go]: Should we use toRPCErr for this conversion instead?  It does the same things but more, except for calling `convertCode`.  But that function says it's intended for use on errors returned by the server application, which is not the case here.

So something like this?

```go
st, _ := status.FromError(toRPCErr(err))
ss.t.WriteStatus(ss.s, st)
```

File: stream.go [hunk 3]
```diff
@@ -640,6 +653,19 @@ func (ss *serverStream) RecvMsg(m interface{}) (err error) {
 			}
 			ss.mu.Unlock()
 		}
+		if err != nil && err != io.EOF {
+			st, ok := status.FromError(err)
```
Comment (dfawley) [inline stream.go]: Same as above.

File: server.go [hunk 4]
```diff
@@ -781,12 +781,7 @@ func (s *Server) processUnaryRPC(t transport.ServerTransport, stream *transport.
 	}
 	reply, appErr := md.Handler(srv.server, stream.Context(), df, s.opts.unaryInt)
 	if appErr != nil {
-		appStatus, ok := status.FromError(appErr)
-		if !ok {
-			// Convert appErr if it is not a grpc status error.
-			appErr = status.Error(convertCode(appErr), appErr.Error())
-			appStatus, _ = status.FromError(appErr)
-		}
+		appStatus, _ := status.FromError(toRPCErr(appErr))
```
Comment (dfawley) [inline server.go]: This is the application error, which is not what toRPCErr is supposed to handle.  This is where convertCode is appropriate to use.

File: server.go [hunk 5]
```diff
@@ -899,16 +894,7 @@ func (s *Server) processStreamingRPC(t transport.ServerTransport, stream *transp
...
-		if !ok {
-			switch err := appErr.(type) {
-			case transport.StreamError:
-				appStatus = status.New(err.Code, err.Desc)
-			default:
-				appStatus = status.New(convertCode(appErr), appErr.Error())
-			}
-			appErr = appStatus.Err()
-		}
+		appStatus, _ := status.FromError(toRPCErr(appErr))
```
Comment (dfawley) [inline server.go]: Ditto

File: server.go [hunk 6]
```diff
@@ -806,9 +807,13 @@ func (s *Server) processUnaryRPC(t transport.ServerTransport, stream *transport.
 	if appErr != nil {
 		appStatus, ok := status.FromError(appErr)
 		if !ok {
-			// Convert appErr if it is not a grpc status error.
-			appErr = status.Error(convertCode(appErr), appErr.Error())
-			appStatus, _ = status.FromError(appErr)
+			switch err := appErr.(type) {
+			case transport.StreamError:
```
Comment (menghanl) [inline server.go]: The error comes from user's handler, why would it be a `transport.StreamError`?

**Comment by lyuxuan** [comment]
ping~~~~
