### PR TITLE
transport: fix handling of header metadata in serverHandler

### LINKED ISSUE #3483: serverHandlerTransport (Go HTTP API): SetHeader doesn't work
### What version of gRPC are you using?

v1.27.0 (latest)

### What version of Go are you using (`go version`)?

1.13.8, 1.14

### What operating system (Linux, Windows, …) and version?

macOS Mojave (10.14.6)

### What did you do?
Use Go's HTTP/2 server with the experimental `(*grpc.Server).ServeHTTP` API, and set a custom header using `SetHeader` on the server stream.

### What did you expect to see?

The client should receive the union (merge) of all header values/metadata provided via `SetHeader` plus any metadata specified in `SendHeader` (if used).

### What did you see instead?

The client only sees the metadata specified in `SendHeader`, and no custom header metadata at all if `SendHeader` is not used.

More precisely, the implementation of the `serverHandlerTransport` suffers from the following when it comes to handling errors:
- Header values set via `SetHeader` are ignored entirely. They are neither sent out implicitly when data is written, nor explicitly merged with the metadata provided in `SendHeader` (note that trailers work just fine).
- `SetHeader` calls that follow the sending of either headers or data do not produce an error, as they should.
- The same applies to repeated `SendHeader` calls.
- A `SendHeader` call immediately followed by a modification of the passed metadata might non-deterministically send out either the original or the modified metadata.

PR with a fix coming right up...

### PR DESCRIPTION
**Pull request by misberner**
This PR changes the `serverHandlerTransport` code to take header metadata from the stream (set via invocations of `SetHeader`) into account, both when implicitly sending headers, or when explicitly sending headers via `SendHeader` (merging any previously set metadata with the additionally supplied one, as per the docs).

It also fixes an issue with `SendHeader` where modifications to the passed metadata map after the `SendHeader` call has already returned might still affect the header values that get written to the stream.

Please check out the first commit in this branch (`3140f261`) for a state that only has the modified test (which of course fails) added.

Fixes #3483.

### CODE REVIEW

File: internal/transport/handler_server.go [hunk 1]
```diff
@@ -186,8 +186,9 @@ func (ht *serverHandlerTransport) WriteStatus(s *Stream, st *status.Status) erro
 	ht.writeStatusMu.Lock()
 	defer ht.writeStatusMu.Unlock()
 
+	s.updateHeaderSent()
```
Comment (misberner) [inline internal/transport/handler_server.go]: These calls need to happen outside of `ht.do` to make sure subsequent invocations fail immediately, even if at that point headers haven't not been fully written (but it's imminent).

File: internal/transport/handler_server.go [hunk 2]
```diff
@@ -264,29 +272,43 @@ func (ht *serverHandlerTransport) writeCommonHeaders(s *Stream) {
...
-		ht.writeCommonHeaders(s)
+		ht.writePendingHeaders(s)
 		ht.rw.Write(hdr)
 		ht.rw.Write(data)
 		ht.rw.(http.Flusher).Flush()
 	})
 }
 
 func (ht *serverHandlerTransport) WriteHeader(s *Stream, md metadata.MD) error {
+	if err := s.SetHeader(md); err != nil {
```
Comment (misberner) [inline internal/transport/handler_server.go]: tbh I don't really understand why `WriteHeader` even takes an `md` parameter - IMHO it would be more elegant to implement `(*Stream).SendHeader` via
```
s.SetHeader(md)
s.st.WriteHeader(s)
```
Since `ServerTransport` is an internal interface, I don't see any issues, but it would require changing the `http2Server` implementation as well, which is why I opted for a more local change.

File: internal/transport/handler_server_test.go [hunk 3]
```diff
@@ -269,6 +269,32 @@ func (s) TestHandlerTransport_HandleStreams(t *testing.T) {
 		if want := "/service/foo.bar"; s.method != want {
 			t.Errorf("stream method = %q; want %q", s.method, want)
 		}
+
+		err := s.SetHeader(metadata.Pairs("custom-header", "Custom header value"))
```
Comment (misberner) [inline internal/transport/handler_server_test.go]: If desired, I can break this out into multiple test cases, but I think it's reasonable to exercise all features in the "happy path" test case as long as there is no mutual interference.

File: internal/transport/handler_server_test.go [hunk 4]
```diff
@@ -277,14 +303,16 @@ func (s) TestHandlerTransport_HandleStreams(t *testing.T) {
...
-		"Date":         nil,
-		"Content-Type": {"application/grpc"},
-		"Trailer":      {"Grpc-Status", "Grpc-Message", "Grpc-Status-Details-Bin"},
-		"Grpc-Status":  {"0"},
+		"Date":          {},
+		"Content-Type":  {"application/grpc"},
+		"Trailer":       {"Grpc-Status", "Grpc-Message", "Grpc-Status-Details-Bin"},
+		"Custom-Header": {"Custom header value", "Another custom header value"},
 	}
-	if !reflect.DeepEqual(st.rw.HeaderMap, wantHeader) {
```
Comment (misberner) [inline internal/transport/handler_server_test.go]: Note that `st.rw.HeaderMap` is not only deprecated but also might contain values that are different from `st.rw.Result().Header` - for example, it would contain the header values from the second `SendHeader` invocation, even though the `ht.do` func arguments are executed strictly sequentially and in-order.

File: internal/transport/handler_server_test.go (hunk 3 above)
Comment (dfawley) [reply internal/transport/handler_server_test.go:273]: This is fine, thanks.

File: internal/transport/handler_server_test.go [hunk 5]
```diff
@@ -308,16 +336,15 @@ func handleStreamCloseBodyTest(t *testing.T, statusCode codes.Code, msg string)
 		func(ctx context.Context, method string) context.Context { return ctx },
 	)
 	wantHeader := http.Header{
-		"Date":         nil,
+		"Date":         {},
 		"Content-Type": {"application/grpc"},
 		"Trailer":      {"Grpc-Status", "Grpc-Message", "Grpc-Status-Details-Bin"},
+	}
+	wantTrailer := http.Header{
```
Comment (dfawley) [inline internal/transport/handler_server_test.go:343]: I guess this (and a test or two below) will have to be updated when #553 is eventually fixed, as there *should* only be one headers frame sent for these kinds of RPCs.  (This is purely FYI.)

**Comment by dfawley** [comment]
> It also fixes an issue with SendHeader where modifications to the passed metadata map after the SendHeader call has already returned might still affect the header values that get written to the stream.

Can you explain this a little more?  What might be modifying the metadata map and why?  I don't believe this should be happening as the metadata godoc says modifying metadata stored in contexts is not allowed ([e.g.](https://godoc.org/google.golang.org/grpc/metadata#FromOutgoingContext)).

**Comment by dfawley** [comment]
Actually, nevermind my last question; I see the problem.  I think there's a cleaner design here somewhere, but your changes LGTM.

**Comment by misberner** [comment]
> Can you explain this a little more? What might be modifying the metadata map and why? I don't believe this should be happening as the metadata godoc says modifying metadata stored in contexts is not allowed ([e.g.](https://godoc.org/google.golang.org/grpc/metadata#FromOutgoingContext)).

This was a concurrency error/race condition. `SendHeader` returns once `ht.do(func() { ... })` returns, which however only means that the closure has been pushed to the channel/accepted by the receiver, but not necessarily finished *dispatching* by the receiver. For this reason, a call

```
md := metadata.Pairs("foo", "bar")
s.SendHeader(md)
delete(md, "foo")
```

might non-deterministically result in a header with the "foo" key being written or not, since the dispatching of the closure which reads `md` happens concurrently with `delete(md, "foo")` without synchronization. That's why I changed the implementation of `SendHeader` to call `SetHeader` first, which ensures that no references to the passed `MD` map are retained after `SendHeader` returns.
