### PR TITLE
transport: Fix the inconsistency between headerChan and headerDone

### LINKED ISSUE #2796: Stream got stuck in waitOnHeader even after the underlying transport has gone away
Please see the FAQ in our main README.md, then answer the questions below before
submitting your issue.

### What version of gRPC are you using?
1.20.1

### What version of Go are you using (`go version`)?
1.12.4

### What operating system (Linux, Windows, …) and version?
Linux, ubuntu 19.04

### What did you do?
The trigger of the issue was unknown, but there is some suspicion a network interruption was in play. One of the newly created gRPC stream got stuck in waitOnHeader() call for very long time (>10hours). The underlying TCP connection was gone already (verified by netstat).

### What did you expect to see?
The stream's context should get cancelled when the underlying TCP connection went away and that should break the wait.

### What did you see instead?
Apparently the context was not cancelled.

Backtrace of the relevant goroutines (goroutines with stacks inside grpc):
```goroutine 19 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc000161d00, 0x2, 0x8)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/transport.go:267 +0xcc
observe/vendor/google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/transport.go:278
observe/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc0003fc700, 0x14a1b20, 0xc0003be090, 0x0, 0xc000248900, 0xc0003be090)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:856 +0x70c
observe/vendor/google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0003fc700, 0x0, 0x203000)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:721 +0x46
observe/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc000248900, 0xc0006adb58, 0xc0006adb48, 0xc00042a360, 0x18)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:577 +0x7c
observe/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc000248900, 0x14a1b20, 0xc0003be090, 0xc00047b580, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:720 +0x100
observe/proto3/agentpb.(*collectorServiceCollectClient).Recv(0xc00064e650, 0xc00047b580, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/proto3/agentpb/agent.pb.go:2114 +0x62
observe/collector/client.register(0x173caa0, 0xc00064e650, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:38 +0x1b0
observe/collector/client.newConn(0x16f34e0, 0xc0000de000, 0x173caa0, 0xc00064e650, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x14f704d, 0x5, ...)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:57 +0x6d
observe/collector/client.Connect(0xc0006aded0, 0x1, 0x1, 0x7ffd0626bc64, 0x3, 0x7ffd0626bc75, 0x12, 0x14f704d, 0x5, 0xc0005a92c0, ...)
	/home/dev/observe/code/go/src/observe/collector/client/client.go:101 +0x3a3
main.runGrpcEmitterOnce(0xc000347650, 0x17231c0, 0xc0003a00c0)
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:192 +0x327
main.runGrpcEmitter(0xc000347650, 0xc00035e160)
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:218 +0x9f
created by main.NewAgent
	/home/dev/observe/code/go/src/observe/cmd/agent/agent.go:745 +0x23ac

goroutine 97642 [select]:
observe/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00047ad80)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x110
created by observe/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x14f

goroutine 97606 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc.newClientStream.func5(0xc0000de840, 0xc0002bf200, 0x1722fc0, 0xc0007b6720)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:320 +0xd7
created by observe/vendor/google.golang.org/grpc.newClientStream
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:319 +0x8e2

goroutine 97659 [select, 873 minutes]:
observe/vendor/google.golang.org/grpc.newClientStream.func5(0xc0000de000, 0xc000248900, 0x1722fc0, 0xc000479f50)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:320 +0xd7
created by observe/vendor/google.golang.org/grpc.newClientStream
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/stream.go:319 +0x8e2

goroutine 97643 [chan receive]:
observe/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000aea00)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:1040 +0x5a1
created by observe/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:700 +0xb6

goroutine 97590 [chan receive]:
observe/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc0000af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:1040 +0x5a1
created by observe/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/clientconn.go:700 +0xb6

goroutine 97589 [select]:
observe/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00011c0c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 +0x110
created by observe/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:106 +0x14f

goroutine 110724 [select]:
observe/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc003521cc0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x104
observe/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc003594de0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1b6
observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0003af6c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:330 +0x7b
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:328 +0xeb2

goroutine 110707 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c7424cbf0, 0x72, 0xffffffffffffffff)
	/usr/local/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00339ee18, 0x72, 0xe00, 0xe87, 0xffffffffffffffff)
	/usr/local/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00339ee00, 0xc0033a4000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00339ee00, 0xc0033a4000, 0xe87, 0xe87, 0x203000, 0x0, 0xe7a)
	/usr/local/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc002efa6b8, 0xc0033a4000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00057f480, 0xc0033a4000, 0xe87, 0xe87, 0x26, 0x16f1a20, 0xc000404a78)
	/usr/local/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0033d2958, 0x16f18c0, 0xc00057f480, 0x410425, 0x13626c0, 0x14a1960)
	/usr/local/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0033d2700, 0x16f1c80, 0xc002efa6b8, 0x5, 0xc002efa6b8, 0x9)
	/usr/local/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0033d2700, 0x158a200, 0xc0033d2838, 0x0)
	/usr/local/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0033d2700, 0xc003574000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc0034cbb60, 0xc0034ece38, 0x9, 0x9, 0xc000061880, 0x7f9c79f59008, 0x0)
	/usr/local/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x16f1720, 0xc0034cbb60, 0xc0034ece38, 0x9, 0x9, 0x9, 0x81be89, 0xc00315ca20, 0xc003150004)
	/usr/local/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/src/io/io.go:329
observe/vendor/golang.org/x/net/http2.readFrameHeader(0xc0034ece38, 0x9, 0x9, 0x16f1720, 0xc0034cbb60, 0x0, 0x0, 0xc00315ca20, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:237 +0x88
observe/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0034ece00, 0xc00315ca20, 0xc00315ca00, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0003af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1236 +0x168
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:286 +0xd15

goroutine 110708 [select]:
observe/vendor/google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc003521740, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:317 +0x104
observe/vendor/google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0034cbc20, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:435 +0x1b6
observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0003af180)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:330 +0x7b
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:328 +0xeb2

goroutine 110723 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c74200a10, 0x72, 0xffffffffffffffff)
	/usr/local/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc003596218, 0x72, 0xe00, 0xe87, 0xffffffffffffffff)
	/usr/local/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc003596200, 0xc0035aa000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc003596200, 0xc0035aa000, 0xe87, 0xe87, 0x203000, 0x0, 0xe7a)
	/usr/local/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc002efa908, 0xc0035aa000, 0xe87, 0xe87, 0x0, 0x0, 0x0)
	/usr/local/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0006566c0, 0xc0035aa000, 0xe87, 0xe87, 0x26, 0x16f1a20, 0xc0008e9a78)
	/usr/local/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0033d3758, 0x16f18c0, 0xc0006566c0, 0x410425, 0x13626c0, 0x14a1960)
	/usr/local/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0033d3500, 0x16f1c80, 0xc002efa908, 0x5, 0xc002efa908, 0x9)
	/usr/local/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0033d3500, 0x158a200, 0xc0033d3638, 0x0)
	/usr/local/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0033d3500, 0xc0035bc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc003594d20, 0xc0034ed0d8, 0x9, 0x9, 0xc000061880, 0x7f9c79f59008, 0x0)
	/usr/local/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x16f1720, 0xc003594d20, 0xc0034ed0d8, 0x9, 0x9, 0x9, 0x81be89, 0xc003070ab0, 0xc003070004)
	/usr/local/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/src/io/io.go:329
observe/vendor/golang.org/x/net/http2.readFrameHeader(0xc0034ed0d8, 0x9, 0x9, 0x16f1720, 0xc003594d20, 0x0, 0x0, 0xc003070ab0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:237 +0x88
observe/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0034ed0a0, 0xc003070ab0, 0xc003070a00, 0x0, 0x0)
	/home/dev/observe/code/go/src/observe/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
observe/vendor/google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0003af6c0)
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1236 +0x168
created by observe/vendor/google.golang.org/grpc/internal/transport.newHTTP2Client
	/home/dev/observe/code/go/src/observe/vendor/google.golang.org/grpc/internal/transport/http2_client.go:286 +0xd15
```

### PR DESCRIPTION
**Pull request by canguler**
fixes #2796

### CODE REVIEW

**Comment by canguler** [comment]
Attempts to fix #2796

File: internal/transport/transport_test.go [hunk 1]
```diff
@@ -1717,6 +1717,27 @@ func TestInvalidHeaderField(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("failed to create the stream")
+	}
+	time.Sleep(10 * time.Millisecond)
+	select {
+	case <-s.headerChan:
+	default:
+		t.Errorf("s.headerChan: got open, want closed")
+	}
+	ct.Close()
```
Comment (menghanl) [inline internal/transport/transport_test.go]: This and the following stop should be deferred right after `setUp`.

File: internal/transport/transport_test.go [hunk 2]
```diff
@@ -1717,6 +1717,27 @@ func TestInvalidHeaderField(t *testing.T) {
...
+	defer cancel()
+	callHdr := &CallHdr{
+		Host:   "localhost",
+		Method: "foo",
+	}
+	s, err := ct.NewStream(context.Background(), callHdr)
+	if err != nil {
+		t.Fatalf("failed to create the stream")
+	}
+	time.Sleep(10 * time.Millisecond)
```
Comment (menghanl) [inline internal/transport/transport_test.go]: Could this be flaky?

And how about this:
```go
timer := time.NewTimer(time.Second)
defer timer.Stop()
select {
case <- s.headerChan:
case <- timer.C:
  t.Errorf("")
}
```
