### PR TITLE
xds: Fail xDS Server Serve() if called after Stop() or GracefulStop()

### LINKED ISSUE #5838: xds: server should fail `Serve()` if called after `Close()`
Currently this can lead to a leaked xDS client, as the latter is created in `Serve()` and closed in `Close().

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #5838.

This PR fails Serve() if called after Stop() or GracefulStop(). This is important because Serve() eventually increments the global singleton xDS Client Ref, and thus if called without a corresponding cleanup, Stop() or GracefulStop(), the singleton xDS Client will eventually leak.

RELEASE NOTES: N/A

### CODE REVIEW

File: xds/server_test.go [hunk 1]
```diff
@@ -890,3 +908,37 @@ func verifyCertProviderNotCreated() error {
...
+	if err != nil {
+		t.Fatalf("testutils.LocalTCPListener() failed: %v", err)
+	}
+
+	server.Stop()
+	serveDone := testutils.NewChannel()
+	// Do this in a goroutine, even though should just receive error. This is to
+	// prevent blocking for (which comes after, so doesn't apply here), but
+	// mainly to wrap this err Receive operation with a testing timeout.
+	go func() { serveDone.Send(server.Serve(lis)) }()
```
Comment (easwars) [inline xds/server_test.go:929]: I don't see any value in doing this in a goroutine and plumbing the returned error value through a channel for the main test goroutine to inspect. I think all we need here is a direct call to `server.Serve()` and inspecting the error returned from the client.

If you want to test `Stop` racing with `Serve`, you should probably do something like this:
```golang
func (s) TestXxx(t *testing.T) {
  // Setup a real management server
  // Setup bootstrap file to point to the management server

  for i := 0 ; i < 100; i++ {
    // Start an xDS enabled server.
    // Spawn a goroutine which calls Serve
    // Spawn a goroutine which calls Stop/GracefulStop
  }

  // Wait for all the above goroutines to complete using a sync.WaitGroup

  // Rely on the leakchecker to detect if any goroutines are leaked (which will be the case if not all references to the real xdsClient being created are not released).
}
```

File: xds/server_test.go [hunk 2]
```diff
@@ -315,6 +315,24 @@ func (p *fakeProvider) Close() {
 	p.Distributor.Stop()
 }
 
+// setupClientOverride sets up an override for new xdsClient creation.
+func setupClientOverride(t *testing.T) func() {
```
Comment (easwars) [inline xds/server_test.go:319]: This code is very similar to what is being done in `setupOverrides`. Can you massage this a bit so that `setupOverrides` calls this, instead of having duplicate code?

File: xds/server.go [hunk 3]
```diff
@@ -332,6 +335,8 @@ func (s *GRPCServer) handleServingModeChanges(updateCh *buffer.Unbounded) {
 // corresponding pending RPCs on the client side will get notified by connection
 // errors.
 func (s *GRPCServer) Stop() {
+	s.clientMu.Lock()
+	defer s.clientMu.Unlock()
```
Comment (easwars) [inline xds/server.go:339]: Would it work if we hold the lock only around `s.quit.Fire()`? Same comment applies to `GracefulStop` as well.

File: xds/server_test.go (hunk 1 above)
Comment (zasweq) [reply xds/server_test.go:929]: Ok I had this same thought. I had option 1 but wanted to wrap the operation with a timeout, since it could possibly hang if it doesn't hit the error and does the while true, and then we have to wait for the test to hit 7 minute timeout. I think the simplicity of just doing err := server.Serve. Hmmmmm ok I never thought about testing with the leak checker. Oh I didn't want to call Serve before Close in a test because I didn't want to send an LDS response so it can call into server.Server in grpc, but thinking about it you don't need a good LDS response, because it will receive from this quit here to exit: https://github.com/grpc/grpc-go/blob/master/xds/server.go#L270, and will already have refed the client conn up 1, which is the part that is interesting to test. Will switch to err := server.Serve and implement your test.

File: xds/server.go (hunk 3 above)
Comment (zasweq) [reply xds/server.go:339]: I don't think so. If you don't protect xdsC and xdsClientClose in the mutex, you can get a write in initXDSClient() and a read in Stop(), which gives you corrupted memory. Also, I think it makes sense to do this processing of the whole (client create/increase ref) and (decrease ref client close if set)  atomically, serially rather than interspliced.

File: xds/server_test.go (hunk 2 above)
Comment (zasweq) [reply xds/server_test.go:319]: Good point. Done.

Comment (zasweq) [reply xds/server_test.go:319]: Actually, I messed with it, and I think it's different enough to warrant a separate helper. The one already in the codebase sends a ref to the channel, and this one doesn't. Thoughts?

Comment (easwars) [reply xds/server_test.go:319]: I would be OK to ignore the returned channel in the case where you don't need it.

File: xds/server.go (hunk 3 above)
Comment (easwars) [reply xds/server.go:339]: My only concern was that we are holding the lock when calling `gs.Stop()` which is a blocking call. But I guess its OK, since the xDS enabled server is being closed at this point, and its not a big deal if we hold the lock and block while the underlying grpc server is being closed.

File: xds/server_test.go (hunk 1 above)
Comment (easwars) [reply xds/server_test.go:929]: Ack.

File: xds/server.go (hunk 3 above)
Comment (zasweq) [reply xds/server.go:339]: Ok, sounds good. Yeah blocking a simultaneous Serve() call seems ok, especially since in other components we process whole events serially through patterns such as a run() goroutine.

File: xds/server_test.go (hunk 2 above)
Comment (zasweq) [reply xds/server_test.go:319]: I agree, but the problem is this newXDSClient is called once, and performs a blocking send. Thus, my test would block forever unless I took I took a local arg to returned channel and received. I can do this if you feel strongly, but it seems like different enough logic to warrant a separate helper for simplicity.

Comment (easwars) [reply xds/server_test.go:319]: Oki dokies. Feel free to leave it as is.

Comment (zasweq) [reply xds/server_test.go:319]: Even in this test case I'm writing for race conditions, I think I want this one. Otherwise in each iteration for the for, I would need to recv from the channel to unblock the newXDSClient(), which would add a lot of code.

File: xds/server_test.go [hunk 4]
```diff
@@ -890,3 +909,50 @@ func verifyCertProviderNotCreated() error {
...
+
+	server.Stop()
+	err = server.Serve(lis)
+	if err == nil || !strings.Contains(err.Error(), grpc.ErrServerStopped.Error()) {
+		t.Fatalf("server erorred with wrong error, want: %v, got :%v", grpc.ErrServerStopped, err)
+	}
+}
+
+// TestServeAndCloseDoNotRace tests that Serve and Close on the xDS Server do
+// not race and leak the xDS Client. A race would be found by the leak checker.
```
Comment (easwars) [inline xds/server_test.go:933]: Nit: the leak would be found by the leak checker and not the race :)

**Review by easwars — APPROVED** [review]

File: xds/server_test.go (hunk 4 above)
Comment (zasweq) [reply xds/server_test.go:933]: Hahahaha fair. Switched.
