### PR TITLE
encoding/proto: do not panic when types do not match

### LINKED ISSUE #4213: [Flatbuffers codec] Content-subtype only set for go lang
Hello, 

 I am working on updating the flatbuffers Grpc support to v1.35.0 for all the languages that are implemented. However I am facing a small issue, whenever I try to make different languages communicate the go server would usually crash. Since I was told all the other languages actually ignore the appended suffix into the `application/grpc+{custom}` where custom is usually removed. I've dig into the code and found out that [processHeaderField func](https://github.com/grpc/grpc-go/blob/c456688b18606b43dcc5a817a05b7585614932d8/internal/transport/http_util.go#L306) has a comment about how it might be better if it was switched to (subtype). 

A suggested solution might be; checking for a `content-subtype` within `f hpack.HeaderField` and if present use that as a codec type/subtype, this can be set by the user as a custom metadata. and if its not it can default back to the `content-type`

It would be really nice to allow the go lang server to communicate with other Flatbuffers implemented clients.
 
 Things I've tried:
 - Communicating with the go server from the following implementations; JS, python, swift.
 - Setting them separately in the languages but that just always gets ignored.

### PR DESCRIPTION
**Pull request by menghanl**
fixes #4213

The type mismatch can happen if
1. user is using a non-proto generated code, so the message is not `proto.Message`
2. the proto codec is picked (e.g. on receiving side, by content-type `application/grpc+subtype`)

### CODE REVIEW

File: encoding/proto/proto.go [hunk 1]
```diff
@@ -36,11 +38,19 @@ func init() {
 type codec struct{}
 
 func (codec) Marshal(v interface{}) ([]byte, error) {
-	return proto.Marshal(v.(proto.Message))
+	vv, ok := v.(proto.Message)
+	if !ok {
+		return nil, fmt.Errorf("failed to marshal, message is %T, want proto", v)
```
Comment (dfawley) [inline encoding/proto/proto.go:43]: nit: `proto.Message`

File: encoding/proto/proto.go [hunk 2]
```diff
@@ -36,11 +38,19 @@ func init() {
...
+	}
+	return proto.Marshal(vv)
 }
 
 func (codec) Unmarshal(data []byte, v interface{}) error {
-	return proto.Unmarshal(data, v.(proto.Message))
+	vv, ok := v.(proto.Message)
+	if !ok {
+		return fmt.Errorf("failed to marshal, message is %T, want proto", v)
```
Comment (dfawley) [inline encoding/proto/proto.go:51]: "*un*marshal", `proto.Message`

**Review by dfawley — APPROVED** [review]

File: encoding/proto/proto.go (hunk 1 above)
Comment (menghanl) [reply encoding/proto/proto.go]: Done

File: encoding/proto/proto.go (hunk 2 above)
Comment (menghanl) [reply encoding/proto/proto.go]: Done
