### PR TITLE
test: fix flaky test ClientSendsAGoAway

### LINKED ISSUE #7160: Flaky test: TestClientSendsAGoAway
This is the first time I'm seeing it: 
https://github.com/grpc/grpc-go/actions/runs/8787418013/job/24112571687?pr=7156

Might be worth to check it out.

### PR DESCRIPTION
**Pull request by aranjans**
Fixes #7160 
fix: `goaway_test/TestClientSendsAGoAway` didn't use to wait for channels to be ready and which is why sometimes it was not able to read the frame and eventually result in test failure. This PR change make sure we read the frame only when the channel's state becomes READY.

RELEASE NOTES: n/a

### CODE REVIEW

File: test/goaway_test.go [hunk 1]
```diff
@@ -816,6 +818,7 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
 			}
 		}
 	}()
+	cc.WaitForStateChange(ctx, connectivity.Connecting)
```
Comment (purnesh42H) [inline test/goaway_test.go:821]: what would be the max wait here? Timeout for all tests is 7m. Is there a chance it can breach that?

**Comment by purnesh42H** [comment]
Probably need some more description about the fix

File: test/goaway_test.go (hunk 1 above)
Comment (aranjans) [reply test/goaway_test.go:821]: Max timeout is as long context is not timed out.

Comment (purnesh42H) [reply test/goaway_test.go:821]: shouldn't the state to wait be `connectivity.Ready`?

Comment (dfawley) [reply test/goaway_test.go:821]: I think it depends where the race is happening.

If there's just a race where we call `Close` before we even start creating the connection, then this is a problem with the test, and `Connecting` should fix that.

If this is a race where a connection is established and doesn't get a GOAWAY written to it (due to internal state in the `ClientConn`/`addrConn`, then `Connecting` will expose that race and we should fix it.

File: test/goaway_test.go [hunk 2]
```diff
@@ -800,6 +800,7 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
 		for {
```
[the remark this answers is not in the document]
Comment (aranjans) [reply test/goaway_test.go:800]: @dfawley we already have a same test with that logic here[https://github.com/grpc/grpc-go/blob/master/internal/transport/transport_test.go#L2666](url). And actually its checking for the same, do you feel we can remove this goaway_test/ClientSendsGoAway as we already have there in transport package or shall we replicate the same here which i don't think makes sense IMO?

[the remark this answers is not in the document]
Comment (dfawley) [reply test/goaway_test.go:800]: I am not sure I understand what you're getting at.

I'm just saying this test seems to do some unnecessary work and is more complicated than it needs to be.

The other test you added is inside the transport layer, and testing at the API layer, which this test does, is _generally_ preferred.

**Comment by dfawley** [comment]
From chat offline:

> Actually, this structure of the test actually proves there is a bug here that I don't think you're fixing
> If a connection is created, we want it to reliably get a goaway.  We know a connection exists otherwise we won't get to this part of the code, because the channel passes it along

So I think the test is correct (though it can still be simplified), but there is a race in the code that prevents the GOAWAY from being sent in some cases.

File: test/goaway_test.go (hunk 1 above)
Comment (aranjans) [reply test/goaway_test.go:821]: @purnesh42H WaitForStateChange waits until the connectivity.State of ClientConn changes from sourceState or ctx expires. A true value is returned in former case and false in latter. So we are providing sourceState as Connecting and hence it will wait until state changes.

File: test/goaway_test.go [hunk 3]
```diff
@@ -800,6 +800,7 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
...
 			f, err := ct.fr.ReadFrame()
 			if err != nil {
+				t.Logf("error reading frame: %v", err)
```
[the remark this answers is not in the document]
Comment (aranjans) [reply test/goaway_test.go:803]: Updated

File: test/goaway_test.go (hunk 1 above)
Comment (aranjans) [reply test/goaway_test.go:821]: I think race is detected when client conn is getting closed before we try to send goAway so believe just waiting for clientConn state change will fix this race condition.

File: test/goaway_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (aranjans) [reply test/goaway_test.go:803]: Updated

**Comment by aranjans** [comment]
@dfawley updated the PR

**Comment by aranjans** [comment]
Update: [this](https://github.com/grpc/grpc-go/blob/0020ccf9d9fc448fcfa099173df4ad330e96326c/clientconn.go#L1409) is the code where we are hardcode closing the transport. Will update the PR with the change where we send goAway frame in this case as well.

**Comment by aranjans** [comment]
@dfawley As per our discussion offline, we won't be waiting for all the transport conn to close down. So this PR's change is ready to review as it just makes sure we are waiting for the clientconn to be READY.

File: test/goaway_test.go [hunk 4]
```diff
@@ -816,8 +800,40 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
 			}
 		}
 	}()
+	defer lis.Close()
```
Comment (dfawley) [inline test/goaway_test.go:803]: This belongs next to the creation of the listener.

File: test/goaway_test.go [hunk 5]
```diff
@@ -816,8 +800,40 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
...
+
+	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
+	if err != nil {
+		t.Fatalf("error dialing: %v", err)
+	}
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+
+	//go func() {
```
Comment (dfawley) [inline test/goaway_test.go:813]: Delete please

File: test/goaway_test.go [hunk 6]
```diff
@@ -816,8 +800,40 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
...
+	//				return
+	//			}
+	//		default:
+	//			t.Errorf("server tester received unexpected frame type %T", f)
+	//			errCh <- fmt.Errorf("server tester received unexpected frame type %T", f)
+	//			close(errCh)
+	//		}
+	//	}
+	//}()
+	cc.WaitForStateChange(ctx, connectivity.Connecting)
```
Comment (dfawley) [inline test/goaway_test.go:835]: Should be `Ready` now.

Comment (aranjans) [reply test/goaway_test.go:835]: @dfawley `WaitForStateChange` waits until the connectivity.State of ClientConn changes from sourceState or ctx expires.  So aren't we already waiting for conn to be READY here as it would wait until state changes from Connecting?

File: test/goaway_test.go [hunk 7]
```diff
@@ -816,8 +801,17 @@ func (s) TestClientSendsAGoAway(t *testing.T) {
 			}
 		}
 	}()
+
+	cc, err := grpc.Dial(lis.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
```
Comment (purnesh42H) [inline test/goaway_test.go:805]: nit: Shall we use NewClient since Dial is in deprecation stage?

Comment (dfawley) [reply test/goaway_test.go:805]: +1

File: test/goaway_test.go (hunk 6 above)
Comment (dfawley) [reply test/goaway_test.go:813]: You are correct.  Instead you should probably be using `AwaitState(Ready)`:

https://github.com/grpc/grpc-go/blob/master/internal/testutils/state.go#L58

File: test/goaway_test.go (hunk 7 above)
Comment (aranjans) [reply test/goaway_test.go]: Updated.

File: test/goaway_test.go (hunk 6 above)
Comment (aranjans) [reply test/goaway_test.go]: Updated.

**Review by dfawley — APPROVED** [review]
