### PR TITLE
credentials: add end-to-end tests for JWT call credentials behavior

### LINKED ISSUE #8635: Add an e2e style test to verify meaningful RPC error when using insecure transport creds with A97 JWT call creds
As part of gRFC A97, we are adding support for JWT call credentials that can be configured via xDS. We are also adding a general purpose mechanism where we can support multiple call credentials specified in the bootstrap configuration.

If one of these call credentials requires a secure transport, but an insecure transport is configured, we expect the RPC to fail.

We need an e2e style test to verify that when this happens, a meaningful error is returned to the user as part of the RPC.

### PR DESCRIPTION
**Pull request by iamrajiv**
This adds e2e style tests to verify that when JWT call credentials (which require transport security) are used with an insecure transport, the RPC fails with a meaningful error as expected per gRFC A97. 

Fixes #8635

RELEASE NOTES: none

### CODE REVIEW

File: credentials/jwt/jwt_e2e_test.go [hunk 1]
```diff
@@ -0,0 +1,258 @@
...
+	}
+	return filePath
+}
+
+// TestJWTCallCredentials_InsecureTransport_AsCallOption verifies that when JWT
+// call credentials (which require transport security) are used with an insecure
+// transport as a per-RPC call option, the RPC fails with a meaningful error.
+//
+// This is an e2e test for gRFC A97 JWT call credentials behavior.
+func (s) TestJWTCallCredentials_InsecureTransport_AsCallOption(t *testing.T) {
```
Comment (Pranjali-2501) [inline credentials/jwt/jwt_e2e_test.go]: Can you convert all three e2e tests into a single table driven test. They share the same setup logic and consolidating them would reduce the boilerplate code. 

https://go.dev/wiki/TableDrivenTests

File: credentials/jwt/jwt_e2e_test.go [hunk 2]
```diff
@@ -0,0 +1,258 @@
...
+type s struct {
+	grpctest.Tester
+}
+
+func Test(t *testing.T) {
+	grpctest.RunSubTests(t, s{})
+}
+
+// createTestJWT creates a test JWT token with the specified expiration.
+func createTestJWT(t *testing.T, expiration time.Time) string {
```
Comment (Pranjali-2501) [inline credentials/jwt/jwt_e2e_test.go]: We can eliminate the duplicate helper functions (i.e.   `createTestJWT` and `writeTempTokenFile`) by moving the e2e tests to the existing `token_file_call_creds_test.go` test file.

File: credentials/jwt/token_file_call_creds_test.go [hunk 3]
```diff
@@ -507,6 +516,131 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+				serverCert, err := tls.LoadX509KeyPair(
+					testdata.Path("x509/server1_cert.pem"),
+					testdata.Path("x509/server1_key.pem"),
+				)
+				if err != nil {
+					t.Fatalf("Failed to load server cert: %v", err)
+				}
+				serverOpts = append(serverOpts, grpc.Creds(credentials.NewServerTLSFromCert(&serverCert)))
+
+				clientCreds, err = credentials.NewClientTLSFromFile(
```
Comment (Pranjali-2501) [inline credentials/jwt/token_file_call_creds_test.go]: Nit: Please keep this in a single line.

File: credentials/jwt/token_file_call_creds_test.go [hunk 4]
```diff
@@ -507,6 +516,131 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+			useTLS:         false,
+			credsAsDialOpt: true,
+			wantErr:        "the credentials require transport level security",
+		},
+		{
+			name:           "secure_transport_success",
+			useTLS:         true,
+			credsAsDialOpt: true,
+			wantErr:        "",
+		},
```
Comment (Pranjali-2501) [inline credentials/jwt/token_file_call_creds_test.go]: Could you please add a testcase to test JWT credentials as a Call Option over TLS.

File: credentials/jwt/token_file_call_creds_test.go [hunk 5]
```diff
@@ -507,6 +516,131 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+			name:           "insecure_transport_creds_as_dial_option",
+			useTLS:         false,
+			credsAsDialOpt: true,
+			wantErr:        "the credentials require transport level security",
+		},
+		{
+			name:           "secure_transport_success",
+			useTLS:         true,
+			credsAsDialOpt: true,
+			wantErr:        "",
```
Comment (Pranjali-2501) [inline credentials/jwt/token_file_call_creds_test.go]: We can remove `wantErr` from this happy testcase.

File: credentials/jwt/token_file_call_creds_test.go [hunk 6]
```diff
@@ -507,6 +516,131 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+						return nil, fmt.Errorf("authorization header mismatch: got %v, want %q", authHeaders, expectedAuth)
+					}
+					return &testpb.Empty{}, nil
+				},
+			}
+
+			var serverOpts []grpc.ServerOption
+			var clientCreds credentials.TransportCredentials
+			if tt.useTLS {
+				serverCert, err := tls.LoadX509KeyPair(
```
Comment (Pranjali-2501) [inline credentials/jwt/token_file_call_creds_test.go]: Nit: keeping this on a single line would look a bit cleaner since it fits reasonably well.

**Review by Pranjali-2501 — APPROVED** [review]
The test looks good to me. I have minor nits.

**Comment by Pranjali-2501** [comment]
@easwars ,  assigning it to you for second review.

File: credentials/jwt/token_file_call_creds_test.go
Comment (easwars) [inline credentials/jwt/token_file_call_creds_test.go:1]: Would you mind moving this test to a new file `credentials/jwt/token_file_call_creds_ext_test.go` and have it be in a separate test_only package `jwt_test`. This will ensure that the test does not inadvertently use any of the internals of the package.

Comment (easwars) [reply credentials/jwt/token_file_call_creds_test.go:1]: I also realized that if we do that we will have to copy over helper functions like `createTestJWT`. This is fine. Eventually, we want all tests to live in this test_only package.

File: credentials/jwt/token_file_call_creds_test.go [hunk 7]
```diff
@@ -507,6 +516,129 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+		t.Run(tt.name, func(t *testing.T) {
+			token := createTestJWT(t, time.Now().Add(time.Hour))
+			tokenFile := writeTempFile(t, "token", token)
+
+			jwtCreds, err := NewTokenFileCallCredentials(tokenFile)
+			if err != nil {
+				t.Fatalf("NewTokenFileCallCredentials(%q) failed: %v", tokenFile, err)
+			}
+
+			expectedAuth := "Bearer " + token
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_test.go]: Nit: s/expectedAuth/wantAuth or `wantAuthHeader`. See: https://google.github.io/styleguide/go/decisions#got-before-want

File: credentials/jwt/token_file_call_creds_test.go [hunk 8]
```diff
@@ -507,6 +516,129 @@ func (s) TestTokenFileCallCreds_BackoffBehavior(t *testing.T) {
...
+		},
+		{
+			name:           "secure_transport_creds_as_call_option",
+			useTLS:         true,
+			credsAsDialOpt: false,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_test.go]: I feel the test logic is too complicated because of having to handle all possible conditions specified in the test table.

See: https://google.github.io/styleguide/go/decisions#table-driven-tests, and specifically the paragraph that says:
When some test cases need to be checked using different logic from other test cases, it is appropriate to write multiple test functions, as explained in [GoTip #50: Disjoint Table Tests](https://google.github.io/styleguide/go/index.html#gotip).

Unfortunately the link to the GoTip episode is still work in progress, but I'm guessing you get the idea. It would be better to split this test up into more focussed ones (there could still be some possibility of having a table in there, but with lesser number of options), such that the test logic in each of them is very simple and straight-forward. The motivation here is that when a test fails, it should be very easy for person who is debugging the failure to understand the test logic and go about fixing it.

**Comment by easwars** [comment]
@iamrajiv I'm sorry. I just realized that some of my comments are in direct contradiction to some of the previous comments made as part of the review process and now you are having to do double work.

**Comment by iamrajiv** [comment]
No worries at all, @easwars! I appreciate the thorough review. The feedback to split into focused tests makes sense it's much cleaner and easier to debug now. Thanks for taking the time to review!

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 9]
```diff
@@ -0,0 +1,271 @@
+/*
+ *
+ * Copyright 2025 gRPC authors.
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go]: Nit: This needs to `2026` now.

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 10]
```diff
@@ -0,0 +1,271 @@
...
+	cc, err := grpc.NewClient(ss.Address, grpc.WithTransportCredentials(insecure.NewCredentials()))
+	if err != nil {
+		t.Fatalf("grpc.NewClient(%q) failed: %v", ss.Address, err)
+	}
+	defer cc.Close()
+
+	ctx, cancel := context.WithTimeout(context.Background(), defaultTestTimeout)
+	defer cancel()
+
+	client := testgrpc.NewTestServiceClient(cc)
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go:76]: Nit: Please consider defining a `const wantErr = "cannot send secure credentials on an insecure connection"`. That way, the subsequent conditional statement and the error string will be shorter and easier to read.

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 11]
```diff
@@ -0,0 +1,271 @@
...
+	_, err = client.EmptyCall(ctx, &testpb.Empty{}, grpc.PerRPCCredentials(jwtCreds))
+
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go]: Nit: Nix this newline.

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 12]
```diff
@@ -0,0 +1,271 @@
...
+		t.Fatalf("NewTokenFileCallCredentials(%q) failed: %v", tokenFile, err)
+	}
+
+	ss := &stubserver.StubServer{}
+	if err := ss.StartServer(grpc.Creds(insecure.NewCredentials())); err != nil {
+		t.Fatalf("Failed to start server: %v", err)
+	}
+	defer ss.Stop()
+
+	_, err = grpc.NewClient(ss.Address,
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go]: Please don't break up lines this way. Please see the "Line length" section of the style guide: cannot send secure credentials on an insecure connection

This line is short enough to be on a single line. In other places where we have to pass a *lot* of dial options, we usually define a slice of dial options right before the call to `NewClient` and pass that slice to it.

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 13]
```diff
@@ -0,0 +1,271 @@
...
+		grpc.WithTransportCredentials(insecure.NewCredentials()),
+		grpc.WithPerRPCCredentials(jwtCreds),
+	)
+
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go]: Nit: Same here. Nix newline.

File: credentials/jwt/token_file_call_creds_ext_test.go [hunk 14]
```diff
@@ -0,0 +1,271 @@
...
+		t.Fatalf("Failed to start server: %v", err)
+	}
+	defer ss.Stop()
+
+	clientCreds, err := credentials.NewClientTLSFromFile(testdata.Path("x509/server_ca_cert.pem"), "x.test.example.com")
+	if err != nil {
+		t.Fatalf("Failed to create client TLS credentials: %v", err)
+	}
+
+	cc, err := grpc.NewClient(ss.Address,
```
Comment (easwars) [inline credentials/jwt/token_file_call_creds_ext_test.go]: Same here too about being on a single line.

File: credentials/jwt/token_file_call_creds_test.go
Comment (easwars) [inline credentials/jwt/token_file_call_creds_test.go:1]: This file doesn't seem to have any code changes, but the file mode has been changed. Could you please revert the file mode changes. Thanks.

**Review by easwars — COMMENTED** [review]
Changes look good to me. Just a bunch of minor nits this time around.
