### PR TITLE
Fix onclose state transition

### LINKED ISSUE #2340: connectivity state: missing transition from READY to TRANSIENT FAILURE
Right now, when the client transport gets closed, it will trigger `resetTransport` which will sets connectivity state directly to `CONNECTING`. As specified by the connectivity spec, `READY` to `CONNECTING` is not a valid transition, so we need to add a transition from `READY` to `TRANSIENT FAILURE` for this type of case (i.e `READY`->`TRANSIENT FAILURE`->`CONNECTING`.

### LINKED ISSUE #2341: waitForHandshake: when onClosedCalled, ac should not transition into READY state
When `waitForHandshake` is set to true, the `addrConn` should not transition into `READY` state when the preface has not been received. In current code, if the underlying transport closes the connection, the [`onCloseCalled`](https://github.com/grpc/grpc-go/blob/b48e364c83c8b7a222f4b43cf5348b3583950ac6/clientconn.go#L1110) case will be unblocked, and will lead to the `addrConn`'s state being transitioned into `READY` state, which is not the correct behavior.

### PR DESCRIPTION
**Pull request by jadekler**
When onClose occurs during WaitForHandshake, it should immediately
exit createTransport instead of leaving CONNECTING and entering READY.

Furthermore, when any onClose happens, the state should change to
TRANSIENT FAILURE.

Fixes #2340
Fixes #2341

Also fixes an unreported bug in which entering READY causes a
Dial call to end prematurely, instead of blocking until a READY
transport is found.

### CODE REVIEW

**Comment by jadekler** [comment]
@lyuxuan I put the test into end2end_test because it seems as though the existence of other grpc servers causes parents to be set, but I did not end up using the grpc server since it was easier to use the `net.Listener` code I already had. WDYT, is that ok? It doesn't need more than that, so it seems nice to keep it simple.

**Comment by jadekler** [comment]
PTAL, new and updated to fix both bugs, and a new test that introspects the transport state periodically instead of relying on channelz.

File: clientconn_test.go [hunk 1]
```diff
@@ -820,3 +820,128 @@ func TestBackoffCancel(t *testing.T) {
 	cc.Close()
 	// Should not leak. May need -count 5000 to exercise.
 }
+
+type signalingBackoffStrategy struct {
+	ready chan struct{}
+}
+
+func (bs *signalingBackoffStrategy) Backoff(retries int) time.Duration {
```
Comment (dfawley) [inline clientconn_test.go]: This doesn't seem like the right way to do this..  We consult the `Backoff()` at the start of an iteration, and it's just a coincidence that we're setting the state to `Connecting` _after_ calling `Backoff()`.  If those were flipped, then you would probably miss the `TransientFailure` state, or at least it would be a race.

I was picturing a backoff time of <minutes>, and the signal to unblock would be a call to `cc.ResetConnectBackoff()`

File: clientconn_test.go [hunk 2]
```diff
@@ -820,3 +820,128 @@ func TestBackoffCancel(t *testing.T) {
...
+	defer client.Close()
+	// This has to happen before client.Close, or client.Close will hang forever waiting for backoff to complete.
+	defer close(exitBackoff)
+
+	if client.GetState() != connectivity.Ready {
+		t.Fatalf("expected addrconn to be in READY, was %v", client.GetState())
+	}
+
+	close(killFirstConnection)
+	time.Sleep(100 * time.Millisecond)
```
Comment (dfawley) [inline clientconn_test.go]: Please use `cc.WaitForStateChange` or else this will be racy and/or sleep unnecessarily.

File: clientconn_test.go (hunk 1 above)
Comment (jadekler) [reply clientconn_test.go]: Done.

File: clientconn_test.go (hunk 2 above)
Comment (jadekler) [reply clientconn_test.go]: So, because I now properly use withBackoff(infiniteBackoff{}), there's another problem here: the first backoff after a successful handshake is skipped and reconnection immediately happens.

That means that I have to add another Accept->close pair to the server to get to the infinite backoff (from `close -> Accept -> signal blocks` to `close -> Accept -> client connects immediately -> close -> Accept -> backoff blocks`).

So, now when I do `close(killFirstConnection)`, the state transition is: 

```
READY -> CONNECTING -> TRANSIENT FAILURE (no backoff) -> CONNECTING -> TRANSIENT FAILURE (infinite backoff)
```

This all happens _really_ fast. When I try to write code that manually follows these five transitions, my test fails 50% of the time. I added `sleep(50ms)` to just skip over all of them. It's not great, but I don't have a better idea. It worked 100% of the time when I did `-cpu 1,4 -count 1000` locally, FWIW.

File: clientconn_test.go [hunk 3]
```diff
@@ -820,3 +820,126 @@ func TestBackoffCancel(t *testing.T) {
 	cc.Close()
 	// Should not leak. May need -count 5000 to exercise.
 }
+
+// CONNECTING -> READY -> TRANSIENT FAILURE -> CONNECTING -> TRANSIENT FAILURE -> CONNECTING -> TRANSIENT FAILURE
+func TestDialCloseStateTransition(t *testing.T) {
+	defer leakcheck.Check(t)
+
+	server, err := net.Listen("tcp", "localhost:0")
```
Comment (dfawley) [inline clientconn_test.go]: Nit: this is a listener not a server, so s/server/lis/.  (It's helpful to follow a convention things like this.)

File: clientconn_test.go [hunk 4]
```diff
@@ -820,3 +820,126 @@ func TestBackoffCancel(t *testing.T) {
...
+		// WaitForHandshake at this point because the preface has not been sent yet.
+		select {
+		case <-testFinished:
+			return
+		case <-killSecondConnection:
+		}
+		conn.Close()
+	}()
+
+	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
```
Comment (dfawley) [inline clientconn_test.go]: How about something longer, like 10s, to avoid flakes in case Travis is feeling sleepy that day?

File: test/channelz_test.go [hunk 5]
```diff
@@ -1343,7 +1343,7 @@ func TestCZSubChannelTraceCreationDeletion(t *testing.T) {
 			return false, fmt.Errorf("there should be at least one trace event for subChannel not 0")
 		}
 		if scm.Trace.Events[len(scm.Trace.Events)-1].Desc != "Subchannel Deleted" {
```
Comment (dfawley) [inline test/channelz_test.go]: This is the pattern that avoids errors like this in the future:

```go
if got := ......; got != "Subchannel Deleted" {
  return false, fmt.Errorf(..... , got)
}
```

File: clientconn.go [hunk 6]
```diff
@@ -643,11 +643,9 @@ func (cc *ClientConn) incrCallsFailed() {
 	atomic.AddInt64(&cc.czData.callsFailed, 1)
 }
 
-// connect starts to creating transport and also starts the transport monitor
-// goroutine for this ac.
+// connect starts to creating transport.
```
Comment (dfawley) [inline clientconn.go]: "connect starts creating a transport"?

File: clientconn_test.go [hunk 7]
```diff
@@ -893,25 +896,29 @@ func TestDialCloseStateTransition(t *testing.T) {
...
 
-	client, err := DialContext(ctx, server.Addr().String(), WithInsecure(), WithWaitForHandshake(), WithBlock(), withBackoff(backoffForever{}))
+	client, err := DialContext(ctx, lis.Addr().String(), WithInsecure(), WithWaitForHandshake(), WithBlock(), withBackoff(backoffForever{}))
 	if err != nil {
 		t.Fatal(err)
 	}
 	defer client.Close()
 
-	// It should start in READY because the server sends the server preface.
+	// It should start in READY because the lis sends the lis preface.
```
Comment (dfawley) [inline clientconn_test.go]: The problem with `sed`...  ;)

File: clientconn_test.go [hunk 8]
```diff
@@ -893,25 +896,29 @@ func TestDialCloseStateTransition(t *testing.T) {
...
 	if client.GetState() != connectivity.Ready {
 		t.Fatalf("expected addrconn to be in READY, was %v", client.GetState())
 	}
 
 	// Once the connection is killed, it should go:
 	// READY -> CONNECTING -> TRANSIENT FAILURE (no backoff) -> CONNECTING -> TRANSIENT FAILURE (infinite backoff)
-	// We tend to miss the middle transitions, since they are racy, so we'll sleep through them.
+	// The first TRANSIENT FAILURE is triggered by closing a channel. Then, we wait for the lis to let us know
```
Comment (dfawley) [inline clientconn_test.go]: again, over-aggressive search&replace.

File: test/channelz_test.go [hunk 9]
```diff
@@ -1342,8 +1342,8 @@ func TestCZSubChannelTraceCreationDeletion(t *testing.T) {
 		if len(scm.Trace.Events) == 0 {
 			return false, fmt.Errorf("there should be at least one trace event for subChannel not 0")
 		}
-		if scm.Trace.Events[len(scm.Trace.Events)-1].Desc != "Subchannel Deleted" {
-			return false, fmt.Errorf("the last trace event should be \"Subchannel Deleted\", not %q", scm.Trace.Events[len(scm.Trace.Events)-1].Desc)
+		if got, want := scm.Trace.Events[len(scm.Trace.Events)-1].Desc, "Subchannel Deleted"; got != want {
+			return false, fmt.Errorf("the last trace event should be \"%s\", not %q", want, scm.Trace.Events[len(scm.Trace.Events)-1].Desc)
```
Comment (dfawley) [inline test/channelz_test.go]: `got`?

File: clientconn_test.go [hunk 10]
```diff
@@ -820,3 +820,129 @@ func TestBackoffCancel(t *testing.T) {
...
+	}
+
+	// Once the connection is killed, it should go:
+	// READY -> CONNECTING -> TRANSIENT FAILURE (no backoff) -> CONNECTING -> TRANSIENT FAILURE (infinite backoff)
+	// The first TRANSIENT FAILURE is triggered by closing a channel. Then, we wait for the lis to let us know
+	// when the client has progressed past the first failure (which does not get backoff, because handshake was
+	// successful).
+	close(killFirstConnection)
+	<-backoffCaseReady
+	client.WaitForStateChange(ctx, connectivity.TransientFailure)
```
Comment (dfawley) [inline clientconn_test.go]: I don't think this line is necessary / may be racy.

We _should_ be in `Connecting` - or already in `TransientFailure` caused by the server closing the connection.  If we hit the latter case, this will block until `ctx` expires.

Comment (jadekler) [reply clientconn_test.go]: Done.

File: test/channelz_test.go (hunk 9 above)
Comment (jadekler) [reply test/channelz_test.go]: Just a pattern we use in google-cloud-go to compare what we got vs what we wanted to get. Do you prefer a different name?

File: clientconn_test.go (hunk 8 above)
Comment (jadekler) [reply clientconn_test.go]: Done.

File: clientconn_test.go (hunk 7 above)
Comment (jadekler) [reply clientconn_test.go]: Shoot. Done.

File: clientconn.go (hunk 6 above)
Comment (jadekler) [reply clientconn.go]: Done.

File: test/channelz_test.go (hunk 9 above)
Comment (jadekler) [reply test/channelz_test.go]: Done!

File: clientconn.go [hunk 11]
```diff
@@ -1057,6 +1055,16 @@ func (ac *addrConn) createTransport(backoffNum int, addr resolver.Address, copts
 
 	onClose := func() {
 		close(onCloseCalled)
+
+		ac.mu.Lock()
+		if ac.state == connectivity.Shutdown {
```
Comment (dfawley) [inline clientconn.go]: As discussed, I believe this should only be done in the allowedToReset case below.  Otherwise the state will go:

Connecting -> Transient Failure -> Connecting -> Transient Failure -> ...

for any addrConn with multiple addresses as each dial attempt within the list fails.  We should stay in Connecting until we get to the very end of the list or succeeds.

I think we also should only be doing it if we received the preface - unless we are currently trying the last address in the list.

Comment (jadekler) [reply clientconn.go]: Hey! I just got an update out that I think mostly resolves this issue, but I need to take another pass over it to double check. In the meantime, let me know what you think.

File: clientconn.go [hunk 12]
```diff
@@ -963,6 +961,21 @@ func (ac *addrConn) resetTransport(resolveNow bool) {
 			ac.mu.Unlock()
 		}
 
+		ac.mu.Lock()
+		if ac.state == connectivity.Shutdown {
+			ac.mu.Unlock()
+			return
+		}
+
+		// If we're at the beginning of the address list
```
Comment (dfawley) [inline clientconn.go]: This comment is backwards -- we are at the end here.

File: clientconn.go [hunk 13]
```diff
@@ -963,6 +961,21 @@ func (ac *addrConn) resetTransport(resolveNow bool) {
...
+		// And we didn't just see a successful handshake
+		// And it's not the very first addr to try (covered by the above if)
+		if ac.addrIdx == len(ac.addrs)-1 && !ac.successfulHandshake {
+			ac.updateConnectivityState(connectivity.TransientFailure)
```
Comment (dfawley) [inline clientconn.go]: Is this the only time we'll set TransientFailure?  We want to make sure we set it whenever the current state is Ready and a connection error occurs, which I believe this will not do.

File: clientconn_test.go [hunk 14]
```diff
@@ -820,3 +820,135 @@ func TestBackoffCancel(t *testing.T) {
...
+		t.Fatalf("expected addrconn state to be %v, was %v", want, got)
+	}
+
+	// Once the connection is killed, it should go:
+	// READY -> CONNECTING -> TRANSIENT FAILURE (no backoff) -> CONNECTING -> TRANSIENT FAILURE (infinite backoff)
+	// The first TRANSIENT FAILURE is triggered by closing a channel. Then, we wait for the server to let us know
+	// when the client has progressed past the first failure (which does not get backoff, because handshake was
+	// successful).
+	close(killFirstConnection)
+	client.WaitForStateChange(ctx, connectivity.Ready)
```
Comment (dfawley) [inline clientconn_test.go]: We should probably be checking the return value of all of these calls, unfortunately.  Maybe a helper function that you also pass `t` to to avoid making the code full of `if !WFSC { Fatal }`s?  It would be a good chance to try out `T.Helper()` (which I only learned about recently, at least).

Comment (jadekler) [reply clientconn_test.go]: My thinking here was that the return value doesn't really tell us much. AFAICT, right after close(killFirstConnection), the connection could be in any part of READY -> TRANSIENT FAILURE -> CONNECTING -> TRANSIENT FAILURE.

I can't guarantee that it will be in READY when I begin waiting, I only want to make sure it's _not_  going to start asserting making the TRANSIENT FAILURE assertion until we know for sure it's the second one, not the first one.

Now that I write that out, I see a cleaner way to write this out. Instead of:

```
close(killFirstConnection)
client.WaitForStateChange(ctx, connectivity.Ready)
client.WaitForStateChange(ctx, connectivity.Connecting)
<-backoffCaseReady
client.WaitForStateChange(ctx, connectivity.Connecting)
if got, want := client.GetState(), connectivity.TransientFailure; got != want {
	t.Fatalf("expected addrconn state to be %v, was %v", want, got)
}
```

We can write:

```
close(killFirstConnection)
client.WaitForStateChange(ctx, connectivity.Ready)
client.WaitForStateChange(ctx, connectivity.TransientFailure)
client.WaitForStateChange(ctx, connectivity.Connecting)
if got, want := client.GetState(), connectivity.TransientFailure; got != want {
	t.Fatalf("expected addrconn state to be %v, was %v", want, got)
}
```

WDYT? I've tested it with `-cpu 1,4 -count 10000` and it seems ok.

File: clientconn.go (hunk 13 above)
Comment (jadekler) [reply clientconn.go]: Ah - I didn't know that. A few questions:

- Is there a definitive flow diagram somewhere I can consult? I've looked around in grpc/grpc-go/Documentation and grpc/grpc/doc and didn't see anything at first glance.

- The flow diagram would probably answer this, but is this the correct set of cases where we should transition into TRANSIENT FAILURE:

  ```
  - Any time a READY connection experiences a retryable error (onClose and onGoAway).
  - Any time we try and fail to dial the full list of addresses.
   ```

^ if the above is correct, I think I can do:

```
if ac.state == connectivity.Ready || (ac.addrIdx == len(ac.addrs)-1 && ac.state == connectivity.Connecting) {
  ac.updateConnectivityState(connectivity.TransientFailure)
  ac.cc.handleSubConnStateChange(ac.acbw, ac.state)
}
```

This would cover:

- State is ready (if we got to the beginning of the retry loop with READY, that means onGoAway or onClose occurred)
- State is connecting and we reached the end of the address list

Comment (dfawley) [reply clientconn.go]: > Is there a definitive flow diagram somewhere I can consult? I've looked around in grpc/grpc-go/Documentation and grpc/grpc/doc and didn't see anything at first glance.

There is a table of valid transitions for the channel (ClientConn) (but not a sub-channel (addrConn)) in grpc/doc, but not a full flow control diagram.  In fact, this particular situation doesn't happen in the other languages.  I have a meeting set up for later this week to discuss it with the other language leads.

What you're suggesting behavior-wise seems to make sense.

That said, if what you're doing now is the same as what we were doing before this change, then I think we should leave it so this can be purely a bug fix.

File: clientconn_test.go [hunk 15]
```diff
@@ -820,3 +820,143 @@ func TestBackoffCancel(t *testing.T) {
...
+func TestDialCloseStateTransition(t *testing.T) {
+	defer leakcheck.Check(t)
+
+	lis, err := net.Listen("tcp", "localhost:0")
+	if err != nil {
+		t.Fatalf("Error while listening. Err: %v", err)
+	}
+	defer lis.Close()
+	testFinished := make(chan struct{})
+	backoffCaseReady := make(chan struct{}, 1)
```
Comment (dfawley) [inline clientconn_test.go]: Can this be an unbuffered struct that is closed instead?

File: test/channelz_test.go [hunk 16]
```diff
@@ -1342,8 +1342,8 @@ func TestCZSubChannelTraceCreationDeletion(t *testing.T) {
 		if len(scm.Trace.Events) == 0 {
 			return false, fmt.Errorf("there should be at least one trace event for subChannel not 0")
 		}
-		if scm.Trace.Events[len(scm.Trace.Events)-1].Desc != "Subchannel Deleted" {
-			return false, fmt.Errorf("the first trace event should be \"Subchannel Deleted\", not %q", scm.Trace.Events[0].Desc)
+		if got, want := scm.Trace.Events[len(scm.Trace.Events)-1].Desc, "Subchannel Deleted"; got != want {
+			return false, fmt.Errorf("the last trace event should be \"%s\", not %q", want, got)
```
Comment (dfawley) [inline test/channelz_test.go]: `\"%s\"` --> `%q`

Comment (jadekler) [reply test/channelz_test.go]: Done

File: clientconn_test.go (hunk 15 above)
Comment (jadekler) [reply clientconn_test.go]: Done

File: clientconn.go (hunk 13 above)
Comment (jadekler) [reply clientconn.go]: Done - it seems to do so in 8ce7e6babb5ad539d8448d25aaba0708af2626ed. Also, put the logic I suggested in with a minor addition of making sure we're also checking for first attempt.
