### PR TITLE
fix: does not validate metadata keys and values

### LINKED ISSUE #468: Go does not validate metadata keys and values
HTTP has restrictions on what characters may be used in headers. For example, newline and control characters are strictly prohibited. In addition, gRPC has additional restrictions and by not enforcing them grpc-go makes it much more likely users will create grpc services that _can't_ be used with the other implementations, because they rely on invalid keys or values.

Enforcing the HTTP restrictions _must_ be done, but it would also make sense to enforce gRPC's metadata restrictions.

https://github.com/grpc/grpc-go/blob/master/metadata/metadata.go#L63
https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L334

### PR DESCRIPTION
**Pull request by Patrick0308**
validate grpc metadata to ensure grpc to follow http standards

close #468

RELEASE NOTES: 
- TBD

### CODE REVIEW

**Comment by easwars** [comment]
Based on https://github.com/grpc/grpc-go/issues/468#issuecomment-309570943, I'm guessing we also need to change client and server side header sending routines to perform this validation.

@Patrick0308 
Was your plan to also do those changes?

Also, it would be better if a regex is used instead of manually checking every character in the metadata key/value.

**Comment by dfawley** [comment]
> Also, it would be better if a regex is used instead of manually checking every character in the metadata key/value.

I wouldn't be certain of this.  Regexes are probably going to be slower.  We'd want to do some performance testing if this is done per-RPC (which it probably should).

**Comment by Patrick0308** [comment]
@easwars Yeah, I'll do it.

**Comment by Patrick0308** [comment]
@dfawley @easwars PTAL

**Comment by dfawley** [comment]
> @dfawley @easwars PTAL

Looks like we also need this validation in `stream.go:(*ClientConn).NewStream`

@menghanl it seems to me this validation should just be private to the `grpc` package, instead of a method on the metadata itself.  WDYT?  And did you say you found a function we can use for this in a stdlib package?

**Comment by menghanl** [comment]
Moving this to a private package sounds good.

There's no function does exactly what we want.
We can use https://pkg.go.dev/unicode#IsDigit for the digits.
https://pkg.go.dev/unicode#IsLetter checks all unicode letters, not just ascii (we can check `<=MaxASCII` but that's an extra step).

File: metadata/metadata.go [hunk 1]
```diff
@@ -82,6 +83,42 @@ func Pairs(kv ...string) MD {
...
 
+// Validate returns error if md is not valid
+// There are check items:
+// - header names contain one or more characters from this set [0-9 a-z _ - .]
+// - if the header-name ends with a "-bin" suffix, the header-value could contain an arbitrary octet sequence. So no real validation required here.
+// - if header-name does not end with a "-bin" suffix, header-value should only contain one or more characters from the set ( %x20-%x7E ) which includes space and printable ASCII.
+func (md MD) Validate() error {
+	for k, vals := range md {
+		// check key
+		for _, rc := range []rune(k) {
```
Comment (menghanl) [inline metadata/metadata.go:94]: `for i := 0; i < len(k); i++ {}` and use `k[i]` _might_ be slightly faster (it saves a conversion, maybe?)

File: metadata/metadata_test.go [hunk 2]
```diff
@@ -262,6 +262,29 @@ func (s) TestAppendToOutgoingContext_FromKVSlice(t *testing.T) {
 	}
 }
 
+func (s) TestValidate(t *testing.T) {
```
Comment (menghanl) [inline metadata/metadata_test.go:265]: Make this a table driven test? Check `TestDelete()` in this file.

File: metadata/metadata.go (hunk 1 above)
Comment (Patrick0308) [reply metadata/metadata.go:94]: Maybe `for _, rc := range k` is DRYer and saves a conversion?

Comment (menghanl) [reply metadata/metadata.go:94]: Range behaves differently for strings: https://go.dev/play/p/2B-0HiWektw

If I understand this correctly, `for range` converts (and merges) bytes to runes, but `for i++` doesn't do that.

File: metadata/metadata.go [hunk 3]
```diff
@@ -82,6 +83,44 @@ func Pairs(kv ...string) MD {
 	return md
 }
 
+// Validate returns error if md is not valid
+// There are check items:
+// - header names contain one or more characters from this set [0-9 a-z _ - .]
+// - if the header-name ends with a "-bin" suffix, the header-value could contain an arbitrary octet sequence. So no real validation required here.
+// - if header-name does not end with a "-bin" suffix, header-value should only contain one or more characters from the set ( %x20-%x7E ) which includes space and printable ASCII.
+func (md MD) Validate() error {
```
Comment (menghanl) [inline metadata/metadata.go:91]: Move this to an internal package (maybe `internal/metadata`?)
Then this cannot be method. A `func Validate(md MD) error` should be fine, too.

**Review by menghanl — CHANGES_REQUESTED** [review]

File: internal/metadata/metadata_test.go [hunk 4]
```diff
@@ -84,3 +88,53 @@ func TestSet(t *testing.T) {
...
 	}
 }
+
+func TestValidate(t *testing.T) {
+	for _, test := range []struct {
+		md        metadata.MD
+		want      error
+	}{
+		{
+			md:        Pairs(string(rune(0x19)), "testVal"),
```
Comment (menghanl) [inline internal/metadata/metadata_test.go:98]: You don't need to call `Pairs` to make md. Just convert from `map` to `metadata`.
Then you can get rid of the function `Pairs` in this file.

File: metadata/metadata_test.go [hunk 5]
```diff
@@ -20,6 +20,7 @@ package metadata
 
 import (
 	"context"
+	"errors"
```
Comment (menghanl) [inline metadata/metadata_test.go:23]: Delete

**Review by menghanl — CHANGES_REQUESTED** [review]

File: internal/metadata/metadata_test.go (hunk 4 above)
Comment (Patrick0308) [reply internal/metadata/metadata_test.go:98]: I found a function `metadata.Pairs`

File: call.go [hunk 6]
```diff
@@ -20,13 +20,21 @@ package grpc
...
+	"google.golang.org/grpc/metadata"
+	imetadata "google.golang.org/grpc/internal/metadata"
 )
 
 // Invoke sends the RPC request on the wire and returns after response is
 // received.  This is typically called by generated code.
 //
 // All errors returned by Invoke are compatible with the status package.
 func (cc *ClientConn) Invoke(ctx context.Context, method string, args, reply interface{}, opts ...CallOption) error {
+	if md, _ ,ok := metadata.FromOutgoingContextRaw(ctx); ok {
```
Comment (menghanl) [inline call.go:33]: This check should be done in `newClientStream()` so it's handled for both unary and streaming RPCs

File: internal/metadata/metadata.go [hunk 7]
```diff
@@ -72,3 +75,41 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
 	addr.Attributes = addr.Attributes.WithValue(mdKey, mdValue(md))
 	return addr
 }
+
+// Validate returns an error if the input md contains invalid keys or values.
+// There are check items:
+// - header names contain one or more characters from this set [0-9 a-z _ - .]
```
Comment (menghanl) [inline internal/metadata/metadata.go:81]: Did you update this godoc?

**Review by menghanl — CHANGES_REQUESTED** [review]

File: internal/metadata/metadata.go (hunk 7 above)
Comment (Patrick0308) [reply internal/metadata/metadata.go:81]: I don't get it. I did `go doc metadata.Validate` then printing the following message.
```sh
❯ go doc metadata.Validate
package metadata // import "google.golang.org/grpc/internal/metadata"

func Validate(md metadata.MD) error
    Validate returns an error if the input md contains invalid keys or values.

    There are check items: - header names contain one or more characters from
    this set [0-9 a-z _ - .] - if the header-name ends with a "-bin" suffix, the
    header-value could contain an arbitrary octet sequence. So no real
    validation required here. - if header-name does not end with a "-bin"
    suffix, header-value should only contain one or more characters from the set
    ( %x20-%x7E ) which includes space and printable ASCII.
```

**Review by menghanl — APPROVED** [review]
LGTM. Thanks for the PR.

**Comment by menghanl** [comment]
The files are not formatted. Please try `gofmt -s -d -l -w .`

**Review by dfawley — COMMENTED** [review]
Could you please add some tests `test/metadata_test.go` that attempt to send invalid metadata and receive errors?  Let us know if you need help with that.  You should be able to model them after this example:

https://github.com/grpc/grpc-go/blob/5d90b32d9dec9e82dd2f5181d3748c57e68e97ac/test/end2end_test.go#L6590

**Comment by Patrick0308** [comment]
@dfawley @menghanl PTAL

File: test/metadata_test.go [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+		{
+			md:   map[string][]string{"test-bin": {string(rune(0x19))}},
+			want: nil,
+		},
+	} {
+		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+		defer cancel()
+
+		ctx = metadata.NewOutgoingContext(ctx, test.md)
+		if _, err := ss.Client.EmptyCall(ctx, &testpb.Empty{}); !reflect.DeepEqual(test.want, err) {
```
Comment (menghanl) [inline test/metadata_test.go:68]: This covers only the unary calls. Can you also add streaming RPCs?
For functions like stream.SetHeader() and others

File: test/metadata_test.go [hunk 9]
```diff
@@ -0,0 +1,72 @@
+/*
+ *
+ * Copyright 2014 gRPC authors.
```
Comment (menghanl) [inline test/metadata_test.go:3]: 2022

**Review by menghanl — CHANGES_REQUESTED** [review]

File: internal/metadata/metadata.go [hunk 10]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+
+// Validate returns an error if the input md contains invalid keys or values.
+//
+// if header name not presudo-header, there are check items:
+// - header names contain one or more characters from this set [0-9 a-z _ - .]
+// - if the header-name ends with a "-bin" suffix, the header-value could contain an arbitrary octet sequence. So no real validation required here.
+// - if header-name does not end with a "-bin" suffix, header-value should only contain one or more characters from the set ( %x20-%x7E ) which includes space and printable ASCII.
+func Validate(md metadata.MD) error {
+	for k, vals := range md {
+		// presudo-header will be ignored
```
Comment (menghanl) [inline internal/metadata/metadata.go:87]: pseudo-header

File: internal/metadata/metadata.go [hunk 11]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
 	addr.Attributes = addr.Attributes.WithValue(mdKey, mdValue(md))
 	return addr
 }
+
+// Validate returns an error if the input md contains invalid keys or values.
+//
+// if header name not presudo-header, there are check items:
```
Comment (menghanl) [inline internal/metadata/metadata.go:81]: If the header is not a pseudo-header

**Review by menghanl — CHANGES_REQUESTED** [review]

**Comment by Patrick0308** [comment]
@dfawley @menghanl https://github.com/grpc/grpc-go/blob/907a202a615d3b2de857e4302cf6032004d65aee/stream.go#L1464 Why not streams's setTrailers return error

**Comment by menghanl** [comment]
The change LGTM. But there's still format problem. Run `gofmt -s -d -l -w .`.

**Review by menghanl — APPROVED** [review]

File: internal/metadata/metadata.go [hunk 12]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
 	addr.Attributes = addr.Attributes.WithValue(mdKey, mdValue(md))
 	return addr
 }
+
+// Validate returns an error if the input md contains invalid keys or values.
+//
+// if the header is not pseudo-header, there are check items:
```
Comment (dfawley) [inline internal/metadata/metadata.go:81]:
```
// If the header is not a pseudo-header, the following items are checked:
```

File: internal/metadata/metadata.go [hunk 13]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+// - header names contain one or more characters from this set [0-9 a-z _ - .]
```
Comment (dfawley) [inline internal/metadata/metadata.go:82]: "header names _must_ contain"...

File: internal/metadata/metadata.go [hunk 14]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+// - if the header-name ends with a "-bin" suffix, the header-value could contain an arbitrary octet sequence. So no real validation required here.
```
Comment (dfawley) [inline internal/metadata/metadata.go:83]:
```
// - if the header name ends with a "-bin" suffix, no validation of the header value is performed.
```

File: internal/metadata/metadata.go [hunk 15]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+// - if header-name does not end with a "-bin" suffix, header-value should only contain one or more characters from the set ( %x20-%x7E ) which includes space and printable ASCII.
```
Comment (dfawley) [inline internal/metadata/metadata.go:84]:
```
// - otherwise, the header value must contain one or more characters from the set [%x20-%x7E].
```

File: internal/metadata/metadata.go [hunk 16]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+func Validate(md metadata.MD) error {
+	for k, vals := range md {
+		// pseudo-header will be ignored
+		if k[0] == ':' {
+			continue
+		}
+		// check key, for i that saving a conversion if not using for range
```
Comment (dfawley) [inline internal/metadata/metadata.go:91]: I don't understand this.  Why would `for _, r := range(k) {` be worse?

File: internal/metadata/metadata.go [hunk 17]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+		for i := 0; i < len(k); i++ {
+			r := k[i]
+			if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '.' && r != '-' && r != '_' {
+				return errors.New("header key contains not 0-9a-z-_. characters")
```
Comment (dfawley) [inline internal/metadata/metadata.go:95]: These errors will go to the user, right?  Let's make sure they have more information / are more readable:
```go
return fmt.Errorf("header key %q contains illegal characters", k)
```

File: internal/metadata/metadata.go [hunk 18]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+			}
+		}
+		if strings.HasSuffix(k, "-bin") {
+			continue
+		}
+		// check value
+		for _, val := range vals {
+			if hasNotPrintable(val) {
+				return errors.New("header val contains not printable ASCII characters")
```
Comment (dfawley) [inline internal/metadata/metadata.go:104]: Similar:
```go
return fmt.Errorf("header key %q contains value non-printable ASCII characters", k)
```
(Headers may contain sensitive data so it's probably best to omit the value itself here.)

File: internal/metadata/metadata.go [hunk 19]
```diff
@@ -72,3 +75,46 @@ func Set(addr resolver.Address, md metadata.MD) resolver.Address {
...
+			}
+		}
+	}
+	return nil
+}
+
+// hasNotPrintable return true if msg contains any characters which are not in %x20-%x7E
+func hasNotPrintable(msg string) bool {
+	// for i that saving a conversion if not using for range
+	for i := 0; i < len(msg); i++ {
```
Comment (dfawley) [inline internal/metadata/metadata.go:114]: Same question re: `range`.

File: internal/metadata/metadata_test.go [hunk 20]
```diff
@@ -84,3 +86,28 @@ func TestSet(t *testing.T) {
...
 	}
 }
+
+func TestValidate(t *testing.T) {
+	for _, test := range []struct {
+		md   metadata.MD
+		want error
+	}{
+		{
+			md:   map[string][]string{string(rune(0x19)): {"testVal"}},
```
Comment (dfawley) [inline internal/metadata/metadata_test.go:96]: Please add a test case for a "normal" key/value that does not error, too.

File: stream.go [hunk 21]
```diff
@@ -1465,6 +1480,9 @@ func (ss *serverStream) SetTrailer(md metadata.MD) {
 	if md.Len() == 0 {
 		return
 	}
+	if imetadata.Validate(md) != nil {
+		return
```
Comment (dfawley) [inline stream.go:1484]: @menghanl, should we do something else here besides silently omit the user's trailers?

What was the old behavior?

File: test/metadata_test.go [hunk 22]
```diff
@@ -0,0 +1,117 @@
...
+
+	"google.golang.org/grpc"
+	"google.golang.org/grpc/codes"
+	"google.golang.org/grpc/internal/stubserver"
+	"google.golang.org/grpc/metadata"
+	"google.golang.org/grpc/status"
+	testpb "google.golang.org/grpc/test/grpc_testing"
+)
+
+// TestInvalidMetadata test invalid metadata
```
Comment (dfawley) [inline test/metadata_test.go:36]: "test**s**"

I'd probably rather just delete this comment entirely since it literally only contains the name of the test.

**Review by dfawley — CHANGES_REQUESTED** [review]
Thank you for the PR.  I have several small comments about style & language and one question (mainly to @menghanl) about the behavior which may change as a result of silently omitting the `SetTrailer` call.

File: stream.go (hunk 21 above)
Comment (menghanl) [reply stream.go:1484]: This depends on the "invalid" characters I believe.
If it violates the wire protocol, it will result in a protocol error.
Otherwise, it will be sent.

But I'm not sure what characters are valid for http2, but invalid for gRPC headers.

File: internal/metadata/metadata.go (hunk 16 above)
Comment (menghanl) [reply internal/metadata/metadata.go:91]: Range is different for strings (runes vs bytes etc): go.dev/play/p/2B-0HiWektw
https://github.com/grpc/grpc-go/pull/4886#discussion_r760434233

File: stream.go (hunk 21 above)
Comment (dfawley) [reply stream.go:1484]: We should probably keep doing what we were doing before here, then, to avoid a behavior change?  I definitely don't think we should silently drop the trailers.

File: internal/metadata/metadata.go (hunk 16 above)
Comment (dfawley) [reply internal/metadata/metadata.go:91]: IIUC all of these will work correctly anyway since we don't allow anything besides low ASCII, right?

File: stream.go (hunk 21 above)
Comment (Patrick0308) [reply stream.go:1484]: > I definitely don't think we should silently drop the trailers.
I'm agree with @dfawley.May be we can printing a warning or error log, and adding a ` func (ss *serverStream) SetTrailer(md metadata.MD) error ` function on interface then deprecating the old function.

File: internal/metadata/metadata.go [hunk 23]
```diff
@@ -101,7 +101,7 @@ func Validate(md metadata.MD) error {
 		// check value
 		for _, val := range vals {
 			if hasNotPrintable(val) {
-				return errors.New("header val contains not printable ASCII characters")
+				return fmt.Errorf("header key %q contains value non-printable ASCII characters", k)
```
Comment (dfawley) [inline internal/metadata/metadata.go:104]: "*contains value _with_ non-printable"

(sorry)

File: internal/metadata/metadata.go [hunk 24]
```diff
@@ -92,7 +92,7 @@ func Validate(md metadata.MD) error {
 		for i := 0; i < len(k); i++ {
 			r := k[i]
 			if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') && r != '.' && r != '-' && r != '_' {
-				return errors.New("header key contains not 0-9a-z-_. characters")
+				return fmt.Errorf("header key %q contains not 0-9a-z-_. characters", k)
```
Comment (dfawley) [inline internal/metadata/metadata.go:95]: "contains illegal characters" (probably good enough)
or
"contains characters not in [0-9a-z_.-]"
or something like that

File: stream.go (hunk 21 above)
Comment (dfawley) [reply stream.go:1484]: > May be we can printing a warning or error log

An error log seems like the best option for now.  To add a new method would require a new name, could not be defined in the `ServerStream` interface, and we could never delete the old method due to our version policy.

File: test/metadata_test.go [hunk 25]
```diff
@@ -0,0 +1,120 @@
...
+		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+		defer cancel()
+
+		ctx = metadata.NewOutgoingContext(ctx, test.md)
+		if _, err := ss.Client.EmptyCall(ctx, &testpb.Empty{}); !reflect.DeepEqual(test.want, err) {
+			t.Fatalf("call ss.Client.EmptyCall() validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
+		}
+	}
+
+	for range tests {
```
Comment (dfawley) [inline test/metadata_test.go:105]: This is not actually testing the behavior specified by the test cases (it's not setting metadata or testing the result of the RPC).

Comment (Patrick0308) [reply test/metadata_test.go:105]: The testing the behavior is at the server side. Multiple calls from the client to the server to trigger the testing.

Comment (dfawley) [reply test/metadata_test.go:105]: I see.  Can you please add a comment here to explain that?

File: test/metadata_test.go [hunk 26]
```diff
@@ -0,0 +1,120 @@
...
+		},
+	}
+
+	testNum := 0
+	ss := &stubserver.StubServer{
+		EmptyCallF: func(ctx context.Context, in *testpb.Empty) (*testpb.Empty, error) {
+			return &testpb.Empty{}, nil
+		},
+		FullDuplexCallF: func(stream testpb.TestService_FullDuplexCallServer) error {
+			for {
```
Comment (dfawley) [inline test/metadata_test.go:66]: Please delete this `for` loop and `return nil` instead of doing `stream.Send` at the end.

File: test/metadata_test.go [hunk 27]
```diff
@@ -0,0 +1,120 @@
...
+				_, err := stream.Recv()
+				if err == io.EOF {
+					return nil
```
Comment (dfawley) [inline test/metadata_test.go:69]: This is an error if it happens at the beginning.

File: test/metadata_test.go [hunk 28]
```diff
@@ -0,0 +1,120 @@
...
+				}
+				if err != nil {
+					return err
+				}
+				test := tests[testNum]
+				testNum = testNum + 1
+				if err := stream.SetHeader(test.md); !reflect.DeepEqual(test.want, err) {
+					t.Errorf("call stream.SendHeader(md) validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
```
Comment (dfawley) [inline test/metadata_test.go:77]: Return an error instead?

File: test/metadata_test.go [hunk 29]
```diff
@@ -0,0 +1,120 @@
...
+				}
+				if err := stream.SendHeader(test.md); !reflect.DeepEqual(test.want, err) {
+					t.Errorf("call stream.SendHeader(md) validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
```
Comment (dfawley) [inline test/metadata_test.go:80]: Same.

File: test/metadata_test.go [hunk 30]
```diff
@@ -0,0 +1,120 @@
...
+	}
+	defer ss.Stop()
+
+	for _, test := range tests {
+		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+		defer cancel()
+
+		ctx = metadata.NewOutgoingContext(ctx, test.md)
+		if _, err := ss.Client.EmptyCall(ctx, &testpb.Empty{}); !reflect.DeepEqual(test.want, err) {
+			t.Fatalf("call ss.Client.EmptyCall() validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
```
Comment (dfawley) [inline test/metadata_test.go:101]: I think `Error` should be sufficient here, as subsequent tests are unaffected.

File: test/metadata_test.go [hunk 31]
```diff
@@ -0,0 +1,120 @@
...
+		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
+		stream, err := ss.Client.FullDuplexCall(ctx, grpc.WaitForReady(true))
+		defer cancel()
+		if err != nil {
+			t.Fatalf("call ss.Client.FullDuplexCall(context.Background()) will success but got err :%v", err)
+		}
+		if err := stream.Send(&testpb.StreamingOutputCallRequest{}); err != nil {
+			t.Fatalf("call ss.Client stream Send(nil) will success but got err :%v", err)
+		}
+		if _, err := stream.Recv(); err != nil {
```
Comment (dfawley) [inline test/metadata_test.go:115]: This should expect `io.EOF` after removing the `Send` call from the server.

File: test/metadata_test.go [hunk 32]
```diff
@@ -0,0 +1,120 @@
...
+			t.Fatalf("stream.Recv() = _, %v", err)
+		}
+		stream.CloseSend()
```
Comment (dfawley) [inline test/metadata_test.go:118]: This is also unnecessary after receiving `io.EOF`.

File: stream.go [hunk 33]
```diff
@@ -1465,6 +1480,10 @@ func (ss *serverStream) SetTrailer(md metadata.MD) {
 	if md.Len() == 0 {
 		return
 	}
+	if err := imetadata.Validate(md); err != nil {
+		logger.Errorf("stream: failed to set trailer, err: %v", err)
+		return
```
Comment (dfawley) [inline stream.go:1485]: Please delete the early `return` here and allow whatever bad behavior was happening before.

**Review by dfawley — COMMENTED** [review]
Thanks!  I have a few comments about the tests to clean them up a bit, otherwise this looks good.

File: test/metadata_test.go [hunk 34]
```diff
@@ -98,23 +96,23 @@ func (s) TestInvalidMetadata(t *testing.T) {
...
-			t.Fatalf("call ss.Client.EmptyCall() validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
+			t.Errorf("call ss.Client.EmptyCall() validate metadata which is %v got err :%v, want err :%v", test.md, err, test.want)
 		}
 	}
 
-	for range tests {
+	// call the stream server's api to drive the server-side unit testing
+	for _, test := range tests {
 		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
 		stream, err := ss.Client.FullDuplexCall(ctx, grpc.WaitForReady(true))
```
Comment (dfawley) [inline test/metadata_test.go:106]: Is the `grpc.WaitForReady` necessary here?  I suspect it shouldn't be since we shouldn't get a connection error AFAIK.

(Unless sending illegal trailers will lead to a connection error & loss, in which case that is a behavior we should fix later.)

**Comment by dfawley** [comment]
Friendly ping.  This is very close to being ready to merge; please let me know if you have any questions or need help with anything.

**Comment by Patrick0308** [comment]
@dfawley I'm back. In the last few days, I've been spending Chinese New Year.

File: test/metadata_test.go [hunk 35]
```diff
@@ -74,7 +73,7 @@ func (s) TestInvalidMetadata(t *testing.T) {
 				return err
 			}
 			test := tests[testNum]
-			testNum = testNum + 1
+			testNum ++
```
Comment (dfawley) [inline test/metadata_test.go:76]: Please remove the space here.

**Review by dfawley — APPROVED** [review]
LGTM except for the one small formatting nit.  Thank you!

**Comment by Patrick0308** [comment]
@dfawley PTAL
