### PR TITLE
client: synchronously verify server preface in newClientTransport

### LINKED ISSUE #5385: transport: perform blocking read of server preface while creating a new client transport
### What version of gRPC are you using?
google.golang.org/grpc v1.46.2

### What version of Go are you using (`go version`)?
1.18.2

### What operating system (Linux, Windows, …) and version?
Linux and Mac OS/X

### What did you do?
See:

https://github.com/Snowflake-Labs/sansshell/tree/jchacon-bad-tls-error/echo

for the example code. Run demo.sh in there to see variations on the testing and being able to replicate the data below.

### What did you expect to see?
When the client sends a cert that the server doesn't have in it's CAPool I expect to get a CA error such as:

x509: certificate signed by unknown authority

i.e. the same thing the client will emit if the server serves up a certificate it can't validate.

### What did you see instead?
If I connect with a client sending a cert that cannot be validated I instead get:

rpc error: code = Unavailable desc = connection closed before server preface received

The output from Go GRPC debugging does show the server was unhappy with this cert:

2022/05/26 11:45:53 WARNING: [core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "ServerHandshake(\"127.0.0.1:56587\") failed: tls: client didn't provide a certificate"

The server should return a real error here and not just close the connection.

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #5385

- Add `grpcsync.OnceFunc`, which is a pattern I also needed in the ORCA PR (#5669).
- Fix some transport tests that were not writing a server preface.
- We had one e2e test that was validating a deadline was set during the handshake.  This was moved to be a transport test, and can verify that newClientTransport honors context _cancelation_ in addition to just the deadline.  This might make the goal of making `ClientConn.Close()` block until all resources are released easier -- previously, if a connection was in flight it would take 20+s for it to stop, which would/should delay that return.  With these changes it will stop very quickly.

RELEASE NOTES: none

### CODE REVIEW

File: internal/transport/http2_client.go [hunk 1]
```diff
@@ -218,12 +215,35 @@ func newHTTP2Client(connectCtx, ctx context.Context, addr resolver.Address, opts
...
+	go func(conn net.Conn) {
+		defer ctxMonitorDone.Fire() // Signal this goroutine has exited.
+		<-newClientCtx.Done()
+		if connectCtx.Err() == nil {
+			// Only newClientCtx was canceled; success.
+			return
+		}
+		// connectCtx expired.  Hard close the connection.
+		conn.Close()
+	}(conn)
```
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_client.go]: Done?

File: internal/transport/http2_client.go [hunk 2]
```diff
@@ -255,15 +275,7 @@ func newHTTP2Client(connectCtx, ctx context.Context, addr resolver.Address, opts
 		}
 	}
 	if transportCreds != nil {
-		rawConn := conn
-		// Pull the deadline from the connectCtx, which will be used for
-		// timeouts in the authentication protocol handshake. Can ignore the
-		// boolean as the deadline will return the zero value, which will make
-		// the conn not timeout on I/O operations.
-		deadline, _ := connectCtx.Deadline()
-		rawConn.SetDeadline(deadline)
```
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_client.go:264]: It's hard to document why code _isn't_ present.

Also note two big flaws with what was deleted:

1. We weren't setting this deadline when reading the server preface (after handshaking), though we were clearing it after it was read (!?).
2. We didn't respect asynchronous context cancellation.

I think the code that now handles these cases is sufficient for the entirety of the function, and needs no comments throughout mentioning how we have a monitoring system in place.  (Comments in code should explain the code as it stands and not attempt to describe diffs in one PR.)

File: internal/transport/http2_client.go [hunk 3]
```diff
@@ -366,21 +377,32 @@ func newHTTP2Client(connectCtx, ctx context.Context, addr resolver.Address, opts
...
+	// dedicated goroutine which reads HTTP2 frames from the network. Then it
+	// dispatches the frame to the corresponding stream entity.  When the
+	// server preface is received, readerErrCh is closed.  If an error occurs
+	// first, an error is pushed to the channel.  This must be checked before
+	// returning from this function.
+	readerErrCh := make(chan error, 1)
+	go t.reader(readerErrCh)
+	defer func() {
+		if err == nil {
+			err = <-readerErrCh
```
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_client.go:391]: I don't think that's possible.  If there's a connection error/loss, the read should unblock.  If there isn't a connection error, I don't know why the writes would error.

[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_client.go:391]: It's probably not useful to record both errors.  In (all?) cases where both would error, the actual error will be that the connection was lost, and both error paths correctly describe this.  The main point of all this is to determine whether any error occurred; logging two messages on connection loss adds log spam for little benefit.

Note that the error passed to `Close` isn't relevant, since no streams can exist and the transport is never even returned from this function.

File: internal/transport/http2_client.go [hunk 4]
```diff
@@ -1509,32 +1526,27 @@ func (t *http2Client) operateHeaders(frame *http2.MetaHeadersFrame) {
...
 	}
 	sf, ok := frame.(*http2.SettingsFrame)
 	if !ok {
 		// this kicks off resetTransport, so must be last before return
-		t.Close(connectionErrorf(true, nil, "initial http2 frame from server is not a settings frame: %T", frame))
+		errCh <- connectionErrorf(true, nil, "initial http2 frame from server is not a settings frame: %T", frame)
 		return
 	}
-	t.onPrefaceReceipt()
+	close(errCh) // received settings frame
```
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_client.go]: :shrug: 

They're equivalent.  I'm okay either way but this seems fine and I see no compelling arguments in favor of pushing a `nil` explicitly.  Is there a better primitive for this purpose than a channel, perhaps?

WDYT about this (see diffs) refactor into another function?

**Review by dfawley — COMMENTED** [review]
Thanks for the comments.  Responses inline.

File: internal/transport/transport_test.go [hunk 5]
```diff
@@ -1248,6 +1254,57 @@ func (s) TestServerWithMisbehavedClient(t *testing.T) {
...
+		}
+	}()
+
+	// Test context cancelation.
+	timeBefore := time.Now()
+	connectCtx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
+	time.AfterFunc(100*time.Millisecond, cancel)
+
+	copts := ConnectOptions{ChannelzParentID: channelz.NewIdentifierForTesting(channelz.RefSubChannel, time.Now().Unix(), nil)}
+	_, err = NewClientTransport(connectCtx, context.Background(), resolver.Address{Addr: lis.Addr().String()}, copts, func(GoAwayReason) {}, func() {})
```
Comment (easwars) [inline internal/transport/transport_test.go:1291]: Because reading of the server preface is done synchronously, and we never receive a server preface, `NewClientTransport()` is expected to fail. Why not check for `err == nil` and fail the test instead of just logging the error?

File: internal/transport/transport_test.go [hunk 6]
```diff
@@ -1248,6 +1254,57 @@ func (s) TestServerWithMisbehavedClient(t *testing.T) {
...
+	t.Logf("NewClientTransport() = _, %v", err)
+	if time.Now().Sub(timeBefore) > 2*time.Second {
```
Comment (easwars) [inline internal/transport/transport_test.go:1293]: Where does this `2s` and `1.5s` come from. The `connectCtx` is canceled in `100ms`.

File: internal/transport/transport_test.go [hunk 7]
```diff
@@ -1248,6 +1254,57 @@ func (s) TestServerWithMisbehavedClient(t *testing.T) {
...
+	}
+
+	// Test context deadline.
+	timeBefore = time.Now()
+	connectCtx, cancel = context.WithTimeout(context.Background(), 100*time.Millisecond)
+	defer cancel()
+	_, err = NewClientTransport(connectCtx, context.Background(), resolver.Address{Addr: lis.Addr().String()}, copts, func(GoAwayReason) {}, func() {})
+	t.Logf("NewClientTransport() = _, %v", err)
+	if time.Now().Sub(timeBefore) > 2*time.Second {
+		t.Fatalf("NewClientTransport returned > 1.5s after context deadline")
```
Comment (easwars) [inline internal/transport/transport_test.go:1304]: Same comments for this block.

Comment (dfawley) [reply internal/transport/transport_test.go]: Fixed this, too.  Couldn't find this comment in the diffs view for some reason.

File: internal/transport/transport_test.go (hunk 6 above)
Comment (easwars) [reply internal/transport/transport_test.go:1295]: I still don't understand why we want to be so generous with the time it takes to return from `NewClientTransport`. We cancel the context in `100ms`. Do we really have to give it `2s`?

File: internal/transport/transport_test.go [hunk 8]
```diff
@@ -1248,6 +1254,62 @@ func (s) TestServerWithMisbehavedClient(t *testing.T) {
...
+		for {
+			if _, err := sfr.ReadFrame(); err != nil {
+				return
+			}
+		}
+	}()
+
+	// Test context cancelation.
+	timeBefore := time.Now()
+	connectCtx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
```
Comment (easwars) [inline internal/transport/transport_test.go:1286]: Could we please use `defaultTestTimeout` which is defined for this package instead of a hard-coded value. We usually end up with different values in different tests over time. Thanks.

**Review by easwars — APPROVED** [review]

File: internal/transport/transport_test.go (hunk 6 above)
Comment (dfawley) [reply internal/transport/transport_test.go:1295]: The tighter you make this check, the more likely you are to have a spurious failure caused by it taking too long to exit, which could be due to a hiccup on github actions / etc.  Ultimately, if we require that it is less than the deadline (3s) then we should be able to distinguish the reason it exited.  And actually, I'll extend the deadline and loosen this slightly since we're not concerned about how long it takes to work if it fails.

And, since there is no secondary cancelation mechanism in the second case, I just removed the time check entirely; the only failure is if no error is returned or if it never returns and times out because it's not honoring the context.

File: internal/transport/transport_test.go (hunk 8 above)
Comment (dfawley) [reply internal/transport/transport_test.go:1286]: Done.  If it ever changes to a value less than 3s then this test becomes broken, though, so it is more sensitive to the value than most other tests.
