### PR TITLE
transport: fix potential race in `TestKeepaliveClientClosesWithActiveStreams`.

### LINKED ISSUE #6099: Fix possible race in Keepalive test: KeepaliveClientClosesWithActiveStreams
KeepaliveClientClosesWithActiveStreams test creates a server which does not respond to keepalive pings, and makes sure that the client closes the transport even when there is an active stream. However there is a possibility of a race here. 

In the test we assign a [large enough](https://github.com/grpc/grpc-go/blob/master/internal/transport/keepalive_test.go#L329) `ClientParameters.Time`.  However this does not guarantee that a create can be created successfully before the timeout hits. This is because with the `NoPingServer` we do not have a configurable way to switch between a ping/noping server. 

This way we can verify that the "no ping server" actually respond to pings until you set a flag, at which point it stops responding and the timeout kicks in to close the transport.

### PR DESCRIPTION
**Pull request by Pranjali-2501**
Fixes #6099

This change resolves the possibility of race in `TestKeepaliveClientClosesWithActiveStreams`.

The fix introduces a `controllablePingServer` that:
* Starts in a responsive "ACK" mode by default.
* Signals via a channel (pingReceived) when the first keepalive ping is received.
* Allows toggling to "unresponsive" by calling setPingAck(false).

The test now deterministically waits for the first ping to be received (confirming the connection is active) then disables ACKs on the server and verifies the connection closes due to the `keepalive` timeout.

RELEASE NOTES: N/A

### CODE REVIEW

File: internal/transport/keepalive_test.go [hunk 1]
```diff
@@ -357,9 +359,8 @@ func (s) TestKeepaliveClientClosesWithActiveStreams(t *testing.T) {
 			Timeout: 500 * time.Millisecond,
```
Comment (arjan-bal) [inline internal/transport/keepalive_test.go]: Can the `Time` and `Timeout` values be reduced to a smaller value now, say `Time=10 millis and Timeout=100 millis`?

File: internal/transport/keepalive_test.go [hunk 2]
```diff
@@ -376,6 +377,17 @@ func (s) TestKeepaliveClientClosesWithActiveStreams(t *testing.T) {
 		t.Fatalf("Stream creation failed: %v", err)
 	}
 
+	// Wait for a ping to be sent and acked.
+	select {
+	case <-server.pingReceived:
+	case <-time.After(time.Second):
+		t.Fatalf("Connection timed out waiting for first ping")
+	}
+
```
Comment (arjan-bal) [inline internal/transport/keepalive_test.go]: Do we really need this check? It seems to add significant test harness code, but we would already be having tests that validate pings are acked correctly.

File: internal/transport/transport_test.go [hunk 3]
```diff
@@ -538,12 +538,60 @@ func setUpWithOptions(t *testing.T, port int, sc *ServerConfig, ht hType, copts
 	return server, ct.(*http2Client), cCancel
 }
 
-func setUpWithNoPingServer(t *testing.T, copts ConnectOptions, connCh chan net.Conn) (*http2Client, func()) {
+type controllablePingServer struct {
+	mu             sync.Mutex
+	pingAck        bool
+	loopDone       chan struct{}
```
Comment (arjan-bal) [inline internal/transport/transport_test.go]: The `loopDone` field seems like a no-op. It gets initialized and closed, but there are not readers of the channel.

File: internal/transport/transport_test.go [hunk 4]
```diff
@@ -538,12 +538,60 @@ func setUpWithOptions(t *testing.T, port int, sc *ServerConfig, ht hType, copts
 	return server, ct.(*http2Client), cCancel
 }
 
-func setUpWithNoPingServer(t *testing.T, copts ConnectOptions, connCh chan net.Conn) (*http2Client, func()) {
+type controllablePingServer struct {
```
Comment (arjan-bal) [inline internal/transport/transport_test.go:541]: If we remove the functionality to wait for the first ping being received, we can have a single field which is an atomic boolean for `pingAck`.  This should simplify things a bit.

**Comment by easwars** [comment]
Unassigned myself since I have too many PRs on my plate and because @arjan-bal has already made a pass on this.

File: internal/transport/keepalive_test.go (hunk 2 above)
Comment (Pranjali-2501) [reply internal/transport/keepalive_test.go]: I have changed it to test the scenario in which we have a responsive server and then server stops responding to keepalive pings, results in client closes the transport.

File: internal/transport/keepalive_test.go (hunk 1 above)
Comment (Pranjali-2501) [reply internal/transport/keepalive_test.go]: Done.

File: internal/transport/transport_test.go (hunk 3 above)
Comment (Pranjali-2501) [reply internal/transport/transport_test.go]: Right, it is not used anywhere. Removed it.

File: internal/transport/transport_test.go (hunk 4 above)
Comment (Pranjali-2501) [reply internal/transport/transport_test.go:541]: Do you want me to keep test `TestKeepaliveClientClosesWithActiveStreams` to only start with an unresponsive server and verifies that it closes the transport.

Comment (arjan-bal) [reply internal/transport/transport_test.go:541]: No, I'm suggesting we keep the current behavior of starting with a responsive server and then switching to an unresponsive one.

However, if we remove the test validation that waits for the first ping, we can also remove the `pingReceived` and `pingRegistered` fields. Only `mu` and `pingAck` would remain. At that point, we could eliminate the mutex entirely and convert `pingAck` to an atomic boolean, since it only requires simple `Get` and `Set` operations.

Comment (Pranjali-2501) [reply internal/transport/transport_test.go:541]: Yeah, it actually make sense to remove `pingReceived` and `pingRegistered`.  

I have made the changes.

File: internal/transport/transport_test.go [hunk 5]
```diff
@@ -538,12 +538,47 @@ func setUpWithOptions(t *testing.T, port int, sc *ServerConfig, ht hType, copts
...
+		return
+	}
+	// Read ping frames and ack checks.
+	framer := http2.NewFramer(conn, conn)
+	for {
+		f, err := framer.ReadFrame()
+		if err != nil {
+			return
+		}
+		if f, ok := f.(*http2.PingFrame); ok {
```
Comment (arjan-bal) [inline internal/transport/transport_test.go]: nit: Can you use guard blocks with early `return` statements to reduce indentation?

```go
if s.pingAck.Load() {
     return
}
f, ok := f.(*http2.PingFrame); ok
if !ok {
    return
}
```

Comment (Pranjali-2501) [reply internal/transport/transport_test.go]: Done.
