### PR TITLE
stats/opencensus: Fix flaky test span

### LINKED ISSUE #6143: Flaky test: Test/Span
https://github.com/grpc/grpc-go/actions/runs/4484710579/jobs/7885495142. Saw this locally as well

Screenshot 2023-03-21 at 8 16 55 PM

### PR DESCRIPTION
**Pull request by zasweq**
Fixes #6143.

The server side span has no happens before relationship with the RPC Finishing, and thus can come at any time and in any index. The Attempt Span and Server Span are guaranteed to be emitted in that order during the RPC. Thus, add a sync point in the test after the RPC completes to wait for the server span, and then sort the seen spans into server, attempt, then call span to then make assertions on.

RELEASE NOTES: N/A

### CODE REVIEW

**Comment by zasweq** [comment]
Ran on Forge. No failures over 10k runs, and tried again with 1k runs and also no failures.

File: stats/opencensus/e2e_test.go [hunk 1]
```diff
@@ -1338,6 +1338,53 @@ func (fe *fakeExporter) ExportSpan(sd *trace.SpanData) {
 	fe.seenSpans = append(fe.seenSpans, gotSI)
 }
 
+// waitForServerSpanAndSort waits until a server span appears somewhere in the
+// span list in an exporter, and then sorts the span list by putting the server
+// span first, the attempt span second, and overall call span third. Returns an
+// error if no server span found within 5 seconds, or if span list isn't length
+// 3 when server span is found.
+func waitForServerSpanAndSort(fe *fakeExporter) error {
```
Comment (dfawley) [inline stats/opencensus/e2e_test.go:1346]: This seems extremely complicated and it very much depends on the test code in the one test case that needs it.

Why not just use `cmpopts.SortSlice` (sorted by `spanKind`) with the `cmp.Diff` calls below?

Comment (zasweq) [reply stats/opencensus/e2e_test.go]: Done. Reverified on forge with 10k runs. I tried using cmpopts, but I switched to sort.Slice instead, because I make assertions on the seenSpans past a pure cmp.Diff call (i.e. relationships between the three spans wrt child parent relationship checked by SpanID). This actually led me to discover a bug where my attempt span wasn't being emitted with Span Kind Client (sorting was failing, and that was why).

File: stats/opencensus/e2e_test.go [hunk 2]
```diff
@@ -1338,6 +1338,25 @@ func (fe *fakeExporter) ExportSpan(sd *trace.SpanData) {
 	fe.seenSpans = append(fe.seenSpans, gotSI)
 }
 
+// waitForServerSpan waits until a server span appears somewhere in the span
+// list in an exporter. Returns an error if no server span found within 5
+// seconds.
```
Comment (dfawley) [inline stats/opencensus/e2e_test.go:1343]: "...within defaultTestTimeout"?

(Isn't that 10s actually?)

Also, a style point: pass in the context instead of having this timeout anyway.  Any reasonable test (including `TestSpan`) should already have a context it's using with this deadline, and we ideally shouldn't ever be declaring new contexts in the code besides `main` and `Test` functions.

**Review by dfawley — APPROVED** [review]

**Review by dfawley — CHANGES_REQUESTED** [review]
Attempts aren't supposed to have a kind.

**Comment by zasweq** [comment]
Verified again on Forge over 10k runs.

**Review by dfawley — APPROVED** [review]
