### PR TITLE
Fix flaky test: TestCloseConnectionWhenServerPrefaceNotReceived

### LINKED ISSUE #1787: Flaky test: TestCloseConnectionWhenServerPrefaceNotReceived
```
E0108 22:41:00.760194    6611 pickfirst.go:59] pickfirstBalancer: failed to NewSubConn: grpc: cannot create SubConn with empty address list
==================
WARNING: DATA RACE
Write at 0x000000e1a608 by goroutine 281:
  google.golang.org/grpc.TestCloseConnectionWhenServerPrefaceNotReceived()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn_test.go:178 +0xca
  testing.tRunner()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
Previous read at 0x000000e1a608 by goroutine 229:
  google.golang.org/grpc.(*addrConn).resetTransport()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn.go:1068 +0x3ec
  google.golang.org/grpc.(*addrConn).transportMonitor()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn.go:1273 +0x619
  google.golang.org/grpc.(*addrConn).connect.func1()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn.go:837 +0x268
Goroutine 281 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206
  main.main()
      google.golang.org/grpc/_test/_testmain.go:220 +0x1d3
Goroutine 229 (finished) created at:
  google.golang.org/grpc.(*addrConn).connect()
      /home/travis/gopath/src/google.golang.org/grpc/clientconn.go:828 +0x185
  google.golang.org/grpc.(*acBalancerWrapper).Connect()
      /home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:293 +0x88
  google.golang.org/grpc.(*pickfirstBalancer).HandleResolvedAddrs()
      /home/travis/gopath/src/google.golang.org/grpc/pickfirst.go:63 +0x4ab
  google.golang.org/grpc.(*ccBalancerWrapper).watcher()
      /home/travis/gopath/src/google.golang.org/grpc/balancer_conn_wrappers.go:139 +0x4e6
==================
--- FAIL: TestCloseConnectionWhenServerPrefaceNotReceived (3.50s)
	testing.go:699: race detected during execution of test
```

#1732 and #1748 both attempted to fix this already; I'm not sure if this is the same failure mode or not.

### PR DESCRIPTION
**Pull request by MakMukhi**
fixes #1787 #1750

Ran 10000 successful runs.

### CODE REVIEW

File: clientconn_test.go [hunk 1]
```diff
@@ -180,91 +180,63 @@ func TestCloseConnectionWhenServerPrefaceNotReceived(t *testing.T) {
...
 		t.Fatalf("Error while listening. Err: %v", err)
 	}
-	defer server.Close()
+	var (
+		conn1, conn2 net.Conn
+		over         uint32
+	)
+	defer func() {
+		server.Close()
+		if conn1 != nil {
```
Comment (dfawley) [inline clientconn_test.go]: This deserves a comment.  Why does what we were doing before not work (i.e. `defer conn1.Close()` in the goroutine)?

File: clientconn_test.go [hunk 2]
```diff
@@ -180,91 +180,63 @@ func TestCloseConnectionWhenServerPrefaceNotReceived(t *testing.T) {
 	if err != nil {
 		t.Fatalf("Error while listening. Err: %v", err)
 	}
-	defer server.Close()
+	var (
+		conn1, conn2 net.Conn
+		over         uint32
+	)
+	defer func() {
+		server.Close()
```
Comment (dfawley) [inline clientconn_test.go]: Can you rename "server" to "lis", please?  It's confusing since it's a listener and not a grpc server.

File: clientconn_test.go [hunk 3]
```diff
@@ -180,91 +180,63 @@ func TestCloseConnectionWhenServerPrefaceNotReceived(t *testing.T) {
...
-	client.mu.Unlock()
-	for ac := range addrConns {
-		ac.mu.Lock()
-		ac.state = connectivity.Shutdown
-		ac.mu.Unlock()
-	}
-	// END
+	time.Sleep(time.Second * 2) // Let things play out.
+	atomic.StoreUint32(&over, 1)
+	server.Close()
```
Comment (dfawley) [inline clientconn_test.go]: Is this necessary?  Why?  It's in the `defer`.

Comment (MakMukhi) [reply clientconn_test.go]: defer will only be called after done channel is closed which might not happen if server.Accept() is blocked so this is to unblock that.

File: clientconn_test.go (hunk 1 above)
Comment (MakMukhi) [reply clientconn_test.go]: This is to make cleanup easier. Otherwise we need to make sure the server goroutine closes the second connection only after the test is successful which requires another signaling mechanism.

File: clientconn_test.go (hunk 2 above)
Comment (MakMukhi) [reply clientconn_test.go]: on it.

File: clientconn_test.go (hunk 1 above)
Comment (dfawley) [reply clientconn_test.go]: Comment in the code please?  If I saw this, I'd try to move it into the goroutine as a `defer conn1.Close()` like it used to be.

Based on your explanation, though...can we still do this for conn1?
