### PR TITLE
transport/server: fix race that could cause a stray header to be sent

### LINKED ISSUE #5511: Race condition in WriteStatus seems to lead to invalid responses from server
### What version of gRPC are you using?
I ran into this on v1.47.0. The same issue was reported https://github.com/spiffe/spire/issues/3229 on v1.48.0 though.

### What version of Go are you using (`go version`)?
1.18

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
I don't yet have a trivial reproducer - I think it should be possible to setup but I wanted to get this written up before I forget.

We have a bi-di stream. It happens to be serving XDS, but I don't think that is relevant. Our server code is essentially:

```
func StreamSecrets(stream sds.SecretDiscoveryService_StreamSecretsServer) {
go func() {
  stream.Recv()
}()
return fmt.Errorf("bad!")
}
```

The real logic is a lot more complicated, but basically we send an error back and are calling Recv() concurrently seem to be the two important aspects.

### What did you expect to see?

We expect the client to get the error "bad!"

### What did you see instead?

Clients get `Status code="Internal" msg="malformed header: missing HTTP status; malformed header: missing HTTP content-type"`

---

I did some debugging here, and I believe I understand what is going on here. However, every time I think there is a gRPC bug its usually a bug in our app, so take it with a grain of salt...

I annotated some key points in the grpc code with some extra logs. The results are below:

```
2022-07-18T23:43:44.734089Z     info    ads     All caches have been synced up in 232.572506ms, marking server ready
2022-07-18T23:43:44.737805Z     info    sds     Starting SDS grpc server
2022-07-18T23:43:44.738124Z     info    ads     XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:
howardjohn start process loop (*transport.incomingSettings)
howardjohn process loop &{ss:[]} (*transport.incomingSettings): <nil>
howardjohn frame  [FrameHeader SETTINGS flags=ACK len=0]
howardjohn start process loop (*transport.incomingSettings)
howardjohn process loop &{ss:[{ID:5 Val:16384}]} (*transport.incomingSettings): <nil>
howardjohn start process loop (*transport.headerFrame)
howardjohn process loop &{streamID:1 hf:[{Name::method Value:POST Sensitive:false} {Name::scheme Value:http Sensitive:false} {Name::path Value:/envoy.service.secret.v3.SecretDiscoveryService/StreamSecrets Sensitive:false} {Name::authority Value:./var/run/secrets/workload-spiffe-uds/socket Sensitive:false} {Name:content-type Value:application/grpc Sensitive:false} {Name:user-agent Value:grpc-go/1.47.0 Sensitive:false} {Name:te Value:trailers Sensitive:false}] endStream:false initStream:0x229b8c0 onWrite:<nil> wq:0xc000c50200 cleanup:<nil> onOrphaned:0x229bbc0} (*transport.headerFrame): <nil>
howardjohn start process loop (*transport.dataFrame)
howardjohn process loop &{streamID:1 endStream:false h:[0 0 0 0 139] d:[18 58 10 54 115 105 100 101 99 97 114 126 49 46 49 46 49 46 49 126 116 101 115 116 46 100 101 102 97 117 108 116 126 100 101 102 97 117 108 116 46 115 118 99 46 99 108 117 115 116 101 114 46 108 111 99 97 108 26 0 26 7 100 101 102 97 117 108 116 34 68 116 121 112 101 46 103 111 111 103 108 101 97 112 105 115 46 99 111 109 47 101 110 118 111 121 46 101 120 116 101 110 115 105 111 110 115 46 116 114 97 110 115 112 111 114 116 95 115 111 99 107 101 116 115 46 116 108 115 46 118 51 46 83 101 99 114 101 116] onEachWrite:<nil>} (*transport.dataFrame): <nil>
howardjohn start process loop (*transport.registerStream)
howardjohn process loop &{streamID:1 wq:0xc000d06260} (*transport.registerStream): <nil>
howardjohn start process loop (*transport.outgoingWindowUpdate)
2022-07-18T23:43:44.747016Z     debug   ads     Unauthenticated XDS: @
howardjohn process loop &{streamID:0 increment:144} (*transport.outgoingWindowUpdate): <nil>
howardjohn start process loop (*transport.ping)
howardjohn process loop &{ack:false data:[2 4 16 16 9 14 7 7]} (*transport.ping): <nil>
howardjohn frame  [FrameHeader WINDOW_UPDATE len=4]
howardjohn frame  [FrameHeader PING len=8]
howardjohn start process loop (*transport.incomingWindowUpdate)
howardjohn process loop &{streamID:0 increment:144} (*transport.incomingWindowUpdate): <nil>
howardjohn start process loop (*transport.ping)
howardjohn process loop &{ack:true data:[2 4 16 16 9 14 7 7]} (*transport.ping): <nil>
2022-07-18T23:43:44.748969Z     warn    model   Istio Version is not found in metadata for test.default, which may have undesirable side effects
2022-07-18T23:43:44.749159Z     info    ads     ADS: new connection for node:test.default-1
2022-07-18T23:43:44.749275Z     debug   ads     ADS:SDS: REQ test.default-1 resources:1 nonce: version:
2022-07-18T23:43:44.749375Z     debug   ads     ADS:SDS: INIT/RECONNECT test.default-1
2022-07-18T23:43:44.749493Z     debug   ads     SDS: SKIP request for node:test.default resource:default
2022-07-18T23:43:44.751622Z     error   howardjohn: complete stream: failed to generate secret for default: resource default not found
howardjohn header set
howardjohn write status [header field ":status" = "200" header field "content-type" = "application/grpc" header field "grpc-status" = "2" header field "grpc-message" = "failed to generate secret for default: resource default not found"], streamID:1, sent:false
goroutine 65 [running]:
runtime/debug.Stack()
        /usr/local/google/home/howardjohn/sdk/go1.18/src/runtime/debug/stack.go:24 +0x72
google.golang.org/grpc/internal/transport.(*http2Server).WriteStatus(0xc0010a8000, 0xc000b2e000, 0xc000d0c0d8)
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/internal/transport/http2_server.go:1051 +0xa8e
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000bdf6c0, {0x61315e0, 0xc0010a8000}, 0xc000b2e000, 0xc000ff58f0, 0x7d93500, 0x0)
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1565 +0x1f0b
google.golang.org/grpc.(*Server).handleStream(0xc000bdf6c0, {0x61315e0, 0xc0010a8000}, 0xc000b2e000, 0x0)
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:1624 +0xf8a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:922 +0xed
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/server.go:920 +0x4be

howardjohn start write status [header field ":status" = "200" header field "content-type" = "application/grpc" header field "grpc-status" = "2" header field "grpc-message" = "failed to generate secret for default: resource default not found"], streamID:1, sent:false
howardjohn header set
howardjohn write status [header field "grpc-status" = "1" header field "grpc-message" = "context canceled"], streamID:1, sent:true
goroutine 114 [running]:
runtime/debug.Stack()
        /usr/local/google/home/howardjohn/sdk/go1.18/src/runtime/debug/stack.go:24 +0x72
google.golang.org/grpc/internal/transport.(*http2Server).WriteStatus(0xc0010a8000, 0xc000b2e000, 0xc000e6e008)
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/internal/transport/http2_server.go:1051 +0xa8e
google.golang.org/grpc.(*serverStream).RecvMsg.func1()
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/stream.go:1580 +0x539
google.golang.org/grpc.(*serverStream).RecvMsg(0xc0003d3450, {0x598db40?, 0xc000eca640})
        /usr/local/google/home/howardjohn/go/pkg/mod/google.golang.org/grpc@v1.47.0/stream.go:1606 +0x3cb
github.com/envoyproxy/go-control-plane/envoy/service/secret/v3.(*secretDiscoveryServiceStreamSecretsServer).Recv(0xc000a4e9c0)
        /usr/local/google/home/howardjohn/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.10.3-0.20220630171008-2ce288a42860/envoy/service/secret/v3/sds.pb.go:373 +0x68
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).receive(0xc000e8db80, 0xc000eca460, {0x0, 0x0, 0x0})
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/xds/ads.go:147 +0x112
created by istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream
        /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/xds/ads.go:298 +0xb76

howardjohn start write status [header field "grpc-status" = "1" header field "grpc-message" = "context canceled"], streamID:1, sent:true
howardjohn executed write status [header field "grpc-status" = "1" header field "grpc-message" = "context canceled"], streamID:1, sent:true, success:true/<nil>
2022-07-18T23:43:44.752983Z     info    ads     ADS: "@" test.default-1 terminated
howardjohn executed write status [header field ":status" = "200" header field "content-type" = "application/grpc" header field "grpc-status" = "2" header field "grpc-message" = "failed to generate secret for default: resource default not found"], streamID:1, sent:false, success:true/<nil>
howardjohn start process loop (*transport.headerFrame)
howardjohn process loop &{streamID:1 hf:[{Name:grpc-status Value:1 Sensitive:false} {Name:grpc-message Value:context canceled Sensitive:false}] endStream:true initStream:<nil> onWrite:0x22c0d00 wq:<nil> cleanup:0xc000d015c0 onOrphaned:<nil>} (*transport.headerFrame): <nil>
howardjohn frame  [FrameHeader HEADERS flags=END_STREAM|END_HEADERS stream=1 len=35]
howardjohn header field "grpc-status" = "1"
howardjohn header field "grpc-message" = "context canceled"
howardjohn frame  [FrameHeader RST_STREAM stream=1 len=4]
2022-07-18T23:43:44.761797Z     warn    ads     ads received error: rpc error: code = Internal desc = malformed header: missing HTTP status; malformed header: missing HTTP content-type
howardjohn start process loop (*transport.cleanupStream)
howardjohn process loop &{streamID:1 rst:true rstCode:1 onWrite:0x229c400} (*transport.cleanupStream): <nil>
    sdsservice_test.go:219: didn't get expected error; got rpc error: code = Internal desc = malformed header: missing HTTP status; malformed header: missing HTTP content-type
howardjohn start process loop (*transport.cleanupStream)
howardjohn process loop &{streamID:1 rst:false rstCode:0 onWrite:0x22af7a0} (*transport.cleanupStream): <nil>
howardjohn loopy err connection error: desc = "transport is closing"
howardjohn loopy err connection error: desc = "transport is closing"
2022-07-18T23:43:45.266704Z     info    sds     SDS server for workload certificates started, listening on "./var/run/secrets/workload-spiffe-uds/socket"
```

What we see is we get two calls to WriteStatus. One is from our application returning the error, and then a later from Recv (https://github.com/grpc/grpc-go/blob/f601dfac73c9ed39935bf1fb6b2d8f5c60b892ae/stream.go#L1588). These are done in the correct order. However, they are not _completed_ in the correct order.

We have a mutex here: https://github.com/grpc/grpc-go/blob/f601dfac73c9ed39935bf1fb6b2d8f5c60b892ae/internal/transport/http2_server.go#L1055, but its unlocked _before_ we actually execute the send headers. Inside this mutex, we check if we have to send the initial `:status` header: https://github.com/grpc/grpc-go/blob/f601dfac73c9ed39935bf1fb6b2d8f5c60b892ae/internal/transport/http2_server.go#L1023.

The order of events that happens is (t1/t2 are different goroutines):

```
* t1: WriteStatus(userError)
* t1: lock header mutex
* t1: updateHeaderSent=false, so add `:status`
* t1: compute headerFields with `:status`
* t1: unlock header mutex
* t2: WriteStatus(Recv error)
* t2: lock header mutex
* t2: updateHeaderSent=true, so do NOT add `:status`
* t2: unlock header mutex
* t2: finishStream() called
```

At this point, we sent an initial header frame without `status`. This ends up being rejected on the client side: https://github.com/grpc/grpc-go/blob/f601dfac73c9ed39935bf1fb6b2d8f5c60b892ae/internal/transport/http2_client.go#L1322.

To validate this idea, I added a mutex covering `finishStream`. This is probably a bad idea for real world performance, but was just for testing this. With this, I was unable to reproduce

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #5511

RELEASE NOTES:
* transport/server: fix race that could cause a stray header to be sent

### CODE REVIEW

File: internal/transport/http2_server.go [hunk 1]
```diff
@@ -1013,17 +1012,19 @@ func (t *http2Server) writeHeaderLocked(s *Stream) error {
 // TODO(zhaoq): Now it indicates the end of entire stream. Revisit if early
 // OK is adopted.
 func (t *http2Server) WriteStatus(s *Stream, st *status.Status) error {
+	s.hdrMu.Lock()
```
Comment (zasweq) [inline internal/transport/http2_server.go:1015]: So what you wrote in issue -" It should be fine to hold the stream's header mutex during these entire functions; they are very infrequently called" is why it is ok for this unlock to be past stuff like stats handlers which would block any operations waiting on the mutex?

File: internal/transport/http2_server.go [hunk 2]
```diff
@@ -945,15 +945,16 @@ func (t *http2Server) streamContextErr(s *Stream) error {
 
 // WriteHeader sends the header metadata md back to the client.
 func (t *http2Server) WriteHeader(s *Stream, md metadata.MD) error {
-	if s.updateHeaderSent() {
-		return ErrIllegalHeaderWrite
-	}
-
+	s.hdrMu.Lock()
+	defer s.hdrMu.Unlock()
```
Comment (zasweq) [inline internal/transport/http2_server.go:949]: This is orthogonal to the bug fix right? I get that this fixes a correctness issue with s.updateHeaderSent, but you could provide me a concrete example of what this fixes?

File: test/end2end_test.go [hunk 3]
```diff
@@ -8077,3 +8077,33 @@ func (s) TestUnexpectedEOF(t *testing.T) {
...
+			// returns and causes stream operations to return errors.
+			go stream.Recv()
+			return nil
+		},
+	}
+	if err := ss.Start(nil); err != nil {
+		t.Fatalf("Error starting endpoint server: %v", err)
+	}
+	defer ss.Stop()
+	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```
Comment (zasweq) [inline test/end2end_test.go:8098]: Nit: 10 * time.Second

File: test/end2end_test.go [hunk 4]
```diff
@@ -8077,3 +8077,33 @@ func (s) TestUnexpectedEOF(t *testing.T) {
 		}
 	}
 }
+
+// TestRecvWhileReturningStatus performs a Recv in a service handler while the
+// handler returns its status.  A race condition could result in the server
```
Comment (zasweq) [inline test/end2end_test.go:8082]: "A race condition could result in the server sending headers twice (once as a result of the status and once as a result of the failed Recv call)." This doesn't seem like the race to me? Isn't the race the bit where instead of writing the header with result from status first it writes the header from failed Recv call without status first due to s.updateHeaderSent is true). Regardless of ordering, both headers get sent out anyway? Hence your comment in issue "E.g. to ignore the extra headers on a stream after END_STREAM was already sent".

Comment (zasweq) [reply test/end2end_test.go:8082]: Yeah, I saw that line when triaging. All I was getting at with this comment was that I think the explanation of the race in the comment is wrong. The race is the fact that the second WriteStatus call reads updateHeaderSent as true, doesn't attach :status, and then sends that BEFORE the first WriteStatus call on the wire without the Status, which is what broke howardjohn. Saying the race is sending headers twice is accurate but not the explanation as to why it broke client in this scenario. (And yes it also breaks HTTP_2 because sends another frame after END_STREAM)

File: internal/transport/http2_server.go (hunk 2 above)
Comment (zasweq) [reply internal/transport/http2_server.go:949]: Yeah makes sense to me. Although you need to hold mutex for writeHeaderLocked() too right? (What you have currently...but your comment just mentions updateHeaderSent and getState).

File: test/end2end_test.go (hunk 3 above)
Comment (zasweq) [reply test/end2end_test.go:8098]: Yeah, talked about offline, this was thought carried over from two of my internship's linters. Didn't realize we have both for some reason. This is fine.

File: test/end2end_test.go (hunk 4 above)
Comment (dfawley) [reply test/end2end_test.go:8082]: Aha, I hadn't completely linked the reason for the failure on the client side, actually, but that makes more sense than my original thought that two `:status` headers were written and the client saw the second one and errored.  So my comment about "ignore the extra headers on a stream after END_STREAM was already sent" is probably bogus.  Updated this comment.

File: internal/transport/http2_server.go [hunk 5]
```diff
@@ -1052,7 +1053,7 @@ func (t *http2Server) WriteStatus(s *Stream, st *status.Status) error {
 		endStream: true,
 		onWrite:   t.setResetPingStrikes,
 	}
-	s.hdrMu.Unlock()
+
```
[the remark this answers is not in the document]
Comment (dfawley) [reply internal/transport/http2_server.go:1056]: I think so. Helps to visually separate building the frame from writing it.

File: test/end2end_test.go (hunk 4 above)
Comment (zasweq) [reply test/end2end_test.go:8082]: Cool thanks comment LGTM.

**Review by zasweq — APPROVED** [review]
LGTM!
