### PR TITLE
client: initialize safe config selector when creating ClientConn

### LINKED ISSUE #4343: Segfault due to access of SafeConfigSelector.cs before initialization
### What version of gRPC are you using?
`v1.37.0` (also observed with `v1.36.1`)
Not observed with `v1.35.0`

### What version of Go are you using (`go version`)?
1.16.2

### What operating system (Linux, Windows, …) and version?
Linux

### What did you do?
If possible, provide a recipe for reproducing the error.

It appears that we're seeing this during initialization of the Google Cloud Spanner client, but creating clients in a loop doesn't seem to reproduce it.
Currently, we're encountering the segfault (below) while running presubmits as a test-flake in tests that interact with a real cloud Spanner instance (hence hitting Google's CFEs). (first encountered after upgrading our `go.mod`)

If the cause of such a race isn't clear to the package maintainers, I can try a bit harder to create a repro. (I suspect this is a race opened up during the xds-related refactoring of the ServiceConfig and Resolver support).

### What did you expect to see?
No panics, just a connection/RPC invocation.

### What did you see instead?
A segfault (nil-pointer dereference) in `google.golang.org/grpc/internal/resolver.(*SafeConfigSelector).SelectConfig`

```
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d6cfc]

goroutine 14208 [running]:
google.golang.org/grpc/internal/resolver.(*SafeConfigSelector).SelectConfig(0xc0063e37a8, 0x1f75b48, 0xc00a7544e0, 0x1cfc3aa, 0x2e, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/resolver/config_selector.go:163 +0x7c
google.golang.org/grpc.newClientStream(0x1f75b48, 0xc00a7544e0, 0x2b6cce0, 0xc0063e3500, 0x1cfc3aa, 0x2e, 0xc00a3e7560, 0x1, 0x1, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.37.0/stream.go:182 +0x230
google.golang.org/grpc.invoke(0x1f75b48, 0xc00a7544e0, 0x1cfc3aa, 0x2e, 0x1b66400, 0xc00a66c8c0, 0x1b01160, 0xc000859dc0, 0xc0063e3500, 0xc00a3e7560, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.37.0/call.go:66 +0x99
google.golang.org/grpc.(*ClientConn).Invoke(0xc0063e3500, 0x1f75b48, 0xc00a7544e0, 0x1cfc3aa, 0x2e, 0x1b66400, 0xc00a66c8c0, 0x1b01160, 0xc000859dc0, 0x0, ...)
	/go/pkg/mod/google.golang.org/grpc@v1.37.0/call.go:37 +0x1b3
google.golang.org/genproto/googleapis/spanner/v1.(*spannerClient).BatchCreateSessions(0xc00691b840, 0x1f75b48, 0xc00a7544e0, 0xc00a66c8c0, 0x0, 0x0, 0x0, 0x1ac3f80, 0xc00a754300, 0x1a3f280)
	/go/pkg/mod/google.golang.org/genproto@v0.0.0-20210331142528-b7513248f0ba/googleapis/spanner/v1/spanner.pb.go:3541 +0xd4
cloud.google.com/go/spanner/apiv1.(*Client).BatchCreateSessions.func1(0x1f75b48, 0xc00a7544e0, 0x1d7d9a0, 0x0, 0x0, 0x0, 0xc000c70ce8, 0x410438)
	/go/pkg/mod/cloud.google.com/go/spanner@v1.17.0/apiv1/spanner_client.go:357 +0x84
github.com/googleapis/gax-go/v2.invoke(0x1f75b48, 0xc00a7544e0, 0xc000f77df0, 0x1d7d9a0, 0x0, 0x0, 0x0, 0x1d7eae8, 0x0, 0x0)
	/go/pkg/mod/github.com/googleapis/gax-go/v2@v2.0.5/invoke.go:70 +0x8f
github.com/googleapis/gax-go/v2.Invoke(0x1f75b48, 0xc00a7544e0, 0xc000c70df0, 0xc00691b780, 0x1, 0x1, 0xc00a7544e0, 0x40fcdb)
	/go/pkg/mod/github.com/googleapis/gax-go/v2@v2.0.5/invoke.go:48 +0xf6
cloud.google.com/go/spanner/apiv1.(*Client).BatchCreateSessions(0xc0008597c0, 0x1f75b48, 0xc00a7544e0, 0xc00a66c8c0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/go/pkg/mod/cloud.google.com/go/spanner@v1.17.0/apiv1/spanner_client.go:355 +0x376
cloud.google.com/go/spanner.(*sessionClient).executeBatchCreateSessions(0xc001e0e8c0, 0xc0008597c0, 0xc000000019, 0xc000f9dad0, 0xc000f9db00, 0x1f49df0, 0xc0002976c0)
	/go/pkg/mod/cloud.google.com/go/spanner@v1.17.0/sessionclient.go:233 +0x4f0
created by cloud.google.com/go/spanner.(*sessionClient).batchCreateSessions
	/go/pkg/mod/cloud.google.com/go/spanner@v1.17.0/sessionclient.go:200 +0x1ab

```

### PR DESCRIPTION
**Pull request by dfawley**
Fixes #4343 

I have identified a race that can happen during initialization time:
1. ClientConn created
2. Stream is created
3. Resolver calls into the ClientConn
4. During a small window of time here, if the ClientConn is closed, no config selector will be applied due to https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/clientconn.go#L607-L616
   This will perform the `defer cc.firstResolveEvent.Fire()` a few lines up.
5. The stream from step 2 is blocked at https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/stream.go#L171
6. If the `firstResolveEvent` case of https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/clientconn.go#L575-L582
   wins over the `cc.ctx.Done()` case, `nil` will be returned and `cc.safeConfigSelector` will be queried.  But since it has never been set, it will panic.

There are several options here:
1. Don't fire `firstResolveEvent` if `cc` is already closed (move the `defer` down a few lines).
   - This seems a little dubious to me since there actually _was_ a resolve event.
2. Fix the race in step 6 and double-check `cc.ctx.Err()` before returning if `firstResolveEvent` wins.
   - This would impact every RPC for a very rare race at startup time.
3. Set the `safeConfigSelector` to some default before returning in step 4.
   - This seems pretty reasonable.
4. Ensure `safeConfigSelector` is set on every path out of `updateResolverState`.
   - This is possible to do through inspection (I did this initially but ignored this path, not noticing the race above), though it is tedious and new paths could be introduced that forget to set it.  We could do this via a `defer`, but this is not as nice as it sounds, as there are currently two other paths out that don't update the config selector because we are certain there already is one.  Without a major refactor, I don't think this can fit in well with the way the code currently works.
5. Always initialize `safeConfigSelector`
   - This seems best, as it means we don't have to be paranoid about `safeConfigSelector` being set after every call to `updateResolverState`.  It is very low risk, and very simple.  Even using a `defer` for option 4 doesn't prevent other kinds of bugs, like setting the config selector to the wrong value.

This PR is option 5.

### CODE REVIEW

File: clientconn.go [hunk 1]
```diff
@@ -143,6 +143,7 @@ func DialContext(ctx context.Context, target string, opts ...DialOption) (conn *
 		firstResolveEvent: grpcsync.NewEvent(),
 	}
 	cc.retryThrottler.Store((*retryThrottler)(nil))
+	cc.safeConfigSelector.UpdateConfigSelector(&defaultConfigSelector{nil})
```
Comment (menghanl) [inline clientconn.go:146]: It seems #4343 can reproduce this bug ~reliably.
Did you look more into that and figure out how it happened?
Maybe we can make a test case from it.

Comment (dfawley) [reply clientconn.go:146]: The logs from #4343 are how I figured out what's happening here.  What's happening there is the resolver is reporting an error while the clientconn is being shut down.  It seems hard to stimulate it reliably since: 1. the window is very small between steps 3-4, and even if you hit it the odds of (6) happening also seems low.

**Review by menghanl — APPROVED** [review]
