### PR TITLE
clustermanager: fix test logic waiting for picker during graceful switch

### LINKED ISSUE #8995: xds: some tests are running for longer than expected
- TestReResolutionAfterTransientFailure in clusterimpl
- TestClusterGracefulSwitch in clustermanager (this should probably be also rewritten as a e2e style test)

### PR DESCRIPTION
**Pull request by easwars**
Fixes https://github.com/grpc/grpc-go/issues/8995

The test was waiting for an event that was not expected to happen, but was waiting for it with the test context instead of a short context. This is the offending line: https://github.com/grpc/grpc-go/blob/master/internal/xds/balancer/clustermanager/clustermanager_test.go#L668-L672

I ended up cleaning the test up, adding comments to make it more readable, and removing a stub policy that was not being used in anyway.

RELEASE NOTES: none

### CODE REVIEW

File: internal/xds/balancer/clustermanager/clustermanager_test.go [hunk 1]
```diff
@@ -47,8 +46,9 @@ func Test(t *testing.T) {
 }
 
 const (
-	defaultTestTimeout    = 5 * time.Second
-	testBackendAddrsCount = 12
+	defaultTestTimeout      = 5 * time.Second
```
Comment (Pranjali-2501) [inline internal/xds/balancer/clustermanager/clustermanager_test.go:49]: Why are we not using the default 10 second timeout in these tests, any specific reason for that?

**Review by Pranjali-2501 — APPROVED** [review]
LGTM.

File: internal/xds/balancer/clustermanager/clustermanager_test.go (hunk 1 above)
Comment (easwars) [reply internal/xds/balancer/clustermanager/clustermanager_test.go:49]: Both `5s` and `10s` are arbitrary numbers. Most of our tests should be able to run in under `5s`, but there are a few which need more than `5s` and there a few that need more than `10s` also. Doesn't really matter is that answer :)
