### PR TITLE
vet: Get it to work on Darwin.

### LINKED ISSUE #2047: vet.sh does not work in mac
### What version of Go are you using (`go version`)?

`go version go1.10.1 darwin/amd64`

### What operating system (Linux, Windows, …) and version?

macOS High Sierra

### What did you do?

`vet.sh`

### What did you expect to see?

Errors per https://travis-ci.org/grpc/grpc-go/jobs/373732686

### What did you see instead?

Silent failure:

```
deklerk at klerk-macbookpro in ~/workspace/go/src/google.golang.org/grpc on withtimeout_cleanup
$ ./vet.sh
+ set -o pipefail
+ PATH=/Users/deklerk/workspace/go/bin:/bin:/Users/deklerk/.rbenv/shims:/Users/deklerk/.rbenv/bin:/usr/local/opt/python/libexec/bin:/Users/deklerk/.rbenv/shims:/Users/deklerk/.rbenv/bin:/usr/local/opt/python/libexec/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/Users/deklerk/dev/google-cloud-sdk/bin:/Users/deklerk/dev/protoc-3.5.1/bin:/Users/deklerk/workspace/go/bin:/Users/deklerk/dev/apache-maven-3.5.2/bin:/Users/deklerk/dev/google-cloud-sdk/bin:/Users/deklerk/dev/protoc-3.5.1/bin:/Users/deklerk/workspace/go/bin:/Users/deklerk/dev/apache-maven-3.5.2/bin:/Users/deklerk/dev/android-tools/bin
+ [[ '' != \t\r\u\e ]]
+ check_proto=true
+ '[' '' = -install ']'
+ [[ 0 -ne 0 ]]
+ git status --porcelain
+ read
+ git ls-files '*.go'
+ xargs grep -L '\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT'
+ tee /dev/stderr
+ read
deklerk at klerk-macbookpro in ~/workspace/go/src/google.golang.org/grpc on withtimeout_cleanup
$ echo $?
1
```

Also, it shouldn't be failing on that line. There's nothing wrong with Copyright notice. It should be failing further down in `go tool vet -all .`.

### PR DESCRIPTION
**Pull request by easwars**
Fixes #2047

### CODE REVIEW

File: vet.sh [hunk 1]
```diff
@@ -70,21 +72,21 @@ elif [[ "$#" -ne 0 ]]; then
 fi
 
 # - Ensure all source files contain a copyright message.
-(! git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- '*.go')
+not 'git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- *.go'
```
Comment (dfawley) [inline vet.sh]: Does this still work as intended with the different quoting?

I didn't think any quote changes would be required at all.  Maybe the `eval` part needs to be tweaked if you are finding that they are (`"$@"`??)

Comment (easwars) [reply vet.sh]: I switched the `eval` part to use `"$@"` and switched this line from its original form of:
```
(! git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- '*.go')	
```
to
```
not git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- '*.go'
```

But I see this in the output:
```
+ not git grep -L '\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT' -- '*.go'
+ eval git grep -L '\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT' -- '*.go'
++ git grep -L '(Copyright' '[0-9]{4,}' gRPC 'authors)|DO' NOT EDIT -- backoff.go balancer.go balancer_conn_wrappers.go balancer_conn_wrappers_test.go balancer_switching_test.go balancer_test.go balancer_v1_wrapper.go call.go call_test.go clientconn.go clientconn_state_transition_test.go clientconn_test.go codec.go codec_test.go dialoptions.go doc.go grpc_test.go interceptor.go picker_wrapper.go picker_wrapper_test.go pickfirst.go pickfirst_test.go preloader.go proxy.go proxy_test.go resolver_conn_wrapper.go resolver_conn_wrapper_test.go rpc_util.go rpc_util_test.go server.go server_test.go service_config.go service_config_test.go stream.go trace.go trace_test.go version.go
fatal: unable to resolve revision: [0-9]{4,}
```

Somehow the pattern to be grep'ed seems to have been broken apart when it is passed to `git grep -L`.

Comment (easwars) [reply vet.sh]: When I call it as:
```
not 'git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- "*.go"' 
```

The output is as follows:
```
+ not 'git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- "*.go"'
+ eval 'git grep -L "\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT" -- "*.go"'
++ git grep -L '\(Copyright [0-9]\{4,\} gRPC authors\)\|DO NOT EDIT' -- '*.go'
```
